src/esp/nav/PathFinder.cpp

Removes usage of cpp14 feature

---

setup.py

Speed up compilation using ALL THE THREADS

---

README.md

Update gif to latest video
Local build of README.md

Update video gif

---

README.md

Added CI and others shields to reflect build status and be more welcome.

Added CI and others shields

---

habitat_sim/__init__.py

Updated version to 0.1.2 as we had the release.

Updated version to v.0.1.2

---

habitat_sim/agent/agent.py
habitat_sim/agent/controls.py
src/esp/bindings/bindings.cpp
src/esp/scene/SceneNode.h

Rename as suggested in #107 
`pytest`

translation -> absolute_translation

---

.circleci/config.yml

Returned back habitat sim pytest run

Returned back habitat sim pytest run to CircleCI

---

.circleci/config.yml

Update `.circleci/config.yml` to be consistent with circleci changes introduced on [habitat-api side](https://github.com/facebookresearch/habitat-api/commit/31318f81db05100099cfd308438d5930c3fb6cd2). 
Additionally, `python setup.py develop -all` now happens before `python setup.py test` so that additional dependencies from habitat_baselines will be installed before unit testing. This will make possible to add baselines-specific tests, with additional dependencies like tensorboard (habitat-api side [mirrored change](https://github.com/facebookresearch/habitat-api/pull/170))

Update circle-ci script for changes from habitat-api

---

src/esp/gfx/PTexMeshShader.cpp

There was a typo that was quickly fixed in this PR, which is introduced in #116.

fix the typo

---

src/CMakeLists.txt
src/esp/agent/Agent.cpp
src/esp/agent/Agent.h
src/esp/bindings/CMakeLists.txt
src/esp/core/Buffer.cpp
src/esp/core/Buffer.h
src/esp/gfx/Simulator.cpp
src/esp/gfx/Simulator.h
src/esp/scene/SceneManager.h
src/esp/sensor/PinholeCamera.cpp
src/esp/sensor/PinholeCamera.h
src/esp/sensor/Sensor.cpp
src/esp/sensor/Sensor.h
src/esp/sim/CMakeLists.txt
src/esp/sim/SimulatorWithAgents.cpp
src/esp/sim/SimulatorWithAgents.h
src/tests/CMakeLists.txt
src/tests/SimTest.cpp

This change creates a new Simulator subclass, SimulatorWithAgents, which functions similar to the Simulator python class. We plan to use this class for the js port initially and then migrate python over to it eventually.
Build.

Add SimulatorWithAgents

---

src/esp/core/logging.h

By default VLOG only logs if level is 0. Add VLOG level
support in the shim code to reduce and control logging in the
emscripten build.
WebGL build and run.

Flush out VLOG shim in order to reduce VLOG messages.

---

habitat_sim/simulator.py
tests/test_simulator.py

Fix not having a navmesh

---

src/esp/bindings_js/navigate.js
src/esp/bindings_js/simenv_embind.js

We should document the js API.
Generated documentation with documentationjs. See below:

WebGL: initial documentation of js classes

---

src/esp/bindings_js/CMakeLists.txt
src/esp/bindings_js/bindings.css
src/esp/bindings_js/bindings.html
src/esp/bindings_js/navigate.js
src/esp/bindings_js/simenv_embind.js

* Currently just supports one hard-coded episode.
* Added UI for radar.
Initial prototype for PointNav.
Verified that the hard-coded episode works in chrome browser.

WebGL: initial implementation of NavigationTask

---

src/CMakeLists.txt
src/esp/CMakeLists.txt
src/esp/assets/FRLInstanceMeshData.cpp
src/esp/assets/ResourceManager.cpp
src/esp/assets/ResourceManager.h
src/esp/gfx/Viewer.cpp
src/esp/gfx/Viewer.h
src/esp/nav/GreedyFollower.h
src/esp/nav/PathFinder.h
src/esp/scene/SemanticScene.h

Catch more bugs at compile-time.
Build.

Lots of warnings and all warnings as errors for esp code

---

habitat_sim/__init__.py
habitat_sim/bindings/__init__.py
tests/conftest.py
tests/test_agent.py
tests/test_controls.py
tests/test_greedy_follower.py
tests/test_sensors.py

I didn't rebase #114 properly before landing.  Let's fix that!
Tests

Fix the imports!

---

src/esp/assets/GenericInstanceMeshData.cpp

Fixes a bug where all ply mesh pixels where painted white.
Rendered semantic mesh using vertex color values.

Normalize when using int vertex attributes for float inputs.

---

build_js.sh
src/esp/bindings_js/bindings.css
src/esp/bindings_js/bindings.html
src/esp/bindings_js/bindings_js.cpp
src/esp/bindings_js/navigate.js
src/esp/bindings_js/simenv_embind.js

Initial plumbing of semantic data to js.
Tested with semantic information from mp3d scene: 17DRP5sb8fy

WebGL: add initial plumbing for semantic sensor

---

src/esp/bindings/ShortestPathBindings.cpp
src/esp/bindings_js/bindings_js.cpp
src/esp/nav/CMakeLists.txt
src/esp/nav/PathFinder.cpp
src/esp/nav/PathFinder.h
src/esp/nav/test/CMakeLists.txt
src/esp/nav/test/PathFinderTest.cpp
src/esp/nav/test/configure.h.cmake

I need to know the bounding box in order to generate a top-down map.
PathFinderTest

Pathfinder bounds

---

habitat_sim/simulator.py

With this you get:
- Magnum Python Bindings working on Windows (helping @cegbertOculus and #84)
- Corrade and Magnum fixed to have global data are shared across `*.so` modules, which unblocks further usage of Magnum Python bindings in the code -- feel free to *finally* start touching all GL APIs from Python!
- however not for Windows yet, there the current workaround is to build everything as shared and not static, fix is scheduled to ship in the 2019.09 release
- Python bindings extended with:
- SDL/GLFW application improvements (key/mouse bindings, ...), which means the GUI Python things could use those instead of `cv2`
- Texturing
- Full texture-enabled Flat and Phong shaders as well as all interfaces for compiling your own shaders (see the Python Textured Triangle example, if you know …

Update Magnum for the latest goodies

---

src/esp/bindings_js/CMakeLists.txt
src/esp/bindings_js/bindings.html
src/esp/bindings_js/bindings_js.cpp
src/esp/bindings_js/navigate.js
src/esp/bindings_js/runtime.js
src/esp/bindings_js/simenv_embind.js
src/esp/bindings_js/topdown.js

[esp/bindings_js] add support for top-down map

---

src/esp/bindings_js/CMakeLists.txt
src/esp/bindings_js/bindings.css
src/esp/bindings_js/index.js
src/esp/bindings_js/modules/vr_demo.js
src/esp/bindings_js/webpack.config.js
src/esp/bindings_js/webvr.html

Depends on #228   x **Don't Merge until #228 merges** x. Also see relevant parts of this PR already existing in #228.
- Add VRDemo class which will initialize demo for WebVR
- Add FPS counter for VRDemo
- Call VRDemo when vrEnabled window variable is set
- Create a separate HTML file for WebVR and build it also in webpack
./build_js.sh and view webvr.html in browser

Initial WebVR PoC Support

---

build_js.sh
src/CMakeLists.txt
src/esp/bindings_js/CMakeLists.txt
src/esp/bindings_js/bindings.html
src/esp/bindings_js/index.js
src/esp/bindings_js/modules/navigate.js
src/esp/bindings_js/modules/simenv_embind.js
src/esp/bindings_js/modules/topdown.js
src/esp/bindings_js/modules/web_demo.js
src/esp/nav/test/CMakeLists.txt
src/tests/CMakeLists.txt

In some scenarios, we want to be able to draw the trajectory on the top-down map.

[esp/bindings_js] add initial trajectory tracing to topdown map

---

src/esp/assets/PTexMeshData.cpp

fix a bug introduced by PR #225

---

src/esp/gfx/Viewer.cpp
src/esp/gfx/Viewer.h

This is to improve the readability of the code.
**Before**: There were two "cameras" in the viewer. One is the RenderCamera, which, by the name, is used to render the scene. And the other camera is conceptual, which actually is the "visual sensor" on the agent. 
**After**: Renamed the 2nd camera mentioned above to "visual sensor", which conforms to our logic everywhere in the simulator. This makes the code a bit easier to understand, and maintain.
Local run with test model files.

Rename the cameraNode_ to visualSensorNode_ in Viewer

---

src/esp/bindings_js/modules/navigate.js

This will also make it easier to handle arrow keys. I also modified the even to keydown because it is more reliable and reduces latency.
First step to getting arrow keys to work.

[esp/bindings_js] simplify event handling logic by using event.key

---

tests/test_agent.py

This test is randomly failing (#233). Try to make it deterministic
so that it always fails or always passes.

[tests] test_agent.py: make test_change_state more deterministic

---

pyproject.toml

This is causing an unrelated diff.

[pyproject] update due to pre-commit

---

src/esp/agent/Agent.h
src/esp/bindings_js/modules/navigate.js

It is nice to have up and down.
Verified that up and down work with WebGL.

[esp/bindings_js] WebGL: add look-up and look-down

---

src/esp/bindings_js/CMakeLists.txt
src/esp/bindings_js/index.js
src/esp/bindings_js/modules/navigate.js
src/esp/bindings_js/modules/viewer_demo.js
src/esp/bindings_js/modules/vr_demo.js
src/esp/bindings_js/modules/web_demo.js
src/esp/bindings_js/viewer.css
src/esp/bindings_js/viewer.html
src/esp/bindings_js/webpack.config.js

Viewer based on WebGL without any kind of extras. Inherits from WebDemo and add some sugar on top of it. 
TODO: I will host this somewhere for demo purposes.
Tested directly, open up viewer.html in your browser

[Viewer] Initial Web Based Viewer PoC

---

README.md

Prepare some documentation in time for launch.
Verified instructions work.

[README.md] add WebGL build instructions

---

src/esp/bindings_js/bindings.css
src/esp/bindings_js/index.js
src/esp/bindings_js/modules/defaults.js
src/esp/bindings_js/viewer.css
src/esp/bindings_js/viewer.html

If we are not on localhost, set the default scene to load from URL.
Tested by deploying on aihabitat.org

[viewer] Support for URL based loading of scenes

---

README.md

Add link to demo to the README.
Rendered Readme in the fork

Update README to include demo information

---

src/esp/bindings_js/index.js
src/esp/bindings_js/modules/defaults.js
src/esp/bindings_js/modules/utils.js
src/esp/bindings_js/tests/utils.test.js

`info_semantic.json` also needs to be handled properly for replica models to work
Tests have been added
- [] I have updated the documentation accordingly.

Support Replica models in browsers

---

CONTRIBUTING.md
docs/Doxyfile

New contributor guidelines based on document created by @msavva.

New contributor guidelines

---

README.md
habitat_sim/__init__.py

- Bump version to v0.1.3.
- Trailing whitespaces removed by hook.

Bump version to v0.1.3.

---

src/esp/physics/PhysicsManager.cpp
src/esp/physics/PhysicsManager.h
src/esp/physics/bullet/BulletPhysicsManager.cpp
src/esp/physics/bullet/BulletPhysicsManager.h

@msbaines pointed out in review for PR #298 that getters should be const.
Local and tests

Getters in PhysicsManager and BulletPhysicsManager should be const.

---

tests/test_sensors.py

Make compare for rendering a tad bit fuzzier.  This is needed for the large MP3D scene added in #326 
Locally

Make compare fuzzier

---

docs/noise_models.rst
habitat_sim/sensors/noise_models/sensor_noise_model.py

Fix the build for habitat-sim docs

---

src/esp/assets/PTexMeshData.cpp

Fix typos, errors when using CORRAD_ASSERT in PTexMeshData.cpp

---

.clang-tidy
src/esp/assets/PTexMeshData.cpp
src/esp/geo/geo.cpp
src/esp/gfx/PTexMeshShader.cpp
src/esp/nav/PathFinder.cpp

C++-style casting is always preferred to C-style casts.
Enforce coding style.
Build.

[clang-tidy] enable google-readability-casting

---

.circleci/config.yml
.gitignore
package.json

Enables code coverage for JS files
`npm run test_with_coverage`

[tests] Enable Code Coverage for JavaScript tests

---

README.md

Fixes issue #436 by updating README to install bullet the way our CI does.
Our CI is installing bullet this way on Ubuntu, tested locally on Mac

Update bullet physics install instructions in README

---

src/esp/nav/PathFinder.cpp
src/esp/nav/PathFinder.h

The PathFinder class has gotten to be overloaded with weirdness due to forward declares (which are great, don't get me wrong).  This PR seeks to resolve this by pimpling the pathfinder.  This gets rid of all forward declares that aren't related to method signatures, thereby removing this weirdness.
If it builds it ships?

Pimpl PathFinder

---

docs/docs.rst
habitat_sim/__init__.py
habitat_sim/sensor.py

Fixes the following errors during doc build:
WARNING:root:could not resolve a link to habitat_sim._ext.habitat_sim_bindings.VisualSensor which is among INPUT_MODULES (referred from habitat_sim.sensor.PinholeCamera.framebuffer_size), possibly hidden/undocumented?
WARNING:root:could not resolve a link to habitat_sim._ext.habitat_sim_bindings.VisualSensor which is among INPUT_MODULES (referred from habitat_sim.sensor.PinholeCamera.render_target), possibly hidden/undocumented?
WARNING:root:Sphinx symbol `gfx.SimulatorConfiguration` not found, rendering as monospace
Fix pybind1 docs
docs/build.sh

[esp/bindings] fix pybind11 documentation regressions caused by recent changes

---

habitat_sim/__init__.py

Version bump, better late than never. That's needed for right package version building.

Version bump 0.1.4, better late than never

---

README.md

Document how to convert 3DSceneGraph to Habitat parseable format
This script was used to generate the dataset we are now using for Gibson

[README.md] document how to run the 3DSceneGraph conversion script

---

tests/test_simulator.py

We rely on being able to construct and destruct the simulator many times.  There are certain programming patterns that can violate this assumption, so add an explicit test!
If you comment out the `sim.close()` in the new test, it fails (as it should since the destructor won't have run yet when you make the simulator for the second time).
New test

Construct Destruct Test

---

src/esp/physics/bullet/BulletPhysicsManager.cpp
src/esp/physics/bullet/BulletPhysicsManager.h
src/tests/PhysicsTest.cpp

Setup `BulletPhysicsManager` world and solver for multi-body physics.
Existing tests are passing. `JoinCompound` was modified to give more time to deactivate stable objects due to solver change.

Setup Bullet world for multi-body physics

---

src/tests/CMakeLists.txt
src/tests/CullingTest.cpp

Corrade::TestSuite provides a convenient way to do benchmark. I may need this functionality later.

[Refactor] Culling test with Corrade::TestSuite

---

examples/ab_test.py

Optionally output csv file during ab test for easier processing later.
Eg of output:
```
num_procs,resolution,sensor_types,fps_test,fps_control
1,128,rgb,1220.180686527348,433.6937190315082
1,128,rgbd,646.3853434963924,225.71452249824296
1,128,depth_only,1536.040313558034,529.8223253269938
1,128,semantic_only,1071.0588643870651,113.05412282733961
1,128,rgbd_semantic,635.9399827759786,97.00690401337553
1,256,rgb,2033.1829804767501,1308.7303209339552
1,256,rgbd,1091.2095574079278,639.8652627467972
1,256,depth_only,1095.6735265382465,436.0366373137765
1,256,semantic_only,925.8233911287207,113.08794255527332
1,256,rgbd_semantic,485.2895269984924,91.28888760233752
```

csv output for ab test

---

src/esp/assets/GltfMeshData.cpp

Since not all glTF files have interleaved buffers, the GPU had to fetch vertex attributes scattered across memory instead of having them nicely localized. The original pre-#542  `MeshData3D`-based workflow interleaved the attributes always during `compile()`, but since the new workflow aims to minimize data processing, a slice of the data comes from the file unchanged. The `interleave()` API is a no-op in case the mesh is already interleaved, and it doesn't allocate/copy anything if a r-value is passed so this should have a strictly positive effect on performance.
:information_source: This currently also resolves an issue with heavier memory usage, which is due to the input glTF files being laid out in a way that hits a suboptimal code path in `TinyGltfImporter`. A fix on that side is …

assets: unconditionally interleave imported glTF mesh data

---

src/esp/assets/Attributes.cpp
src/esp/assets/Attributes.h
src/esp/assets/ResourceManager.cpp
src/esp/core/CMakeLists.txt
src/esp/core/Configuration.h
src/esp/physics/PhysicsManager.cpp
src/esp/physics/RigidObject.h
src/esp/physics/bullet/BulletPhysicsManager.cpp

This change aims to replace existing derivations of the `assets::Attributes` class with a slightly modified `esp::core::Configuration` in order to leverage existing, tested implementations and reduce code bloat in preparation for full object template python bindings.
To support this change, `src/deps/corrade` submodule updated to master.
Existing tests.

esp::core::Configuration derived Attributes refactor

---

src/esp/assets/ResourceManager.cpp
src/esp/assets/ResourceManager.h
src/esp/physics/PhysicsManager.cpp
src/esp/sim/Simulator.cpp
src/tests/PhysicsTest.cpp
src/utils/viewer/viewer.cpp

refactor ResourceManager so that loadObject functions are named more appropriately;
Previously 3 methods named "loadObject" resided in ResourceManager, all performing slightly different functionality.  They have been renamed to more appropriately reflect their behavior.
--run_tests all passed

--Refactor ResourceManager;

---

habitat_sim/__init__.py
habitat_sim/attributes.py
habitat_sim/bindings/__init__.py
src/esp/assets/Attributes.h
src/esp/bindings/CMakeLists.txt
src/esp/bindings/attributesBindings.cpp
src/esp/bindings/bindings.cpp
src/esp/bindings/bindings.h
tests/test_configs.py

Python bindings and test for `assets::PhysicsObjectAttributes` with getter/setter functions.
New python test: `test_physics_object_attributes`.

PhysicsObjectAttributes python bindings

---

src/esp/assets/Attributes.cpp
src/esp/assets/Attributes.h
src/esp/assets/ResourceManager.cpp
src/esp/assets/ResourceManager.h
src/esp/physics/PhysicsManager.cpp
src/esp/physics/PhysicsManager.h
src/esp/physics/RigidObject.cpp
src/esp/physics/RigidObject.h
src/esp/physics/bullet/BulletPhysicsManager.cpp
src/esp/physics/bullet/BulletPhysicsManager.h
src/esp/physics/bullet/BulletRigidObject.cpp
src/esp/physics/bullet/BulletRigidObject.h
src/esp/sim/Simulator.cpp

This pullreq primarily addresses the process of adding Rigid Objects in the scene via PhysicsManager, in order to facilitate adding physically-based primitives to the scene.  Previously the method for adding objects was made somewhat arcane and, in places, redundant, by inefficient overloads of functionality in PhysicsManager by BulletPhysicsManager, which these changes address.  
This pullreq also makes some minor changes to ResourceManager and Attributes to follow the updated attribute access  with respect to the ObjectTemplateID, and to change access to CollisionMeshGroups to be based on the collisionMeshHandle, instead of the physicsObjectMeshHandle, removing redundant entries where multiple templates might use the same collision mesh groups.
Passed all run_tests

Improve Adding Physics Objects to Scene; Update ResourceManager to follow new attributes protocols

---

README.md

Someone brought-up that they didn't know the build flags stack.  Added a note to make this clearer.

Add comment about build flags stacking

---

habitat_sim/attributes.py
src/esp/assets/Attributes.cpp
src/esp/assets/Attributes.h
src/esp/assets/ResourceManager.cpp
src/esp/assets/ResourceManager.h
src/esp/bindings/attributesBindings.cpp
src/esp/physics/PhysicsManager.cpp
src/esp/physics/PhysicsManager.h
src/esp/physics/RigidObject.cpp
src/esp/physics/bullet/BulletPhysicsManager.cpp
src/esp/physics/bullet/BulletPhysicsManager.h
src/utils/viewer/viewer.cpp

(This PR bundles preliminary code from #585)
In order to instantiate primitive objects programmatically in the most efficient manner possible, changes to Attributes, PhysicsManager and ResourceManager are required, and this PR aims to address these changes.  Some of these changes are new functionality to support primitives, while others are refactors intending on facilitating code reuse or otherwise streamlining the instantiation process.
- Object and Scene Attributes classes were changed to inherit from a base class that held common functionality, to minimize potential for key naming convention issues, and the python bindings were updated to support this.  Derived classes for each primitive object type were also added, to hold necessary values to facilitate object synthesis.
- Physics …

More groundwork for physics primitives

---

src/esp/bindings/SimBindings.cpp
tests/test_physics.py

Fix typo in get/set_angular_velocity python bindings.
Re-arranged test to catch this.

Angular velocity bindings bugfix

---

conda-build/README.md
conda-build/habitat-sim/meta.yaml
conda-build/linux_matrix_builder.py
conda-build/macos_matrix_builder.py
requirements.txt

Assorted improvements to README, build functions to keep track of version numbers, etc. 
CC: @mpiseno

Improvements to Conda build

---

.circleci/config.yml

Following: https://github.com/facebookresearch/habitat-sim/pull/630

removing unnecessary mkdirs

---

src/esp/assets/Attributes.h
src/esp/assets/ResourceManager.cpp
src/esp/assets/ResourceManager.h
src/esp/physics/PhysicsManager.cpp
src/esp/physics/bullet/BulletRigidObject.cpp
src/esp/sim/Simulator.h
src/utils/viewer/viewer.cpp

Reorganize ResourceManager.h to be more accessible by grouping and labeling similar methods and constructs;
This PR affects ResourceManager : changes some method names to be more consistent, reorders some method declarations in header to group based on context/functionality, and verifies existence of files using the same method.
cpp and python tests

--Refactor to make method names consistent;

---

habitat_sim/__init__.py

Update version from 0.1.4 to 0.1.5 for the version release.

Update version number from 0.1.4 to 0.1.5

---

tests/test_greedy_follower.py

`tests/test_greedy_follower.py` occasionally fails. with error:
```
if not test_all: 
>           assert test_spl / NUM_TESTS >= ACCEPTABLE_SPLS[(move_filter_fn, action_noise)] 
E           assert (82.33217626187597 / 100) >= 0.825 
tests/test_greedy_follower.py:182: AssertionError 
```
[That made CI fails on master](https://app.circleci.com/pipelines/github/facebookresearch/habitat-sim/2574/workflows/fa63344a-508a-42b9-a63a-0ceb6b2aad34/jobs/9529).
Fixed random seed for Greedy Follower test and made it more forgiving.

Fixed random seed for Greedy Follower test and made it more forgiving.

---

src/utils/viewer/viewer.cpp

We do not use this function anywhere, thus remove it to make the cod a bit simpler.

[viewer] remove unused function positionOnSphere

---

.circleci/config.yml
src/utils/datatool/SceneLoader.cpp
src/utils/datatool/SceneLoader.h

Get the datatool to build again.
Closes #648 
The CI will now build the datatool, so at least it will build?
I also tried the fixed codepath locally and it works.

Fix datatool build

---

habitat_sim/simulator.py
tests/test_simulator.py

Adds proper 'with' context hooks to habitat-sim like just like in [habitat-api](https://github.com/facebookresearch/habitat-api/pull/383)
Passes appropriate tests

Added 'with' context to simulator.py

---

examples/demo_runner.py
tests/test_examples.py

Fixed a minor attribute library conversion bug in `demo_runner.py` and added `example.py --enable_physics` to test suite to prevent introduction of bugs here in the future.
Added test.

[bug-fix] examples/example.py --enable_physics

---

README.md

Adds a pre-commit badge to our readme to let people know that we use it.

Add a precommit badge to the readme.

---

.pre-commit-config.yaml
examples/demo_runner.py
examples/instance_segmentation/common.py
examples/settings.py
examples/tutorials/rigid_object_tutorial.py
habitat_sim/__init__.py
habitat_sim/agent/agent.py
habitat_sim/agent/controls/controls.py
habitat_sim/agent/controls/object_controls.py
habitat_sim/agent/controls/pyrobot_noisy_controls.py
habitat_sim/errors.py
habitat_sim/sensors/noise_models/redwood_depth_noise_model.py
habitat_sim/sensors/sensor_suite.py
habitat_sim/simulator.py
habitat_sim/utils/data/__init__.py
habitat_sim/utils/data/data_extractor.py
habitat_sim/utils/data/pose_extractor.py
setup.py
tests/conftest.py
tests/test_controls.py
tests/test_data_extraction.py
tests/test_examples.py
tests/test_greedy_follower.py
tests/test_physics.py
tests/test_pyrobot_noisy_controls.py
tests/test_recompute_navmesh.py
tests/test_semantic_scene.py
tests/test_sensors.py
tests/test_simulator.py
tests/test_snap_point.py

Fixes CircleCI by updating our pre-commit hooks

Fixes isort linter so it agrees with .circleci

---

.pre-commit-config.yaml
conda-build/habitat-sim/meta.yaml
requirements.txt

Update requirements to reflect colab tutorials requirements.
Update requirements.txt to reflect dependencies on imagio with new colab tutorials.
Also propagate update into conda build metadata, and relax pre-commit python restrictions to be version 3 instead of 3.6
Python tests pass with these installed

Update requirements 

---

build_js.sh

#688 
Check if bullet was able to be linked to magnum properly and it was.
Succesfully builds with bullet_emscripten_port.

Adds --bullet option to build_js.sh

---

.circleci/config.yml
README.md

Adds some new badges to the ReadMe

New markdown badges

---

src/esp/assets/Attributes.h
src/esp/assets/managers/AssetAttributesManager.h
src/esp/assets/managers/AttributesManagerBase.h
src/esp/assets/managers/ObjectAttributesManager.cpp
src/esp/assets/managers/ObjectAttributesManager.h
src/esp/assets/managers/PhysicsAttributesManager.cpp
src/esp/assets/managers/PhysicsAttributesManager.h
src/esp/assets/managers/SceneAttributesManager.cpp
src/esp/assets/managers/SceneAttributesManager.h
src/esp/bindings/AttributesBindings.cpp
src/esp/io/json.h
src/tests/CMakeLists.txt
src/tests/CoreTest.cpp

This PR generalizes the handling of reading json data values in the file-based attributes managers create functions and populating the appropriate attributes files.  This is part of an intended larger PR that will support scene attributes being populated by json description files, and introduces scene JSON support.
The purpose of this refactoring of functionality is to 1) decrease the code base size and 2) standardize the parsing of json files and make this process less susceptible to typos or inconsistencies between similar fields in different types of attributes managers. 

--Generalize json handling;

---

src/esp/assets/managers/AssetAttributesManager.cpp
src/esp/io/json.h

Address some warnings regarding unused arguments in template function prototype and unintended copies being made with looping variable.
All cpp and python tests passed.

--Address some build warnings

---

habitat_sim/geo.py
src/esp/bindings/GeoBindings.cpp
src/esp/geo/geo.h

Want to compute transformed bounding boxes in python.
Tested in C++.

[python bindings] geo::getTransformedBB

---

src/esp/gfx/DepthUnprojection.cpp

As discussed in #713 
Closes #710 
Visually?

Change depth shader to GL330

---

src/esp/assets/Attributes.cpp
src/esp/assets/Attributes.h
src/esp/assets/ResourceManager.cpp
src/esp/assets/ResourceManager.h
src/esp/assets/managers/AttributesManagerBase.h
src/esp/assets/managers/ObjectAttributesManager.cpp
src/esp/assets/managers/ObjectAttributesManager.h
src/esp/assets/managers/PhysicsAttributesManager.h
src/esp/assets/managers/SceneAttributesManager.cpp
src/esp/assets/managers/SceneAttributesManager.h
src/esp/bindings/AttributesBindings.cpp
src/esp/io/json.h
src/esp/sim/Simulator.cpp
src/tests/CullingTest.cpp
src/tests/DrawableTest.cpp
src/tests/PhysicsTest.cpp
src/tests/ResourceManagerTest.cpp
src/utils/viewer/viewer.cpp

This is the final functionality PR for the scene import functionality.  This PR supports json files holding scene-specific configurations to override the old scene filename-based functionality settings.  If json configuration files for a particular scene do not exist, the current mechanism for setting values based on file name/extension are still followed.
This PR will be followed by a tutorial PR on how to consume this new functionality.
C++ tests needed to be modified to consume the new sceneAttributes-based protocol.  All existing c++ and python tests pass.

Scene import implementation

---

.pre-commit-config.yaml
examples/tutorials/nb_python/rigid_object_tutorial.py

Fixes a loop caused by pre-commit and isort.
Fixes a loop caused by jupytext and isort is the ipython notebook needs be isorted. 
Makes jupytext manually run isort as part of the pipe.

Add isort to jupytext

---

examples/colab_utils/colab_install.sh

Nit: change from habitat-api to habitat-lab in Colab scripts.
CI

Nit: change from habitat-api to habitat-lab in colab scripts

---

.pre-commit-config.yaml
build.sh
build_js.sh
install_deps.sh
tools/gen_gibson_semantics.sh

* Helps ensure that we aren't making any simple to avoid mistakes when writing bash scripts.
* Ran shellcheck on the shell files in our repo.
* Added shellcheck to our pre-commit hooks
* Added some newer, but useful pre-commit hooks to the repo.
- [] I have updated the documentation accordingly.
- [] I have added tests to cover my changes.
- [] All new and existing tests passed.

Added a shell-script linter

---

src/esp/assets/ResourceManager.cpp

Bug fix for handling scenes being loaded without collision support.
All C++ and python tests passed.

--Fix 2 bugs with loading collision meshes.

---

.pre-commit-config.yaml
examples/ab_test.py
examples/demo_runner.py
examples/tutorials/stereo_agent.py
habitat_sim/__init__.py
habitat_sim/agent/controls/controls.py
habitat_sim/agent/controls/default_controls.py
habitat_sim/sensors/noise_models/sensor_noise_model.py
habitat_sim/utils/data/data_extractor.py
habitat_sim/utils/data/pose_extractor.py
habitat_sim/utils/viz_utils.py
tests/test_examples.py
tests/test_gfx.py
tests/test_greedy_follower.py
tests/test_navmesh.py

It will automatically remove unused imports from the standard library, I could do make it more aggressive, but the big concern would be numpy-quaternion since it relies solely on side-effects. It's not perfect, but it does get quite a few of them. It could also be used to automatically remove unused variables, but that is quite aggressive.
I autoflaked the whole repo, all tests passed, then I added the pre-commit hook.
- [] Docs change / refactoring / dependency upgrade
- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)
- [] My code follows the code style of this project.
- [] I …

Add autoflake precommit hook

---

src/esp/assets/PTexMeshData.cpp
src/esp/assets/PTexMeshData.h
src/esp/assets/ResourceManager.cpp
src/esp/gfx/Drawable.h
src/esp/gfx/GenericDrawable.cpp
src/esp/gfx/PTexMeshDrawable.cpp
src/esp/gfx/PTexMeshDrawable.h
src/esp/gfx/PTexMeshShader.cpp
src/esp/gfx/PTexMeshShader.h
src/esp/gfx/RenderCamera.cpp
src/esp/gfx/RenderCamera.h
src/shaders/ptex-default-gl410.frag
src/utils/viewer/ObjectPickingHelper.cpp
src/utils/viewer/viewer.cpp

As titled.
A very useful functionality for the future development.

Object picking for replica mesh

---

.lgtm.yml

Enables lgtm.com to build analyze the C++ of this repo and remove some annoying alerts from its analysis.
As for now I am only building it as headless and with bullet. I don't think the machine has a GPU, but it apparently doesn't need one to run it's static code analysis. I got it to build a few test build from master using this config, but I can't see the actual alert we get from it until it's merged.
Open to how to make this file more maintainable, but I think I made it as minimalistic as possible for now. Also torn if we should use SYSTEM_ASSIMP or not. I can remove that flag and build ASSIMP as well. 
I used the test config function on lgtm.com.
- [] Docs change / refactoring / dependency upgrade
- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking …

Add .lgtm.yml config

---

.lgtm.yml
.pre-commit-config.yaml
examples/colab_utils/colab_install.sh
examples/tutorials/colabs/ECCV_2020_Advanced_Features.ipynb
examples/tutorials/colabs/ECCV_2020_Interactivity.ipynb
examples/tutorials/colabs/ECCV_2020_Navigation.ipynb
examples/tutorials/colabs/rigid_object_tutorial.ipynb
examples/tutorials/nb_python/ECCV_2020_Advanced_Features.py
examples/tutorials/nb_python/ECCV_2020_Interactivity.py
examples/tutorials/nb_python/ECCV_2020_Navigation.py
examples/tutorials/nb_python/rigid_object_tutorial.py
habitat_sim/sensors/noise_models/gaussian_noise_model.py
habitat_sim/sensors/noise_models/poisson_noise_model.py
habitat_sim/sensors/noise_models/redwood_depth_noise_model.py
habitat_sim/sensors/noise_models/salt_and_pepper_noise_model.py
habitat_sim/sensors/noise_models/sensor_noise_model.py
habitat_sim/sensors/noise_models/speckle_noise_model.py
habitat_sim/utils/data/data_extractor.py
habitat_sim/utils/profiling_utils.py
habitat_sim/utils/viz_utils.py

This PR does three things
* It allows ipynb to be run locally but dynamically changing the working directory to the root with iPython magic
* It cleans up the global install so to not say that an error has occured during installation if aborts early due to realizing its not in Colab.
* I also fixes the .lgtm analysis to exclude third party libraries and docs which will give us actually useful C++ alerts. I ran the test config on .lgtm to verify it has proper syntax.
I was able to run the ipynbs locally and generate HTML for all of them.
- [] I have updated the documentation accordingly.
- [] I have added tests to cover my changes.

Fix local ipynb and .lgtm

---

habitat_sim/__init__.py
habitat_sim/attributes.py
habitat_sim/attributes_managers.py
src/esp/assets/managers/PhysicsAttributesManager.cpp
src/esp/bindings/AttributesBindings.cpp
src/esp/bindings/AttributesManagersBindings.cpp

This PR has 2 main foci :
1. Add doc string tags for attributes properties
2. Add attributesManagers into automated documentation process
c++ and python tests.

--Add attributes document tags, and automate attributesManagers documentation for website

---

src/utils/viewer/viewer.cpp

As titled.
Recently I played with the MP3D dataset a lot. My work requires me to navigate in the scene quickly. I do not need any navigation constraint or collision response.
So I am adding this functionality to turn off the navMesh if user does not need it.

Add an option to the viewer to disable the NavMesh

---

docs/pages/index.rst

We're revamping this index (landing page) to show more helpful content. The ideas here are from recent team discussions. Some meeting notes here: https://cvmlp.slack.com/archives/G0131KVLBLL/p1598552266041100
I generated the index page and clicked on the links.

Refactor Docs landing page to include ECCV tutorials and selected unit tests

---

src/esp/assets/ResourceManager.cpp
src/esp/assets/managers/AssetAttributesManager.cpp
src/esp/assets/managers/AssetAttributesManager.h
src/esp/assets/managers/AttributesManagerBase.h
src/esp/assets/managers/ObjectAttributesManager.cpp
src/esp/assets/managers/ObjectAttributesManager.h
src/esp/assets/managers/PhysicsAttributesManager.cpp
src/esp/assets/managers/PhysicsAttributesManager.h
src/esp/assets/managers/StageAttributesManager.cpp
src/esp/assets/managers/StageAttributesManager.h

When attempting to load a stage attributes using a configuration provided by JSON, the current process did not know how to find the file.  This PR corrects this.
All c++ and python tests pass.

--Fix loading of stage attributes via json.

---

habitat_sim/simulator.py
src/esp/bindings/SimBindings.cpp
src/esp/gfx/LightSetup.h
src/esp/physics/PhysicsManager.cpp
src/esp/physics/PhysicsManager.h
src/esp/physics/RigidBase.h
src/esp/sim/Simulator.cpp
src/esp/sim/Simulator.h

This PR adds some doc-strings to Simulator python bindings and polishes some related docs.
Local doc build.

[docs] Simulator python bindings

---

BUILD_FROM_SOURCE.MD
README.md

Introducing conda install on this release, so tell new users how to use this for install.

[docs] README conda install

---

.circleci/config.yml
conda-build/Dockerfile

Added release conda package with version tag creation. Now all workflows are implemented:
*PR has commented code for testing purposes that will be removed before merge.*

Added release conda package with version tag pushed

---

habitat_sim/__init__.py

Update version to 0.1.6

---

examples/tutorials/lighting_tutorial.py
src/esp/assets/ResourceManager.cpp
src/esp/bindings/GfxBindings.cpp
src/esp/gfx/CMakeLists.txt
src/esp/gfx/GenericDrawable.cpp
src/esp/gfx/GenericDrawable.h
src/esp/gfx/LightSetup.cpp
src/esp/gfx/LightSetup.h
src/esp/gfx/MaterialUtil.cpp
src/esp/gfx/MaterialUtil.h
src/tests/SimTest.cpp
tests/test_light_setup.py

Several related changes to lights, materials, and Phong shading, with the goal of getting our upcoming ReplicaCAD dynamically-lit scenes presentable for public release. For pretty screenshots, see my [longer walkthrough message, below](https://github.com/facebookresearch/habitat-sim/pull/792#issuecomment-691793952).
The visual improvements coming to ReplicaCAD are a combination of these code changes plus [changes to the 3D assets, themselves](https://drive.google.com/drive/u/1/folders/1BFZUqeGaBDYDViB5SqalIkFwhW8Lpkk1) .
A review of existing lights in Habitat: they have a position but not distance-based attenuation. Thus they are a kind of hybrid between point lights (like light bulbs) and directional lights (like the Sun). In this PR, we get rid of these in favor of traditional point and …

Lights, materials, phong updates

---

src/utils/viewer/viewer.cpp

Minor change to add a screenshot directory and incremental screenshot saving for viewer.
Local testing.

Improved viewer screenshot handling

---

src/tests/DrawableTest.cpp
src/tests/PhysicsTest.cpp

This refactors a couple tests to reference ResourceManager as a smart pointer.  This is in preparation for when MetadataMediator will need to be passed to RM in its constructor.
c++ and python tests

--Prepare tests for MetadataMediator;

---

src/esp/scene/Mp3dSemanticScene.cpp

Fixing a bug in loading.
Closes #830 
Manually.

Fix aabb loading

---

src/esp/io/json.cpp
src/esp/io/json.h
src/tests/IOTest.cpp

Need JSON file writing for config exports.
Added a test.

JsonDocument file writing.

---

src/esp/assets/ResourceManager.cpp
src/esp/assets/ResourceManager.h

Since #837 keeps failing the cI test, let us split that PR even further into 2 PRs. See what will happen.

Rename lightSetup, material to lightSetupKey, materialKey in certain places.

---

README.md

Update outdated WebGL instructions

---

src/esp/gfx/CMakeLists.txt
src/esp/gfx/PbrShader.cpp
src/esp/gfx/PbrShader.h
src/shaders/Shaders.conf
src/shaders/pbr.frag
src/shaders/pbr.vert

This is the 2nd diff in the PBR project.
This diff is to introduce the PBR OpenGL shaders for forward rendering.

[PBR 2] PBR GL shaders (forward rendering)

---

src/esp/core/ManagedContainer.h
src/esp/core/ManagedContainerBase.cpp
src/esp/core/ManagedContainerBase.h
src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
src/esp/metadata/managers/AssetAttributesManager.cpp
src/esp/metadata/managers/AssetAttributesManager.h
src/esp/metadata/managers/AttributesManagerBase.h
src/esp/metadata/managers/ObjectAttributesManager.cpp
src/esp/metadata/managers/ObjectAttributesManager.h
src/esp/metadata/managers/PhysicsAttributesManager.cpp
src/esp/metadata/managers/PhysicsAttributesManager.h
src/esp/metadata/managers/StageAttributesManager.cpp
src/esp/metadata/managers/StageAttributesManager.h

This PR introduces a few functional modifications to how the ManagedContainer Class template handles constructing copies from default attributes, how JSON file name proposals are constructed, and provides some expanded search capabilities.  These capabilities are being introduced in preparation for the MetadataMediator/Dataset/SceneInstance functionality.

Managed container refactor

---

src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
src/esp/metadata/managers/SceneDatasetAttributesManager.h

Through the adventures of rebasing, some snake-case tag specifications in SceneDatasetAttributesManagers got reverted to non-snake-ness.  This PR fixes this.
All c++ and python tests pass.

--[BUGFIX] Address some mis-formatted tags in SceneDatasetAttributesManager

---

conda-build/README.md
conda-build/habitat-sim/meta.yaml
conda-build/macos_matrix_builder.py

Some minor updates and helpful notes.

Some updates to conda-build stuff

---

habitat_sim/utils/compare_profiles.py
tests/test_compare_profiles.py

I added a count column--the number of times the profiling scope was entered. Looks like this:
```
prof_node1_local0.sqlite             
event name               count     incl (ms)     excl (ms)  
_worker_env                  4     2,918,822       265,574  
connection_read_fn       60844     2,395,342     2,395,342  
train                        1       736,439         5,577  
train update               120       658,844           247  
rollouts loop              120       356,758         6,452  
_collect_rollout_step    15207       350,306       175,535  
_update_agent              120       297,924       297,924  
Policy.act               15207       174,771       174,771 
```
I updated test_compare_profiles.py.

add count column to compare_profiles

---

examples/colab_utils/colab_install.sh

Fixes an error caused by a change in PILLOW's API. Forces Colab's Pillow to update
Fixes Colab (almost still a libbullet bug).

[BUGFIX] Update colab install script to fix pillow issue

---

.circleci/config.yml
.clang-tidy
README.md
examples/colab_utils/colab_install.sh
src/esp/agent/Agent.cpp
src/esp/agent/Agent.h
src/esp/assets/ResourceManager.cpp
src/esp/assets/ResourceManager.h
src/esp/bindings/AttributesManagersBindings.cpp
src/esp/bindings/GfxBindings.cpp
src/esp/bindings/SensorBindings.cpp
src/esp/core/ManagedContainerBase.cpp
src/esp/geo/geo.cpp
src/esp/io/io.cpp
src/esp/metadata/attributes/SceneDatasetAttributes.cpp
src/esp/metadata/attributes/SceneDatasetAttributes.h
src/esp/metadata/managers/LightLayoutAttributesManager.cpp
src/esp/metadata/managers/LightLayoutAttributesManager.h
src/esp/metadata/managers/StageAttributesManager.cpp
src/esp/nav/PathFinder.cpp
src/esp/physics/bullet/BulletRigidObject.cpp
src/esp/physics/bullet/BulletRigidStage.cpp
src/esp/scene/ObjectControls.cpp
src/esp/scene/SuncgSemanticScene.cpp
src/esp/sensor/PinholeCamera.cpp
src/esp/sensor/PinholeCamera.h
src/esp/sensor/Sensor.cpp
src/esp/sensor/Sensor.h
src/esp/sensor/VisualSensor.cpp
src/esp/sim/Simulator.cpp

* Fixes #901 
Locally and with CI.

[CIRCLECI] Enable clang-tidy performance checks (CI)

---

src/esp/metadata/managers/SceneAttributesManager.cpp

Fixes an LGTM-caught bug.
c++ and python tests pass.

--[BUG-FIX] Fix is-own-initializer bug

---

src/esp/nav/PathFinder.cpp

Fixes an unused param for isNavigable.
CI tests and found with clang-tidy.

[BUGFIX] Pathfinder bugfix for isNavigable

---

habitat_sim/agent/agent.py

Little QOL improvement change.  The error message for providing an np.ndarray is pretty uninterruptible and this feels like something that _should_ work.
Locally.
QOL

Add support for ndarray to set_state

---

habitat_sim/utils/viz_utils.py

Adds a new function that creates images on a per frame basis. This make it easy to integrate with Habitat_Lab and also makes it more flexible. It will also allow videos to be generated with less memory.
Colab
Partially fixes #921

[VIZ_UTILS] Factor out make_video_frame from make_video

---

src/esp/assets/ResourceManager.cpp
src/esp/assets/ResourceManager.h
src/esp/gfx/MaterialUtil.cpp
src/esp/gfx/MaterialUtil.h

Refactor ResourceManager data structures from vectors of contiguous entries to maps to support upcoming resource de-allocation and modification features. No change in functionality yet.
Tests pass.

[refactor] Resource maps

---

src/esp/assets/PTexMeshData.cpp

[bugfix] fix a useless assertion

---

.pre-commit-config.yaml
examples/instance_segmentation/common.py
habitat_sim/simulator.py
setup.cfg

Fixes a false positive on the new flake8-simplify plugin version. Issue filed with flake8-simplify: https://github.com/MartinThoma/flake8-simplify/issues/25
With flake8

Fix false positive on flake8-simplify

---

src/esp/assets/ResourceManager.cpp
src/esp/bindings/AttributesBindings.cpp
src/esp/metadata/attributes/ObjectAttributes.h
src/esp/metadata/attributes/SceneDatasetAttributes.h
src/esp/metadata/managers/SceneDatasetAttributesManager.h
src/esp/metadata/managers/StageAttributesManager.cpp
src/esp/metadata/managers/StageAttributesManager.h

This PR fixes the spelling error "frustrum" to be "frustum"

--[BUGFIX]Fix spelling error : Frustrum -> Frustum

---

docs/pages/attributesJSON.rst
src/esp/metadata/attributes/ObjectAttributes.h
src/esp/metadata/managers/ObjectAttributesManager.cpp
src/tests/AttributesManagersTest.cpp

Semantic ID was not being read from JSON files.  This PR fixes this.

--[BUGFIX]Support reading semantic ID from object attributes json config

---

src/esp/bindings_js/bindings_js.cpp
src/esp/bindings_js/index.js
src/esp/bindings_js/modules/vr_demo.js
src/esp/bindings_js/modules/web_demo.js
src/esp/bindings_js/webvr.html
src/esp/sensor/Sensor.h

The existing WebVR integration doesn't work with newer browsers
Tested locally with a Rift S on Chrome 87.0.4280.88
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] I have completed my CLA (see **CONTRIBUTING**)

Replace WebVR integration with WebXR

---

habitat_sim/sensors/noise_models/redwood_depth_noise_model.py
src/esp/sensor/RedwoodNoiseModel.cu
tests/test_noise_models.py

The CUDA and CPU noise model implementations were producing pretty different results, this PR fixes that.
With the new test (it use to fail before I fixed the bugs).

Fix bugs in cuda noise model

---

.circleci/config.yml

Our nightly conda packages were broken for sometime. One of the reasons was using old version of the circleci image for document build.
```
sudo apt-get install -yq \
>       rsync
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
libpopt0
Suggested packages:
openssh-server
The following NEW packages will be installed:
libpopt0 rsync
0 upgraded, 2 newly installed, 0 to remove and 6 not upgraded.
Need to get 361 kB of archives.
After this operation, 882 kB of additional disk space will be used.
Err:1 http://archive.ubuntu.com/ubuntu disco/main amd64 libpopt0 amd64 1.16-12
404  Not Found [IP: 91.189.88.142 80]
Err:2 http://archive.ubuntu.com/ubuntu disco/main amd64 rsync amd64 3.1.3-6
404  Not Found [IP: …
```

Updated Circle CI images to use update cimg namespace

---

.coveragerc

I noticed setup.py is on our coverage report. This is rather silly and it should be explicitly omitted.
codecov

Remove setup.py from coverage report

---

build.sh

There is a nasty EGL bug in nv driver 450.80.02 -- see https://github.com/mosra/magnum/pull/491 for details.  
@eundersander When talking with @mosra about this update, he mentioned that it may be time to also lock down the lighting pixel tests since the Phong shader in Magnum shouldn't be changing anymore (those tests are still be skipped).
Tests pass.

Update Magnum + friends for EGL workaround

---

src/esp/core/ManagedContainer.h
src/esp/io/JsonStlTypes.h
src/esp/physics/bullet/BulletRigidObject.cpp
src/esp/physics/bullet/BulletRigidStage.cpp

Minor fixes to address various compilation warnings. 
c++ and python tests pass

--Fix various compilation warnings

---

tests/test_controls.py

Solves another hypothesis issue with it complaining about PyTest fixtures being mixed in. This should unblock #1016 .
Locally with PyTest

[pytest] Fix another pytest hypothesis issue

---

docs/Doxyfile-public
docs/conf-public.py

We don't really use the analytics for so best to not have them

Remove google analytics

---

.pre-commit-config.yaml
requirements.txt

This just updates some precommit dependencies (mostly for better 3.9 support) and ensures are requirement file is sorted and contains valid values using a precommit hook. 
* Locally with pre-commit

[precommit] Sort requirements and update precommit

---

.circleci/config.yml
.pre-commit-config.yaml
setup.cfg

This updates some dependencies for flake8. Also I noticed that our python-lint circleci wasn't install all of the flake8 requirements so I added them. I also modified the cfg file slightly.
* locally

[CircleCI] some flake8 updates

---

src/esp/bindings/SimBindings.cpp

Typo in new binding. 
C++ and python tests.

--Typo in new Simulator Configuration binding

---

BUILD_FROM_SOURCE.md

Since Bullet comes bundled as a submodule now, we don't need to ask the user to install it.
* Bullet physics is now available as a submodule so we don't need to asks user to install it. 
* Locally om a Mac

Update install instructions (remove need for Bullet system install.

---

habitat_sim/agent/agent.py
habitat_sim/utils/__init__.py
habitat_sim/utils/validators.py
tests/test_agent.py

As a sanity check, prevent users from setting an agent_state which has inf or NaN in any of the arrays. It is not sensible behavior and is indicative of an error. 
* This has been tested with PyTest

[Validator] Add agent_state validator

---

src/esp/scene/CMakeLists.txt
src/esp/scene/GibsonSemanticScene.cpp
src/esp/scene/Mp3dSemanticScene.cpp
src/esp/scene/ReplicaSemanticScene.cpp
src/esp/scene/SemanticScene.cpp
src/esp/scene/SemanticScene.h
src/esp/sim/Simulator.cpp

This PR generalizes the loading mechanism of the Semantic Scene Descriptor files, with the intention that the data, and not the file name, should be used to determine the file type.  
This change is being proposed now mainly because the SceneDataset/Scene Import tutorials and tests are going to describe how to properly configure SceneDataset and SceneAttributes configs to support, among other things, SSD file loading. 
Presented is a working proposal for loading SSD files based on contents (although I don't think it is sufficiently exclusionary to be merged).
In the existing system, the SSD text file loading process is brittle in that it expects users to obey certain file extension or directory hierarchy constraints to successfully load the appropriate SSD files for a particular dataset. …

--Semantic Scene Descriptor generalized loading

---

README.md

Add a colab badge to the README to advertise the tutorials
Improves the visibility of Habitat-Sim Tutorials

[README] Colab Badge for the ReadMe

---

.clang-tidy
src/esp/assets/CollisionMeshData.h
src/esp/assets/ResourceManager.h
src/esp/core/spimpl.h
src/esp/gfx/MaterialUtil.h
src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
src/esp/metadata/managers/LightLayoutAttributesManager.cpp
src/esp/metadata/managers/ObjectAttributesManager.cpp
src/esp/metadata/managers/PhysicsAttributesManager.cpp
src/esp/metadata/managers/SceneAttributesManager.cpp
src/esp/metadata/managers/StageAttributesManager.cpp
src/esp/nav/test/PathFinderTest.cpp
src/esp/physics/RigidBase.h
src/esp/physics/bullet/BulletRigidObject.cpp
src/esp/physics/bullet/BulletRigidObject.h
src/esp/scene/test/ReplicaSceneTest.cpp

With the new, stricter clang-tidy checks [introduced in this PR](https://github.com/facebookresearch/habitat-sim/pull/1102) some legacy code was not passing.  This PR addresses these issues.
c++ and python tests

--[Bug fix] Satisfy new, stricter Clang-tidy constraints 

---

habitat_sim/simulator.py
src/cmake/dependencies.cmake
src/deps/atomic_wait/atomic_wait.cpp
src/deps/atomic_wait/atomic_wait.h
src/esp/bindings/GfxBindings.cpp
src/esp/gfx/CMakeLists.txt
src/esp/gfx/RenderCamera.cpp
src/esp/gfx/RenderCamera.h
src/esp/gfx/Renderer.cpp
src/esp/gfx/Renderer.h
src/esp/gfx/WindowlessContext.cpp
src/esp/gfx/WindowlessContext.h
src/esp/sim/Simulator.cpp

Background rendering thread to enable overlap of physics and rendering.  This means that sim(a_t) advances the world state to s_{t+1} but returns o_t, not o_{t+1} as it normally would.
Things train and rendering time is sub-millisecond.

[AO Prototype] Background rendering thread

---

src/esp/physics/CollisionGroupHelper.cpp
src/esp/physics/CollisionGroupHelper.h
src/esp/physics/bullet/BulletArticulatedObject.cpp
src/esp/physics/bullet/BulletArticulatedObject.h
src/esp/physics/bullet/BulletDebugManager.cpp
src/esp/physics/bullet/BulletDebugManager.h
src/esp/physics/bullet/BulletPhysicsManager.cpp
src/esp/physics/bullet/BulletRigidObject.cpp
src/esp/physics/bullet/BulletRigidStage.cpp
src/esp/physics/bullet/BulletURDFImporter.cpp

See individual commit messages.
There's some code here that should really be cleaned up. This isn't suitable to merge to Hab-sim master as-is.
I tested this a couple weeks ago in my perf branch. Unfortunately, I'm unable to run/test latest pvizplan play.py with latest AO branch due to some error about missing sensor config.

Bullet perf fixes and better Bullet debugging

---

src/esp/assets/ResourceManager.cpp
src/esp/sim/Simulator.cpp

Switch to Phong lighting because I saw some lighting artifacts with the PBR shader that we don't have time to troubleshoot. https://cvmlp.slack.com/archives/G0131KVLBLL/p1614641284025100
Also fix the fetch material so it isn't too dark. https://cvmlp.slack.com/archives/CFN5TAUSD/p1604448841393900
See also https://github.com/ASzot/p-viz-plan/pull/6 .
Tested in orp/play.py .

pvizplan lighting changes

---

src/esp/bindings/SimBindings.cpp
src/esp/gfx/Renderer.cpp
src/esp/io/URDFParser.cpp
src/esp/io/URDFParser.h
src/esp/physics/ArticulatedObject.h
src/esp/physics/CollisionGroupHelper.cpp
src/esp/physics/PhysicsManager.h
src/esp/physics/URDFImporter.cpp
src/esp/physics/URDFImporter.h
src/esp/physics/bullet/BulletArticulatedObject.cpp
src/esp/physics/bullet/BulletArticulatedObject.h
src/esp/physics/bullet/BulletURDFImporter.h
src/esp/sim/Simulator.h

Addressing clang-tidy complaints for AO branch.
CI (note we expect SimTest to fail with Phong enabled instead of PBR)

[AO] - clang-tidy

---

.circleci/config.yml

[CI] Add hdf5 headers

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/questions-help-support.md
README.md

Updated Readme to emphasize sticking to releases.

Emphasizing versions

---

docs/Doxyfile-mcss

The [C++ API docs page](https://aihabitat.org/docs/habitat-sim/cpp.html) is generated by `docs/Doxyfile-mcss` rather than `docs/conf.py` which is used to generate the navbar for all other pages. These should be synchronized and any navbar changes made to both files.
This PR updates `docs/Doxyfile-mcss` to match existing `docs/conf.py`.
Local docs build.

[docs] C++ API navbar update

---

examples/colab_utils/colab_install.sh

[COLAB] Pin Numpy Version in Colab install

---

.circleci/config.yml

* Temporary fix to repair the CI.
* With CircleCI

[CircleCI] Fix docutils version issue

---

src/esp/core/ManagedContainer.h

GCC complains about the docConfig being 0 by default instead of a nullptr constant so I went ahead and fixed it.

[Minor][Bugfix] Fix docConfig complaint

---

src/esp/gfx/CMakeLists.txt
src/esp/gfx/CubeMapShaderBase.cpp
src/esp/gfx/CubeMapShaderBase.h
src/esp/gfx/DoubleSphereCameraShader.cpp
src/esp/gfx/DoubleSphereCameraShader.h
src/esp/gfx/EquirectangularShader.cpp
src/esp/gfx/EquirectangularShader.h
src/esp/sensor/CMakeLists.txt
src/esp/sensor/CameraSensor.cpp
src/esp/sensor/CameraSensor.h
src/esp/sensor/CubeMapSensorBase.cpp
src/esp/sensor/CubeMapSensorBase.h
src/esp/sensor/EquirectangularSensor.cpp
src/esp/sensor/EquirectangularSensor.h
src/esp/sensor/FisheyeSensor.cpp
src/esp/sensor/FisheyeSensor.h
src/esp/sensor/Sensor.cpp
src/esp/sensor/Sensor.h
src/esp/sensor/SensorFactory.cpp
src/esp/sensor/VisualSensor.cpp
src/esp/sensor/VisualSensor.h
src/shaders/Shaders.conf
src/shaders/doubleSphereCamera.frag
src/shaders/equirectangular.frag
src/utils/viewer/viewer.cpp

- Introduce equirectangular sensor. Unlike #1141, which is a prototype and contains a large amount of code duplication, this one refactors the existing class hierarchy to accommodate this new sensor.
- Introduces an intermediate class called `CubeMapSensorBase` as the immediate parent class for `FisheyeSensor` and `Equirectangular` sensor.
- Introduces another intermediate class named `CubeMapShaderBase` to be the parent class for specific sensor shaders.
- Small fixes in both the C++ code and shader code.
- Shaders has been verified using:
```
magnum-shaderconverter --validate equirectangular.frag --input-version "300 es" --output-version opengl
```
Results:

[Sensor] Improved Equirectangular sensor

---

src/esp/bindings/CoreBindings.cpp
src/esp/bindings/PhysicsBindings.cpp
src/esp/core/AbstractManagedObject.h
src/esp/core/ManagedContainer.h
src/esp/physics/CMakeLists.txt
src/esp/physics/PhysicsManager.cpp
src/esp/physics/PhysicsManager.h
src/esp/physics/PhysicsObjectBase.h
src/esp/physics/RigidBase.h
src/esp/physics/RigidObject.cpp
src/esp/physics/RigidObject.h
src/esp/physics/RigidStage.cpp
src/esp/physics/RigidStage.h
src/esp/physics/bullet/BulletRigidObject.cpp
src/esp/physics/bullet/BulletRigidObject.h
src/esp/physics/bullet/BulletRigidStage.cpp
src/esp/physics/bullet/BulletRigidStage.h
src/esp/sim/Simulator.cpp
src/esp/sim/Simulator.h
tests/test_physics.py

This PR sets up some necessary prep work for the Managed rigid objects work and is [split off from this PR](https://github.com/facebookresearch/habitat-sim/pull/1182). 
This PR introduces a new base class for RigidBase that will hold required information to be used by the Managed Containers.  These constructs will be wrapped in a wrapper class that will reference the underlying object via a weak pointer, to facilitate safe access from python.
Existing python and c++ tests pass.

Managed rigid object prep

---

src/esp/assets/ResourceManager.cpp

Previously custom materials were re-loaded as unique resources every time a URDF was loaded resulting in limitless build-up of duplicated materials. Now that asset materials are keyed by string this change generates string keys from custom URDF material override colors and enables re-use of previously defined materials. 
This is currently limited to the simple Phong URDF material overrides we support and is only used for ArticulatedObjects. This could be extended in the future to all materials with simple parameterization (i.e., no textures).
local testing

[AO] - Reuse URDF override materials 

---

examples/tutorials/physics_benchmarking.py

Fix black complaint on extra space in comment.

--Fix black complaint in comment.

---

.pre-commit-config.yaml

* Updates some dependencies on pre-commit. That way it's more useful to finding problems before they pop up in CI. Also the flake8 git repo location moved so I updated that too.
* Locally.

[PRECOMMIT] Precommit autoupdate

---

docs/pages/lighting-setups.rst

This tutorial was a bit out of date. Primary updates are:
- new object config format
- point and directional light sources specified by homogenous `vector` parameter
- default to PBR for most assets
- change to default light setup
local doc build

[docs] Update lighting-setups.rst

---

.pre-commit-config.yaml
examples/tutorials/colabs/rigid_object_tutorial.ipynb
examples/tutorials/nb_python/ECCV_2020_Advanced_Features.py
examples/tutorials/nb_python/ECCV_2020_Interactivity.py
examples/tutorials/nb_python/ECCV_2020_Navigation.py
examples/tutorials/nb_python/replay_tutorial.py
examples/tutorials/nb_python/rigid_object_tutorial.py
tools/sync_notebooks.sh

* This adds a new Pre-commit hook to check the CircleCI.yaml to make sure the config is valid.
* This also updates the JuPyText hook to use the new official pre-commit hook I contributed to the repo.
* Locally with pre-commit hook

[PRECOMMIT] Add CircleCI Validator and update JuPyText

---

src/esp/physics/bullet/BulletBase.cpp
src/esp/physics/bullet/BulletRigidObject.h

Migrating some physics fixes from Eric.
1. Scaling fix missed migration from master (#823)
2. Force activate then setting sleep(false)

[AO][bugfix] - physics fixes

---

src/esp/nav/PathFinder.h
src/esp/sim/Simulator.h

Seems like some bugs slipped around a recent clang-tidy update.  This PR hopes to address these.
local C++ and python tests pass.

[Bugfix] Address new clang-tidy complaints.

---

.circleci/config.yml

* This updates Magnum-Bindings to improve the bindings for the Corrade::Optional and also should fix the flakey coverage tests in CircleCI. 
* Locally and in CircleCI

[CircleCI][Magnum] make lcov less flaky and update bindings

---

data/test_assets/dataset_tests/dataset_1/test_dataset_1.scene_dataset_config.json
src/tests/MetadataMediatorTest.cpp

This PR expands the MM tests while making them more efficient and faster.  It also specifically tests glob file wildcard loading from scene dataset configuration files.
All existing c++ and python tests pass

Improve Metadata Mediator Testing

---

.gitignore

Just adding 'data/versioned_data' directory to git ignore.

--update to ignore data from automated dl.

---

src/esp/bindings_js/bindings_js.cpp
src/esp/bindings_js/modules/test_page.js
src/utils/viewer/viewer.cpp

This further develops the online Habitat viewer by adding a castRay binding for Javascript.
A test was added in test_page.js.

castRay function for Javascript

---

examples/tutorials/VHACD_tutorial.py
tests/test_examples.py

Apply recent API changes and add the tutorial to test_examples so future issues will be caught by CI.
New CI coverage.

[bugfix] update VHACD tutorial script

---

examples/tutorials/URDF_robotics_tutorial.py
src/esp/bindings/PhysicsObjectBindings.cpp
src/esp/bindings/PhysicsWrapperManagerBindings.cpp
src/esp/physics/ArticulatedObject.h
src/esp/physics/PhysicsManager.cpp
src/esp/physics/PhysicsManager.h
src/esp/physics/bullet/BulletArticulatedObject.h
src/esp/physics/bullet/BulletPhysicsManager.cpp
src/esp/physics/objectManagers/ArticulatedObjectManager.h
src/esp/physics/objectManagers/RigidObjectManager.h

Refactors URDF_robotics_tutorial.py to use the new object wrapper API + some supporting changes and bug-fixes.
Run the script.

[AO] refactor tutorial for new API

---

README.md

Fix a broken link in the readme.
I viewed the markdown preview in VS code.

Fix the readme Contents section to link to the Web Apps section

---

habitat_sim/__init__.py
habitat_sim/bindings/__init__.py
habitat_sim/physics.py
src/esp/assets/CollisionMeshData.h
src/esp/bindings/PhysicsObjectBindings.cpp
src/esp/bindings/PhysicsWrapperManagerBindings.cpp
src/esp/bindings/bindings.cpp
src/esp/physics/PhysicsManager.cpp
src/esp/physics/PhysicsManager.h
src/esp/physics/PhysicsObjectBase.h
src/esp/physics/RigidBase.h
src/esp/physics/bullet/BulletPhysicsManager.cpp
src/esp/physics/bullet/BulletRigidObject.cpp
src/esp/physics/bullet/BulletRigidObject.h
src/esp/physics/bullet/objectWrappers/ManagedBulletRigidObject.h
src/esp/physics/objectManagers/PhysicsObjectBaseManager.h
src/esp/physics/objectManagers/RigidObjectManager.cpp
src/esp/physics/objectManagers/RigidObjectManager.h
src/esp/physics/objectWrappers/ManagedPhysicsObjectBase.h
src/esp/physics/objectWrappers/ManagedRigidBase.h

This PR migrates a variety of minor changes from AO branch so they don't clog up upcoming PRs.
Includes:
- `built_with_bullet` python binding
- changes to rigid object managers
- re-naming and docstring cleanup 
Current tests pass.

[AO migration] minor changes

---

tools/create_basis_compressed_glbs.py

Fixes a typo in the script.
* bugfix. Caught by static analysis: https://lgtm.com/projects/g/facebookresearch/habitat-sim/snapshot/46a5eb8505859533636a5224d35738049c8ef0cb/files/tools/create_basis_compressed_glbs.py#x52a71506adf14e38:1

[bugfix] Fix typo in basis script

---

src/esp/bindings/AttributesBindings.cpp
src/esp/metadata/attributes/ObjectAttributes.h

Very small PR updating some bindings messages and rolling back a change from last week that is now causing certain scenes to be properly lit in certain instances.
All local python and c++ tests pass.

[BUGFIX] address some issues with configs

---

habitat_sim/__init__.py
package.json

Bump version to 0.2.0

---

docs/pages/index.rst

See https://github.com/facebookmicrosites/habitat-website/pull/98
This will merge after the above PR. The tutorial won't be live until the above PR merges.
http://rst.aaroniles.net/

add link to "Editing in Blender" tutorial

---

docs/Doxyfile-mcss
docs/conf.py
docs/docs.rst
habitat_sim/robots/mobile_manipulator.py
habitat_sim/simulator.py

Add legal policy links to docs
Visually.

Add legal polices and fix a couple little bugs in docs

---

habitat_sim/robots/fetch_robot.py
habitat_sim/robots/mobile_manipulator.py
tests/test_robot_wrapper.py

Necessary to have option to enable fixed base for kinematic base navigation with dynamic arm.
Parameterized the pytest.

Add fixed_base option to RobotInterface MobileManipulator

---

README.md

The recently released Habitat 2.0 paper needs to be in the references and citations list.
Same changes from #1354 but CI was unhappy with that PR. 🤷 
Visually inspected rendered README.

Update the Habitat 2.0 citation

---

examples/colab_utils/colab_install.sh

* Fixes a bug which broke the colab install script
* On Colab

[BUGFIX] Fix Colab install issue (scipy)

---

src/utils/viewer/viewer.cpp

This PR adds the ability to cycle through all the SceneInstances specified in the current dataset, starting with the chosen scene on the command line.  By pressing Tab/Shift-Tab, the user can cycle to the next/previous SceneInstance without having to reload any configuration data or restart (about 5 seconds per ReplicaCAD scene).
Locally - all changes are in viewer.cpp

Viewer Hot-swap scenes

---

.circleci/config.yml
conda-build/habitat-sim/build.sh
conda-build/linux_matrix_builder.py
conda-build/macos_matrix_builder.py
setup.py

* Example of building the Mac-OS conda-package through CircleCI.
* CircleCI

[CI] OSX Conda Build

---

habitat_sim/robots/__init__.py
habitat_sim/robots/fetch_robot.py
habitat_sim/robots/mobile_manipulator.py

Fixed a bug with the placement of the head camera. 
Updated camera positions and added more flexibility to the camera definitions in the robot wrapper and cleaned up this code. 
With the interactive play script from Habitat Lab. See output below.

Fixed head camera placement / configurable robot cameras

---

README.md

Video was broken. 
- [x ] Docs change / refactoring / dependency upgrade

Fixing video in readme

---

DATASETS.md

This note provides information about achieving the best quality rendering with replica.
Updating information about replica rendering.
None
- [x ] Docs change / refactoring / dependency upgrade
- [ x] My change requires a change to the documentation.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have completed my CLA (see **CONTRIBUTING**)

Added note about replica rendering

---

habitat_sim/__init__.py
package.json

Version bump v0.2.1

---

habitat_sim/utils/datasets_download.py

Updating the download script to get the most recent version of ReplicaCAD.
Locally

[BugFix] Update download script to get most recent version of ReplicaCAD dataset

---

src/esp/core/managedContainers/ManagedContainerBase.cpp

* Minor Perf Bugfix
* CI / Locally

[bugfix] Fix missing reserve call for std::vector for ManagedContainer

---

src/esp/scene/test/ReplicaSceneTest.cpp

Add missing logging context

---

src/esp/core/logging.cpp

to fix link error in debug build
built locally

add definition for LoggingContext::DEFAULT_LEVEL 

---

DATASETS.md

This PR provides instructions to load ScanNet scans in habitat-sim. This addresses issue #1142.

loading ScanNet scans in habitat-sim

---

codecov.yml

* Fixes a minor bug that included tests in codecov.
* With CI

CI: Don't include tests in codecov

---

.circleci/config.yml
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/questions-help-support.md
BUILD_FROM_SOURCE.md
CONTRIBUTING.md
README.md
docs/pages/asset-viewer-tutorial.rst
docs/pages/image-extractor.rst
docs/pages/index.rst
docs/pages/managed-rigid-object-tutorial.rst
examples/tutorials/colabs/ECCV_2020_Advanced_Features.ipynb
examples/tutorials/colabs/ECCV_2020_Interactivity.ipynb
examples/tutorials/colabs/ECCV_2020_Navigation.ipynb
examples/tutorials/colabs/ReplicaCAD_quickstart.ipynb
examples/tutorials/colabs/asset_viewer.ipynb
examples/tutorials/colabs/managed_rigid_object_tutorial.ipynb
examples/tutorials/colabs/replay_tutorial.ipynb
examples/tutorials/colabs/rigid_object_tutorial.ipynb
examples/tutorials/nb_python/ECCV_2020_Advanced_Features.py
examples/tutorials/nb_python/ECCV_2020_Interactivity.py
examples/tutorials/nb_python/ECCV_2020_Navigation.py
examples/tutorials/nb_python/ReplicaCAD_quickstart.py
examples/tutorials/nb_python/asset_viewer.py
examples/tutorials/nb_python/managed_rigid_object_tutorial.py
examples/tutorials/nb_python/replay_tutorial.py
examples/tutorials/nb_python/rigid_object_tutorial.py

This PR is part of our process to rename habitat-sim master to main.
The plan for the whole process:
1. get green checks on this PR (don't merge)
2. notify people of impending branch rename
3. merge this PR
4. rename habitat-sim master branch to main using the FB OSS tool (this should automatically update open PRs to merge to main instead of master)
5. update habitat-lab's old references to habitat-sim master (if any)
6. semi-related and part of this work: rename habitat-website master to main (similar process to above)
7. monitor nightly CI jobs and otherwise deal with problems that arise
(Note not part of this work: renaming habitat-lab master to main)
No testing yet. I expect to find problems after the fact (step 6 above).

change references to habitat-sim "master" branch to "main"

---

DATASETS.md

Fixes the broken link in the DATASETS.md file for HM3D dataset website.

added correct link to hm3d page

---

.circleci/config.yml

* Fixes one last miniconda error. Hopefully, this will restore our conda builds.

Fix one more miniconda reference

---

src/esp/bindings/AttributesBindings.cpp
src/esp/core/Logging.cpp

This PR has a few minor refactors that improve functionality : 
- Changing aborts to python errors in bindings that hide Configuration::set for Attributes.
- Improved Log message formatting.
Local C++ and python

[TechDebt]--Minor refactors

---

src/esp/bindings/SimBindings.cpp
src/esp/physics/PhysicsManager.h
src/esp/physics/bullet/BulletCollisionHelper.cpp
src/esp/physics/bullet/BulletCollisionHelper.h
src/esp/physics/bullet/BulletPhysicsManager.cpp
src/esp/physics/bullet/BulletPhysicsManager.h
src/esp/physics/bullet/BulletRigidObject.cpp
src/esp/physics/bullet/BulletRigidObject.h
src/esp/physics/bullet/BulletRigidStage.cpp
src/esp/physics/bullet/BulletRigidStage.h
src/esp/physics/bullet/BulletURDFImporter.cpp
src/esp/physics/bullet/CMakeLists.txt
src/esp/sim/Simulator.cpp
src/esp/sim/Simulator.h
src/tests/PhysicsTest.cpp
tests/test_physics.py

Some utils for troubleshooting Bullet collision-detection.
C++ PhysicsTest and python test_physics.py

Add Bullet collision helper

---

.circleci/config.yml

* Fixes the CI without upgrading to the latest Ubuntu and all the possible changes that come with it.
* Alternative to #1516

[CI]: Quickfix the CI by updating certificates

---

.gitignore

Ignore the downloaded data and the web assembly for the vr hand demo

--ignore js demo data and web assembly

---

README.md

Updated citation for NeurIPS 2021.

Updated citations

---

README.md

Add attribution for demo scene assets to README.md license section
Local preview of README.md update

Add attribution for demo scenes to README.md license section

---

src_python/habitat_sim/sensors/noise_models/gaussian_noise_model.py
src_python/habitat_sim/sensors/noise_models/poisson_noise_model.py
src_python/habitat_sim/sensors/noise_models/salt_and_pepper_noise_model.py
src_python/habitat_sim/sensors/noise_models/speckle_noise_model.py

This small PR addresses the missing slot declarations for pimpl refs in sensor models.   
Locally python tests pass

[Bugfix]--fix missing slots declarations of pimpl implementation refs.

---

.circleci/config.yml

Xcode11.3.0 is to be deprecated. Attempting to upgrade to 13.0.0.
Running the CI

Upgrading XCode in CI to 13.0.0

---

src_python/habitat_sim/simulator.py
tests/test_simulator.py

Fix a silly segfault.
Via the test.

Fix segfault on __init__ failure

---

src/utils/viewer/viewer.cpp

Added some helpful interaction utilities for the viewer:
- rotate an object gripped with a fixed constraint (`GRAB` mode `RIGHT` click) with mouse wheel
- ALT (yaw)
- CTRL (pitch)
- ALT + CTRL (roll)
- above+SHIFT to rotate faster
- debug line render projecting COM downward for easier understanding of depth without shadows
Cleaned up the help text and some other typos/redundant code
Locally w/ ReplicaCAD:
https://user-images.githubusercontent.com/1445143/149604432-778325bf-b251-4e1a-b11f-e77ce4d5c99a.mov

Viewer improvements

---

examples/viewer.py
src/esp/bindings/SimBindings.cpp
src/utils/viewer/viewer.cpp

This PR ports features from #1628 and #1624 and Bullet debug draw overlay to python viewer.
Locally with python viewer.

Python viewer improvements - GRAB rotation, Bullet debug, URDF load

---

examples/viewer.py
src_python/habitat_sim/gfx.py
src_python/habitat_sim/utils/viz_utils.py

Add scene cycling to Python viewer (`TAB` and `SHIFT+TAB`) and refactor scene reload to `ALT+TAB`.
Minor fixes:
- add missing license header to viz_utils.py
- expose DebugLineRender to habitat_sim module
Locally.

Python viewer improvements

---

README.md

Updated README to reflect headless not working with MacOS.

Updated README to Clarify MacOS Installation

---

data/matterport_semantics/matterport_category_mappings.tsv

This PR adds a table of semantic mappings for Mp3d and HM3D datasets.  It was [copied from here](https://github.com/niessner/Matterport/blob/master/metadata/category_mapping.tsv); our copy facilitates us having remappings, edits and expansions, if such things should become necessary.
Has no impact on existing c++ and python tests

--Add semantic mappings table used by MP3D/HM3D datasets.

---

.pre-commit-config.yaml
tests/test_physics.py

Python linting tool black has been updated to 22.1.0, so this PR updates the precommit hook yaml and updates the code in a test (test_physics.py) to be compatible

--Black python linting tool update to 22.1.0

---

.circleci/config.yml

Update the GPU resource class to address CI resource deprecation. 
CI

update gpu resource

---

src/esp/bindings/ShortestPathBindings.cpp
src/esp/nav/PathFinder.cpp
src/esp/nav/PathFinder.h
tests/test_navmesh.py

* This allow the efficient sampling of points of the navmesh within a specifeid radius of an existing point on the navmesh. This is useful as it allows the user to control the region the points are sampled from within the Navmesh.
* I also applied some clang-tidy fixits to make this file happy and a few other miscellaneous style fixes.
* Locally with pytest. All existing tests pass.

Pathfinder sample near point

---

DATASETS.md
src_python/habitat_sim/utils/datasets_download.py

Added download links for HM3D semantics v0.1 in `datasets_download.py`
Not yet tested. Waiting for permissions change on Matterport side.

Download links for HM3D semantics v0.1

---

README.md

Updates the README testing section to suggest interactive viewer (C++ and python) options and physics interactions testing with ReplicaCAD.
NOTE: I chose default console commands (i.e. instead of adding /path/to/habitat-sim/) for user quickstart copy-paste. 
Locally
- [x Docs change / refactoring / dependency upgrade
- [x I have updated the documentation accordingly.

Update README with interactive ReplicaCAD example

---

examples/viewer.py

- No longer try to recompute NavMesh for "NONE" scene which would previously crash the application.
- Include STATIC objects in the NavMesh recomputation
Locally

viewer.py minor NavMesh fixes

---

examples/viewer.py

Add contact debug visualization to viewer.py:
- `'c'` to perform discrete collision detection and render visualization of active contact points
- `SHIFT` + `'c'` to toggle visualization
Locally with ReplicaCAD

viewer.py contact debug visualization

---

DATASETS.md

This PR adds useful information for loading semantic annotations in HM3D.

Instructions for loading semantics in HM3D

---

DATASETS.md

This PR adds a link and explanation for including the appropriate scene dataset configuration file with the Gibson dataset, so that visual and semantic assets will display with the proper orientation.
Docs fix.

--updated DATASETS.md to reflect Gibson config download requirement.

---

src_python/habitat_sim/utils/datasets_download.py

New version 1.5 of ReplicaCAD includes the following changes:
- BASIS compressed asset textures for baked lighting scenes (reduced GPU memory and improved performance)
- NOTE: assets with uncompressed textures also provided for use in applications which don't support BASIS format (e.g. Blender)
- New NavMeshes with embedded settings for compatibility with #1724 
- Fixed incorrectly transparent underside of staircases
Local

ReplicaCAD v1.5

---

.circleci/config.yml
.pre-commit-config.yaml
conda-build/common/delete_old_night_packages.py
src_python/habitat_sim/nav/greedy_geodesic_follower.py
src_python/habitat_sim/robots/mobile_manipulator.py
src_python/habitat_sim/simulator.py

Public branch replacement for #1764.
Also updates clang-tidy CI job to Ubuntu 20 as 14 and 16 are deprecated.
CI

Flake8 comprehensions update

---

DATASETS.md

Additional habitat config setup has been fully encapsulated in the Replica repo (https://github.com/facebookresearch/Replica-Dataset/pull/80). This PR removes all specialized setup requirements from the README.
Locally

Update Replica dataset instructions

---

examples/tutorials/lighting_tutorial.py

As acknowledged in several issues (e.g. #1450), the lighting tutorial `Working with Lights` is a bit out of date. 
The goal of this PR is to apply necessary changes to fix and update the tutorial. 
Changes:
- To change the Stage lighting, `SimulatorConfiguration.override_scene_light_defaults` must be set to `True`
- Specify point vs. directional lights with homogenous 4th vector value (`directional == [x,y,z,0]`, `point == [x,y,z,1]`)
TODO:
- update the example settings to better values given new lighting schemes. 
On CI and locally.

[WIP][bugfix] - Working with Lights tutorial update

---

examples/tutorials/audio_agent.py

Update audio binaries

---

BUILD_FROM_SOURCE.md
docs/AUDIO.md

Add build instructions for audio sensors

---

package.json
src_python/habitat_sim/__init__.py

Update version to v0.2.2

---

src/tests/IOTest.cpp

bugfix for #1758.
CI install_and_test_ubuntu

[bugfix] - declare allocator in IOTest

---

src/tests/IOTest.cpp

* This PR updates pybind11 to the latest version which should allow habitat-sim to build on 3.11 beta, adds a bunch of speed and correctness fixes, and optimize pybind11 exception handling significantly, especially for large Python stack traces. This update should improve performance, build speed, and overall correctness of the Python bindings.
* I've also optimized the speed of handling of attributes, function casting, and other aspects of pybind11 in this PR which should hopefully further reduce overhead.

Update pybind11 to v2.10.0

---

README.md

making README consistent with Habitat-Lab readme

---

.circleci/config.yml

Added to habitat-lab CI in [PR 960](https://github.com/facebookresearch/habitat-lab/pull/906)
CI

[CI] Add cython for habitat-lab compatibility 

---

DATASETS.md

Documents how habitat test scenes and pointnav episodes can be downloaded.
Tested locally

Documenting habitat test scenes and pointnav episodes

---

src_python/habitat_sim/utils/datasets_download.py

Given new examples using the franka robot in habitat lab, the download utility was updated to include the source for the franka panda URDF model

Add Franka download

---

data/test_assets/dataset_tests/dataset_0/objects/dataset_test_object1.object_config.json
data/test_assets/dataset_tests/dataset_0/test_dataset_0.scene_dataset_config.json
data/test_assets/dataset_tests/dataset_1/test_dataset_1.scene_dataset_config.json
docs/pages/attributesJSON.rst
src/esp/bindings/AttributesBindings.cpp
src/esp/bindings/PhysicsObjectBindings.cpp
src/esp/metadata/attributes/ObjectAttributes.cpp
src/esp/metadata/attributes/ObjectAttributes.h
src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
src/esp/physics/RigidBase.h
src/esp/physics/bullet/BulletRigidObject.cpp
src/esp/physics/bullet/BulletRigidObject.h
src/esp/physics/objectWrappers/ManagedRigidBase.h
src/tests/AttributesConfigsTest.cpp
src/tests/MetadataMediatorTest.cpp
tests/test_configs.py
tests/test_physics.py

This PR exposes rolling and spinning friction coefficients for objects to the API and configuration system. 
CI tests include get/set through API and configuration system. Locally tested with viewer for correct physics behavior.

Add rolling and spinning friction coefficient parameters 

---

src_python/habitat_sim/utils/datasets_download.py

Given new examples using Spot robot in habitat lab, the download utility was updated to include the source for the Spot URDF model
Downloaded the dataset

Add Spot download

---

src_python/habitat_sim/utils/datasets_download.py

v0.2 is released, the downloader should get this version.
Note: changed downloader version from `1.0` to `0.2`. Appears to downgrade, but this should have been `0.1` to begin with.
Should be tested.

Update data downloader for hm3d v0.2

---

DATASETS.md

Update HM3D dataset details for v0.2

---

src/esp/nav/PathFinder.cpp

* Static Analysis seems to have missed this one. One more extra copy gone.

perf: add another missing move in pathfinder

---

src/esp/metadata/managers/AssetAttributesManager.cpp
src/esp/metadata/managers/LightLayoutAttributesManager.cpp
src/esp/metadata/managers/ObjectAttributesManager.cpp
src/esp/metadata/managers/PhysicsAttributesManager.h
src/esp/metadata/managers/SceneAttributesManager.cpp
src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
src/esp/metadata/managers/StageAttributesManager.cpp
src/esp/nav/PathFinder.cpp
src/esp/sim/Simulator.cpp

* Perf improvements backported to Gala_Kinematic

Apply perf improvements to gala_kinematic

---

.circleci/config.yml
.pre-commit-config.yaml
examples/fairmotion_interface.py
setup.cfg
src_python/habitat_sim/nav/greedy_geodesic_follower.py
src_python/habitat_sim/registry.py
src_python/habitat_sim/sensors/noise_models/no_noise_model.py
src_python/habitat_sim/sensors/noise_models/redwood_depth_noise_model.py
src_python/habitat_sim/simulator.py
src_python/habitat_sim/utils/data/data_structures.py
src_python/habitat_sim/utils/datasets_download.py

Branched from #1928 to handle cuda/pytorch incompatibility. 
Downgrades pytorch to 1.12 for compatibility with cuda 11.3 because Ubuntu 20.04 with llvm 11 supports system max cuda 11.4 and pytorch 1.13 min cuda version is 11.6.
CI passes!

Fix ci pytorch cuda

---

DATASETS.md

Add a table of contents to make dataset details easier to navigate
Local

[docs] - Add table of contents to DATASETS.md

---

README.md

We are directing all habitat-sim and habitat-lab users to the habitat-lab Discussions forum.
- [x ] Docs change / refactoring / dependency upgrade

Add a link to the github Discussions page on README

---

src_python/habitat_sim/utils/datasets_download.py

The v1 Fetch Suction robot gripper URDF model had the issue where some of the links would create strange ghost forces that were very large (>1 million Newtons in a single time step). This change adds the download to get the fixed Fetch model that no longer has this issue.

Added Updated Fetch Model

---

.circleci/config.yml

This fixes the ongoing Pytorch-CUDA CI issue by enforcing specific Anaconda dependencies.
A CI stage was also added for early validation of installed libraries.
Tested through CI.

Fix Pytorch-CUDA dependency on CI.

---

examples/colab_utils/colab_install.sh

Fixes https://github.com/facebookresearch/habitat-sim/issues/1965.

Fix baselines installation in colab_install.sh

---

src_python/habitat_sim/utils/datasets_download.py

Downloads human armature assets, required to control humanoid agent in Habitat
Tested the download script

Add Human Armature into Downloader

---

.gitignore

This adds JetBrains IDE config (PyCharm) to `gitignore`.
N/A

Add .idea to gitignore.

---

src/esp/sim/ClassicReplayRenderer.cpp

This add more rigorous context checks when creating classic replay renderer to help diagnose incorrect usage.

Add more rigorous context checks when creating classic replay renderer.

---

package.json
src_python/habitat_sim/__init__.py

Bumping version to v0.2.4 in advance of stable release.
CI

update to v0.2.4

---

src/esp/sim/BatchReplayRenderer.cpp

The batch renderer doesn't yet support 3D primitives, e.g. a render asset named `cubeSolid`. With this change, we skip instancing/visualizing the requested asset and print a warning (instead of the old behavior, which was a fatal file-not-found error).
Local testing.

BatchReplayRenderer: skip unsupported 3D primitives

---

src/cmake/FindMagnum.cmake
src/cmake/FindMagnumPlugins.cmake

Another batch of updates since #2032 a month ago:
- Minor fix for compatibility with Clang 16
- Fixed a GCC warning that started appearing after introduction of GL texture view APIs; fixing various other GCC-specific false-positive "uninitialized variable" warnings
- Various fixes to allow creation and use of [Trade::MeshData](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1MeshData.html) over 4 GB, because with Floorplanner and the batch renderer that'll be an increasingly common use case :fire:
- Dropped a fancy *guaranteed-to-be-more-correct-than-what-everyone-was-using* implementation of [Matrix4::normalMatrix()](https://doc.magnum.graphics/magnum/classMagnum_1_1Math_1_1Matrix4.html#aae3f4e7f98d6838ef7be4f70531a7583) because it actually wasn't correct at all, causing issues …

Update Magnum submodules to latest

---

DATASETS.md

To add HSSD scene dataset information, download links, etc. along with the dataset release.

Adds HSSD (Habitat Synthetic Scene Dataset) and AI2THOR-hab dataset info

---

.pre-commit-config.yaml
examples/demo_runner.py
examples/instance_segmentation/common.py
pyproject.toml
src_python/habitat_sim/agent/agent.py
tests/test_agent.py
tools/create_basis_compressed_glbs.py
tools/npz2scn.py

* Ruff is a faster, more featureful reimplementation of flake8 in rust that also provides autofixes

[BE Week] Add Ruff pre-commit hook

---

package.json
src_python/habitat_sim/__init__.py

Update module version to v0.2.5 for release.
CI

version bump v0.2.5

---

DATASETS.md
src_python/habitat_sim/utils/datasets_download.py

Updating DATASETS.md to provide downloader info for HSSD.
NA

[docs] Add details for getting hssd from datasets_downloader

---

.gitignore

This adds `data/humanoids` to `.gitignore`.

Add humanoids to gitignore.

---

DETAILS.md

This provides the JS documentation with up-to-date setup commands.
The commands were tested on a new configuration.

Update JS build doc.

---

src/esp/gfx/RenderTarget.cpp
src/esp/gfx_batch/Hbao.cpp
src/esp/gfx_batch/Hbao.h
src/shaders/gfx_batch/hbao/fullscreenquad.geom
src/shaders/gfx_batch/hbao/hbao.frag
src/shaders/gfx_batch/hbao/hbao_deinterleave.frag
src/tests/GfxBatchHbaoTest.cpp

This PR adds benchmarking for the HBAO effect for various permutations of the various options available.
Here's how various configurations are performing (thanks @mosra for the great graphic)
C++ tests pass.

--Add benchmarking for HBAO effect.

---

.circleci/config.yml
src_python/habitat_sim/utils/datasets_download.py

Update to new supported machine images.
Adds an additional lfs pull to the dataset clone flow to correct for new system issues.
CI

[CI] - resource class update

---

src_python/habitat_sim/utils/datasets_download.py

- Added `hab3-episodes` HF download link. 
- HF no longer allows password authentication. I switched the downloader to use SSH for the HF sources with `requires_auth=True`.
- Updated humanoid data source.
Tested locally downloading data.

New HF Dataset Download

---

package.json
src_python/habitat_sim/__init__.py

update version tags to v0.3.0

---

src_python/habitat_sim/utils/datasets_download.py

Updates auth requirement for now-public repos and sets hssd-hab version to `main`.
NA

Update Hab3 entries for datasets_download.py

---

src_python/habitat_sim/utils/datasets_download.py

HSSD is no longer gated, so does not need the auth flag.

Correct HSSD public repo to un-authenticated

---

DATASETS.md
build_js.sh
src/CMakeLists.txt
tools/create_basis_compressed_glbs.py
tools/sync_notebooks.sh

This addresses typos in top-level files and tools.
N/A

Fix typos in top-level files and tools.

---

docs/README.md

This fixes a command in the docs `README.md`.

Update doc readme.

---

.circleci/config.yml

Update the ssh key for website deployment.
Tested with changes in previous commit.

[ci] - new website key

---

src_python/habitat_sim/utils/datasets_download.py

They should be there so tests are not skipped.
CI

[CI] - Add hm3d example scenes to ci test assets

---

src_python/habitat_sim/utils/datasets_download.py

v1.2 has a misnamed folder causing collision proxies not to be loaded. Fixed on main, use that instead.
locally

Get ycb dataset from main branch

---

package.json
src_python/habitat_sim/__init__.py

bump the version to 0.3.1

---

DATASETS.md

Update AI-2Thor hab links in DATASETS.md

---

.pre-commit-config.yaml
src_python/habitat_sim/utils/viz_utils.py

CI is failing with a new mypy error. This PR fixes the error and update the pre-commit mypy version to match the CI lint version.
locally ran mypy 1.9.0 and resolved the issue

[CI] - fix mypy on CI

---

requirements.txt

This updates the minimum scipy version to match `habitat-lab`.
The current version is obsolete and vulnerable.
CI

Update minimum scipy version.

---

src/cmake/FindGLFW.cmake

Another two months worth of random Corrade + Magnum updates.
Mainly contains various fixes and updates to the Python bindings to make it possible to generate stubs for IDE autocompletion and type checking.
Besides that, the update contains the following:
- New [Containers::StringView::count()](https://doc.magnum.graphics/corrade/classCorrade_1_1Containers_1_1BasicStringView.html#a40396c33b33c92deb820c2130eaf6c15) and [Utility::String::commonPrefix()](https://doc.magnum.graphics/corrade/namespaceCorrade_1_1Utility_1_1String.html#ad948cc3cfb619dde9deb7f1d012ec928) APIs, internally with SSE2, AVX2 and WASM SIMD variants
- [Utility::String::replaceAllInPlace()](https://doc.magnum.graphics/corrade/namespaceCorrade_1_1Utility_1_1String.html#ac2501662a6ae75e262549dbf02840135) gained a SSE4.1, …

Update Corrade and Magnum with changes for Python stub generation

---

.circleci/config.yml
.gitignore

CI dropped support for intel mac this past June, so we need to use miniconda for M1.
Execution on CI

--[CI BugFix] -Change circle CI mac conda install from intel mac to m1.

---

.gitignore

Small update to git ignore : 
- Remove ancient references to semantic test assets
- Reorganize `/data/` ignore pattern - ignore everything in data except currently specified directories and files. This is to facilitate development, while also requiring any additions to the /data/` to be explicitly specified (since data should be accessed via the downloader and stored elsewhere)
- Add ignore for local src/test/configure.h shortcut for gitkraken users :) (which does not support .git/info/exclude specifications)
Via git access

--Update/cleanup gitignore

---

.circleci/config.yml

Our [CI Ubuntu image](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177) is being removed on September 30. This change will hopefully dodge this at least until we can move to greener pastures (github actions)

--[CI] - Modify ubuntu image to dodge brownout/deprecation

---

src/esp/metadata/URDFParser.cpp

This PR is for any necessary c++ fixes we come across as we prepare the HSSD datset for primetime. These fixes originated in [the branch we're using for this effort](https://github.com/facebookresearch/habitat-sim/tree/hssd_ao_utilities_JT).
Fixes/Mods so far :
- A check and remedy was added to test for box primitives used in the construction of AOs having 0-length dims specified in their metadata.

--[BE/Bugfix] - Sim c++ fixes exposed by HSSD effort

---

package.json
src_python/habitat_sim/__init__.py

version bump to v0.3.2

---

src/esp/gfx/DebugLineRender.cpp

Addresses if the normal vector is [0,0,-1].
Locally c++ and python

--[BUGFIX] - DebugLineRender : minor bug in perp vector gen

---

src_python/habitat_sim/utils/datasets_download.py

Adds new public repos to the dataset_download for use in CI and installation processes.

add PARTNR data repos to the dataset_downloader

---

src/esp/assets/ResourceManager.cpp
src/esp/bindings/ConfigBindings.cpp
src/esp/metadata/URDFParser.cpp
src/esp/metadata/attributes/AbstractAttributes.h
src/esp/metadata/attributes/AttributesEnumMaps.cpp
src/esp/metadata/attributes/LightLayoutAttributes.cpp
src/esp/metadata/attributes/SceneInstanceAttributes.cpp
src/esp/metadata/attributes/SemanticAttributes.cpp
src/esp/metadata/managers/AbstractAttributesManager.h
src/esp/metadata/managers/AssetAttributesManager.cpp
src/esp/metadata/managers/AssetAttributesManager.h
src/esp/metadata/managers/LightLayoutAttributesManager.cpp
src/esp/metadata/managers/PbrShaderAttributesManager.cpp
src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
src/esp/metadata/managers/SceneDatasetAttributesManager.h
src/esp/metadata/managers/SceneInstanceAttributesManager.cpp
src/esp/sensor/CameraSensor.cpp
src/esp/sensor/VisualSensor.cpp
src/esp/sim/BatchPlayerImplementation.cpp
src/esp/sim/BatchReplayRenderer.cpp
src/esp/sim/ClassicReplayRenderer.cpp

This PR is for various random small clean up and refactor tasks, to help other, larger PRs to stay uncluttered, as well as to address the various warnings that the recent addition of pedantic warning output messages has helped illuminate.
Locally c++ tests

--[BE] - Miscellaneous Clean-up and Refactors

---

.github/workflows/install_and_test.yml

Nightly workflow runs are failing conda build deployment, debugging and patching here.
workflow runs

[CI] fix nightly conda deployment

---

src/tests/HM3DSceneTest.cpp

Small PR to update HM3DSceneTest's asset source directory to correct location so test will not skip.
Locally C++

--Use correct path for HM3DSceneTest

---

.github/workflows/install_and_test.yml
src/esp/bindings/AttributesManagersBindings.cpp

Small BE PR. Nightly run needed to test.
CI

[BE] - bindings variable names and pass the upload flag for nightly osx conda

---

src_python/habitat_sim/__init__.py

bump the version to v0.3.3

---

src/cmake/FindBullet.cmake
src/cmake/FindCorrade.cmake
src/cmake/FindMagnum.cmake
src/cmake/FindMagnumBindings.cmake
src/cmake/FindMagnumIntegration.cmake
src/cmake/FindMagnumPlugins.cmake
src/esp/assets/GenericMeshData.cpp
src/esp/assets/ResourceManager.cpp
src/esp/core/Logging.cpp
src/esp/core/managedContainers/AbstractFileBasedManagedObject.h
src/esp/core/managedContainers/ManagedFileBasedContainer.h
src/esp/gfx/DebugLineRender.cpp
src/esp/gfx_batch/Renderer.cpp
src/esp/io/Io.cpp
src/esp/metadata/managers/AbstractAttributesManager.h

Regular, 35th update of Magnum dependencies.
This update mainly fixes an old TODO for a more efficient vertex data import in `GltfImporter`, where certain files such as [the Buggy from the glTF sample models repository](https://github.com/KhronosGroup/glTF-Sample-Models/tree/main/2.0/Buggy) expanded to over 800 MB of mesh data, while the file alone is just ~7 MB.
With this fix I removed a [MeshTools::interleave()](https://doc.magnum.graphics/magnum/namespaceMagnum_1_1MeshTools.html#aa9114dc837636b2f5870289c05aa909b) call inside `GenericMeshData` which was primarily put there to counter the above issue. In certain cases, such as depth-only rendering, it may be beneficial to have the model files processed for example with positions *not* interleaved with the other attributes, and this call …

Update to latest Magnum with more efficient glTF mesh import and various UX improvements
