facebookresearch/habitat-sim

- src/esp/scene/Mp3dSemanticScene.cpp
- src/esp/scene/SemanticScene.h
The MP3D bounding boxes need to be transformed to -Y down instead of -Z down to fit with the coordinate system that the agent/world is in.
Compiles and we use this exact same transform (I literally copied that line) to rotate the MP3D meshes to -Y down, so it should work here too!
> Fix orientation of MP3D bounding boxes

- src/esp/scene/SemanticScene.h
- src/tests/Mp3dTest.cpp
- src/tests/SuncgTest.cpp
Segfaults are no fun, see https://github.com/facebookresearch/habitat-api/issues/59 for full context.
I also changed the return types of things related to the semantic scene to be shared_ptr instead of references as nullptr becomes `None` on the python side, so now if you do `obj.region.id` for an object with no region, you get a nice, pythonic error message:
```
Traceback (most recent call last):
File "repro.py", line 11, in <module>
obj.region.id
AttributeError: 'NoneType' object has no attribute 'id'
```
With the following code:
```
import habitat_sim
cfg = habitat_sim.SimulatorConfiguration()
cfg.agents = [habitat_sim.AgentConfiguration()]
cfg.scene.id = "./data/scene_datasets/mp3d/ur6pFq6Qu1A/ur6pFq6Qu1A.glb"
sim = habitat_sim.Simulator(cfg)
for obj in sim.semantic_scene.objects: …
```
> Properly handles objects that don't have a region and regions that don't have a level

- habitat_sim/bindings/__init__.py
- habitat_sim/bindings/dev_bindings.py
- habitat_sim/bindings/mode.py
- setup.py
Issue #13 brought up that the current method of figuring out how to import the bindings leads to confusing error messages when things are installed with `setup.py.   The relevant error, that it couldn't import `habitat_sim._ext.habitat_sim_bindings`, is buried by the error message that it couldn't import the bindings in developer mode.  
This PR uses `setup.py` to modify the value of a variable such that the code knows where it should expect the bindings to be, and only looks in that location.
Installed in a clean conda environment.  After deleting the `build` folder and doing `unset PYTHONPATH`, `python examples/example.py` works.   Doing
```
cd ..
python
>>> import habitat_sim
```
also works.  That `cd ..` is still key however.
In a different clean conda environment, I built with …
> Better install with setup.py

- src/esp/bindings/bindings.cpp
- src/esp/scene/Mp3dSemanticScene.cpp
- src/esp/scene/Mp3dSemanticScene.h
- src/esp/scene/SemanticScene.h
- src/esp/scene/SuncgSemanticScene.cpp
- src/esp/scene/SuncgSemanticScene.h
- tests/test_agent.py
- tests/test_semantic_scene.py
PyBind11 requires explicit bindings whenever subclasses are used to implement an abstract base class or when a subclass is used to override virtual methods.  Those subclasses weren't bound, which results in memory corruptions.
Also binds a lambda for the OBB rotation as we can't convert an `Eigen::Quaternion` into python
https://github.com/facebookresearch/habitat-api/issues/59
With the following re-production script:
```
import habitat_sim
cfg = habitat_sim.SimulatorConfiguration()
cfg.agents = [habitat_sim.AgentConfiguration()]
cfg.scene.id = "data/scene_datasets/mp3d/ur6pFq6Qu1A/ur6pFq6Qu1A.glb"
sim = habitat_sim.Simulator(cfg)
scene = sim.semantic_scene
for obj in scene.objects:
obj.id
obj.category.name()
obj.category.index()
for region in scene.regions:
region.id …
```
> Exposes the subclasses used for {Mp3d, Suncg}SemanticScene

- src/esp/gfx/GenericShader.cpp
- src/esp/gfx/PTexMeshShader.cpp
- src/esp/gfx/Viewer.cpp
Recent updates in MacOS and clang have caused build errors and runtime crashes in the viewer app (see #16).  Updating to latest upstream Magnum resolves build issues, while explicit setting of pixel buffer size in viewer resolves the viewer runtime crash.
Build was tested on MacOS 10.14.4 with Xcode 12.1 (clang-1001.0.46.4) and on Ubuntu 18.04.1 with gcc 7.1.0. Viewer no longer crashes on latest MacOS. 🙂
> Update to latest Magnum and fix Viewer crash on latest MacOS

- src/esp/gfx/Viewer.cpp
The overloaded `setHelp()` function led to many accidents where option help was mistakenly set as global help (as seen here as well), the overload got renamed to `setGlobalHelp()` to avoid such mistakes. The code was updated to use the new API.
No deprecation warnings are emitted during compilation anymore. No functional change, apart from correct label being printed in viewer's `--help`.
> esp/gfx: update Viewer to not use deprecated Utility::Arguments APIs

- .gitignore
- setup.cfg
- setup.py
- src/esp/gfx/Viewer.cpp
While #24 said that
> do we expect people to be multitasking while installing habitat-sim [...]?
I'm actually one of those crazy multitaskers :) 100% CPU wouldn't be a problem, but when running on all cores, *something* in the build demands 8 GB of RAM which I usually don't have, so my system comes to a grinding halt. (I still want to investigate what's responsible and if it's possible to tell `ninja` to not overschedule such jobs.)
While the default is still *all the cores*, it now allows to override the setting using the setuptools' builtin `--parallel` option. Together with redirecting it to use a pre-existing CMake build (which was set up manually for #35) dir my command-line looks like this:
```sh
python setup.py build_ext --build-temp=build --parallel 3
```
Apart from this, because …
> Setup py improvements

- src/esp/gfx/GenericDrawable.cpp
On devfair, OpenGL optimizes out the dummy `objectId = uint(objectIdUniform);` when rendering with ID textured meshes, which then produces an annoying `GL::AbstractShaderProgram: location of uniform 'objectIdUniform' cannot be retrieved` warning.  This PR simply adds PrimitiveIDTextured meshes to the list of things to not set the `objectIdUniform` with.  This is fine in both the case where the line is and isn't optimized out.
`pytest` passes both on linux box and my local MacOS laptop.
`pytest -s` has no annoying `GL::AbstractShaderProgram: location of uniform 'objectIdUniform' cannot be retrieved` warnings.
> Gets rid of GLSL undefined uniform warning

- README.md
- examples/benchmark.py
- examples/demo_runner.py
- examples/example.py
- examples/settings.py
- habitat_sim/utils.py
The `benchmark.py` script assumed the presence of a `test.glb` file and had unexpected behavior when the file was not present.  Moreover, multi-process benchmarking was not incorporated, making it hard to reproduce the benchmark table out-of-the-box.  @danielgordon10 thanks for bringing up this issue.
This PR removes defaulting of the `--scene` argument from both `benchmark.py` and `example.py` and requires the user to specify the intended scene, avoiding confusing behavior and unexpected errors.  It also incorporates multi-process benchmarking implemented by @erikwijmans .
Download the Matterport3D Habitat data and run `examples/benchmark.py --scene /path/to/mp3d/17DRP5sb8fy/17DRP5sb8fy.glb`. The benchmark script should output a table similar to the one below:
```
================ …
```
> Fixes and improvements to benchmark script

- setup.cfg
setup.py makes no sense and the install breaks if you set inplace to be the default for build_ext!
In a fresh conda env with `python setup.py install`
> setup.py: Can't do inplace=1 because that breaks the install

- habitat_sim/agent/agent.py
- habitat_sim/agent/controls.py
- habitat_sim/agent/default_controls.py
The current way the controls are defined is kinda confusing at the delineation between body action and not is not apparent at the definition of the control!
This PR aims to fix this by having the `register_move_fn` take an argument that determines control or not.  I also made the controls a class that implements a `__call__` function as that way `body_action` can be set on a per-instance basis.
Closes #52 #51 
Via `pytest`
> Revamps controls

- setup.py
One my changes to setup.py broke the compile commands, so my auto-complete doesn't work and I can only code with auto-complete!
By me, I can now code again!
> Fix compile_commands

- .circleci/config.yml
- examples/example.py
CI setup that runs tests using GPU machines:
- Builds and installs habitat-sim with ` python setup.py install` and `./build.sh --headless`
- Runs `pytest` tests on habitat-sim with testing data
- Added speed regression test with FPS threshold (900 FPS) , thanks @erikwijmans for advice how to do it in elegant way.
- Added run of habitat-api tests on master branch. That will guarantee that HSIM changes won't break HAPI
- Added pytorch installation and running habitat baseline test in prediction mode. That maybe too much of testing, but decided to keep it for now.
Have ideas how to speed  up and parallelize jobs. Will follow up in next PRs.
Tests time estimations:
```
Install conda and dependencies 02:56
Install cuda 04:32
Build, install habitat-sim and run benchmark 03:13
Run sim tests …
```
> CI setup that runs tests e2e testing using GPU machines

- examples/stereo_agent.py
- tests/test_examples.py
See #56 for context!
This one adds an example of creating an agent that uses a stereo RGB pair or a stereo depth pair.  The displaying to the user is done via cv2
Also via the new smoke test in pytest.
-  New feature (non-breaking change which adds functionality)
> Example of creating a stereo agent

- tests/test_greedy_follower.py
I Ctrl-C'd while running the `test_greedy_follower` test and instead of `KeyboardInterrupt` it ended up with a "variable referenced before assignment" error on the line with `raise e`. This fixes it simply by copying it from the similar code below.
Everything compiles and runs, tests pass and do the expected thing during Ctrl-C.
> Tests: fix a "variable referenced before assignment" error

- habitat_sim/simulator.py
- src/esp/bindings/bindings.cpp
- src/esp/gfx/Simulator.cpp
- src/esp/gfx/Simulator.h
- tests/test_semantic_scene.py
- tests/test_sensors.py
Sometimes we don't need sensors (generating datasets for instance), so it is nice to not need to load-up the mesh and get a rendering context.  This PR allows the simulator to be configured without any sensors.
I adapted the test for the semantic annotations to use its own instance of the simulator loaded up with no sensors -- this ensures that the semantic scene graph is also loaded.  This test would crash due to having two OpenGL contexts if the no-sensor thing didn't work :)
> Support no sensors

- src/cmake/FindCorrade.cmake
- src/cmake/FindMagnum.cmake
Pulling in a new version of `magnum-bindings` along with all other Magnum projects to have a consistent state. What this brings:
* A performance fix for converting Magnum Vector types to `np.array` where due to (probably) unfortunate perf issues of pybind11exceptions the conversion took 20x more than it should. The fix is done by implementing also the other side of the buffer protocol instead of relying on automatic creation of np.array from iterable types.
* Magnum Python bindings now require the freshly released pybind11 2.3.0 (which allowed them to drop some ugly workarounds). Updated the pybind11 submodule here to that version tag as well so we don't depend on a random commit from master.
* All Magnum projects now build on MSVC 2019, plus there's a new …
> Update Magnum and Python bindings

- habitat_sim/agent/agent.py
- habitat_sim/agent/controls.py
- habitat_sim/agent/default_controls.py
- src/esp/bindings/ShortestPathBindings.cpp
- src/esp/bindings/bindings.cpp
- src/esp/nav/PathFinder.cpp
- src/esp/nav/PathFinder.h
- src/esp/scene/SceneNode.h
Slightly faster implementations of things since a lot of the internal logic now uses magnum types instead of numpy types.
Via a profiling script using python's `cProfile` package.
Performance enhancement
> Performance enhancements

- habitat_sim/agent/agent.py
- habitat_sim/nav/greedy_geodesic_follower.py
- habitat_sim/utils.py
- src/esp/bindings/OpaqueTypes.h
- src/esp/bindings/ShortestPathBindings.cpp
- src/esp/bindings/bindings.cpp
- The binding code was referencing types that weren't known yet to pybind (either described later or not at all), causing the exported functions to have C++ names in their signatures, making them unusable from Python.
- Various Python APIs had wrong type annotations. In particular, the `np.array()` is a function, the correct type is `np.ndarray`. Unfortunately that's all we can annotate for now; type, dimensionality and size needs to wait until https://github.com/numpy/numpy/issues/7370.
Discovered while running [m.css](https://mcss.mosra.cz) on the project to generate docs for the Python side.
It builds? :sunglasses: 
This brings no functional change, so should be easy to review and merge.
> Fix bindings cyclic type references and type annotations

- README.md
- setup.py
The behavior of not installing magnum if you already have it is nice for development and incremental builds, but not nice for user.  This PR makes reinstalling magnum the default and adds a `--skip-reinstall-magnum` flag to the build to skip the reinstall.
`build.sh` and `setup.py install` now both always install magnum by default.
-  Bug fix (non-breaking change which fixes an issue)
> Make installing magnum always the default

- .circleci/config.yml
- pyproject.toml
- Added caching to CI and synced with habitat-api.
- Added smoke test for training of baselines
- Fixed Pytorch caching installation and habitat-api
- Added ccaching to speed up build: it should fall back to master branch ccache for new branches. (https://circleci.com/docs/2.0/caching/#source-caching)
Full testing drops from **18 minutes to 9 minutes(2x times)** for second run. That will help run testing on same PR faster.
Build step drops from **5 minutes to 2 minutes(2x times)** with ccache usage
> Added caching and ccaching to CI and synced with habitat-api

- habitat_sim/agent/default_controls.py
The move controllers should move the scene-node in its local coordinate system, not the global coordinate system as currently the move controllers don't make any sense when moving a sensor instead of the agents body.
Via in interactive viewer.
-  Bug fix (non-breaking change which fixes an issue)
> Move actions in local coordinates

- src/esp/assets/PTexMeshData.cpp
- src/esp/gfx/WindowlessContext.cpp
Should help with #84 -- we don't need to reinvent things that are already implemented and tested :) Also made the code a bit more `const`-correct and simplified some pointer chasings.
It builds for me on Linux.
~~:warning: Even though the change is pretty straightforward, there's not much to screw up and the underlying API has been extensively tested in other contexts, unfortunately I'm afraid I don't have any PTex mesh data to give this a *real* test, sorry.~~ Successfully tested with Replica.
> Switch to a multiplatform mmap implementation.

- .editorconfig
- habitat_sim/simulator.py
- src/cmake/FindMagnumIntegration.cmake
- src/cmake/FindMagnumPlugins.cmake
- src/esp/assets/GenericInstanceMeshData.cpp
- src/esp/assets/ResourceManager.cpp
- src/esp/bindings/bindings.cpp
- src/esp/gfx/RenderingTarget.cpp
- src/esp/gfx/RenderingTarget.h
Following [the discussion on #114](https://github.com/facebookresearch/habitat-sim/pull/114#discussion_r305228969) this updates the code to avoid an unnecessary memcpy of each frame. I set the `gpu-gpu` branch as base so you see just my changes here, not all of #114 as well.
I was not sure what should be exposed to Python and what not, exposing the whole framebuffer in order to make it possible for the user to call [gl.Framebuffer.read()](https://doc.magnum.graphics/python/magnum.gl.Framebuffer.html#read-2c68b) seemed *a bit* much, OTOH exposing just a [MutableArrayView](https://doc.magnum.graphics/python/corrade.containers.MutableArrayView.html) felt too typeless, so I'm exposing [MutableImageView](https://doc.magnum.graphics/python/magnum.MutableImageView2D.html), which contains size …
> Zero-copy transfer of image data

- habitat_sim/simulator.py
- src/esp/bindings/bindings.cpp
- src/esp/gfx/GenericShader.h
- src/esp/gfx/RenderingTarget.cpp
- src/esp/gfx/WindowlessContext.cpp
Another addition to #114, with `gpu-gpu` being the base branch. Again deleting more code than it adds, I'm slowly removing all code here, sorry :laughing: 
~~**Note:** the last commit in this PR is a bit controversional, so you might want to look at the [diff without this change](https://github.com/facebookresearch/habitat-sim/compare/gpu-gpu...gpu-gpu-additions^) first ;)~~ last commit removed, it unconvered a serious problem I will need to look at.
What this does:
- the Magnum Python bindings now have a better way to expose classes that need to refcount their dependencies (such as `ArrayView`, `ImageView` or `GL::Framebuffer`), meaning there are no `PyImageView` types and such and it's possible to just directly expose the classes to Python without any hassle.
- I went around all Clang …
> Further improvements to python-side framebuffer reading

- src/esp/nav/GreedyFollower.cpp
The current heuristics of the greedy follower are set very conservatively such that it maximizes how often it is able to find a goal.  These have been set too conservatively and it commonly generates odd looking and not very short action-space paths.  This PR sets those significantly more aggressively such that the paths are significantly shorter (about 30% shorter on average).  This comes at the cost of how often it fails to find a path --  it fails to find a path about 6x more than it use to -- but it still finds a path 99.9% of the time (failed to find a path 600 times over 600k tests).
With the unit test.
-  New feature (non-breaking change which adds functionality)
> Update greedy follower heuristics

- .circleci/config.yml
- src/CMakeLists.txt
Fixes #137. Ideally this would be done via `configure_file()` together with other options, but as that's not that urgent, I'm throwing that on the pile in #42.
@mathfac (or somebody who's in charge of the CI) -- can we configure the CI to use some older CMake version (3.8, for example) so these issues get caught early enough? For Magnum itself I'm going as far as 3.1, but I don't think that level of compatibility is needed here. I'm on Arch and most of you are on macOS, which means we all probably have 3.15, but we shouldn't forget about LTS Linux distros.
Things that worked before continue to work; things that temporarily didn't work are working again.
> Avoid using too new CMake features

- .editorconfig
- src/cmake/FindCorrade.cmake
- src/cmake/FindEGL.cmake
- src/cmake/FindMagnumIntegration.cmake
- src/cmake/FindMagnumPlugins.cmake
- src/esp/assets/GenericInstanceMeshData.cpp
- src/esp/assets/ResourceManager.cpp
- src/esp/gfx/GenericShader.h
- src/esp/gfx/Renderer.cpp
This should be a fairly noncontroversial change, just pulling latest submodules and adapting code when needed, in the least invasive way. There's a minor code simplification in Renderer, as the [Image::data&lt;T&gt;()](https://doc.magnum.graphics/magnum/classMagnum_1_1Image.html#a0e2fd4c4389ae9c10ff5bd9eed3ba20a) functions are now deprecated in favor of better APIs with proper bounds checking -- and thus we can just reuse the bounds information from there.
Part of these changes is already present in #114, but I need those on master so I figured it would make sense to submit them separately.
Magnum's CI is as green as ever and this builds properly as well, implying things continue to work just the way they did before.
> Update Magnum to latest

- src/esp/gfx/Renderer.cpp
Fixes the following GL_ERROR on WebGL:
glClear: can't be called on integer buffers
The problem is that glClear will clear all glDrawBuffers.
Before this change, the main color_attachement was not clearing.
Tested with work-in-progress embind patch.
> Fix WebGL glClear issue.

- examples/demo_runner.py
- examples/example.py
FPS have inverse relation to the performance and thus are hard to reason about. Example output:
```
========================= Performance ======================== 
640 x 480, total time 15.1 s, frame time 3.010 ms (332.3 FPS)
============================================================== 
```
The output is rearranged a bit to fit all the values better, the FPS output in the dict is kept as-is to preserve the FPS regression test behavior (but those would be ideal to have converted to frame time as well, at some point).
It prints both frame time and FPS and their product seems to be 1 second :tada:
> Show both frame time and FPS in the benchmark

- src/esp/assets/FRLInstanceMeshData.cpp
- src/esp/assets/GenericInstanceMeshData.cpp
- src/esp/assets/PTexMeshData.cpp
- src/esp/gfx/GenericDrawable.cpp
- src/esp/gfx/GenericShader.h
- src/esp/gfx/Renderer.cpp
- src/shaders/generic-default-gl410.frag
- src/shaders/generic-default-gl410.vert
This is a first step towards the goal of integrating Magnum builtin shaders -- they don't have any such feature and thus it was a blocker that had to be removed first.
Apart from that this gives a nice little speedup in color-only rendering (0.2 ms) thanks to one clear less and one less render target being written to; while the additional operations for depth rendering aren't really slower in total.
Pytest passes (it was a *pain* but yes it does!), CI passed the 1400 FPS milestone :tada:
> Reuse GPU-created depth buffer and unproject it during a read

- .circleci/config.yml
Doing the same as here: https://github.com/facebookresearch/habitat-api/commit/dd75f18fb81e00810126a46c23c812e75230e86f#diff-1d37e48f9ceff6d8030570cd36286a61
I expect the CI to not be red anymore.
> CI: adapt to be consistent with habitat-api

- src/esp/sensor/PinholeCamera.cpp
This was causing frames from rgba_sensor to be stretched.
The bug was recently introduced by me in PR#141. Since know one yet uses this API, no one was affected by this bug.
Before:
After:
With this fix, frames pulled from the rgba_sensor are no longer stretched when specifying a width of 640 and height of 480.
> Height and width were swapped in PinholeCamera.

- src/esp/agent/CMakeLists.txt
- src/esp/assets/CMakeLists.txt
- src/esp/bindings/CMakeLists.txt
- src/esp/core/CMakeLists.txt
- src/esp/geo/CMakeLists.txt
- src/esp/gfx/CMakeLists.txt
- src/esp/io/CMakeLists.txt
- src/esp/nav/CMakeLists.txt
- src/esp/physics/CMakeLists.txt
- src/esp/physics/bullet/CMakeLists.txt
- src/esp/scene/CMakeLists.txt
- src/esp/sensor/CMakeLists.txt
- src/esp/sim/CMakeLists.txt
Part of #42. I tried to postpone this but finally lost patience when a branch switch *again* led to linker errors :sweat_smile: There are several reasons why this is bad (and why CMake guides discourage this practice):
* Newly added files aren't detected unless CMake is explicitly run again (which is slow). Running just ninja won't pick them up, leading to linker errors or other strange issues. This makes switching branches and other tasks more painful than it should be and incremental builds aren't reliable.
* Target-dependent compilation has to *remove* files from the list instead of adding them, which is less clear.
* It's not possible to have untracked cpp files in the working copy (for example an unfinished work from another branch) because CMake would pick them up and try to compile …
> CMake: stop using file(GLOB)

- build.sh
- build_js.sh
The CI happily continued running pytest even if the C++ build failed. That is *not* wanted.
It no longer succeeds when it should fail, while it still succeeds when it should succeed.
> Properly propagate errors from the build shell scripts

- src/esp/assets/ResourceManager.cpp
- src/esp/gfx/Viewer.cpp
First commit fixes #157, accessing pathfinder only if it's loaded. Reproducible by doing the following:
```sh
cd path/to/mp3d/82sE5b5pLXE
path/to/viewer 82sE5b5pLXE_semantic.ply    # boom, there's no 82sE5b5pLXE_semantic.navmesh
```
Second commit fixes the following:
```sh
cd path/to/any/house
path/to/viewer house.json         # boom
path/to/viewer $(pwd)/house.json  # doesn't boom
```
Doesn't crash as much as before -- however the pathfinder should be more robust I think, accessing it while it's not loaded should not segfault.
> Fix a bunch of silly crashes.

- src/esp/assets/ResourceManager.cpp
- src/esp/physics/PhysicsManager.cpp
The PTexMeshShader relies on Texture::imageSize which is not
available with WebGL or GLES versions < 3.1.
Build and run.
> Get emscripten build compiling again.

- .circleci/config.yml
- build_js.sh
- src/esp/bindings_js/CMakeLists.txt
- Add javascript binding build to CircleCI in order to prevent breakages of emscripten build.
- To enable this, I needed to add logic in build_js.sh to build corrade-rc.
CircleCI
> Add hsim js bindings build to CircleCI.

- src/esp/bindings_js/bindings.html
- src/esp/bindings_js/bindings_js.cpp
- src/esp/bindings_js/simenv_embind.js
This is required for reproducibility.
Verified that agent is now always in the same location at start.
> WebGL: Add support for setting initial position and location.

- habitat_sim/agent/controls/pyrobot_noisy_controls.py
- requirements.txt
- tests/test_pyrobot_noisy_controls.py
After some more chats with people, we've decided two things make more sense:
* Sample the noise from a truncated normal such that the noise never exceeds 3 sigma
* Sample the noise such that robot always moves at least a little bit in its intended direction. i.e. doesn't turn left when it mean to turn right.  I've set this little bit to mean at least 5% of its intended amount as this allows all actuation amounts to still be well defined.  For actuations without too much noise, large actuation amounts will pretty quick get into the 3 sigma regime, so noise will go back to being independent of actuation amount
This involves adding a dependency on scipy as I need to be able to sample from a truncated normal.  I can make this a soft dependency if this feels like to big of a dependency.
Via …
> Sample from truncated normal

- examples/demo_runner.py
- examples/example.py
- examples/settings.py
- src/esp/assets/Asset.h
- src/esp/assets/ResourceManager.cpp
- src/esp/bindings/bindings.cpp
- src/esp/gfx/Simulator.cpp
Currently a scene mesh is required to initialize the simulator. This made sense when the simulator was rendering only the scene. Now that we have dynamic object add/remove through physics manager, some use cases may require that objects can be spawned in an empty scene. One example of this is generating RGB/D/S masks for individual objects at arbitrary viewpoints. Another is dynamically building mobile scenes from an object library with no static scene mesh.
This PR introduces the option to set scene file path to "NONE" in which case the simulator will be initialized without a scene mesh required for load.
Additional change: added python bindings for "physics_config_file" field in SimulatorConfiguration class.
Local machine testing:
C++ interactive testing:
./build/viewer -- "NONE" …
> Enable loading empty scene with scene="NONE" in simulator config

- .circleci/config.yml
- setup.py
- src/CMakeLists.txt
- src/cmake/dependencies.cmake
- src/esp/gfx/CMakeLists.txt
- src/esp/gfx/DepthUnprojection.cpp
- src/esp/gfx/DepthUnprojection.h
- src/esp/gfx/Renderer.cpp
- src/esp/gfx/test/CMakeLists.txt
- src/esp/gfx/test/DepthUnprojectionTest.cpp
- src/shaders/Shaders.conf
- src/shaders/depth.frag
- src/shaders/depth.vert
Added a test and a benchmark for the existing code, applied an even better optimization by @msbaines from #150 and then added a GPU-based implementation -- both a depth-only shader and a depth unprojection shader, which is meant to be used in GPU-to-GPU cases to avoid a CPU roundtrip.
While benchmarking I realized there's a huge perf penalty coming from the branch that converts depth values at the far plane to `0.0f`. Run the benchmark for yourself, results for posterity here:
In general, the CPU code could be sped up about five times by removing the branching -- ~~according to @erikwijmans this is done because users expect depth values at far plane to be zero (while for me, coming from GPU background, values at far plane should have the depth value of far plane). I'm leaving the decision …
> GPU-based depth unprojection

- habitat_sim/simulator.py
- src/esp/assets/Attributes.cpp
- src/esp/assets/Attributes.h
- src/esp/assets/BaseMesh.h
- src/esp/assets/ResourceManager.h
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/RigidObject.cpp
- src/esp/physics/RigidObject.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
#91 introduced a lot of warnings.  This make debugging harder.  This PR deals with those warnings.
It builds/compiles both with and without `--bullet`.
> Get rid of the warnings added in PR91

- src/esp/assets/FRLInstanceMeshData.cpp
- src/esp/assets/FRLInstanceMeshData.h
- src/esp/assets/GenericInstanceMeshData.cpp
- src/esp/assets/GenericInstanceMeshData.h
- src/esp/gfx/PrimitiveIDTexturedShader.cpp
- src/esp/gfx/PrimitiveIDTexturedShader.h
- src/shaders/primitive-id-textured-gl410.frag
- src/shaders/primitive-id-textured-gl410.vert
Follow-up to #151, doing a cleanup pass over the `PrimitiveIDTexturedShader`. There was a few outdated assumptions about how GPUs work, unnecessarily large used data types and inconsistent attribute definitions. In short:
- Using a rectangular 16-bit texture instead of a 32-bit power-of-two texture, saving more than half of the memory. The textures can be neither power-of-two nor square, those restrictions are useful only in order to save memory when having mipmapping (which is not the case here). Aassuming the object IDs never go over 65k, we can also save a half of the memory by using a smaller type.
- Using `texelFetch()` instead of `texture()` -- that way we sidestep all coordinate rounding, filtering etc., making the texel access faster, *and* we don't need to pass texture size to …
> Clean up the primitive ID textured shader, resolve the WebGL TODO

- setup.py
As reported by @msbaines. Otherwise Mac `--headless` build breaks (and probably Windows build as
well).
Looks correct to my eyes. Hope the CI agrees and @msbaines too.
> Whitelist the TARGET_HEADLESS CMake option for EGL platforms only.

- examples/demo_runner.py
"example.py --enable_physics" crashes trying to instance objects from an empty object library.
Currently, this occurs when acquiring a random objectID due to empty range in random. This fix better identifies the root of the issue as an empty library.
Local test.
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] I have completed my CLA (see **CONTRIBUTING**)
- [ x] All new and existing tests passed.
> Better identify physics object initialization crash with empty library in example.py

- habitat_sim/__init__.py
- habitat_sim/agent/__init__.py
- habitat_sim/agent/controls/__init__.py
- habitat_sim/bindings/__init__.py
- habitat_sim/geo.py
- habitat_sim/gfx.py
- habitat_sim/nav/__init__.py
- habitat_sim/scene.py
- habitat_sim/sensor.py
- habitat_sim/sensors/__init__.py
In preparation for reworked docs (#71), reorganizing the `__all__` property of all modules to make more sense and be inspectable by doc generation tools. In particular:
- Avoiding extra deep hierarchies like `habitat_sim.agent.controls` but also not putting everything directly into `habitat_sim`.
- Taking stuff out of the `bindings` module and reorganizing it to other modules. The `bindings` module only grouped things coming from C++ until now and that semantically didn't have any value.
- Adding random things that were missing from `__all__`, being invisible to doc generators, IDE autocompletion etc.
What is *not* done:
- Getting rid of the old `bindings` module. It's kept there for backwards compatibility with existing code.
- Removing the `from foo import *` in the root `__init__.py` …
> Rework the __all__ property of Python modules, phase out the bindings module

- setup.py
- src/esp/assets/ResourceManager.cpp
- src/esp/core/CMakeLists.txt
- src/esp/core/configure.h.cmake
- src/esp/gfx/Viewer.h
- src/esp/physics/CMakeLists.txt
- Use configure.h introduced in #143.
- Fix a segfault I found while testing the bullet build.
- Add a `--with-bullet` alias to match the other `--with-*`.
Locally
> Cleanup physics things

- src/shaders/ptex-default-gl410.frag
- src/shaders/ptex-default-gl410.geom
This PR is to
-) fix the winding of triangles in the geometry shader;
-) apply correct uv;
-) use a more standard way to read data from the buffer texture;
To support ptex mesh rendering in our simulator
Local on Mac and Linux. See details at #132
> Support ptex mesh - Step 2: fix the shader

- src/esp/assets/Asset.cpp
- src/esp/assets/PTexMeshData.cpp
- src/esp/assets/ResourceManager.cpp
- src/esp/gfx/PTexMeshDrawable.cpp
- src/esp/gfx/PTexMeshShader.cpp
- src/esp/gfx/PTexMeshShader.h
We would like to support ptex mesh rendering in our simulator.
Status before step 1:
Code was implemented, no compile error; 
Cannot render the ptex mesh in the utility viewer or in headless mode;
The viewer can be run but returns a black screen;
In this PR:
-) it fixes the texture binding points for adjFaces (buffer texture) and atlas textures;
-) it sets correct number of primitives when setup the magnum;
-) it updates the Asset.cpp to recognize the ptex mesh in publicly released Replica data set;
1st step to support ptex mesh rendering
Local. No compile error.
If would eventually work (tested in #132) once all the mandatory fix are done.
> Support ptex mesh - step 1: fix texture binding points, number of primitives.

- habitat_sim/simulator.py
On a multi-gpu system, it seems like you need to call `torch.cuda.set_device(device)` so that the cuda runtime environment gets loaded only on the intended device (otherwise it seems to get loaded on both the intended device and GPU 0).
Locally.  Without this fix, every process would eventually load cuda runtime on GPU0 even tho I am trying to use just GPU1.  With this, GPU0 stays clean.
> Call torch.cuda.set_device

- src/esp/bindings_js/CMakeLists.txt
Currently an incremental build requires an install which requires
all targets be built. By avoid an install, I can avoid building
the viewer.js target, cutting my incremental build time in half.
Currently an incremental build requires an install which requires
all targets be built. By avoid an install, I can avoid building
the viewer.js target, cutting my incremental build time in half.
Build.
> Speedup incremental build of WebGL

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
The resource manager calls `importer.openFile` a whole bunch.  This causes the MP3D meshes take 30 minutes to load.
I made `addComponent` expected that `importer.openFile(info.filepath);` was already called and removed `const AssetInfo& info` from the signature to as `importer.openFile(info.filepath);` was the only thing using that arg.
Via tests and with the viewer in physics mode.
> Fix resource manager load times.

- src/esp/bindings/bindings.cpp
- src/esp/bindings_js/bindings.html
- src/esp/bindings_js/bindings_js.cpp
- src/esp/bindings_js/navigate.js
- src/esp/bindings_js/simenv_embind.js
- src/esp/gfx/RenderTarget.cpp
- src/esp/gfx/RenderTarget.h
- src/esp/sensor/PinholeCamera.cpp
- src/esp/sensor/PinholeCamera.h
- src/esp/sensor/Sensor.cpp
- src/esp/sensor/Sensor.h
- src/esp/sim/SimulatorWithAgents.cpp
- src/esp/sim/SimulatorWithAgents.h
In our Web demo, we are currently taking observation from Simulator and then pasting it on 2d canvas which is very slow. In this change, we directly blit the offscreen render target's RGBA buffer to default frame buffer which will render in the browser as canvas. This also removes custom rendering code on frontend side and relies totally on simulator now to provide that information.
./build_js.sh and then manually testing in browser
> Blit to defaultFrameBuffer to directly render in EmScripten Build

- src/esp/assets/PTexMeshData.cpp
- src/esp/assets/PTexMeshData.h
- src/esp/gfx/PTexMeshDrawable.cpp
- src/esp/gfx/PTexMeshDrawable.h
- src/esp/gfx/PTexMeshShader.cpp
- src/esp/gfx/PTexMeshShader.h
- src/shaders/ptex-default-gl410.frag
As titled.
-) added illumination parameters, gamma, saturation etc.;
-) refactored the PTexMeshShader a bit, moving function implementations to .cpp file;
-) renamed a couple of functions in PTexMeshShader;
-) cached the uniform positions;
local built
> Support ptex mesh - step 5: improve the shader and rendering code

- src/esp/sensor/PinholeCamera.cpp
Thanks @erikwijmans for pointing the redundant render context calls out. This PR specifically removes those.
build and bindings.html test
> Remove redundant render contexts in display observation

- .circleci/config.yml
- .eslintrc.json
- .gitignore
- .pre-commit-config.yaml
- README.md
- package.json
- src/esp/bindings_js/CMakeLists.txt
- src/esp/bindings_js/bindings.html
- src/esp/bindings_js/navigate.js
- src/esp/bindings_js/runtime.js
- src/esp/bindings_js/simenv_embind.js
ESLint is a linter for JS while Prettier is a formatter. Both are kind of a standard in industry and FB also uses them. Prettier can be used along with ESLint with help of a plugin.
This PR introduces following things:
- ESLint based linting and Prettier based formatting. Use `npm run lint` to see if there are any lint issues and `npm run lint-fix` to fix those issues.
- Add a new CircleCI task for checking if JS is properly linted
- Precommit hook for JS linting
- ESLint configuration files and package.json for easy install of deps
- Updates to existing files so that they comply with ESLint and Prettier
- Move the inline script code in `bindings.html` to a separate file `runtime.js`
Later, I will introduce a PR to introduce Babel based compilation so we can fully move to ES6. This will …
> Support JS formatting and linting through ESLint and Prettier

- docs/Doxyfile
- docs/build.sh
- docs/developer-guide.dox
This should prevent @aclegg3 from dying of copypaste boredom before #195 is finished ([see my comment there](https://github.com/facebookresearch/habitat-sim/pull/195#discussion_r325318523))  :) Proof (all Bullet types clickable, leading to concrete pages in https://pybullet.org/Bullet/BulletFull/):
This of course also works when referencing to any Bullet type, variable, function, page ... via `@ref`.
The tagfile is generated by hand as Bullet doesn't distribute it anywhere, added a seed of a Developer Guide page with details on how to replicate the process. This Developer Guide could be also place for the other things like code style, PR workflow and so on. Feel free to extend it :)
See the image above.
:warning: **Note:** I had to do `SKIP=check-added-large-files git commit` in order to …
> docs: add Bullet tagfile

- src/esp/gfx/Viewer.cpp
The setting of the MoveFilterFunction was commented out when we
adding support for physics.
Fix issue #236 
Verified that the navmesh is now respected.
> [esp/gfx] fix regression: Viewer wasn't using navmesh for navigation

- build_js.sh
- src/CMakeLists.txt
- src/esp/bindings_js/CMakeLists.txt
- src/esp/bindings_js/index.js
- src/esp/bindings_js/modules/web_demo.js
- src/esp/nav/test/CMakeLists.txt
- src/tests/CMakeLists.txt
Instead of using a large .data file, we preload the scene files
into the virtual filesystem based on URL scene parameter. This is
a workaround until Corrade PR#39 is ready.
This should speed up startup since we now only load the files we
need.
Speedup startup by only loading files we need for the current scene.
Verified that the new URL parameter scene works.
- [ X I have completed my CLA (see **CONTRIBUTING**)
> [esp/bindings_js] load scene files bases on URL parameters

- src/cmake/dependencies.cmake
We don't supply gflags in a submodule and we don't need any of it. Disables the gflags dependency of glog and thus prevents further re-appearance of issues described in #179 and #205.
Also vaguely related to #121.
CMake doesn't complain about gflags not being found during configuration anymore.
> cmake: disable gflags to avoid random build issues

- src/esp/bindings_js/modules/navigate.js
- src/esp/bindings_js/modules/topdown.js
Replica models have a floor that is non-zero. We were assuming
a floor of zero. Also, made the top-down map generation more
dynamic in order to support going up and down floors.
Top-down map was not rendering correctly for replica scenes.
> [esp/bindinds_js] topdown: don't assume floor is at y=0

- src/esp/bindings_js/index.js
- src/esp/bindings_js/modules/defaults.js
My earlier change where I allowed specifying the scene broke
semantic mesh support. Adding back semantic mesh support as
a URL parameter.
Get semantic mesh working again with WebGL port.
Tested via http://0.0.0.0:8000/esp/bindings_js/bindings.html?scene=17DRP5sb8fy.glb&semantic=mp3d
> [esp/bindings_js] add back support for semantic information

- habitat_sim/simulator.py
As titled.
Currently the simulator.py cannot set and load the navmesh for replica model correctly.
local run banchmark.py
> Set correct navmesh for the ptex mesh

- src/cmake/dependencies.cmake
In a response to https://github.com/mosra/magnum-bindings/issues/4. On macOS (without any special setup at least), `python` defaults to python 2, and this override here is causing the version 2 to be picked up first.
@erikwijmans actually, I'm not sure about the whole check at all -- why was `find_package(PythonInterp 3.6 REQUIRED)` not enough? This override after is not doing any version checks and if version 2 gets picked up, it just happily continues without any indication of things being wrong. What would break if this whole part was not there?
`/usr/bin/python` shouldn't be picked up by accident anymore.
> cmake: prefer the python3 executable over python

- src/esp/gfx/Simulator.cpp
- src/esp/scene/CMakeLists.txt
- src/esp/scene/ReplicaSemanticScene.cpp
- src/esp/scene/ReplicaSemanticScene.h
- src/esp/scene/SemanticScene.h
Initial support for Replica semantic information.
Testing semantic information using WebGL demo.
> [esp/scene] add initial support for Replica_v1 semantic information

- src/esp/bindings_js/bindings.css
- src/esp/bindings_js/bindings.html
- src/esp/bindings_js/index.js
- src/esp/bindings_js/modules/defaults.js
- src/esp/bindings_js/modules/navigate.js
- src/esp/bindings_js/modules/simenv_embind.js
- src/esp/bindings_js/modules/topdown.js
- src/esp/bindings_js/modules/utils.js
- src/esp/bindings_js/modules/vr_demo.js
- src/esp/bindings_js/modules/web_demo.js
- src/esp/bindings_js/webpack.config.js
- src/esp/bindings_js/webvr.html
Due to slow rendering of TopDown map it slows down VR a lot. We use throttle to mitigate that for now. But the problem still remains as when this paint happens everything gets blocked. So, we disable this in VR mode. See more info on throttle and debouce [here](https://codeburst.io/throttling-and-debouncing-in-javascript-b01cad5c8edf).
I also added the missing license headers to all of the files.
Manual testing
> [JS] Debounce while generating topdown map and disable it in VR

- docs/Doxyfile
- docs/Doxyfile-public
- docs/build-public.sh
- docs/conf-public.py
- docs/conf.py
- docs/theme.css
- habitat_sim/utils/__init__.py
To be consistent with https://aihabitat.org main site theme. This affects habitat-api as well, as that repo looks here for the CSS.
While generating a fresh batch of docs, I discovered a crashy corner-case with the `typing` module, so this pulls in a slightly fresher m.css as well. And in #235 the `habitat_sim.utils.common` submodule got lost, so adding it back (and then reverting the temporary hack for docs so the quat-related functions aren't on two places).
Things look consistent again, doc generation is neither crashing nor complaining too much.
> docs: sync doc theme with website updates, random fixes.

- src/esp/agent/Agent.cpp
- src/esp/agent/Agent.h
- src/esp/bindings/ShortestPathBindings.cpp
- src/esp/bindings_js/modules/navigate.js
- src/esp/scene/ObjectControls.cpp
- src/tests/NavTest.cpp
- src/utils/viewer/viewer.cpp
lookLeft is not correct. We are actually turning the agent body.
Since only SimulatorWithAgents is using this it should only
affect WebGL. Fixed a bunch of places where Agent.h was included
but not used in order to confirm that only WebGL was affected.
I want to clean up and rationalize actions in Agent.h before adding lookUp and lookDown.
Verified that turning still works in WebGL demo.
> [esp/agent] rename lookLeft/Right to turnLeft/Right

- src/utils/viewer/viewer.cpp
Fix for Issue #274 where MotionType::DYNAMIC objects pushed into the ground plane kinematically fall through the floor. To remedy this, the function now only generates translations with positive Y values.
Local tests.
> Viewer's wiggleLastObject should only nudge in +y direction.

- src/esp/core/logging.h
This will allow code using the logging wrapper (emscripten) to
use LOG(FATAL).
Needed in order to use LOG(FATAL) in emscripten builds.
> [esp/core] add support for FATAL in logging wrapper

- src/esp/assets/PTexMeshData.h
The old default value, which is from ReplicaSDK, would cause over-exposure for certain scenes.
> Optimized exposure

- .circleci/config.yml
- docs/docs.rst
- pyproject.toml
- src/esp/bindings/ShortestPathBindings.cpp
- src/esp/nav/PathFinder.cpp
- src/esp/nav/PathFinder.h
- tests/test_controls.py
- tests/test_snap_point.py
Expose projectToPoly as `snap_point`.  Sometimes it is useful to be able to snap a point to the nearest navigable point, people had been using `pathfinder.try_step(pt, pt)` to do that, but this has some weird edge cases.
Via the test!  If you swap `snap_point(pt)` for `try_step(pt, pt)`, it finds a failure very fast.
- New feature (non-breaking change which adds functionality)
> Expose snap point

- src/esp/gfx/Simulator.cpp
In response to issue #283.
`Simulator::addObject` takes a `sceneID` parameter for multi-scene use case. Since we don't support multi-scene physics presently, this should always add to the active scene graph instead.
This will need to be changed back in the future as we support multi-scene simulation.
Local testing with multiple `sim.reconfigure()` to create several sceneIDs in the Simulator.
> Simulator::addObject should add to the active scene graph

- src/esp/assets/PTexMeshData.cpp
- src/esp/gfx/PTexMeshDrawable.cpp
- src/esp/gfx/PTexMeshDrawable.h
- src/esp/gfx/PTexMeshShader.cpp
- src/shaders/ptex-default-gl410.frag
The buffer texture cannot work properly on Mac OSX. We suspect it is due to OpenGL driver shipped with the Mac OSX.
This PR is to add preprocessor directive for conditional compilation on different OS.
-) disabled the bufferTexture in PTexMeshData, Drawable, Shader;
-) disabled the "adjFace" computation;
-) disabled the index computation in shader code;  
Test it on Mac:
Test it on Linux (to show it does not affect rendering on linux):
> Support ptex mesh - step 7: Disable texture buffer on Mac OSX

- src/esp/bindings_js/CMakeLists.txt
- src/esp/bindings_js/bindings.css
- src/esp/bindings_js/bindings.html
- src/esp/bindings_js/index.js
- src/esp/bindings_js/modules/utils.js
On mobile browsers and other which don't support both of these, we should have a proper message to the user instead of showing asm logs. This PR aims to check for the support of both of them and then accordingly show a message to the end user.
bindings.html use firefox's experimental flags to disable/enable support.
> [js] Check for support of WebGL and WebASM

- src/utils/viewer/viewer.cpp
For WebGL, all resources need to be explicitly loaded. This gets
us part way to WebGL viewer working again.
Trying to get viewer working again with WebGL.
Verified that with this change, viewer works without a physics config when enable
physics is not true.
> [utils/viewer] only check for physics config is physics is enabled

- .circleci/config.yml
- .eslintrc.json
- package.json
- src/esp/bindings_js/tests/utils.test.js
- tests/test_controls.py
- Running `npm test` will run JS tests using Jest
- Tests live inside tests folder in bindings_js and are suffixed with
.test.js extension
Add support for testing on JS side using Jest.
Also includes a complex testing example of throttle function 
`npm test`
> [tests/js] Add testing support for JS through Jest

- src/esp/gfx/Simulator.cpp
Related to issue #284. A semantic scene ID should be assigned by default so that semantic rendering can be done regardless of the provided annotations. For example on the empty "NONE" scene.
In the future we would like to provide a method for setting those semantic annotations for physics objects programmatically.
Comments welcome.
Local testing.
Empty scene with physics object rendered via rgb and semantic sensors:
(Image courtesy of a script by Daniel Huber.)
> Semantic scene ID assigned by default

- src/esp/bindings/bindings.cpp
- src/esp/scene/SceneGraph.cpp
- src/esp/scene/SceneGraph.h
- src/esp/sensor/PinholeCamera.cpp
- src/esp/sensor/PinholeCamera.h
- src/esp/sensor/Sensor.h
Set the camera matrices (model view, proj), viewport **uniformly** from sensor to the render camera;
When people create their own visual sensor (other than pinhole camera), they can inherit from the "Sensor" class, and customize and implement their own version of aforementioned functions;
Test it with the example model (the castle):
> Set modelview, projection matrices, viewport respectively from sensor to render camera

- src/esp/bindings_js/index.js
- src/esp/bindings_js/modules/simenv_embind.js
- src/esp/bindings_js/modules/utils.js
- src/esp/bindings_js/modules/web_demo.js
- src/esp/bindings_js/tests/utils.test.js
Our default start position has been hardcoded for castle scene. We need to rely back on SimulatorWithAgents to set a default position for us. You can reset back to default episode by adding `&useDefaultEpisode=1` to the back of your url.
This allows van-gogh and replica apartment to be rendered inside web browser.
Other than that some of the link sharing websites URI encode the URLs so they should be decoded back on our end.
Tests have been added for the changes that were made in this PR. And as mentioned in chat on the URLs shared there.
> Default to random start position and allow URI decoding

- src/esp/bindings_js/modules/navigate.js
We are using arrow keys lookUp and lookDown.
> [esp/bindings_js] prevent arrow keys from scrolling

- src/esp/bindings_js/modules/navigate.js
Fixed a typo that was preventing semantic render from working.
Fixes bug.
Verified that semantic information is now being rendered.
> [esp/bindings_js] get semantic render working again

- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/utils/viewer/viewer.cpp
To diagnose future Bullet physics issues, we would like to register Habitat-sim state with Bullet physics state visually. Magnum/BulletIntegration/DebugDraw provides this. This PR pulls debug functionality into the viewer demo.
Local testing:
Skokloster Castle:
CODA room:
Empty scene with objects:
> Enable Magnum BulletIntegration DebugDraw in viewer.

- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
The debugDraw function in PhysicsManager should be const. It was not since the debugDrawer_ in BulletPhysicsManager is updated with a new transform when this function is called. To remedy this, debugDrawer_ has is been made mutable. 
Based on a comment by @msbaines in PR #298. 👍  
Local testing.
> Make debugDrawer mutable and debugDraw const

- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
This PR replaces if statements in PhysicsManager and BulletPhysicsManager based on the validity of object IDs with CHECK().
As @msbaines mentioned in a review for PR #237, PhysicsManager functions taking an object ID as input should not fail silently when an invalid object ID is provided. This may allow hidden bugs to crop up. For example: setting a force or torque on an object which does not exist and then receiving no indication that the set failed resulting in extended debugging. Instead, such an invalid set should be fatal and produce a clear error message. 
Local testing.
> PhysicsManager CHECK cleanup

- src/esp/gfx/RenderTarget.cpp
- Before, we used to blit from same source rectangle to same destination
rectangle
- Instead, we should blit from source framebuffer viewport to default
frame buffer's viewport
- Also, instead of hardcoded source rectangle, we will take the source rectangle from `frameBuffer_.viewport`
Tested on viewer.html and webvr.html
> Blit from frameBuffer to defaultFrameBuffer viewport

- src/esp/bindings_js/modules/navigate.js
Sometimes users have extensions enabled which override default key behavior. This change intends to fix that behavior by triggering the event listener for keys at the capturing phase so it can't be stopped via event.stopPropagation(). See https://stackoverflow.com/questions/13880126/override-existing-onkeydown-function
Tested on viewer
> Trigger event listener for keys at capturing phase

- src/esp/bindings_js/CMakeLists.txt
- src/esp/bindings_js/bindings.css
- src/esp/bindings_js/bindings.html
- src/esp/bindings_js/bindings_js.cpp
- src/esp/bindings_js/index.js
- src/esp/bindings_js/modules/navigate.js
- src/esp/bindings_js/modules/object_sensor.js
- src/esp/bindings_js/modules/web_demo.js
Object and best-view IoU is specified by a URL parameter. If the
user presses the spacebar and IoU of object exceeds 50% of best-view
the task is successfully completed.
Required for object nav.
Verified that object nav is working.
> [esp/bindings_js] add initial support for object nav

- habitat_sim/agent/agent.py
- habitat_sim/simulator.py
- tests/test_agent.py
- tests/test_simulator.py
Habitat-sim currently crashes if you do
```
agent = sim.get_agent(0)
sim.close()
```
as the sensors have OpenGL related things, but the simulator owns the OpenGL context.
Also makes `sensors` on the agent private, so we don't have to go down this rabbit hole further.
With the test!
> Allow agent reference to be kept

- src/esp/assets/MeshMetaData.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/bindings_js/modules/navigate.js
This is the first step toward a solution for Issue #301 .
In order to build collision objects from mesh hierarchies, we first need to store them. 
Since the hierarchies are metadata, this PR adds a `MeshTransformNode` data structure to the `MeshMetaData` structure. When a mesh is loaded into assets the hierarchy is computed and stored.
Now that the hierarchy of transforms is available, we no longer need Importer to reload the source files in order to add objects to the scene graph with `addComponent`. This has been refactored.
No previously exposed functionality should change as a result of this refactor.
Local testing with physics.
> Store mesh transform hierarchy (Issue #301 fix part 1/2)

- src/esp/gfx/RenderCamera.cpp
- src/utils/viewer/viewer.cpp
In the viewport event, we only reset the viewport but do not specify what to do when window size is changed.
This PR is to update the projection matrix to handle it.
As titled.
The OLD version looks like this:
Initial screen:
After window size was changed:
Local test:
Initial screen:
After window size was changed:
> Bug fix: add "reshape" functionality to utility viewer

- src/esp/gfx/RenderCamera.cpp
- src/utils/viewer/viewer.cpp
-) revert the extra code and comments in #322;
-) move setAspectRatioPolicy out of the setProjectionMatrix;
-) set the correct policy in the viewer;
See #322 
Local test:
Original window:
After window size was changed:
> Revert #322 and add "reshape" functionality to utility viewer

- habitat_sim/simulator.py
- src/esp/bindings/bindings.cpp
- src/esp/gfx/Simulator.cpp
- src/esp/gfx/Simulator.h
- tests/test_physics.py
Default `MotionType` for objects is determined by the active simulator. For dynamics simulators (e.g. Bullet), this default is `MotionType::DYNAMIC`. However, many use cases require kinematic or static objects. This should be settable in python as in C++.
Local testing and new CI testing code.
> Added MotionType setting to python

- src/esp/assets/ResourceManager.cpp
Static builds could pick up different-versioned dynamic plugins for Magnum, resulting in version mismatch errors such as:
```
Trade::JpegImporter::image2D(): error: Wrong JPEG library version: library is 90, caller expects 80
```
This is particularly confusing when building inside conda or venv where a hermetic build is expected. The change in this PR disables dynamic plugin loading for static magnum builds.
Built static build locally. Confirmed `build/viewer` no longer exhibits above version mismatch error.
> Disable PluginManager dynamic plugin loading for static magnum builds

- src/esp/nav/PathFinder.cpp
- src/tests/NavTest.cpp
- tests/test_sensors.py
Currently, tryStep returns {NAN, NAN, NAN} if you give it a non-navigable, just having it return the start position seems cleaner as returning in all NANs results in a crash if you try to render from that location (which makes sense, but just not moving seems cleaner/less confusing).
Also, I found out that `moveAlongSurface` isn't guaranteed to return a point on the surface of the navmesh, only within a polygon by [x, z].  I added an explicit call to get the height of the polygon.  It seems like almost all the time, the height isn't different, but sometimes it is a bit different.
I needed to make the comparison fuzzier for the rendering test to accommodate the newly added larger MP3D mesh (we had be running into bugs in the resource manager that were only apparent on larger meshes, so I …
> Fix tryStep edge cases

- .circleci/config.yml
- setup.cfg
We need to add `--cov-append` for the second invocation of pytest in habitat-sim
Also moves the `--cov-report=xml --cov=./` flags to just the CI as those aren't needed locally
On the CI!
> --cov-append for second pytest

- src/esp/nav/PathFinder.cpp
- src/esp/nav/PathFinder.h
- tests/test_snap_point.py
There are some zero-area polygons in the navmeshes for some reason.  Those cause issues (#370).  This PR marks the zero are polygons as disabled, effectively removing them from the navigation mesh.
I have also pulled in the latest changes from recast as those do contain stability enhancements for methods that we heavily rely on.
Fixes #370 
Via the test point in #370 (I can add that point to an explicit test, but its an MP3D mesh and we don't have them on the CI).
> Remove zero area polys

- README.md
Update README to use https link `https://github.com/facebookresearch/habitat-sim.git` for git clone as it is the [recommended way](https://help.github.com/en/github/using-git/which-remote-url-should-i-use#cloning-with-https-urls-recommended) by GitHub. 
Current git@github clone link in README `git@github.com:facebookresearch/habitat-sim.git` may not work for users in general who do not have set up ssh keys.
Rendered README on the local fork and cloned the repository using the updated link.
> Update git clone link in README

- src/utils/viewer/viewer.cpp
Revert a change to the physics timestep from testing PR #317.
Local testing.
> Revert testing code change to viewer physics timestep.

- src/esp/assets/MeshMetaData.h
- src/esp/assets/ResourceManager.cpp
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
To make transformation variables more semantically obvious, we have agreed upon the convention: `transformationFrom<frameA>To<frameB>`. This change modifies existing transform variables to comply with this convention.
Local testing.
> Modify transform variable naming conventions.

- src/esp/assets/GenericInstanceMeshData.cpp
- src/esp/assets/GenericInstanceMeshData.h
`CollisionMeshData` is used to reference mesh geometry during construction of collision objects for physics simulation. Manipulation of geometry data in `GenericInstanceMeshData::uploadBuffersToGPU` caused this reference set in `GenericInstanceMeshData::loadPLY` to be incorrect. This PR aims to fix this bug.
Moved from #333 as suggested by @msbaines.
> Fix CollisionMeshData bug in GenericInstanceMeshData after mesh data manipulation

- src/utils/viewer/viewer.cpp
Currently the agent position in viewer is hardcoded in initialization resulting in cases where the agent is initialized outside of the scene as shown for the `van-gogh-room.glb` below:
Running viewer for multiple scenes (e.g. `van-gogh-room.glb`):
> Viewer: set agent position from navmesh if loaded in initialization 

- .clang-format
- CONTRIBUTING.md
Specified clang-tidy version 8 for contributing guidelines, as our clang config isn't backward compatible.
> Specified clang-tidy version 8 for contributing guidelines

- src/esp/gfx/Simulator.cpp
- src/esp/scene/test/CMakeLists.txt
- src/esp/scene/test/GibsonSceneTest.cpp
- src/esp/scene/test/configure.h.cmake
With current code state [3dscenegraph](https://3dscenegraph.stanford.edu/) semantic annotation files (*.scn) won't load, as our semantic loading pipeline triggers only on `*.house` files. To enable functionality implemented in https://github.com/facebookresearch/habitat-sim/pull/393 and https://github.com/facebookresearch/habitat-sim/issues/374 added loading of Gibson Semantics scene if MP3D semantic is missing. To test semantic loading e2e added integration test that will run only when *.scn test data is available.
Added the integration test and run it locally with `*.scn` data:
```
Running main() from /private/home/maksymets/habitat-sim/src/deps/googletest/googletest/src/gtest_main.cc
[==========] Running 2 tests from 2 test cases.
[----------] Global test environment set-up. …
```
> [esp/scene] Added loading of Gibson Semantics scene if MP3D semantic is missing, integration test

- .eslintrc.json
- package.json
- src/esp/bindings_js/webpack.config.js
- tsconfig.json
TypeScript enables type checking for JavaScript and will help improve quality of code on JS side.
This PR enables typescript compilation support and makes it work alongside ES6.
Same commands nothing has changed. A separate PR will be opened for moving files to .ts.
> [feature] TypeScript support

- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/tests/PhysicsTest.cpp
It is often desirable to fetch the SceneNode associated with a physics object. However, we provide many PhysicsManager functions to avoid direct manipulation of SceneNode states which may invalidate simulation state. Here we add a const reference getter for a query only object SceneNode.
Some testing lines in existing physics C++ test function. Will likely be moved to another test function once this functionality is needed (upcoming).
> Add getObjectSceneNode function to PhysicsManager

- src/utils/viewer/viewer.cpp
Viewer functions for applying linear force and impulse to objects transform agent forward direction into world push direction. This was improperly done with `transformPoint` instead of `transformVector`.
Local testing.
> Bug fix: transformPoint used on vectors in viewer

- src/esp/bindings/GfxBindings.cpp
- src/esp/gfx/RenderCamera.cpp
- src/esp/gfx/RenderCamera.h
- src/esp/sensor/PinholeCamera.cpp
- src/tests/SimTest.cpp
- src/utils/viewer/viewer.cpp
Addresses #391 
- Eliminates the getMagnumCamera(...) in the interface API;
- gains all the existing APIs in MagnumCamera;
- The development could be easier in Frustum Culling project. Culling can happen in the RenderCamera class;
- Manual testing using viewer app
- Manual testing ensuring `MagnumCamera` api accessible from python bindings
- habitat-sim and habitat-api have been grepped for usages of `RenderCamera`
- passes all tests
> Refactor RenderCamera to inherit from MagnumCamera

- src/esp/assets/GenericInstanceMeshData.cpp
Support uint32 object IDs.
With a mesh that has uint32 object IDs.
> Support uint32 object IDs

- habitat_sim/simulator.py
- src/esp/bindings/GfxBindings.cpp
- src/esp/gfx/Simulator.cpp
- src/esp/gfx/Simulator.h
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
- src/tests/PhysicsTest.cpp
Discrete contact testing is useful for a variety of tasks including agent/object placement and collision filter functions. This PR introduces the first step: binary contact testing for a specific object with the collision world. 
Includes Simulator.cpp wrapper and python bindings for simulator.py.
This infra can later be extended to include a configurable contact distance threshold and collection of contact points, normals, friction directions, contact distances, and colliding object pair identifiers.
C++ CI test for object/object and object/scene contact results.
> Bullet discrete contact testing

- src/esp/bindings/GfxBindings.cpp
- src/esp/bindings/SensorBindings.cpp
- src/esp/gfx/Renderer.cpp
- src/esp/gfx/Renderer.h
- src/esp/scene/SceneGraph.cpp
- src/esp/scene/SceneGraph.h
- src/esp/sensor/CMakeLists.txt
- src/esp/sensor/PinholeCamera.cpp
- src/esp/sensor/PinholeCamera.h
- src/esp/sensor/Sensor.cpp
- src/esp/sensor/Sensor.h
- src/esp/sensor/VisualSensor.h
- src/esp/sim/SimulatorWithAgents.cpp
This is part of the Sensor refactor. The goal of this change is to bring the Sensor class into closer alignment with the new Sensor API design.
Also removed a few APIs we were exporting to python that didn't
really need to be exported.
Sensor refactor
SimTest
> [sensor] extract out visual parts of Sensor into VisualSensor

- .circleci/config.yml
- habitat_sim/simulator.py
- src/esp/bindings/ShortestPathBindings.cpp
- src/tests/NavTest.cpp
- tests/test_random_seed.py
Previously, calling sim.seed() followed by sim.pathfinder.get_random_navigable_point() would not work as expected. The same seed would not result in the same point. More information can be found in this issue: https://github.com/facebookresearch/habitat-sim/issues/44
Now seeding with the same seed results in the same navigable point deterministically.
Added a test in tests/test_random_seed.py that tests seeding in various circumstances (same seed, different seeds, multiple samples of random points) and verified that it works as desired. Run this individual test with
$pytest tests/test_random_seed.py
> Fixed seeding to work as desired

- habitat_sim/__init__.py
- habitat_sim/gfx.py
- habitat_sim/sim.py
- src/esp/bindings/CMakeLists.txt
- src/esp/bindings/GfxBindings.cpp
- src/esp/bindings/SensorBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/bindings/bindings.cpp
- src/esp/bindings/bindings.h
- src/esp/gfx/CMakeLists.txt
- src/esp/scene/test/GibsonSceneTest.cpp
- src/esp/sensor/PinholeCamera.cpp
- src/esp/sensor/PinholeCamera.h
- src/esp/sensor/Sensor.h
- src/esp/sim/CMakeLists.txt
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/esp/sim/SimulatorWithAgents.cpp
- src/esp/sim/SimulatorWithAgents.h
- src/tests/PhysicsTest.cpp
- src/tests/SimTest.cpp
- src/utils/viewer/viewer.cpp
Goal is to collapse Simulator and SimulatorWithAgents into one class.
Moved Simulator to sim namespace an in intermediate step. Next step
is to pull up SimulatorWithAgents logic into Simulator.
The change is part of the sensor refactoring.
Collapse Simulator and SimulatorWithAgents into one class.
SimTest
> [esp/sim] move Simulator to sim namespace

- src/CMakeLists.txt
- src/tests/ResourceManagerTest.cpp
- src/tests/configure.h.cmake
This PR focuses on ResourceeManagerTest only, which partially addressed the issue mentioned in #442.
Briefly, the path to the asset is wrong in previous version, which leads to failure of the the tests. The wrong path is based on SCENE_DATASETS, which by default does not exist in our repository.
Local test
> [bug fix] Set correct asset path for the ResourceManagerTest

- src/esp/gfx/Simulator.cpp
The `Simulator::recomputeNavmesh` function requires scene geometry to rebuild the recast navmesh for the scene. This geometry is not loaded when no sensors are configured. Trying to call this function without geometry loaded results in a failed assert during mesh joining which is non-obvious. 
This PR introduces a clearer assertion that `SimulatorConfiguration::createRenderer == true` is required to use this function.
May want to discuss whether this behavior is desired, or geometry loading should be decoupled from sensor initialization and what that would entail.
Add the following code to the end of `test_recompute_navmesh.py` and see assertion failure.
```
#test recompute navmesh with no sensors
cfg_settings["color_sensor"] = False
hab_cfg = examples.settings.make_cfg(cfg_settings) …
```
> Assert createRenderer is configured for Simulator::recomputeNavmesh

- .circleci/config.yml
Automatic documentation build [fails when there is no changes to push](https://app.circleci.com/jobs/github/facebookresearch/habitat-sim/5795). Added the check if there are changes to commit first.
Switched running for current branch to check success.
> Fix: Handle exit code 1 if there is no changes to doc

- .circleci/config.yml
Fix: Added build sha to doc update key to avoid stale doc build. In CircleCI cache can't be overwritten with same key.
> Fix: Added build sha to doc update key

- src/tests/ResourceManagerTest.cpp
C++ test build was failing on macOS due to minor implicit double to float casting issue. CI was not failing, so may be system/compiler specific.
E.g.
On macOS
`./build.sh --run-tests`
> Fixed initializer cast error on mac test compile

- src/esp/bindings/SceneBindings.cpp
- src/esp/bindings/SensorBindings.cpp
- src/esp/bindings/bindings.cpp
This does not fix all pybind11 doc errors. There are still a few
unresolved due to cross-references between some namespaces.
The cross-references can be avoided and I think the architecture
will benefit as a result. I hope to address this as part of the
sensor refactor.
Remaining errors:
WARNING:root:cannot parse pybind11 function signature bind_render_target(self: habitat_sim._ext.habitat_sim_bindings.Renderer, arg0: esp::sensor::VisualSensor) -> None
WARNING:root:cannot parse pybind11 function signature draw(self: habitat_sim._ext.habitat_sim_bindings.Renderer, visualSensor: esp::sensor::VisualSensor, scene: habitat_sim._ext.habitat_sim_bindings.SceneGraph) -> None
WARNING:root:cannot parse pybind11 function signature get_default_render_camera(self: …
> [esp/bindings] fix a bunch of pybind11 doc reference issues

- src/esp/bindings/GfxBindings.cpp
Use consistent python binding naming conventions, so update `setProjectionMatrix` to `set_projection_matrix`
-Tests pass
-grepped habitat-api for usages
> Update RenderCamera::setProjectionMatrix PyBind to snake_case

- habitat_sim/agent/controls/__init__.py
- habitat_sim/agent/controls/controls.py
- habitat_sim/agent/controls/default_controls.py
- tests/test_controls.py
Our current LookUp and LookDown actions allow you to spin a full 360 degrees.  This is very unrealistic.  This PR introduces a constraint to that.
Via the test
- New feature (non-breaking change which adds functionality)
> Constrained LookUp and LookDown

- src/esp/nav/PathFinder.cpp
- src/esp/nav/test/PathFinderTest.cpp
The multigoal path implementation was relying on being able to compare path lengths on the navigation mesh before optimization, this turns out to be not correct a little too often.  This PR changes it to be simply min(A* paths).
This also has the benefit of removing on our deviations from recast main!
With the test!  Also added a benchmark because Corrade's test suite is fun.
> Update multi goal path implementation

- tools/gen_gibson_semantics.sh
This script generated semantic scene information from the
https://3dscenegraph.stanford.edu/ dataset.
This script can be used to generate Gibson semantic scene information.
We are using the data generated from this script.
> [tools] add Gibson semantic scene generations script

- habitat_sim/sensors/noise_models/redwood_depth_noise_model.py
Since 0.1.4, attempting to import habitat_sim without having PyTorch installed results in `ModuleNotFoundError`. This PR fixes that.
> Make PyTorch dependency optional in redwood_depth_noise_model

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/gfx/CMakeLists.txt
- src/esp/gfx/Drawable.cpp
- src/esp/gfx/Drawable.h
- src/esp/gfx/DrawableGroup.cpp
- src/esp/gfx/DrawableGroup.h
- src/esp/gfx/GenericDrawable.cpp
- src/esp/gfx/GenericDrawable.h
- src/esp/gfx/PTexMeshDrawable.cpp
- src/esp/gfx/PTexMeshDrawable.h
- src/esp/gfx/PrimitiveIDDrawable.cpp
- src/esp/gfx/PrimitiveIDDrawable.h
- src/esp/gfx/Renderer.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/scene/SceneGraph.cpp
- src/esp/scene/SceneGraph.h
- src/tests/CMakeLists.txt
- src/tests/SceneGraphTest.cpp
- src/utils/viewer/viewer.cpp
As part of the configurable Shader project, we need to have multiple DrawableGroups instead of using only 1. Each Drawable also needs a pointer to their drawable group in order to retrieve its shader at render time. This PR lays the groundwork for this to happen, while minimizing the number of changes by still using a single default group.
Part of #319 
Need to add tests before merge (will update).
> Multiple drawable groups

- habitat_sim/simulator.py
- tests/test_recompute_navmesh.py
Added a check and recomputation of navmesh for non standard agent size. That will add the support of navigation metrics and shortest path calculation for custom agent configuration.
> Added a check and recomputation of navmesh for non-standard agents

- tools/npz2scn.py
I was assuming that the bounding boxes from 3DSceneGraph were using
the same -y gravity coordinate system that was used by the Gibson
dataset .obj files but it appears that the bounding boxes are with
a -z gravity coordinate system.
Fix bounding boxes in .scn files.
Verified bounding boxes using WebGL application.
> [esp/scene] fix scn file bounding boxes

- src/esp/assets/ResourceManager.cpp
Currently, when physics object configuration templates are loaded from a directory, they are not sorted by name before insertion. This results in datasets with clear ordering (e.g. numbered YCB objects) being loaded un-intuitively out of order. This change sortd configs by filename.
Local testing loading YCB dataset.
Before:
__
After:
> Sort object template library directory by filename during load

- setup.py
Fixes #476 
I ran it locally and was able to build in an absolute path that has spaces after this change.
> Let CMake run with spaces in folder name fixes #476 

- src/esp/gfx/RenderCamera.cpp
- src/esp/scene/SceneNode.h
Let the simulator memorize the frustum plane index, which culls the object in the last frame.
In the current frame, it is likely the object will be rejected again by this plane. Thus, start the culling from this plane first.
> [Culling][Optimization] Fustum culling with temporal coherence

- src/esp/scene/Mp3dSemanticScene.cpp
- src/tests/Mp3dTest.cpp
The semantic region index logic isn't correct currently.  Doesn't deal with the capital letters or the gap in the label codes.  This PR uses the ordering in the `std::map` to get indexes to each label code.
Locally -- category indexes now look fine!
> Fix semantic region index logic

- src/esp/bindings/SceneBindings.cpp
- tests/test_simulator.py
For domain randomization, it is often useful to sample a 3D position from inside a scene. This PR enables users to compute/query the approximate scene bounding box from the SceneGraph root node (or any other SceneNode of interest).
added python test
> python bindings for SceneNode bounding boxes

- habitat_sim/geo.py
- src/esp/bindings/geoBindings.cpp
- src/esp/geo/OBB.cpp
- src/esp/geo/geo.cpp
- src/esp/nav/PathFinder.cpp
Added some functionality needed for properly using OBBs in the Habitat-API. 
1). Add new python bindings to OBB
2). Fix bugs computeMOBB and expose to python.
3). Have sampleNavigablePoint return a point that will always not be navigable if it fails. That ensure that we get a proper error state that we can check against pt(inf,inf,inf).
It has been tested by being used for generating the ObjectNav datasets in the Habitat-API.
> Extend bindings for OBB and misc fixes.

- src/esp/assets/ResourceManager.cpp
The "basisified" MP3D files @erikwijmans encoded a while ago contain a mip pyramid for each image, however until earlier today, Magnum APIs were only able to load the first one (see https://github.com/mosra/magnum/pull/369 for the corresponding change on Magnum's side). While this is a relatively minor change, it has non-negligible impact on rendering times. A very rough artificial benchmark is below, showing clear advantage of having the extra mip levels loaded. 
Originally, before the files were basisified, the loaded JPEGs got their mip levels generated during import (second bar in the plot above). Above that is comparison to JPEGs loaded in a single level, which is slower due to extra memory fetches needed for minifying the full-size textures. 
What is interesting that, on my machine …
> Load all available texture mip levels in ResourceManager

- src/tests/CullingTest.cpp
The `CullingTest` was not compiling on my machine due to `sqrt()` returning a double, which got passed to `Vector3` initializer list. Using builtin Magnum constants for that instead, also adding `f` to all literals to avoid warnings/errors on random other compilers and initializing the `std::vector` in a single step.
CIs pass, I hope.
> Tests: fix double narrowing errors on GCC 9

- src/tests/PhysicsTest.cpp
Build without `--bullet` was not including `PhysicsManager`. in PhysicsTest.cpp.
Existing tests run with `./build.sh --run-tests`
> [bug fix] - PhysicsTest did not include PhysicsManager when built without bullet

- src/esp/assets/GenericInstanceMeshData.h
- src/esp/scene/ReplicaSemanticScene.cpp
- src/esp/scene/SemanticScene.h
- src/esp/scene/test/CMakeLists.txt
- src/esp/scene/test/ReplicaSceneTest.cpp
Add Replica OBB parsing.
Via the test
> Replica OBB

- README.md
Communicate new performance after semantic culling.
I kept the `*Note` section mentioning semantic performance since its still not as fast as RGB+depth.
Ran: `python examples/benchmark.py --scene /datasets01/mp3d/073118/v1/habitat/17DRP5sb8fy/17DRP5sb8fy.glb --max_frames 4000 --benchmark_semantic_sensor`
> update semantic benchmark numbers

- docs/pages/image-extractor.rst
Added a tutorial to the doc/pages/ directory that explains how to use the ImageExtractor class in habitat sim to generate image data.
> Tutorial for image data extraction

- src/esp/assets/ResourceManager.cpp
Currently, assets with 'AssetType::UNKOWN' are parsed through the gltf pipeline by default (this includes `.obj` files). However, these assets were being gated at physical scene initialization. 
After this change, 'AssetType::UNKOWN' assets for physical scenes now attempt to load 'CollisionMeshData' as 'GltfMeshData' objects. If this fails, load is aborted.
This change also enables culling for 'AssetType::UNKOWN' in the same manner.
Loading an `.obj` scene in viewer.cpp
> [bug fix] - get CollisionMeshData for AssetType::UNKOWN assets

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/tests/SimTest.cpp
- src/utils/viewer/viewer.cpp
Often we want to load new objects which were not originally configured upon load. This change both refactors object loading to separate parsing of object template paths from the simulator configuration and adds `loadObjectConfigs` and `loadObjectTemplate` functions to the `Simulator` class to facilitate object loading without direct access to `ResourceManager`.
Includes a minor fix to a recent bug in `viewer.cpp` when loading "NONE" scene without a navmesh introduced in PR #531.
New C++ unit test.
> (Simulator): On demand object loading

- .clang-tidy
I hope this is not too much of a controversial change — while upgrading Habitat to make use of the new Magnum [MeshData](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1MeshData.html) APIs (PR with that comes right next), the first thing I did before adapting all code was bumping submodules and letting the CI check that existing code continues to work, to avoid repeating what happened in #496. It *did* work (even though there's >35kLOC changes on Magnum side), *except* that Clang Tidy failed the build due to the newly appearing deprecation warnings. To fix that I'd be forced to update all code first, losing the chance of knowing what exactly is responsible for a potential new test failure.
This PR makes Clang Tidy let deprecation warnings through. In case of Magnum at least, …
> Clang Tidy: don't treat deprecation warnings as errors

- .clang-tidy
- src/esp/assets/BaseMesh.h
- src/esp/assets/CollisionMeshData.h
- src/esp/assets/GenericInstanceMeshData.cpp
- src/esp/assets/GenericInstanceMeshData.h
- src/esp/assets/GltfMeshData.cpp
- src/esp/assets/GltfMeshData.h
- src/esp/assets/Mp3dInstanceMeshData.h
- src/esp/assets/ResourceManager.cpp
- src/esp/gfx/GenericDrawable.cpp
- src/esp/gfx/PTexMeshDrawable.cpp
- src/esp/gfx/PrimitiveIDDrawable.cpp
- src/esp/gfx/RenderTarget.cpp
- src/esp/gfx/test/DepthUnprojectionTest.cpp
- src/esp/physics/PhysicsManager.h
Depends on #540.
In a classic import pipeline implemented in many 3D asset libraries, Assimp included, the process of importing a mesh and uploading it to a GPU looks roughly like shown the left side of the image above. There's nothing wrong with that for many file formats — especially textual ones such as OBJ — as various amounts of parsing and processing needs to be done anyway. 
Thanks to the new [`Trade::MeshData`](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1MeshData.html) API coming in this PR, *if* the file format is designed in a way that allows this, the process can be reduced to just metadata extraction and a direct copy of the data.
Compared to the classic case it also means that if the source files already has the data packed in some way (for example storing …
> Upgrade to Magnum's new MeshData API

- habitat_sim/nav/greedy_geodesic_follower.py
- habitat_sim/sensors/noise_models/gaussian_noise_model.py
- habitat_sim/sensors/noise_models/redwood_depth_noise_model.py
We noticed that RGB noise models are 7x times slower than whole Habitat step call.
@erikwijmans with @Skylion007  made our RGB noise models 50x faster with following PR.
- One minor change is to make GreedyFollower compatible with PyRobot actions. The change makes it possible to build shortest path on the fly with noise actuations.
Existing [HSIM noise tests](https://github.com/facebookresearch/habitat-sim/blob/master/tests/test_sensors.py#L152-L207), [HAPI noise tests](https://github.com/facebookresearch/habitat-api/blob/master/test/test_sensors.py#L329).
> Faster RGB & Depth noise models

- src/esp/assets/Attributes.cpp
- src/esp/assets/Attributes.h
- src/esp/assets/ResourceManager.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/sim/Simulator.cpp
- src/tests/PhysicsTest.cpp
- src/tests/SimTest.cpp
This change refactors derived classes of `assets::Attributes` to expose getter/setter methods for expected default fields. This change is preparation for python bindings and tutorials to enable user friendly manipulation of object, scene, and simulator templates (e.g. `PhysicsObjectAttributes`) for domain randomization. 
Existing code (including tests) modified to use getter/setters.
> Getter/setters for derived Attribute defaults

- .gitignore
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
- src/esp/sim/Simulator.cpp
- src/utils/viewer/viewer.cpp
Fix includes in BulletRigidObject; refactor ResourceManager so that PhysicsObjectAttributes template tracks its own ID, (used to instance objects); Refactor ambiguous references to objectID in resource manager that really refer to object templates.
The motivation for this fix is primarily to serve as a "first push" so that I am sure to get the process correct.  Functional changes : 
1. (Bug Fix) The include of MotionState.h in BuiletRigidObject.cpp was moved to BuiletRigidObject.h, since that is where MotionState is referenced by the code. 
2. (Refactor) ResourceManager.* : accessing object template IDs was improved by setting an ID field in the PhysicsObjectAttributes field corresponding to the template upon its creation, and then referencing that ID on demand.
3. (Refactor) …
> --basic groundwork for support of rendered physical primitives.

- habitat_sim/bindings/__init__.py
- src/esp/bindings/bindings.cpp
- tests/test_configs.py
This change refactors the python bindings for the `esp::core::Configuration` class to support the upcoming `PhysicsObjectAttributes` bindings. The python class is renamed to `Attributes` to prevent name collision with the `Configuration` python class in `simulator.py` which is used ubiquitously throughout the code. 
This is a breaking change, but there are no uses of `esp::core::Configuration` in the current codebase.
New `test_core_configuration` test in `test_configs.py`.
> Refactor python bindings for core::Configuration 

- src/esp/assets/ResourceManager.cpp
Found this while working on the promised normal map support, so opening a separate PR.
Magnum's PhongMaterialData is now able to contain both colors and textures, so the branching is no longer needed. Apart from that, `TinyGltfImporter` had an issue where shininess was imported as 1.0 instead of 80.0, and that's fixed now as well so this workaround isn't needed either.
:warning: CI passes, *except* that I had to modify the Van Gogh Room GLB to not darken the texture to 60% (which was apparently caused by a less-than ideal conversion of the [source OBJ](https://sketchfab.com/3d-models/van-gogh-room-311d052a9f034ba8bce55a1a8296b6f9) from 60% of the texture as an ambient and 60% as diffuse to a GLB that had only the diffuse part left). This worked before because the diffuse factor was …
> assets: clean up PhongMaterialData usage

- .circleci/config.yml
- .coveragerc
*(This a bad thing to do on April Fools, I know.)*
Discovered this while checking how well are meshes with semantic info tested (not really, https://github.com/facebookresearch/habitat-sim/issues/556#issuecomment-607211470). Tests for C++ and Python code are one third of the total code size (~1.7kLoC, while the total code size is ~5k), and as it usually is with tests, those are ran in full with >95% coverage. This however skews the coverage percentage into suspiciously high numbers, making us think the codebase is covered better than it actually is.
This is consistent with how coverage is measured for all Magnum projects, and I'd personally say it's a good thing to do -- however you may have a different opinion about this :) I'm open for a discussion. The only potential disadvantage of …
> Exclude test code from coverage reports

- src/esp/assets/ResourceManager.cpp
- src/esp/gfx/GenericDrawable.cpp
- src/esp/gfx/MaterialData.h
Normal mapping improves realism, in case the input models contain normal maps. Loading the [Lantern](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Lantern) glTF sample model before:
and now (sorry for the sideways view, I *really tried* to navigate the viewer differently but ultimately failed):
99.98% work needed for this is done on Magnum side, most of it arrived with #542 already, this PR brings `TinyGltfImporter` and `AssimpImporter` updates to import vertex tangents / bitangents and normal textures and does minimal changes in Habitat's code to make use of those. This also means that both glTF files *and* all formats supported by Assimp now can be rendered with normal maps.
Since #542, `TinyGltfImporter` also received a rather massive update in order to support the …
> gfx: support normal mapping and quantized glTF meshes

- src/esp/bindings/ShortestPathBindings.cpp
- src/esp/nav/CMakeLists.txt
- src/esp/nav/PathFinder.cpp
- src/esp/nav/PathFinder.h
- src/esp/nav/test/PathFinderTest.cpp
I did some additional benchmarking of the multigoal path finding, and the setup for projecting all the requested ends onto the navmesh is actually the bottleneck in a lot of cases.  This PR enables that setup to be cached so that subsequent called with the same path object/end points will not have to re-project them.
This PR also speeds up multigoal path finding by leveraging temporal consistency.  It is very likely that two concurrent calls with the same end points will have very similar starting points, thus we can heavily restrict the set of locations we need to search through by using their previously known distance and updating that to provide a minimum distance the point could possibly be.  We then explore candidate points based on this minimum distance.
Existing tests pass, new …
> Cache pathfinding setup

- habitat_sim/simulator.py
- tests/conftest.py
- tests/test_sensors.py
Finding a bug in #564 brought up that we don't have an e2e test for frustum culling ATM.  This PR adds frustum culling to the list of things we test in the existing e2e sensor test.
Via  itself!
New feature (non-breaking change which adds functionality)
> Add e2e test for frustum culling

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/RigidObject.cpp
- src/esp/physics/RigidObject.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
Change map refs for scene and physics attributes to be ESP smart pointers; modify PhysicsManager physics and scene inits to more appropriately utilize inheritance and minimize dupe code.
Following the modifications to PhysicsAttributeObjects to be ESP smart pointers, the references in resource manager to PhysicsSceneAttributes and PhysicsManagerAttributes have also been changed to shared pointers.  
Physics manager initialization functions that directly consume these attributes have also been slightly refactored to more appropriately respect inheritance and minimize code reuse.
run_tests and pytest successfully completed,
> --Change refs to scene and physics attributes to smart pointers

- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/RigidObject.cpp
- src/esp/physics/RigidObject.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
RigidObject base class and Bullet-based child class objects now have better inheritance pathways and more obvious overloading.
This pull request contains code to more clearly execute functionality with RigidObjects and BulletRigidObjects which inherit from them without code duplication or excess casting.  The base class functionality in rigidObject for initializing a scene object or an actual physical object is universal, while method hooks have been added for instancing/child class functionality to be added.  This will be easier to maintain (without code duplication) and easier to expand to support other physics engines.
run_tests and pytest execute without issues.
> --Better inheritance structure

- src/esp/assets/ResourceManager.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/RigidObject.cpp
- src/esp/physics/RigidObject.h
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
This pull request addresses 2 issues that were raised in #573 :  
1) access to ResourceManager via the various physics managers should be changed from ptr to reference
2) access to rigid body finalizing methods should be elevated to private from protected
--run_test and pytest both passed without issues
> --Change rigid body finalizing methods access to private.

- src/utils/viewer/viewer.cpp
navmeshVisNode_ needed to be verified not null before deletion
Addressing issue #581 
Bug Fix
run_test and pytest passed
> --Address Issue #581

- src/cmake/FindImGui.cmake
- src/cmake/FindMagnum.cmake
- src/cmake/FindMagnumPlugins.cmake
- src/tests/CMakeLists.txt
Was lying around in my working copy for a while, should be a pretty non-controversial change.
* Added a `FindImGui` module
* Updated `FindMagnum`, `FindMagnumPlugins`
* Explicitly finding dependency libraries where it wasn't done already
There's no real change, so there should be no real breakage either.
> Minor updates needed to make a build with system dependencies work again

- src/cmake/dependencies.cmake
Reported by @dexter1691 -- it breaks things when doing `./build.sh --debug`, in particular it causes
the Python bindings to have a different name, which are then not found properly by Python.
There should be no `d` suffix anymore in bindings produced in the Debug build.
:warning: Unfortunately the `INJECT_DEBUG_POSTFIX` option that's meant to fix this behavior wasn't working properly in the submodule commit that was in the repository, so I had to upgrade the `assimp` submodule to the `v5.0.1` tag. While I know about several things that got fixed for this version, there are also known regressions -- so please if you could check with random OBJ, STL or COLLADA files and check for suspicious behavior, it'd be great.
> Prevent Assimp from appending `d` to all our binaries

- src/esp/scene/Mp3dSemanticScene.cpp
Little bug in OBB loading for mp3d.  The radius of the obb is getting double corrected by the worldRotation.
User has a visualization script, used that.
> Don't double apply rotation

- data/default.phys_scene_config.json
- src/esp/assets/Attributes.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/RigidObject.cpp
- src/esp/physics/RigidObject.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
- src/tests/PhysicsTest.cpp
- src/utils/viewer/viewer.cpp
- tests/test_physics.py
This change fixes several bugs and addresses simulation stability.
[Test objects](http://dl.fbaipublicfiles.com/habitat/objects_v0.1.zip) have been updated with new visuals, better physical parameters, and better convex approximations. New test scene `apartment_1` added to [example scenes](http://dl.fbaipublicfiles.com/habitat/habitat-test-scenes.zip). Following empirical simulation stability testing, several changes seemed beneficial. 
- default simulation timestep and collision margins (world and objects) increased.
- `PhysicsManager::maxSubSteps_` variable replaced with hard-coded large value and specific treatment in interactive viewer application. 
- all post-initialization `setScale` functions have been removed. We only allow scale to be changed in templates before instancing …
> Bug fixes and stability improvements for physics simulation.

- src/esp/assets/ResourceManager.cpp
- src/esp/gfx/MaterialData.h
The `DEFAULT_MATERIAL` was initialized with full white ambient and diffuse light, causing objects to appear flat shaded. These values have been modified for a subjectively better appearance.
Original:
New:
> Better default material

- habitat_sim/simulator.py
- src/esp/bindings/SimBindings.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- tests/test_physics.py
When an object is initialized, a copy of its construction parameters template is saved. Querying this allows for static properties of the object (unchanging after instancing) to be queried including mass, scale, friction, and restitution.
Consumed this functionality in a test. If queried mass is wrong, the test will fail.
> Add python bindings for getObjectInitializationTemplate

- src/esp/assets/GenericInstanceMeshData.h
- src/esp/assets/PTexMeshData.cpp
- src/esp/assets/ResourceManager.cpp
- src/esp/gfx/GenericDrawable.cpp
- src/esp/gfx/LightSetup.cpp
- src/esp/gfx/MaterialData.h
- src/esp/nav/test/PathFinderTest.cpp
The vertex colored shader for ply meshes currently doesn't work, we rely on this for Replica meshes for webgl.
Visually (I need to add a replica scene to the list of sensors).
> Fix vertex colored

- habitat_sim/simulator.py
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/bindings/SimBindings.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/tests/SimTest.cpp
- src/utils/viewer/viewer.cpp
- tests/test_physics.py
This PR adds the ability to search by substring within the existing library of object templates in resource manager.  The user provides a substring to search for and a vector/list of all template handles that contain that substring are returned.  An empty substring returns all available handles. This functionality was extended to python bindings as well, and requisite testing was added.
Const correctness was also enforced in pure getters in Resource Manager.
C++ tests were added to verify the empty substring will return all handles and a partial string built from a known handle will return the full handle.  Python tests were modified so that the handle corresponding to the desired object ID was retrieved and used to instantiate the desired object.
> Attributes string search

- habitat_sim/simulator.py
- src/esp/bindings/SimBindings.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- tests/test_physics.py
Bounding boxes and other information can be queried from SceneNodes. Added method to query the SceneNode of an object from Simulator in C++ and python.
Added a test to `tests/test_physics.py`
> Add Simulator::getObjectSceneNode

- habitat_sim/simulator.py
- src/esp/bindings/SimBindings.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
Users may want to visualize an object's render asset bounding box (Axis-Aligned in the object's local space) in python.
Tested locally with python script:
> Add Simulator::setObjectBBDraw and python bindings

- src/esp/assets/BaseMesh.h
- src/esp/assets/CMakeLists.txt
- src/esp/assets/GenericMeshData.cpp
- src/esp/assets/GenericMeshData.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/core/RigidState.h
This PR renames the GltfMeshData class to be GenericMeshData, to more accurately reflect this class's applicability to many different mesh formats.  A method was added to instance a mesh object by the importer using a string name, in order to support mesh instancing using PrimitiveImporter.
All existing c++ and python tests
> --Renamed GltfMeshData -> GenericMeshData;

- src/esp/bindings/ShortestPathBindings.cpp
Users may want to recompute the NavMesh and then cache it to disk in python for large scenes or high-resolution NavMeshes.
Local testing.
> Save NavMesh python bindings

- src/esp/assets/Attributes.cpp
- src/esp/assets/Attributes.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/RigidObject.cpp
- src/esp/physics/RigidObject.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
- src/esp/sim/Simulator.h
- src/tests/SimTest.cpp
- src/utils/viewer/viewer.cpp
This PR introduces synthesized, primitive-based physical objects.  Currently they do not support collision (a future PR will provide implicit collision calculation support in Bullet; mesh-based collision support will follow at a later date).  
These synthesized primitive objects consume Magnum::Primitives as rendering assets, and use the default physical quantities as specified in the PhysicsObjectAttributes constructors, but otherwise follow the same code path and use cases as the file-loaded physical objects.  
Sim test was also modified to instantiate objects based on the name of the object template desired.
Existing tests all pass
> Physics primitives (non-colliding)

- docs/Doxyfile
- docs/README.md
Assorted updated to the documentation generator.
- Handles issues like in https://github.com/facebookresearch/habitat-api/issues/385 more gracefully. Unfortunately I wasn't able to reproduce locally (maybe it's something specific to a particular Python version, I'm on 3.8 here), so if this happens again it should print a descriptive warning and continue.
- Fixes non-deterministic output for default arguments containing function pointers, which means useless changes like in https://github.com/facebookmicrosites/habitat-website/commit/9cbead7f85aad0c30d86514e0bd790fe4dda8c1c won't happen anymore
- Creates output directory for Doxygen because Doxygen is unable to do that on its own.
- Adjusts itself for new bugs and regression in Doxygen 1.8.17 and 1.8.18.
- Properly includes CONTRIBUTING.md …
> Documentation generator updates

- src/esp/assets/GenericMeshData.cpp
- src/esp/assets/GenericMeshData.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/physics/bullet/BulletRigidObject.cpp
This PR provides direct setting of MeshData  in GenericMeshData objects, to facilitate programmatically composed MeshData objects, such as the navMesh, in an ongoing effort to move away from custom "PrimitiveMesh" handling. A future PR will actually consume this functionality for NavMeshes.
The PluginManager object is also now treated as a protected instance variable for ResourceManager, instantiated in constructor, so that it does not need to be reinstanced everywhere an importer is required.  A primitive importer is provided as an instance variable, to be used whenever primitive meshes are needed, so it also does not need to be reinstanced.
Lastly, some existing functions were renamed/reworked to reflect recent changes with regard to attributes and how certain resources are …
> Direct Navmesh/Meshdata handling; PluginManager instance variable

- habitat_sim/agent/agent.py
- tests/test_agent.py
The agent state setting is kinda confusing currently as the sensors don't follow the agent body by default, this leads to the anti-pattern of
```python
state = agent.state
state.rotation = something
agent.state = state
```
seemingly doing nothing!  This PR makes the more intuitive behavior of the sensors following the agent base the default.
The example above now moves the sensors.
- Breaking change (fix or feature that would cause existing functionality to change)
> Update agent state set state to be less confusing

- docs/Doxyfile
- docs/Doxyfile-public
- docs/conf-public.py
Followup to https://github.com/facebookresearch/habitat-sim/pull/624 based on a comment by @dhruvbatra. 
Yet another case of Doxygen unable to create a directory, however this time it fails silently. Sigh.
When generating public docs and the `build/docs/` directory didn't exist, Doxygen fails to create `build/docs/habitat-cpp.tag`, without any error, without any warning, nothing. To aid Doxygen in another case, m.css script creates `build/docs-public/` in that case, so tell Doxygen to put everything there, including the tagfile.
Also updated the Doxyfile to what 1.8.18 expects, getting rid of one warning in the output. (Tangential: the C++ docs are a *total mess*, not even my 5000 line terminal history scrollback was enough to fit all the warnings, and it seems to be getting progressively …
> Hopefully the final fix to yet another Doxygen failure

- src/esp/assets/Attributes.cpp
- src/esp/assets/Attributes.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
- src/esp/physics/bullet/BulletRigidScene.h
This PR introduces a mapping of Bullet Collider Primitives to our primitive meshes.  Now the primitives will interact with each other and other physical objects.  
This PR concludes the recent effort of introducing physically modeled primitives.  These can be used in a scene to provide physical objects without requiring file-based meshes. Currently these primitives are assigned the default material, but a future PR will introduce material editing.
All tests passed.
> Physics Primitives with collisions

- habitat_sim/simulator.py
- src/esp/bindings/SimBindings.cpp
- src/esp/bindings/bindings.cpp
- src/esp/core/random.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
Add random seed to the simulators config and expose core::Random to python so that the initial agent position/orientation is a) independent of np.random and b) consistent.
@mathfac I believe this won't effect habitat-api at all.  Habitat-api already calls `.seed` in habitat sim, so the random seed in the config here is irrelevant.
Took the random seeding out of my little viewer script and the agent always spawns at the same location!
> Agent position random seeding

- pyproject.toml
- src/esp/physics/RigidObject.cpp
- src/tests/PhysicsTest.cpp
Kinematic integration of angular velocity was failing trying to normalize a zero vector. Added a check for this and a test.
Added test with zero linear/angular velocity.
> [bugfix] Handle zero angular velocity in VelocityControl::integrateTransform

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/physics/bullet/BulletRigidObject.cpp
Enable the construction of PrimitiveAttributes objects by accessing a map of preconfigured template function pointers keyed by string name of Magnum Primitive Class.
As users wish to instantiate modified primitives to be used for rendering or collisions, we will want to instantiate new attributes on demand.  Instead of having a different instantiation method for each type of attributes, it would be ideal if we could reuse a single function, passing the desired type as a template parameter.  This functionality premaps calls to a template function that instantiates the appropriate shared pointer for each type of primitive currently supported.  Now, all that is required is knowledge of the name of the primitive desired to access the appropriate function to instantiate the desired primitive …
> --Enable construction of PrimitiveAttributes using string name

- src/esp/assets/Attributes.cpp
- src/esp/assets/Attributes.h
- src/esp/assets/BaseMesh.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/bindings/SimBindings.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/RigidObject.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/tests/PhysicsTest.cpp
- src/tests/SimTest.cpp
This PR changes how rendering and collision assets for physical objects (both file-based and primitive-based) are loaded.  Now, on program start, the assets requested are verified to exist but not loaded/instantiated.  Instead the required assets for an object are instantiated when the first object using a particular asset is instanced.  This will allow many physical objects to be made available without loading all their assets immediately, nor filling memory with object assets that may not even be used.  The program also starts much faster now, since the load time for the assets has been deferred until they are actually used.
Also, checks are put in place in case a user decides to change a template's render or collision asset handle and forgets to register this modified template.  Now, …
> --Make physical object asset loading/instantiation on demand

- src/CMakeLists.txt
- src/utils/viewer/viewer.cpp
Play will the viewer you will find:
-) Rendering images are discontinuous when you press left mouse button to rotate + scroll to zoom in and out, and use keyboard to control the agent and the sensors;
-) Rotation on left mouse button suffers significant numerical drifts, a bit difficult to manipulate the scene.
Root cause:
Different from keyboard event, when handling mouse press and scroll event, we convert such motions directly to the render camera, not to the agent or the attached sensors.
We are suffering such artifacts for quite a long time. This is the 1st diff to fix this problem.
> [Bug Fix][Viewer] Fix inconsistency between mouse move and keyboard move

- habitat_sim/attributes.py
- src/esp/assets/Attributes.cpp
- src/esp/assets/Attributes.h
- src/esp/assets/CMakeLists.txt
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/assets/managers/AssetAttributesManager.cpp
- src/esp/assets/managers/AssetAttributesManager.h
- src/esp/assets/managers/AttributesManagerBase.h
- src/esp/assets/managers/ObjectAttributesManager.cpp
- src/esp/assets/managers/ObjectAttributesManager.h
- src/esp/assets/managers/PhysicsAttributesManager.cpp
- src/esp/assets/managers/PhysicsAttributesManager.h
- src/esp/assets/managers/SceneAttributesManager.cpp
- src/esp/assets/managers/SceneAttributesManager.h
- src/esp/bindings/attributesBindings.cpp
- src/esp/sim/Simulator.cpp
- src/tests/PhysicsTest.cpp
- tests/test_physics.py
As per comments in #639, the accessor methods for attributes quantities are becoming absurdly long.  This is because of the extant chaining for all of these quantities through Simulator and into ResourceManager - full context must be given to differentiate functionality with respect to Simulator.  Furthermore, in order to support flexible editing capabilities, ResourceManager is becoming intolerably large, filled with nearly duplicated methods to handle attributes, and only stands to get larger as new attribute-related functionality is implemented.
Enter AttributeManagers.  This PR introduces AttributesManagers as a mechanism for managing instantiation and interaction with all attributes.  No more going through Simulator->ResourceManager for every attribute-related interaction, now the …
> Attribute managers

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/gfx/GenericDrawable.cpp
- src/esp/gfx/GenericDrawable.h
I am working on a new functionality in viewer -- object picking. This is a rather useful function that we would like to have for quite a long time.
This is 1st diff that is to address this problem.
We did not use the object id anywhere in our simulator, and it confuses the developers and users. The solution is to deprecate it, and introduce a drawableID in the Drawable class (parent class of GenericaDrawable) to address this problem (in the coming diff). So each drawable (NOT just the GenericDrawable) would have a unique id to identify itself.
> [object picking] Step 1: remove object id from GenericDrawable

- src/esp/assets/Attributes.cpp
- src/esp/assets/Attributes.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/assets/managers/AssetAttributesManager.h
- src/esp/assets/managers/AttributesManagerBase.h
- src/esp/assets/managers/ObjectAttributesManager.cpp
- src/esp/core/Configuration.h
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/RigidBase.h
- src/esp/physics/RigidObject.cpp
- src/esp/physics/RigidObject.h
- src/esp/physics/RigidScene.cpp
- src/esp/physics/RigidScene.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
- src/esp/physics/bullet/BulletRigidScene.cpp
- src/esp/physics/bullet/BulletRigidScene.h
- src/tests/PhysicsTest.cpp
- src/tests/SimTest.cpp
This PR presents the final C++ code to support and test the attributes managers implementations.  Included in this PR are : 
1. Added testing to SimTest to test the creation of objects based on primitive assets.
2. Removed simulator access to individual attribute templates for most cases.  All attributes should be accessed via attribute managers.
3. Most attributes access has been changed to provide a copy of the attributes being stored by the manager, instead of the actual attributes.  The goal is to have all such access be via copies, but this will be a breaking change, and will be introduced with the next PR, which will also introduce a tutorial on the proper usage of the attributes.
4. Cleaned up rigid object and rigid scene attributes access, and made object creation more efficient. …
> Attributes managers object sim tests

- .circleci/config.yml
- README.md
- conda-build/README.md
- conda-build/common/install_conda.sh
- conda-build/habitat-sim/meta.yaml
- conda-build/linux_matrix_builder.py
- conda-build/macos_matrix_builder.py
- Made Linux binaries build for head / headless x with bullet / without bullet
- Improved Conda build readme
- Use Frozen `conda-build` lib version that works with current setup
- Added conda binaries build step to CI without upload to Anaconda upload for testing purposes. 
- Next Conda workflows are supported now:
- Built v0.1.5 binaries.
- Added CI build step
> Conda build for head/headless x with bullet/without bullet, CI test, issues fixed

- data/default.phys_scene_config.json
- examples/tutorials/semantic_id_tutorial.py
- src/esp/assets/Attributes.cpp
- src/esp/assets/Attributes.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/bindings/AttributesBindings.cpp
- src/esp/bindings/SceneBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/gfx/GenericDrawable.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/RigidBase.h
- src/esp/physics/RigidObject.cpp
- src/esp/scene/SceneNode.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- tests/test_examples.py
Many use cases require the ability to set semantic id for objects introduced to the scene via the physics pipeline. This PR aims to address that need.
Currently, `SEMANTIC` sensor observations include per-vertex object ids imported from some datasets (e.g. MP3D and Replica). All other objects are rendered through this sensor by `SceneNode::id_` which defaults to -1 (not ideal as it is converted to unsigned int). This PR introduces a new `SceneNode::semanticId_` variable for this purpose with default 0 and necessary getters/setters + python property. 
A single object will have multiple SceneNodes which can have Drawables attached. This PR adds a function to assist users with setting the semantic id for all object nodes, an object template field for default semantic id, and a function to …
> Configurable Semantic id

- src/esp/bindings/ShortestPathBindings.cpp
- src/esp/nav/PathFinder.cpp
- src/esp/nav/PathFinder.h
- tests/test_navmesh.py
- tests/test_recompute_navmesh.py
In response to [this issue](https://github.com/facebookresearch/habitat-api/issues/420) this PR adds NavMesh area computation/query to Pathfinder. This computes the sum of all NavMesh polygon areas including all floors and isolated islands.
**Query the navigable area in python with:** `pathfinder.navigable_area`
Validated area locally on a 1.1m radius cylinder and 0.1m radius agent resulting in ~`π` area.
Added golden number test to pytest for `skokloster-castle` and `van-gogh-room`.
> Compute/query navigable area in Pathfinder

- docs/pages/image-extractor.rst
- habitat_sim/utils/data/data_extractor.py
- habitat_sim/utils/data/pose_extractor.py
- src/esp/bindings/ShortestPathBindings.cpp
- src/esp/nav/PathFinder.cpp
- src/esp/nav/PathFinder.h
- tests/test_data_extraction.py
Fix a bug in the pathfinder code and correct a name.
1. `encodePolyId(iTile, tile->salt, jPoly)` should be `encodePolyId(tile->salt, iTile, jPoly)`.  This bug didn't actually cause any issues since we just have 1 tile, thus `iTile` is `0`, and our tiles are never changed, so `tile->salt` is also always `0`.  But should fix it non-the-less to prevent future issues.
2. `pixels_per_meter` is actually `meters_per_pixel` based on the doc-string and usage.
CC @mpiseno 
Tests still pass
Docs change / refactoring / dependency upgrade
> Pathfinder House Keeping

- examples/demo_runner.py
- examples/example.py
- examples/settings.py
- tests/test_examples.py
It allows benchmark.py and other scripts to run on scenes that don't come with a precomputed navmesh. I also added args to examples/example.py. It automatically runs if a navmesh isn't loaded.
Added additional tests to tests/test_example.py
> Add recompute_navmesh to demo_runner and examples

- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/RigidBase.h
- src/esp/physics/RigidObject.h
- src/esp/physics/RigidScene.h
- src/esp/sim/Simulator.cpp
Retrieve a copy of the attributes template owned by an object that was used to create it.
This PR modifies the process to retrieve an object/scene's initialization attributes by returning a copy instead of const cptr of the attributes themselves.  The purpose of this was to allow users to modify the attributes to make modified copies of the object.
All existing c++ and python tests pass
> --Retrieve Copy of object creation attributes

- habitat_sim/simulator.py
Python implementation of split SEMANTIC render assigns the agent SceneNode's parent to the semantic SceneGraph root before rendering. Attaching an agent to a simulation object creates all rendering assets for the object under the agent's SceneGraph sub-tree. This results in an error during the secondary SEMANTIC rendering pass over the active SceneGraph added in #679. 
For reference this error displays as: 
```
SceneGraph::Object::transformations(): the objects are not part of the same tree
```
This PR re-assigns the agent SceneNode's parent to the active SceneGraph root before the 2nd pass to fix this bug.
Still no separate semantic testing on CI, leading to this bug slipping through. Tested locally.
> [bug-fix] Object-attached Agent with Split Semantic Scene

- .circleci/config.yml
Makes nightly build run at midnight PST instead of 5PM PST
> Change nightly to run at midnight PST (7AM UTC)

- src/esp/assets/Attributes.cpp
- src/esp/assets/Attributes.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/assets/managers/PhysicsAttributesManager.cpp
- src/esp/assets/managers/SceneAttributesManager.cpp
- src/esp/bindings/AttributesBindings.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/tests/CullingTest.cpp
- src/tests/DrawableTest.cpp
- src/tests/PhysicsTest.cpp
- src/tests/ResourceManagerTest.cpp
- src/utils/viewer/viewer.cpp
This PR introduces some changes to how the PhysicsManager object is maintained, and how scenes are loaded, in preparation for upcoming Scene Importing, to help generalize loading functionality and facilitate backwards compatibility with current scene loading/importing, as well as always giving the user access to default (primitive) objects.  The primary changes in this PR are : 
1. Configure physicsManager to always be constructed in some state in simulator/viewer so long as a renderer is created.
2. ResourceManager is changed to have only a single loadScene method.
3. The meaning of the --enable-physics flag has been changed to denote whether a BulletPhysicsManager is instantiated (if it has been installed).
C++ tests were modified slightly to load scenes in the appropriate manner;  All …
> --Configuration for SceneImport and Default Kinematics

- src/esp/bindings/SimBindings.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- tests/test_navmesh.py
Previous implementation (#683) enabled toggling the NavMesh visualization in Simulator. Would rather have a way to query/set the state of the visualization explicitly. This PR refactors the `Simulator.toggle_navmesh_visualization` function to a `Simulator.navmesh_visualization` property.
Local testing and small pytest check.
> Refactor NavMesh visualization to Simulator property

- .circleci/config.yml
Followup to #702. This introduces new `String` and `StringView` classes, which were not included in the previous update as those triggered an issue with `ar` on Emscripten, and an attempted fix for that issue triggered an issue with CMake < 3.13, and actually I just spent two days on an issue in Emscripten that was fixed *by us* in the first place, a year ago: https://github.com/emscripten-core/emscripten/commit/2c6c3cd8c3fcfc36add03881fd2bea7aacca04f0
Additionally fixes an issue with generating Magnum version headers that was shown as a warning during CMake configure step.
It took me **two days**, but the CIs *should finally pass now*.
> Updated Corrade/Magnum to latest, again

- src/esp/assets/managers/AssetAttributesManager.h
- src/esp/assets/managers/AttributesManagerBase.h
- src/esp/assets/managers/ObjectAttributesManager.h
- src/esp/assets/managers/PhysicsAttributesManager.h
- src/esp/assets/managers/SceneAttributesManager.h
- src/tests/AttributesManagersTest.cpp
The removal functionality within the attributes handler did not remove the handle from any specialization-specific handle lists.  Currently this is only an issue with ObjectAttributesManager, where file based and synthesized/prim-based attributes are partitioned.
This PR introduces a fix for this issue, and also includes c++ tests to verify this works.
Added c++ test functionality, and all c++/python tests pass.
> --Fix issue with attributes handle remove.

- src/esp/assets/Asset.cpp
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/managers/AssetAttributesManager.h
- src/esp/assets/managers/AttributesManagerBase.h
- src/esp/assets/managers/ObjectAttributesManager.cpp
- src/esp/assets/managers/ObjectAttributesManager.h
- src/esp/assets/managers/PhysicsAttributesManager.cpp
- src/esp/assets/managers/PhysicsAttributesManager.h
- src/esp/assets/managers/SceneAttributesManager.cpp
- src/esp/assets/managers/SceneAttributesManager.h
- src/esp/sim/Simulator.cpp
This PR is an incremental change for scene Import support that adds the ability to initialize newly created attributes with defaults before any file-based or otherwise specified values are set.  This also addresses some warnings related to unused arguments in certain method calls.
All existing c++ any python tests passed.
> Scene Import setup/initialization of newly-created attributes

- habitat_sim/geo.py
- habitat_sim/physics.py
- src/esp/assets/ResourceManager.cpp
- src/esp/bindings/GeoBindings.cpp
- src/esp/bindings/GfxBindings.cpp
- src/esp/bindings/PhysicsBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/geo/geo.h
- src/esp/gfx/RenderCamera.cpp
- src/esp/gfx/RenderCamera.h
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/RigidBase.h
- src/esp/physics/RigidObject.cpp
- src/esp/physics/RigidObject.h
- src/esp/physics/bullet/BulletBase.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
- src/esp/physics/bullet/BulletRigidScene.cpp
- src/esp/physics/bullet/BulletRigidScene.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/utils/viewer/viewer.cpp
- tests/test_gfx.py
- tests/test_physics.py
Several existing use cases (e.g. #717, #699) require ray-casting in the simulation's collision world and viewport to ray un-projection. This PR adds support for these features and includes the following changes:
- `esp::geo::Ray` struct and python bindings
- `RenderCamera::unproject` function for 2D viewport -> 3D Ray
- PhysicsManager API for ray-casting: `castRay` function as well as `RayHitInfo` and `RaycastResults` structs.
- BulletPhysicsManager implementation of ray-casting including map of `btCollisionObjects` to object ids for faster identification of objects hit by rays.
New python test: `test_physics.test_raycast`.
and
Demo viewer implementation (**will be removed before merge**):
> RenderCamera::unproject and Simulator::castRay via Bullet physics

- src/esp/assets/ResourceManager.cpp
Variable returned from configuration query should be reference to config, but auto caused a copy to be made, preventing primitive configurations to be modified; replace namespace tags with aliases for consistency.
all c++ and python tests passed
> --Address improper auto type deduction

- src/esp/assets/Attributes.cpp
- src/esp/assets/Attributes.h
- src/esp/assets/managers/AssetAttributesManager.cpp
- src/esp/assets/managers/AssetAttributesManager.h
- src/esp/assets/managers/AttributesManagerBase.h
- src/esp/assets/managers/ObjectAttributesManager.cpp
- src/esp/assets/managers/ObjectAttributesManager.h
- src/esp/assets/managers/PhysicsAttributesManager.cpp
- src/esp/assets/managers/PhysicsAttributesManager.h
- src/esp/assets/managers/SceneAttributesManager.cpp
- src/esp/assets/managers/SceneAttributesManager.h
- src/esp/physics/PhysicsManager.h
Reading json handles and json meshtypes improved -if a mesh handle is changed in json, but no mesh type is specified, rudimentary mesh type setting is performed; Unused methods are removed;
Possibility of changing mesh handle to different type of mesh in json, without specifying new type.  This puts hooks into process that allows for semi-intelligent mesh type setting if needed.  Also a few methods have been removed that were not being used from attributes handlers.
All C++ and python tests have passed.
> --Plug possible loophole in mesh handle/type setting in json;

- examples/colab_utils/colab_install.sh
* Fixes the Habitat-API and Habitat_baseline global installs so that they don't need to be added to the colab path.
* Fixes bug with aborting if not in Colab
* Fixes bug that prevented ifcfg from being installed
* Adds stderr message to let it know it's aborting the install script due to prior install
* Refactor nightly build command to be more concise
* Add CHANNEL env variable for changing the install channel
In Colab. You can test yourself by changing the colab download URL
- [] I have added tests to cover my changes.
- [] All new and existing tests passed.
> Fix habitat-api + habitat_baselines global install

- habitat_sim/utils/__init__.py
- habitat_sim/utils/viz_utils.py
Instead of duplicating the process of making a video from sensor observations with overlays we'll provide a fairly general utility.
Based on #706 
Local in Colab.
E.g.
```
overlay_dims = (int(sim_settings["width"]/5), int(sim_settings["height"]/5))
overlay_settings = [
{
"obs": "color_sensor_1st_person",
"type": "color",
"dims": overlay_dims,
"pos": (10,10),
"border": 2
},
{
"obs": "depth_sensor_1st_person",
"type": "depth",
"dims": overlay_dims,
"pos": (10,30+overlay_dims[1]),
"border": 2
},
{
"obs": "semantic_sensor_1st_person",
"type": "semantic",
"dims": overlay_dims,
"pos": (10,50+overlay_dims[1]*2),
"border": 2
}
]
make_video(
observations = observations,
primary_obs = "color_sensor_3rd_person",
primary_obs_type = "color",
video_file= "test_new_video",
fps= int(1.0 / time_step), …
```
> Add make_video utility to viz_utils

- src/esp/assets/managers/SceneAttributesManager.cpp
Added support in scene import of lists of object paths to be used in scene, using the same protocol as is presently used for physics manager json.
existing tests passed
> --Add support for lists of file locations for scene objects.

- .circleci/config.yml
- CONTRIBUTING.md
- README.md
- docs/Doxyfile-mcss
- docs/conf.py
- habitat_sim/utils/__init__.py
We changed the name of `Habitat-API` to `Habitat Lab` to make less confusing and stress the purpose of the repo to propose Tasks, Metrics, Baselines to the community. Mirroring https://github.com/facebookresearch/habitat-lab/pull/448 for Habitat Lab.
- Fixed the referenced links that become broken on the website
- Added `--depth 1` option to speed up Hab Lab clone step
> Added changes supporting renaming of habitat-api to habitat-lab

- src/esp/assets/Attributes.cpp
- src/esp/assets/Attributes.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/managers/AssetAttributesManager.cpp
- src/esp/assets/managers/AssetAttributesManager.h
- src/esp/assets/managers/AttributesManagerBase.h
- src/esp/assets/managers/ObjectAttributesManager.cpp
- src/esp/assets/managers/ObjectAttributesManager.h
- src/esp/assets/managers/PhysicsAttributesManager.cpp
- src/esp/assets/managers/PhysicsAttributesManager.h
- src/esp/assets/managers/SceneAttributesManager.cpp
- src/esp/assets/managers/SceneAttributesManager.h
- src/esp/bindings/AttributesManagersBindings.cpp
- src/tests/AttributesManagersTest.cpp
Expand default attributes handling to be available to all attributes managers.  Makes object templates specified by physics world attributes or scene attributes, as well as those associated with primitive assets, to be unable to be removed by the user.  Adds a single function and python binding to be able to remove all removable templates in one command.  Adds tests to verify functionality.
C++ tests added to verify functionality.  All c++ and python tests passed.
> --Make default attributes templates read-only.

- docs/Doxyfile
We have around 100+ broken links from the doc page: https://aihabitat.org/docs/habitat-cpp/namespacestd.html.
To fix broken links in docs excluded std lib to from linking pipeline.
Check docs build in CI.
> To fix broken links in docs excluded std lib to from linking pipeline

- src/esp/assets/managers/AssetAttributesManager.cpp
- src/esp/assets/managers/AttributesManagerBase.h
- src/esp/assets/managers/ObjectAttributesManager.cpp
- src/esp/bindings/AttributesManagersBindings.cpp
- src/tests/AttributesManagersTest.cpp
- tests/test_attributes_managers.py
Certain attributes templates are expected to always be around (such as default primitive asset attribute templates and the object templates built from them.  Furthermore, users may wish to set templates to be locked to prevent accidental deletion, or to unlock them once they decide to delete them.  This PR supports this functionality.
Existing c++ and python tests passed.
EDIT (JT) : Tests have been added in c++ and python to verify functionality.
> -Allow for expanded 'read-only' setting for Attributes Templates.

- src/esp/assets/ResourceManager.cpp
- src/esp/gfx/RenderTarget.cpp
Updates to the new [Trade::MaterialData](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1MaterialData.html) APIs in Magnum, which provide:
- generic key/value store for arbitrary material properties including strings and pointers
- generic material layer support for PBR clearcoat/thinfilm/sheen... properties as well as custom material layering
- convenience APIs for common Flat, Phong and PBR material properties
- import of glTF PBR specular/glossiness properties via [Trade::PbrSpecularGlossinessMaterialData](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1PbrSpecularGlossinessMaterialData.html)
- import of glTF PBR metallic/roughness properties via [Trade::PbrMetallicRoughnessMaterialData](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1PbrMetallicRoughnes …
> Update to the new MaterialData APIs in Magnum

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
As titled.
In this diff, 2 changes:
- compute the absolute AABB for replica mesh by default.
- add some comments to improve the code readability.
> Bug fix: no frustum culling for replica data set.

- README.md
There is no mentions of Habitat-Lab from the Readme. That can lead to users re-inventing the wheel for embodied AI experiments. Added Habitat-Lab link as experiment framework to Readme.
> Added Habitat-Lab link as experiment framework to Readme

- setup.py
It makes sure the pip being called to install magnum is the one that is actually associated with the current python environment. It also removes some unnecessary shlex to make sure paths with quotes, spaces, or other special characters will work.
I also added an automatic way of running pytest tests from setup.py including install pytest and improved some of the features inside of setup.py
Ran the setup.py with all the options
- [] Docs change / refactoring / dependency upgrade
- [] New feature (non-breaking change which adds functionality)
- [] I have updated the documentation accordingly.
- [] I have added tests to cover my changes.
> Fix pip install and shlex in setup.py

- habitat_sim/utils/__init__.py
- habitat_sim/utils/profiling_utils.py
- tests/test_profiling_utils.py
profiling_utils.py adds helper functions for profiling. Profilers like Nvidia Nsight can capture the time spent in annotated ranges.
This code has already been reviewed in a previous PR into Hab-lab: https://github.com/facebookresearch/habitat-lab/pull/451 . We've since decided that profiling_utils should live in Hab-sim. I'll open a new Hab-lab PR shortly to delete profiling_utils there.
I introduce the `HABITAT_PROFILING` environment variable to selectively enable these and future profiling-related stuff. 
Currently, `range_push`/`range_pop` are thin wrappers over the NVTX versions. In the future, we might add a different backend that doesn't depend on Nvidia or that works across multiple machines.
Example usage for marking ranges. For convenience, there are three syntax options; …
> add profiling_utils.py

- habitat_sim/utils/compare_profiles.py
- tests/test_compare_profiles.py
Helper script to print summary timings for one or more profiles captured by Nvidia Nsight containing NVTX events. The script reads all sqlite files in the working directory. To add NVTX ranges to your program, see profiling_utils.py.
See also previous PR into Hab-Lab, which I've closed in favor of this one: https://github.com/facebookresearch/habitat-lab/pull/454
Exampe usage:
```
apt-get install nvidia-nsight
export HABITAT_PROFILING=1
path/to/nvidia/nsight-systems/bin/nsys profile --sample=none --trace=nvtx
--trace-fork-before-exec=true --output=profile1 --export=sqlite python
my_program.py
path/to/nvidia/nsight-systems/bin/nsys profile --sample=none --trace=nvtx
--trace-fork-before-exec=true --output=profile2 --export=sqlite python
my_program.py
python habitat/utils/compare_profiles.py …
```
> Add compare_profiles.py

- tests/test_sensors.py
I had a recent CI build fail on this check. The next CI build passed, with no changes related to depth-rendering. I don't want to dig too deep here; I'm guessing there's been no render regressions here and epsilon just needs to be a bit larger (5e-2 -> 9e-2).
Note also that Mosra recently increased the epsilon from 2e-2 to 5e-2.
Here's the recent failed test: https://app.circleci.com/pipelines/github/facebookresearch/habitat-sim/3230/workflows/dd2a5508-26d1-4796-ad98-db21227d1616/jobs/12089
Not much. I don't have a way to repro the CI failure. I re-ran the test on my devfair machine and certainly it passed, but I didn't try to verify that this test is still working as designed.
> Increase epsilon for test_sensors.py pixel test

- src/esp/assets/attributes/AttributesBase.h
- src/esp/assets/attributes/ObjectAttributes.cpp
- src/esp/assets/attributes/ObjectAttributes.h
- src/esp/assets/attributes/PhysicsManagerAttributes.cpp
- src/esp/assets/attributes/PhysicsManagerAttributes.h
- src/esp/assets/managers/AssetAttributesManager.cpp
- src/esp/assets/managers/AssetAttributesManager.h
- src/esp/assets/managers/AttributesManagerBase.h
- src/esp/assets/managers/ObjectAttributesManager.cpp
- src/esp/assets/managers/ObjectAttributesManager.h
- src/esp/assets/managers/PhysicsAttributesManager.cpp
- src/esp/assets/managers/PhysicsAttributesManager.h
- src/esp/assets/managers/StageAttributesManager.cpp
- src/esp/assets/managers/StageAttributesManager.h
- src/esp/bindings/AttributesBindings.cpp
- src/esp/io/json.h
- src/tests/AttributesManagersTest.cpp
- src/tests/CMakeLists.txt
- src/tests/CoreTest.cpp
- src/tests/IOTest.cpp
We needed more tests for attributes setting via JSON.  This PR adds the following : 
1. The ability to parse a JSON doc directly into an attributes template.  The JSON did not have to originate from a file.
2. Example JSON strings for each type attributes that can be built from a JSON file.  These illustrate tags being used, with non-default values so that they can be used to test the JSON parsing functionality.
3. Test JSON loading and parsing for PhysicsManager, Object and Stage Attributes
4.  JSON tests were also moved from core to IO. 
All existing c++ and python tests have passed; Test added to verify all expected JSON fields are correctly populated.
> -- Expand Attributes' JSON-loading tests

- src/esp/gfx/RenderTarget.cpp
- src/esp/gfx/RenderTarget.h
- src/esp/sensor/PinholeCamera.cpp
- src/esp/sensor/PinholeCamera.h
- src/esp/sensor/VisualSensor.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/utils/viewer/viewer.cpp
Tested the PR752 and found a couple of issues:
- In Linux: "imgui" did not display run-time info;
- In Linux: object picking functionality is broken;
- In Mac OSX: The rendering of the picked object is wrong. Occluded triangles would be displayed suggesting the depth buffer was broken.
This PR is to fix this problem.
Root cause:
For the broken object picking:
Now we display the observation via the sensor. A sensor will draw the observation to a framebuffer other than the default main buffer, and then blit the RGB result to the default buffer (NOTE: ONLY color info, NO depth info). However, we need the depth info in rendering the picked object.
For imgui:
The problem was that we did not re-bind the default framebuffer after we displayed the observation of the sensor.
Solution:
When an …
> Fix the depth buffer issue in PR752

- docs/Doxyfile-mcss
- docs/conf.py
- docs/pages/image-extractor.rst
- docs/pages/lighting-setups.rst
- docs/pages/notebooks.rst
- docs/pages/rigid-object-tutorial.rst
Minor changes to documentation to remove unused notebooks.rst page and fix pages.html linking to some tutorial pages.
local build
Fixed pages.html:
> [docs] Fix page linking and remove unused notebooks.rst page

- setup.py
Fixes a bug in setup.py introduced by #757 that prevented setup.py from using make if ninja was not available. Apparently, if the subprocess executable is not found it throws a `FileNotFoundError` instead of a `subprocess Error`. This patch widens the exception catching target to include this as well as other permission related errors.  
I was able to build on my machine that doesn't have Ninja installed.
> Fix building with make in setup.py

- src/esp/assets/managers/AssetAttributesManager.h
- src/esp/assets/managers/AttributesManagerBase.h
- src/esp/assets/managers/ObjectAttributesManager.h
- src/esp/assets/managers/PhysicsAttributesManager.h
- src/esp/assets/managers/StageAttributesManager.cpp
- src/esp/assets/managers/StageAttributesManager.h
- src/esp/bindings/AttributesManagersBindings.cpp
Previously, the attributes managers specialized the class template by specifying a smart pointer to an attributes class as the class template type parameter.  This relied on the implementer knowing what was required by the class template, method -wise, in order for the manager to properly function.  If an inappropriate class was specified, the class template functionality would fail.
This PR introduces a verification process to make sure the class template type parameter references a class that has the required methods for the manager to function.  This is accomplished by sending the actual attributes class as the template type to specialize the class template.  This allows us to verify that the specified template class is derived from the desired base class (so we can be sure that the …
> --[Bug Fix] Verify AttributesManager template type is valid

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/physics/PhysicsManager.h
- src/esp/sensor/VisualSensor.h
- src/tests/PhysicsTest.cpp
RigidStage objects were not being made if there was no collision asset being constructed.  This would only happen if physicsManager was nullptr (which only happens during certain tests) or if none-type physicsManager is specified.  
This makes RigidStage objects if collision assets are not requested, and will attempt to build collisionMeshGroups out of render mesh if no valid collision mesh is specified. 
A warning for an unused argument in VisualSensor is also addressed.
C++ and Python tests have passed
> --[Bug fix] Address stage load w/"none" physicsManager

- habitat_sim/simulator.py
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/bindings/GfxBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/gfx/RenderTarget.cpp
- src/esp/gfx/RenderTarget.h
- src/esp/gfx/Renderer.cpp
- src/esp/gfx/Renderer.h
- src/esp/sensor/CMakeLists.txt
- src/esp/sensor/VisualSensor.cpp
- src/esp/sensor/VisualSensor.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/utils/viewer/viewer.cpp
- tests/test_sensors.py
Textures take a lot of GPU memory but we don't need them unless we are doing RGB rendering.  So don't load them if we aren't!
I also removed the compressTextures_ flag while I was poking around.  That is certainly deprecated as it was subsumed by basis and it never worked on Gibson (those textures are too big).
One thing this has revealed is that is likely time to get rid of the hack of sharing the simulator between tests to make them run faster.  That will make tests right slightly slower but at least it will put pressure on us to make spin-up time as fast as possible?
Tests pass.  You can tell it is not loading textures by GPU memory usage and just pure load time :)
New feature (non-breaking change which adds functionality)
> Don't load textures if you don't need them

- .circleci/config.yml
- tests/conftest.py
- tests/test_attributes_managers.py
- tests/test_data_extraction.py
- tests/test_gfx.py
- tests/test_light_setup.py
- tests/test_navmesh.py
- tests/test_physics.py
- tests/test_random_seed.py
- tests/test_sensors.py
- tests/test_simulator.py
It's time to get rid of the sharing the instance of the simulator among all the tests hack.  I also added an explicit test that the current test_sensors was implicitly testing -- making sure reconfigure actually swaps the scene correctly.
This also allows us to enable parallel testing through https://github.com/browsertron/pytest-parallel so total test time is actually reduced!
Via the tests
Docs change / refactoring / dependency upgrade
> No shared sim

- .circleci/config.yml
- conda-build/Dockerfile
After latest change we noticed that Conda build step was triggered both for tagged commit and for the one merged into master:
Based on [CircelCI documentation](https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag) that's the right way to disabled running version_conda_release on every master commit as `filters` section is union not intersection of branch and tag filters.
Hard to tests without landing.
> Disabled running version_conda_release on every master commit

- src/esp/assets/attributes/ObjectAttributes.cpp
- src/esp/assets/attributes/ObjectAttributes.h
- src/esp/assets/managers/AssetAttributesManager.cpp
- src/esp/assets/managers/AssetAttributesManager.h
- src/esp/assets/managers/AttributesManagerBase.h
- src/esp/assets/managers/ObjectAttributesManager.cpp
- src/esp/assets/managers/ObjectAttributesManager.h
- src/esp/assets/managers/PhysicsAttributesManager.h
- src/esp/assets/managers/StageAttributesManager.cpp
- src/esp/assets/managers/StageAttributesManager.h
- src/esp/bindings/AttributesBindings.cpp
- src/esp/physics/bullet/BulletRigidObject.cpp
This supports using primitive asset attributes tags as collision or render mesh names in object JSON configuration files.
To use this, the exact name of the primitive asset attributes template must be used in the object attributes template as either the render or collision mesh.  
So, for example, to use a sphere primitive as the collision asset, use "uvSphereSolid_rings_8_segments_16_useTexCoords_false_useTangents_false" as the "collision mesh" value in the object's configuration JSON file.
Also, another tag has been added, "collision asset size", which is a 3-vector to enable resizing the primitive to match the render asset.  So if the render asset has is a sphere of radius .1 meters, then this tag should be :
"collision asset size" : [0.1,0.1,0.1]
all c++ and python tests passed
> Object Attributes allow for primitives as asset handles

- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
- src/tests/PhysicsTest.cpp
An issue was identified where removing a sleeping object supporting other objects would not activate the supported objects, causing them to float instead of falling as expected. This PR fixes the issue by activating a sleeping object's collision island upon removal.
Added `TestRemoveSleepingSupport ` to `PhysicsTest.cpp`.
Testing in viewer:
Green outline denotes sleeping object.
**Before**:
**After**:
> [bugfix] Activate island when removing sleeping objects

- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
- src/tests/PhysicsTest.cpp
Noticed that `MotionType::KINEMATIC` objects were not responding correctly in many cases. Investigation led to this refactor. We need to create a new `btRigidObject` with different properties when swapping between `KINEMATIC` and `DYNAMIC` `MotionTypes`.
Current tests pass.
Local testing in viewer for identified edge case:
**Before:**
Notice the sleeping object's collision shape is out of sync after set to kinematic.
Notice the skating of dynamic objects when stacking on a kinematic object.
**After:**
These issues are fixed. Notice objects in contact with kinematic objects will not sleep.
> [bugfix] Better handling for MotionType::KINEMATIC

- data/test_assets/objects/sphere.phys_properties.json
The existing test asset "sphere.glb" was using its render mesh (1.5k polys) as a collision mesh, which resulted in overly expensive collision calcs.  This PR has a change to the configuration so the sphere will use a properly sized primitive for implicit collision calculation.
> --Update sphere test asset to use primitive sphere implicit collider.

- src/esp/bindings/SimBindings.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletBase.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidStage.cpp
- src/esp/sim/Simulator.h
- src/tests/PhysicsTest.cpp
This is a change to how we create Bullet static objects (including the stage). The previous approach caused an issue where the static object would never go to sleep, thus causing a potential runtime perf hit. The new approach is more consistent with Bullet example code and fixes the non-sleeping issue.
I've also added `get_num_active_contact_points`, which is generally useful as a proxy for Bullet collision cost/complexity and also helps diagnose/test the specific issue with static objects.
`SimTest` unit test. Ad hoc testing in viewer with stage, dynamic objects, and static objects.
> Fix for Bullet static objects/stage and add get_num_active_contact_points, 

- src/esp/bindings/SimBindings.cpp
- src/esp/sim/CMakeLists.txt
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/esp/sim/SimulatorConfiguration.cpp
- src/esp/sim/SimulatorConfiguration.h
This PR moves the SimulatorConfiguration class to its own file, so that it can be consumed by other classes without importing all of Simulator.h.  
C++ and python tests
> --Move SimulatorConfiguration to separate file.

- examples/tutorials/colabs/ECCV_2020_Advanced_Features.ipynb
- examples/tutorials/colabs/ECCV_2020_Interactivity.ipynb
- examples/tutorials/colabs/rigid_object_tutorial.ipynb
- examples/tutorials/nb_python/ECCV_2020_Advanced_Features.py
- examples/tutorials/nb_python/ECCV_2020_Interactivity.py
- examples/tutorials/nb_python/rigid_object_tutorial.py
- src/esp/bindings/AttributesManagersBindings.cpp
- tests/test_physics.py
- tests/test_simulator.py
This adds an additional python binding to load objects, and deprecates, but does not remove, the existing binding.  This is in preparation for MetadataMediator/Dataset config handling.
c++ and python tests
> --Refactor load configs call.

- src/esp/core/ManagedContainerBase.h
- src/esp/metadata/managers/AssetAttributesManager.h
- src/esp/metadata/managers/ObjectAttributesManager.cpp
- src/esp/metadata/managers/PhysicsAttributesManager.h
- src/esp/metadata/managers/StageAttributesManager.cpp
This allows for the AttributesManagers to accept a default attributes object to be used to construct all future objects. If one is not provided, construction proceeds as before.  This is in preparation for MetadataMediator.
c++ and python tests.
> --Handle setting a default object for Attributes Managers

- src/esp/assets/MeshData.h
This is to fix the comments in the MeshData.h and thus reduce the warning during compilation
> remove "\" which causes compilation warning

- src/esp/physics/bullet/BulletRigidObject.cpp
We looked at some physics videos recently that showed books falling through the bookcase and objects not resting properly on the sofa. As a result, we were concerned about the long-term usability of convex shapes.
I tracked this down to a bug in how we're constructing the convex shapes. Specifically, while GLB nodes/meshes often contain *scale*, the Bullet `btTransform` class does *not* support scale/shear. And sadly, Bullet doesn't assert or warn about this when you construct btTransforms.
My fix here is to give Bullet world-space vertices (already transformed) instead of local-space.
Ad hoc testing in viewer with our sofa object (composed of multiple convex parts). See screenshot.
> fix for BulletRigidObject convex shapes

- src/esp/gfx/LightSetup.cpp
- src/esp/gfx/LightSetup.h
- src/esp/sim/Simulator.cpp
Better default lighting. The previous set of point lights was too dark for large scenes.
Ad hoc testing in viewer
> add getDefaultLights

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
- src/esp/metadata/managers/AssetAttributesManager.cpp
- src/esp/metadata/managers/AssetAttributesManager.h
- src/esp/metadata/managers/AttributesManagerBase.h
- src/esp/metadata/managers/ObjectAttributesManager.cpp
- src/esp/metadata/managers/ObjectAttributesManager.h
- src/esp/metadata/managers/PhysicsAttributesManager.cpp
- src/esp/metadata/managers/PhysicsAttributesManager.h
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.h
- src/esp/physics/PhysicsManager.h
- src/esp/physics/RigidBase.h
- src/esp/physics/RigidObject.cpp
- src/esp/physics/RigidObject.h
- src/esp/physics/RigidStage.h
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
This removes namespace aliases into the metadata attributes and metadata managers that were unnecessary.
c++ and python tests
> --Remove unnecessary namespace alias

- src/esp/gfx/GenericDrawable.cpp
- src/esp/gfx/GenericDrawable.h
- Use `normalMatrix()` in the GenericDrawable;
- Light range is set to `Mn::Constants::inf()`;
- Remove not used variables;
> Use normalMatrix in the GenericDrawable

- .circleci/config.yml
- habitat_sim/agent/controls/object_controls.py
- habitat_sim/agent/controls/pyrobot_noisy_controls.py
- habitat_sim/logging.py
- habitat_sim/nav/greedy_geodesic_follower.py
- habitat_sim/registry.py
- habitat_sim/sensors/noise_models/no_noise_model.py
- habitat_sim/simulator.py
- habitat_sim/utils/common.py
- habitat_sim/utils/compare_profiles.py
- habitat_sim/utils/data/pose_extractor.py
- habitat_sim/utils/viz_utils.py
We have static type guarding, now we can use pytest to do runtime typeguarding too (only when pytest is run). 
It also caught a few minor typing bugs (with lists/ndarrays) used interchangably that have now been fixed.
This will only check if any existing typehints are used incorrectly. (Ex passing a list when it expects a numpy array etc).
Typeguard and pytest
> Enable typeguard pytest plugin

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/gfx/Drawable.h
- src/esp/gfx/GenericDrawable.cpp
- src/esp/gfx/GenericDrawable.h
- src/tests/DrawableTest.cpp
First, this diff fixes a bug. Now it will ignore the normal maps with a warning for meshes without tangents. This is quite similar to:
https://github.com/mosra/magnum-extras/commit/ad06e1ab741cb62eff43bf1b3de3be679d4a1610
Second, it improves the code readability  by changing 
```
lightSetup --> lightSetupKey
material --> materialKey
```
in a number of places.
Third, this is the 1st diff to implement the PBR. (I am going to split the giant PR #812 into many small PRs to make the reviewers' life a bit easier.)
> [bug fix][PBR 1] Ignore normal maps with a warning for meshes without tangents

- .pre-commit-config.yaml
Ensures that only properly formatted JSONs can be committed (unless added to the pre-commit exclude)
Partially addresses this comment: https://github.com/facebookresearch/habitat-sim/pull/852#discussion_r503550351
Ran the pre-commit hook locally.
> Add json validator pre-commit hook

- src/esp/physics/bullet/BulletBase.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidStage.cpp
- src/esp/physics/bullet/BulletURDFImporter.cpp
Various small fixes to improve runtime perf related to Bullet collision-detection. For details, see inline comments.
One change here is an overhaul of collision filtering. This is the choice of "group" and "mask" for collision objects added to the Bullet world. My new proposed scheme is:
- Static objects use group btBroadphaseProxy::StaticFilter and are set to collide with dynamic objects.
- Dynamic objects use group btBroadphaseProxy::DefaultFilter and are set to collide with static objects, kinematic objects, and other dynamic objects.
- Kinematic objects use group btBroadphaseProxy::KinematicFilter and are set to collide with dynamic objects.
- castRay uses group btBroadphaseProxy::DefaultFilter and is set to collide with everything (btBroadphaseProxy::AllFilter). This is the default …
> Bullet collision tuning

- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
- tests/test_physics.py
Recent changes brought all MotionTypes into the `btRigidBody` API. This PR cleans up unnecessary separate treatment and unifies the construction pipeline.
Note: some changes to existing physical simulation results are expected as `STATIC` objects will now have the properly configured friction, restitution, and damping.
Velocity setting for KINEMATIC objects is allowed. These will not be integrated, but may improve Bullet internal contact response with DYNAMIC objects.
All tests should still pass.
> Unify RigidObject construction pipeline and MotionType treatment.

- src/esp/bindings/PhysicsBindings.cpp
- src/esp/physics/RigidBase.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
Renaming motion type default value to be "UNDEFINED" and assigning it a value of -1 in the enum class wherein it resides.  This has been done to more accurately reflect what it represents, and to facilitate object motion-type setting via scene instance descriptors in the upcoming MetadataMediator/Dataset/Scene instance import functionality.
all existing c++ and python tests
> --Change name of unknown motion type to "UNDEFINED" and assign value of -1

- src/esp/bindings/SimBindings.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletDebugManager.cpp
- src/esp/physics/bullet/BulletDebugManager.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
- src/esp/physics/bullet/BulletRigidStage.cpp
- src/esp/physics/bullet/BulletRigidStage.h
- src/esp/physics/bullet/BulletURDFImporter.cpp
- src/esp/physics/bullet/CMakeLists.txt
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
Debugging tech to help us identify when/why collision-detection is hurting runtime perf.
Sample output from getStepCollisionSummary:
```
[URDF, kitchen_counter, link body, act state 3, group 1, mask -1] vs [RigidObject, ./data/objects/frl_apartment_cup_03.phys_properties.json, id 13, act state 2, group 2, mask -3], 1 points
[URDF, kitchen_counter, link body, act state 3, group 1, mask -1] vs [RigidObject, ./data/objects/frl_apartment_cup_03.phys_properties.json, id 14, act state 2, group 1, mask -1], 4 points
[URDF, fetch, link l_wheel_link, act state 2, group 1, mask -1] vs [Stage, ./orp/start_data/frl_apartment_stage_pvizplan_empty_simplified.stage_config.json, subpart 11, act state 1, group 2, mask -3], 3 points
[URDF, fetch, link r_wheel_link, act state 2, group 1, mask -1] vs [Stage, …
```
> add BulletDebugManager

- habitat_sim/utils/profiling_utils.py
- tests/test_profiling_utils.py
We want to control the range of train steps that we capture for profiling.
Example usage for capturing a certain range of train steps (from step 200 to
step 300):
```
@profiling_utils.RangeContext("train")
def train():
profiling_utils.configure(capture_start_step=200, num_steps_to_capture=100)
initialize_training()
for _ in range(10000)):
profiling_utils.on_start_step()
with profiling_utils.RangeContext("collect_rollout_steps"):
collect_rollout_steps()
with profiling_utils.RangeContext("update_agent"):
update_agent()
```
Added a unit test. Also some ad hoc testing with DDPPO training.
> add profiling_utils.configure and on_start_step

- tests/test_profiling_utils.py
This unit test can randomly fail based on the order of other tests running. I'm fixing it.
I'm unable to reproduce the failure, so this fix is somewhat speculative. I re-ran the test locally.
> fix for test_configure_and_on_start_step

- src/esp/assets/PTexMeshData.cpp
- src/esp/assets/PTexMeshData.h
- src/esp/assets/ResourceManager.cpp
Add collision mesh data to ptex meshes.  Slightly messy as there are some complications of ownership, but, at some point, we will want to use a decimated mesh for collisions so the containers that only are used when the mesh is split will be used all the time.
Closes #866 
Fixes #865 
Locally.  Viewer loads the ptex mesh and navmesh recomputation works as expected with it.
New feature (non-breaking change which adds functionality)
> Add ptex collision mesh data

- src/esp/gfx/GenericDrawable.cpp
This is to address a bug mentioned by @eundersander . Here I quote:
"the warning about lacking tangents is essentially setting up the user to inevitably fail this later assert.
https://github.com/facebookresearch/habitat-sim/commit/77d201a15442e8bb6e68baca5d8552e81c763803#diff-e849e837346024527e3aadac345a485c682ccfe8ba595cc2662a3e328ee707bfR44
Because, on the one hand, the model has a normal texture but not tangents, so the shader is not created with the normalmap flag. But then later in the same file, you have:
```
if (materialData_->normalTexture)
shader_->bindNormalTexture(*(materialData_->normalTexture)); 
```
The correct way is to use `flags_` not the `materialData_` in the if clause.
This PR is to fix it.
> [Bug fix] Use flags, not materialData in order to set the uniforms, textures properly in the GenericDrawable. 

- src/shaders/pbr.frag
@aclegg3  found this problem that did not happen  on a linux machine.
`half` is a reserved word in certain GPU driver implementation. We will have to change it to some other variables.
see here:
https://stackoverflow.com/questions/22798477/glsl-shader-strange-error-on-word-half
> [Bug fix] change half, a reserved word in certain GPU driver to halfVector

- src/esp/assets/ResourceManager.h
- src/esp/bindings/AttributesBindings.cpp
- src/esp/bindings/AttributesManagersBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/core/Configuration.h
- src/esp/io/json.h
- src/esp/metadata/CMakeLists.txt
- src/esp/metadata/MetadataMediator.cpp
- src/esp/metadata/MetadataMediator.h
- src/esp/metadata/attributes/LightLayoutAttributes.cpp
- src/esp/metadata/attributes/LightLayoutAttributes.h
- src/esp/metadata/attributes/SceneDatasetAttributes.cpp
- src/esp/metadata/attributes/SceneDatasetAttributes.h
- src/esp/metadata/managers/LightLayoutAttributesManager.cpp
- src/esp/metadata/managers/LightLayoutAttributesManager.h
- src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
- src/esp/sim/Simulator.h
- src/esp/sim/SimulatorConfiguration.h
- src/tests/AttributesManagersTest.cpp
This PR adds support for parsing lighting layout files, of the format found [here](https://drive.google.com/file/d/1oPO9m3ws69k8wlipgU0C1XPGoLf8P_v5/view?usp=sharing) into appropriately configured attributes files, which are to then be used to instantiate lights in scenes.
A ".lighting_config.json" configuration file is assumed to describe a single lighting layout, consisting off multiple lights. The file is parsed so that each light entry is parsed into a LightInstanceAttributes object, which is aggregated into a single LightLayoutAttributes object.  This in turn is used to instance a lighting layout upon scene creation.
All existing c++ and python tests passed.  Tests were added to verify proper parsing of JSON.
> --MetadataMediator - Lighting Layout Configurations

- src/shaders/pbr.frag
As titled.
This is just a temporary fix as in the future we would like to seek the normal mapping without the precomputed tangents.
> add a condition in the Pbr Shader to avoid an error when precomputed tangents are not presented.

- src/esp/metadata/CMakeLists.txt
- src/esp/metadata/MetadataMediator.h
- src/esp/metadata/attributes/SceneAttributes.cpp
- src/esp/metadata/attributes/SceneAttributes.h
- src/esp/metadata/attributes/SceneDatasetAttributes.cpp
- src/esp/metadata/attributes/SceneDatasetAttributes.h
- src/esp/metadata/managers/SceneAttributesManager.cpp
- src/esp/metadata/managers/SceneAttributesManager.h
- src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
- src/tests/AttributesManagersTest.cpp
This PR add support for parsing "scene_instance.json" into SceneAttributes configuration files, which are then consumed to instantiate a scene.  
A "scene_instance.json" file, whose format can be found [here](https://drive.google.com/file/d/1_1fw5y93mAE1FuwQZWqgbQKtVQGOx-CA/view?usp=sharing), describes the layout of a scene, potentially specifying a stage and/or 0 or more objects, a lighting configuration, navmesh and semantic scene descriptor.  This configuration file is parsed by SceneAttributesManager into a SceneAttributes configuration object, which manages references to the various scene assets, including individual instances of SceneInstanceAttributes objects which describe which object and stage templates to use, if any, and where to put the instantiated construct within the …
> --MetadataMediator - Scene Instance Configurations

- src/esp/assets/ResourceManager.h
- src/esp/bindings/SimBindings.cpp
- src/esp/metadata/MetadataMediator.cpp
- src/esp/metadata/MetadataMediator.h
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/esp/sim/SimulatorConfiguration.h
- src/tests/CMakeLists.txt
- src/tests/MetadataMediatorTest.cpp
This PR adds a c++ test to verify MetadataMediator functionality.  It also makes Sim.reconfigure maintain an appropriate current ref to the current MetadataMediator in ResourceManager, and provides some accessors.
Passes all existing c++ and python tests; Adds tests
> --MetadataMediator : Tests and bindings.

- examples/colab_utils/colab_install.sh
This will make it so we don't have to worry about the Colab versions for these two libraries by keeping conda from clobbering those two libraries which are imported early.
This should remove the need to do an explicit importlib reload on future Colabs.
Easier Colab install
Because it can overwrite cffi and PIL on colab so that which causes issues since each library is only partially loaded. This means the user won't have to let habitat-lab crash the first time.
On Colab
> Futureproof PIL/CFFI versions for colab install.

- examples/__init__.py
This PR addresses an issue when habitat-sim repo and habitat-lab repo are within the same directory and habitat-lab is installed as per the given directions : 
python setup.py develop --all
Attempting to run pytest in habitat-sim will yield an error due to pytest looking in habitat-lab/examples directory for habitat-sim/examples modules.
Adding an empty __init__.py in the examples directory addresses this issue.
c++ and python tests pass
> --[BUG FIX]add empty init for examples directory 

- src/esp/physics/bullet/BulletRigidObject.cpp
- src/tests/PhysicsTest.cpp
Previously PR #801 fixed an issue where removal of sleeping objects did not wake nearby objects causing simulation artifacts. This was done by iteratively waking all objects which were part of the same simulation island as the sleeping object (`activateCollisionIsland`). 
However, `STATIC` btRigidBodies do not share a simulation island tag with non-static objects which they are in contact with, causing this previous fix to miss the case that the supporting object is STATIC, not sleeping.
This PR adds a step to the `activateCollisionIsland` which checks the previously computed overlapping pairs to collect all relevant simulation islands to activate.
Adjusted the existing test to catch this case.
Viewer testing: bottom object is STATIC. Green denotes STATIC or sleeping. First remove a …
> [bugfix] Remove STATIC Support

- src/esp/bindings/AttributesManagersBindings.cpp
The attributes manager bindings were missing a comma after the context help. This PR addresses this.
C++ and python tests passed.
> [BUG FIX] Attributes manager bindings load objects missing comma

- .circleci/config.yml
This allows us to have a much cleaner pytest output when running tests in parallel and lets us know instantly which test is failing.
Currently, it's impossible to tell even in which file pytest is failing. I can even enable -vv here which will tell us what individual call is failing in habitat-sim. Furthermore, this gives us a progress bar, more frequent updates, and an overall cleaner output. It also can tell us what tests fail as soon as they fail. This all while allowing us to maintain our parallel pytests for habitat-sim. It will also make the output a little nice for habitat-lab tests. 
I switched to pytest-xdist since it has better support with other plugins. We can switch back to pytest-parallel output if preferred, but we aren't using any of the advanced features to test …
> [CIRCLECI] Improve PYTEST output Habitat-Sim

- src/esp/bindings/AttributesManagersBindings.cpp
- src/esp/core/ManagedContainer.h
- src/esp/metadata/managers/AssetAttributesManager.cpp
- src/esp/metadata/managers/AssetAttributesManager.h
- src/esp/metadata/managers/LightLayoutAttributesManager.cpp
- src/esp/metadata/managers/LightLayoutAttributesManager.h
- src/esp/metadata/managers/ObjectAttributesManager.cpp
- src/esp/metadata/managers/ObjectAttributesManager.h
- src/esp/metadata/managers/PhysicsAttributesManager.h
- src/esp/metadata/managers/SceneAttributesManager.cpp
- src/esp/metadata/managers/SceneAttributesManager.h
- src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
- src/esp/metadata/managers/SceneDatasetAttributesManager.h
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.h
Currently to register an object or stage attributes the specified render asset handle must exist, either as a valid object on disk, a valid existing primitive, or (in the case of a stage) be "none".  If none of these conditions are true, the registration will fail and the attributes will not be added to the attributesManager library.  This is useful in case errors exist in the attributes, so that object creation does not fail due to misnamed target assets.  
The ability to override registration checks for object and stage attributes checks is useful for when render assets are computationally/"hand" crafted meshes.  This PR adds a boolean argument to the registration process that allows for overriding the non-existing asset failure with a warning. 
The default behavior will be to fail if …
> --Enable override of default Attributes Registration checks

- src/esp/core/ManagedContainerBase.cpp
- src/esp/metadata/managers/AttributesManagerBase.h
Attributes creation messages were a bit arcane, so this PR hopes to clarify what exactly is going on.
> --Update Attributes creation messages to be clearer.

- docs/pages/attributesJSON.rst
- src/esp/bindings/AttributesBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/metadata/attributes/ObjectAttributes.cpp
- src/esp/metadata/attributes/ObjectAttributes.h
- src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/RigidBase.h
- src/esp/physics/RigidObject.cpp
- src/esp/physics/RigidObject.h
- src/esp/physics/RigidStage.cpp
- src/esp/physics/RigidStage.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
- src/esp/physics/bullet/BulletRigidStage.cpp
- src/esp/physics/bullet/BulletRigidStage.h
- src/esp/sim/Simulator.h
- src/tests/AttributesManagersTest.cpp
- src/tests/PhysicsTest.cpp
- tests/test_physics.py
To support 3D visualization use cases in Habitat, this PR adds a flag and getter/setters to enable/disable collisions for objects and stages. This is done by manipulating the collision shape allowing all MotionType properties regardless of collidable setting. Flag exposed to Simulator API in C++ and Python as well as Object and Stage Attributes and config files.
Includes minor bugfix:
- Friction/restitution/damping set on objects after construction were getting overwritten by initialization attributes when changing object MotionType.
Unit tests added for config value parsing, contact and raycast tests w/ non-collidable objects and stage.
Local testing results in viewer:
- 3 stacks of objects with bottom object of different MotionType: dynamic(left), kinematic(middle), static(right).
- …
> Add Stage/Object Collidable setting

- habitat_sim/agent/controls/object_controls.py
- habitat_sim/agent/controls/pyrobot_noisy_controls.py
- habitat_sim/sensors/noise_models/gaussian_noise_model.py
- habitat_sim/sensors/noise_models/no_noise_model.py
- habitat_sim/sensors/noise_models/poisson_noise_model.py
- habitat_sim/sensors/noise_models/salt_and_pepper_noise_model.py
- habitat_sim/sensors/noise_models/speckle_noise_model.py
* Noise models are often a bottleneck in Habitat-Sim. I realized since we are using attr.s for all of them, we can make them slot classes to make them just a tiny bit faster.
on CircleCI with PyTest
@erikwijmans was looking more closely at the attr.s features and thought we should be using this one more aggressively in noise models. It hasn't broken anything, and it should speed up things if only by a tiny amount.
> Make noise_models use slot_classes for extra speed.

- src/esp/bindings/PhysicsBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
`BulletPhysicsManager::getContactPoints` returns `ContactPointData` objects describing the contacts from the most recent physics substep. This implementation is roughly identical to PyBullet's `getContactPoints`.
Users should take care to call stepWorld with a dt equal to the Bullet substep dt prior to calling getContactPoints, because getContactPoints only returns data about the most recent substep. There's a warning to encourage correct usage.
The most obvious usage is to get info about the recent substep during physics simulation. However, another planned use case is similar to an async "what if" collision query, as follows:
1. Save the state of the physics world.
2. Move desired query object(s) to a desired query pose.
3. stepWorld(substepDt)
4. getContactPoints()
5. Restore the state …
> add BulletPhysicsManager::getContactPoints and python bindings

- examples/settings.py
Warn users that they need to upgrade habitat_sim
Adds an exception asking people to upgrade habitat_sim if their SimConfiguration object is outdated.
Closes #938 
* CI
> Adds an upgrade_warning for SimulatorConfig

- .pre-commit-config.yaml
- examples/demo_runner.py
- examples/settings.py
- habitat_sim/__init__.py
- setup.cfg
- tests/test_pyrobot_noisy_controls.py
- tools/custom_il_contracts.py
Adds a pre-commit hook that enforces a custom import contract that forbids examples and test modules from directly using habitat_sim.bindings. This way, it reminds users to create an alternative location for the Python binding which we missed for the SensorSubtype.
CircleCI and locally.
> Add import linter contract pre-commit hook and fix SensorSubtype Python bindings

- .gitmodules
- build_js.sh
- conda-build/habitat-sim/meta.yaml
- conda-build/linux_matrix_builder.py
- conda-build/macos_matrix_builder.py
- src/CMakeLists.txt
- src/cmake/FindBullet.cmake
- src/cmake/FindMagnumIntegration.cmake
- src/cmake/dependencies.cmake
- src/esp/physics/bullet/CMakeLists.txt
The main motivation here is to get all Habitat users on the same version of Bullet. Compare to the current setup of having the Hab user install Bullet on her system: conda and package managers currently give different versions of Bullet across platforms.
This PR chooses Bullet 2.89 because that's what most current Hab users are "on" (again, depends on platform). However, another big motivation for this PR is to unblock a version upgrade. We expect to upgrade to 3.06 very soon. 
There are various downsides to no longer using a system install of Bullet: increased build time (building Bullet from source), increased conda distribution size, increased space on disk for the Habitat-sim worktree (all the Bullet source code), etc.
@mosra has included a `USE_SYSTEM_BULLET` build option which lets …
> Use Bullet 2.89 as a CMake subproject

- docs/pages/index.rst
- docs/pages/rigid-object-tutorial.rst
Minor change to add links to the Collab for the rigid object tutorial and correct the python run path.
local build
> [docs] Add Collab links for rigid object tutorial

- src/esp/assets/Asset.h
- src/esp/assets/CMakeLists.txt
- src/esp/assets/RenderAssetInstanceCreation.h
- src/esp/assets/RenderAssetInstanceCreationInfo.cpp
- src/esp/assets/RenderAssetInstanceCreationInfo.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
This PR is (mostly) a no-op refactor of ResourceManager (no behavior change). The motivation is to unblock the upcoming render replay feature.
I introduce the terms "render asset" and "render asset instance". A render asset is basically a mesh. A render asset can be of type InstanceMesh ("IMesh"), PTex, Primitive, or General (see `isRenderAssetGeneral`).
A somewhat unrelated change is mixed in here: I'm converting some usage of ResourceKey (a hash) to std::string so that I can better serialize the key.
This is (mostly) a no-op refactor that conceptually replaces `loadPTexMeshData / loadInstanceMeshData / loadGeneralMeshData` with `loadRenderAssetPTex,createRenderAssetInstancePTex / loadRenderAssetIMesh,createRenderAssetInstanceIMesh / …
> refactor ResourceManager render assets

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/bindings/SimBindings.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/SimulatorConfiguration.h
- src/tests/ResourceManagerTest.cpp
This PR supports the upcoming render-replay feature.
A review of two "modes" for our renderer: depending on the stage, we either create a single scene graph (for RGB, depth, and semantic observations), or we create two scene graphs (loosely speaking, one is for RGB+depth and one is for semantic).
Previously, the "mode" decision was coupled to what stage you're loading (some stages have separate RGBD and Semantic models, others don't). For playback of a render replay, we won't load a stage at all (we'll use EMPTY_STAGE). However, I still need a way to select the mode (before loading any models). So, I've added SimulatorConfiguration.forceSeparateSemanticSceneGraph. 
This is pretty straightforward usage of our existing loadRenderAsset and createRenderAssetInstance. The only complication …
> forceSeparateSemanticSceneGraph and loadAndCreateRenderAssetInstance

- habitat_sim/agent/agent.py
- habitat_sim/sensors/sensor_suite.py
- habitat_sim/simulator.py
- tests/test_gfx.py
- tests/test_sensors.py
- tests/test_simulator.py
Closes #856 
This also allows other static sensors to be added to the scene (like security cameras / static ortho cameras / bird eye views etc...)
Locally. Will add a test case shortly, just want to finalize the API. 
Also expanded the _sensor_dict to be multi-agent compatible, let me know if I should be doing it in a different way, like by making _sensors a ```dict[int, dict]``` instead. 
With this, the only thing unblocking multi-agent support on the habitat-sim part would be testing and the step function.
> Refactor Multi-Agent Sensors API and allow dynamic adding of Sensors

- src/shaders/pbr.frag
Bugfix for point lights attenuation calculation.
My test case here is a GLOBAL red point light and a GLOBAL green point light placed arbitrarily in the ReplicaCAD scene. In the before video, notice how the  attentuation changes dramatically as the camera moves. For GLOBAL lights, this shouldn't happen.
Before:
After:
Here's a different test, a single CAMERA red point light placed in front of the camera, slightly offset to the right. As desired, it moves with the camera. (I don't have a "before" video for this case but I did want to test it with this fix).
See gifs above. For the first two gifs, I tested in the viewer by hard-coding these point lights:
```
esp::gfx::LightInfo info1{.vector{0.0, 0.0, 0.0, 1.0},
.color{3.0, 0.0, 0.0},
.model{esp::gfx::LightPositionModel::GLOBAL}}; …
```
> pbr.frag fix for point lights attenuation

- src/esp/sim/Simulator.cpp
The modified code addresses a bug in rare instances, where Simulator::requiresLighting_ is true, config_.requiresLighting is false, and the renderer_ did not exist but is now needing to be created.  The existing code was using the incorrect value for requiresLighting (see line 112 in Simulator) - config_.requiresLighting's value is ignored by Simulator if Simulator::requiresLighting_ is true.
All c++ and python tests
> --[BUGFIX] Incorrect requiresTextures state is used.

- src/esp/assets/RenderAssetInstanceCreationInfo.h
- src/esp/gfx/CMakeLists.txt
- src/esp/gfx/replay/Keyframe.h
- src/esp/gfx/replay/Recorder.cpp
- src/esp/gfx/replay/Recorder.h
- src/tests/CMakeLists.txt
- src/tests/GfxReplayTest.cpp
Part of the upcoming render-replay feature.
The Recorder class saves and serializes render keyframes. A render keyframe is a visual snapshot of a scene. It includes the visual parts of a scene, such that observations can be reproduced (from the same camera perspective or a different one). The render keyframe includes support for named "user transforms" which can be used to store cameras, agents, or other application-specific objects.
This is only part of the upcoming render-replay feature. Other PRs coming soon:
- gfx::replay::Player
- integration PR, which includes integration with Simulator and ResourceManager, sim bindings, and a python replay tutorial.
Serialization/saving is disabled, waiting on this PR: https://github.com/facebookresearch/habitat-sim/pull/959 .
See GfxReplayTest
> Add gfx::replay::Recorder

- src/esp/gfx/CMakeLists.txt
- src/esp/gfx/replay/Player.cpp
- src/esp/gfx/replay/Player.h
- src/tests/GfxReplayTest.cpp
Part of the upcoming render-replay feature.
The Player class reads render keyframes from a file so that observations can be reproduced (from the same camera perspective or a different one). A loaded keyframe can be set (applied to the scene) with setKeyframeIndex; render asset instances are added to the scene as needed and new observations can be rendered. Render assets are loaded as needed.
This is only part of the upcoming render-replay feature. Coming soon:
- an integration PR, which includes integration with Simulator and ResourceManager, sim bindings, and a python replay tutorial
- Serialization/saving (currently disabled) #959
player test added to GfxReplayTest
> Add gfx::replay::Player

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/bindings/GfxBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/gfx/Drawable.h
- src/esp/metadata/MetadataMediator.cpp
- src/esp/metadata/MetadataMediator.h
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/sim/Simulator.h
- src/esp/sim/SimulatorConfiguration.h
- src/tests/DrawableTest.cpp
- src/tests/SimTest.cpp
- src/utils/viewer/viewer.cpp
ResourceManager defined static const string keys to be used for default lighting and material entries in ShaderManager.  With the advent of MetadataMediator, which was designed specifically to be able to exist independent of a Simulator instance, these keys may be required by attributes templates when ResourceManager does not exist.  This PR moves these keys from ResourceManager to MetadataMediator.  There should be no impact on any python code since these values are accessed via python bindings, which have not changed.
Existing c++ and python tests passed.
> --[Refactor/Bugfix] Move static const ShaderManager default light and material keys to MM

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/bindings/GfxBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/core/esp.h
- src/esp/metadata/MetadataMediator.cpp
- src/esp/metadata/MetadataMediator.h
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/sim/Simulator.h
- src/esp/sim/SimulatorConfiguration.h
- src/tests/DrawableTest.cpp
- src/tests/SimTest.cpp
- src/utils/viewer/viewer.cpp
[Please see this previous PR](https://github.com/facebookresearch/habitat-sim/pull/966).  Moving the default string constants created a difficulty with the implementation of the scene import functionality where SceneConfiguration could not be easily referenced within MetadataMediator; Furthermore, precedent has been set to have constants in esp.h (with esp::ID_UNDEFINED).  This PR moves these keys to their hopefully final home, in esp.h.
Existing cpp and python tests pass
> --[Refactor/BugFix] Move global default const string resource keys to esp.h

- src/utils/viewer/viewer.cpp
Uncovered while @bigbike was debugging a crash on exit, which happened only when closing the window via the close button and not via pressing <kbd>Esc</kbd>. This is why.
I switched to [Application::exit()](https://doc.magnum.graphics/magnum/classMagnum_1_1Platform_1_1GlfwApplication.html#a7de5fd1778375d52c93d8ee50495684c), which exits at the next iteration of the event loop (same as the window close button would do). Using `std::exit()` would exit immediately, but without calling any scoped destructors, which could hide potential destruction order issues or crashes at exit. We don't want that.
I had more than enough pain with CIs this week, so I hope this won't add more to the pile. :fire:
> viewer: avoid std::exit(), it's not doing nice things to the codebase

- .circleci/config.yml
- src/esp/bindings_js/CMakeLists.txt
- src/esp/bindings_js/index.js
This solves two issues. One it removes the need for a cp after building the viewer and also allows the viewer to take in arbitrary relative urls (including those in folders or absolute file locations).
Now we can have folders of scenes, configs, and other params on the webserver and they will load properly.
* Locally
Closes #527
> [WebGL] Viewer improve CMake  and folder path handling

- src/esp/bindings/CMakeLists.txt
- src/esp/bindings/MetadataMediatorBindings.cpp
- src/esp/bindings/bindings.cpp
- src/esp/bindings/bindings.h
- src/esp/sim/Simulator.h
This PR introduces python bindings to facilitate access to Metadata Mediator and the functionality it provides (i.e. access to attributes managers) independent of chaining through Simulator.  Simulator-specific access to attributes managers will probably remain, but the MM is intended to be able to persist through iterations of Simulator, so providing direct python access is essential, and will be expanded as needed.   Pytests to follow in future PR (as part of scene import). 
existing c++ and python tests
> --Create MetadataMediator python bindings.

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/physics/PhysicsManager.cpp
This PR is a small change where the attributes specifically used to create an object are passed to RM directly when the object is added to drawables.  It also removes an unused (and unlikely to ever be used) AddToDrawables function overload.
> --pass object creation attributes to addObjectToDrawables

- src/esp/assets/RenderAssetInstanceCreationInfo.h
- src/esp/gfx/replay/Player.cpp
- src/esp/gfx/replay/Recorder.cpp
- src/esp/io/CMakeLists.txt
- src/esp/io/JsonAllTypes.h
- src/esp/io/JsonBuiltinTypes.h
- src/esp/io/JsonEspTypes.cpp
- src/esp/io/JsonEspTypes.h
- src/esp/io/JsonMagnumTypes.h
- src/esp/io/JsonStlTypes.h
- src/esp/io/json.h
- src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
- src/esp/metadata/managers/SceneAttributesManager.cpp
- src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/tests/IOTest.cpp
This is a second stab at json helpers for writing, which has grown into a larger refactor. The earlier work is here: https://github.com/facebookresearch/habitat-sim/pull/959 . Per @jturner65 's [suggestion](https://github.com/facebookresearch/habitat-sim/pull/959#issuecomment-740161636), I've refactored to consolidate my new write helpers with the existing read helpers.
From JsonAllTypes.h:
These helpers are designed so that every builtin type and user type can be serialized/deserialized with esp::io::addMember/readMember. The leads to uniform and readable serialization code. To achieve this, every user type defines toJsonValue/fromJsonValue, and then template versions of addMember/readMember will automatically use these.
See IOTest. I've also tested with the upcoming render-replay …
> rapidjson serialization and refactor

- examples/settings.py
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/bindings/CMakeLists.txt
- src/esp/bindings/GfxReplayBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/bindings/bindings.cpp
- src/esp/bindings/bindings.h
- src/esp/gfx/CMakeLists.txt
- src/esp/gfx/replay/Player.cpp
- src/esp/gfx/replay/Recorder.cpp
- src/esp/gfx/replay/Recorder.h
- src/esp/gfx/replay/ReplayManager.cpp
- src/esp/gfx/replay/ReplayManager.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/esp/sim/SimulatorConfiguration.h
- src/tests/GfxReplayTest.cpp
This PR integrates the render-replay Recorder and Player into Simulator and ResourceManager and sets up python bindings to use them. Recorder and Player are already merged and unit-tested so this PR is fairly small and just does the hookup/integration.
~Note file reading/writing is still disabled (waiting on https://github.com/facebookresearch/habitat-sim/pull/980 ) so this is more like a stub implementation. I may wait for https://github.com/facebookresearch/habitat-sim/pull/980 to merge before merging this, but I'd like to get this under review now.~ Update: https://github.com/facebookresearch/habitat-sim/pull/980 has merged.
I have a working replay tutorial which I was planning to merge as a separate PR (or I can add it here if requested). Anyway it's …
> render replay integration and python bindings

- .clang-tidy
- src/esp/bindings/AttributesBindings.cpp
- src/esp/bindings/AttributesManagersBindings.cpp
- src/esp/bindings/SensorBindings.cpp
- src/esp/scene/Mp3dSemanticScene.cpp
* There were a few annoying RAII warnings and bugprone-branch clones that were being emitted as warnings instead of errors. It seems like the RAII warnings are false positives though since Caffe2 has similar nolints. False positive occurs when a module is constructed with nodefs, which usually is an error, but in these few cases is not. When it is not an error, nolint comments should be explicit.
* Now the main warning left in the code base is implicit narrowing conversions.
* Locally and on CircleCI
-
> [Clang-Tidy] Tighten clang-tidy warnings into errors for bugprone.

- src/tests/GfxReplayTest.cpp
A garbage JSON file is being created as part of the GfxReplayTest suite and currently ends up lingering after the test completes.  This PR deletes this file at the end of the test.
C++ and python tests pass.
> --delete JSON garbage file at the end of the test creating/using it.

- src/esp/gfx/CMakeLists.txt
- src/esp/gfx/CubeMapCamera.cpp
- src/esp/gfx/CubeMapCamera.h
- src/esp/gfx/RenderCamera.cpp
- src/esp/gfx/RenderCamera.h
This is a camera that can be put into the scene (attaching to a node in the scene graph), and render the surroundings into the cubemap.
We need the cubemap for:
- Fisheye sensor;
- Pbr Image based rendering;
More about this camera:
- It is a render camera that can render the scene. So it is inherited from the RenderCamera;
- The FOV is fixed to 90 degrees;
- The rendering plane is a square (width must be the same as height.);
- It has a convenient function called SwitchToFace() to control which cubemap's face it is rendering to;
> [sensor] A camera to render the scene into the cubemap

- .circleci/config.yml
Removes setting pip_interop_enabled to true in conda builds.  This is expected to address CircleCI issue with documentation building.
C++ and python tests.
> --Fix issues with hab lab doc-building.

- src/esp/bindings/SensorBindings.cpp
- src/esp/bindings_js/bindings_js.cpp
- src/esp/scene/SceneNode.h
- src/esp/sensor/CameraSensor.cpp
- src/esp/sensor/Sensor.h
- src/tests/SimTest.cpp
Changing the style of the enumeration in Sensor.h
Built and compiled
> Change sensor enum from ALL_CAPS to Pascal style

- habitat_sim/sensors/noise_models/no_noise_model.py
- habitat_sim/sensors/noise_models/sensor_noise_model.py
- tests/test_snap_point.py
Fixes two bugs. One in our hypothesis code that only generated a single navigable point for our hypothesis testing, and softened some hard dependency on PyTorch that were not necessary.
This should resolve the CircleCI issues.
```
E                               hypothesis.errors.FailedHealthCheck: tests/test_snap_point.py::test_snap_point uses the 'test_data' fixture, which is reset between function calls but not between test cases generated by `@given(...)`.  You can change it to a module- or session-scoped fixture if it is safe to reuse; if not we recommend using a context manager inside your test function.  See https://docs.pytest.org/en/latest/fixture.html#sharing-test-data for details on fixture scope.
E                               See …
```
> Pytest bugfix and PyTorch dependency softening

- src/utils/viewer/viewer.cpp
Previously, the viewer controls to move and look-around moved the agent in discrete steps, and multiple controls could not be used at the same time. To rationalize this, holding "W" in the viewer had the same effect as doing so in a text editor: the agent moves forward once, pauses, and then stutters forward.
To obtain smoother movement and looking-around, this feature does 3 things:
1. Holding movement keys now results in gliding forward smoothly
2. Roughly, the rate of movement is independent of frame rate (i.e. it is nearly constant in the world time)
3. Multiple movement/look-around keys can be handled simultaneously
Only ad-hoc testing so far. I am concerned that physics may behave slightly differently around pauses (spacebar) and frame-by-frame stepping (.) now, since a minor change …
> add smooth moving/looking in viewer

- src/utils/viewer/viewer.cpp
We wish to integrate the FrameProfiler functionality which is present in magnum-player into the habitat simulator viewer.
Build and run, compare functionality to magnum-player profiling tool
> Integrate per-frame profiler into viewer.cpp

- src/esp/scene/Mp3dSemanticScene.cpp
Looks like gcc 9 has some weirdness with inferring eigen types.  This makes everything concrete types instead of eigen's lazy types.
Fixes #1022 
With the repro
> Fix eigen weirdness

- src/shaders/pbr.frag
The shader doesn't compile on Fedora/Ubuntu Chrome WebGL and is currently causing Habitat JS apps to crash.
More context:
https://github.com/facebookresearch/habitat-sim/pull/1002
https://cvmlp.slack.com/archives/CFN5TAUSD/p1606160816031500?thread_ts=1606149864.021100&cid=CFN5TAUSD
I tested the fix on a JS app on Ubuntu Chrome. I tested on Mac Chrome, which seems to work fine with or without the fix.
I tested on Mac Safari but hit a possibly-unrelated error with or without the fix: "Platform::WindowlessEglApplication::tryCreateContext(): cannot create EGL context: EGL_BAD_MATCH
WindowlessContext: Unable to create windowless context".
> fix for PBR fragment shader for WebGL

- .pre-commit-config.yaml
With the introduction of the nbformat version 4.5 (and cell ids) in `nbformat>=5.1.0`, the pre-commit test in Circle CI started to fail, cf. https://github.com/mwouts/jupytext/issues/715
With this commit we add the requirement `nbformat <=5.0.8`, i.e. the last version of nbformat expected to work with Jupytext at the moment.
> Jupytext requires nbformat <= 5.0.8 at the moment

- src/esp/bindings/ShortestPathBindings.cpp
- tests/test_navmesh.py
It allows Python code to directly get the triangles from the NavMesh, before it was impossible to get NavMesh data into Python directly. This will add a property to pathfinders that is an array of 3D arrays indicating the triangles.
Locally, it builds properly
> [PYTHON_BINDINGS] Expose navmesh triangles to Python

- src/esp/bindings/AttributesBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/bindings_js/bindings_js.cpp
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.h
- src/esp/scene/test/GibsonSceneTest.cpp
- src/esp/scene/test/ReplicaSceneTest.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/SimulatorConfiguration.cpp
- src/esp/sim/SimulatorConfiguration.h
- src/tests/SimTest.cpp
- src/utils/viewer/viewer.cpp
This PR is laying pertinent groundwork for the [SceneInstance Import functionality PR found here](https://github.com/facebookresearch/habitat-sim/pull/954). Primarily this PR renames the SimulatorConfiguration field activeSceneID to be activeSceneName - in our system, "ID"s are nearly always integers; "name" or "handle" is used to denote a descriptive string, which is what this field represents.  NOTE : scene_id is still used in the python to reference this field.  
Also, this PR also introduces a bit more support for Scene Dataset name, particularly in viewer (which will be one of the mechanisms used to demonstrate SceneInstance importing once that functionality goes live)
Lastly, this PR repairs omissions in the SimulatorConfiguration equality operator override relating to render …
> [Refactor/BUGFIX] Scene Import 1/Prep : Refactor SimulatorConfiguration

- src/esp/assets/ResourceManager.cpp
- src/esp/metadata/managers/AssetAttributesManager.h
- src/esp/sim/Simulator.cpp
This small PR fixes loop vars not having const specified, and adds file name to info message for basis loading.  It also checks whether a render asset has been loaded with the same name as a specified collision asset during loadStage before allowing loadStageInternal to be called, which was throwing an unnecessary error message before.  This PR also serves to remove some secondary functionality from [the already very large Scene Import 1.0 PR that can be found here](https://github.com/facebookresearch/habitat-sim/pull/954)
This is the 2nd of multiple SceneImport PRs that will be presented over the next day or two.
All existing c++ and python tests
> [Refactor/BUGFIX] Scene Import 2/Prep : ResourceManager and loop fixes

- src/esp/core/ManagedContainer.h
- src/esp/core/ManagedContainerBase.h
- src/esp/metadata/attributes/AttributesBase.h
- src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
- src/esp/metadata/managers/AttributesManagerBase.h
This small PR provides a few functions that are used by Scene Import, and is intended to simplify [the existing very large Scene Import 1.0 PR that can be found here](https://github.com/facebookresearch/habitat-sim/pull/954) by separating some of the file changes from it that are not related to the primary functionality. 
A mechanism is provided by which attributes can provide a simplified name, useful for display purposes (only).  Often an attributes template's handle is composed of its filename with complete file path (in order to guarantee uniqueness), which can be unwieldy for display purposes.  This simplified name is only the file name of the attributes, without any extensions. This name will hold no guarantees of uniqueness, however; the standard getHandle() query should be used …
> [Refactor] Scene Import 3/prep : Simple Attributes Display name & attributes load efficiency

- src/esp/gfx/replay/Recorder.h
- src/utils/viewer/viewer.cpp
This adds gfx-replay recording to the C++ viewer. Specify an output filepath via command line. A keyframe is saved after every physics step. Press R to write all keyframes to the file. Every time you press R, you'll overwrite the old replay file with new keyframes.
Ad hoc testing in the viewer.
> gfx-replay recording for C++ viewer

- src/utils/viewer/viewer.cpp
This PR fixes a bug with how viewer processes mouseScrollEvent offsets on a mac by looking at both x and y offsets if a mouseScrollEvent is processed.  If shift is pressed, the scroll is defaulted to be horizontal on a mac, whereas previously in viewer we only examined the y offset to determine if a valid scroll has occurred, and in what direction.  
C++ and python
> --[BUGFIX] query both x and y offset in mouseScrollEvent for an active scroll.

- src/utils/viewer/viewer.cpp
This feature has been requested by Yili, and he wrote the original code in the branch demo-pbr-before-after.
This adds functionality to save and load the positions of scene nodes, particularly the camera. Currently, the camera position/orientation can be saved to the filesystem by its timestamp for future use. Saved camera position/orientation can be loaded from the filesystem with a timestamp specified in the command line (or else if the timestamp is not specified, from the last save in the current instance of viewer).
In practicality, the camera is usually locked on the agent. So in order for loading camera position/orientation to take effect, a feature called flying camera mode is introduced, in which the camera is unlocked from the agent.
Handling and logging for the following errors: …
> [viewer.cpp] Saving/loading camera position/orientation (support for more general scene nodes)

- src/utils/viewer/viewer.cpp
We added a per-frame profiler in #1015 to display frame duration, cpu duration, and gpu duration at runtime to be aware of bottlenecks in data processing when running our viewer. This PR adds comments to clarify how to interpret values.
Build and run
- [ x] Docs change / refactoring / dependency upgrade
- [x ] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.
- [x ] I have completed my CLA (see **CONTRIBUTING**)
> Add comments to clarify per-frame profiler

- conda-build/habitat-sim/meta.yaml
`gitpython`'s pip package requires `smmap<4.0,>=3.0.1`, however, it's conda package does not list this requirement properly.  That mismatch means conda-build pulls a version of smmap that will later break the build due to dependency checking for gitpython failing.
The CI
> Fix the conda binary build

- docs/pages/index.rst
- examples/tutorials/colabs/replay_tutorial.ipynb
- examples/tutorials/nb_python/replay_tutorial.py
- habitat_sim/utils/gfx_replay_utils.py
Tutorial for Gfx Replay (aka graphics replay, aka render replay).
Gfx Replay is a feature that lets you save the visual state of the sim, restore the visual state later, and either reproduce earlier observations (from the same camera position) or produce new observations (from different camera positions).
Note that restoring the visual state is not the same as restoring the full simulation state. When playing a replay, no physics or other simulation is running. Object ids from the earlier recorded simulation aren't valid and you can't interact with objects in the scene. However, you can move your agent, sensor, or camera to produce new observations from different camera positions.
The recording API (see replay_tutorial.py):
- cfg.enable_gfx_replay_save
- …
> Gfx replay tutorial

- .circleci/config.yml
Added doc build before conda binaries build to fix documentation build for conda binaries build introduced here https://github.com/facebookresearch/habitat-sim/pull/886.
> Added doc build before conda binaries build to fix documentation build for conda binaries build

- docs/docs.rst
- src/esp/bindings/ShortestPathBindings.cpp
- src/esp/nav/PathFinder.cpp
- src/esp/nav/PathFinder.h
Looking at the recast code, there are two reasons why `navQuery_->findRandomPoint` would fail on a well formed navmesh. 
1. It fails to sample a polygon.  This can happen because the tile is sampled without checking to see if it has any polygons to select
2. There is a machine precision error that causes the sampled point to fail a point-in-poly test.
In both cases, trying again makes sense.  I added a runtime error to throw when the navmesh is definitely bad, no navigable area.
Made a little script that samples a couple hundred million points.  That use to error once or twice even tho the navmesh is fine.  It no longer errors.
> Make nav point sampling more robust

- tests/test_data_extraction.py
- tests/test_profiling_utils.py
- tests/test_sensors.py
This PR introduces code that will skip pytest tests that require soft dependencies that may not be installed, such as torch or torch with cuda
Python tests pass, appropriately skip non-cuda installs.
> --Verify torch and cuda are installed if required by python tests

- data/test_assets/dataset_tests/scenes/dataset_test_scene.scene_instance.json
- docs/pages/attributesJSON.rst
- docs/pages/index.rst
- src/esp/bindings/GfxBindings.cpp
- src/esp/gfx/LightSetup.h
- src/esp/metadata/MetadataMediator.cpp
- src/esp/metadata/MetadataMediator.h
- src/esp/metadata/attributes/LightLayoutAttributes.cpp
- src/esp/metadata/attributes/LightLayoutAttributes.h
- src/esp/metadata/attributes/ObjectAttributes.h
- src/esp/metadata/attributes/SceneAttributes.cpp
- src/esp/metadata/attributes/SceneAttributes.h
- src/esp/metadata/attributes/SceneDatasetAttributes.cpp
- src/esp/metadata/attributes/SceneDatasetAttributes.h
- src/esp/metadata/managers/LightLayoutAttributesManager.cpp
- src/esp/metadata/managers/LightLayoutAttributesManager.h
- src/esp/metadata/managers/SceneAttributesManager.cpp
- src/esp/metadata/managers/SceneAttributesManager.h
- src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
- src/esp/metadata/managers/SceneDatasetAttributesManager.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/tests/AttributesManagersTest.cpp
- src/tests/CullingTest.cpp
- src/tests/DrawableTest.cpp
- src/tests/GfxReplayTest.cpp
- src/tests/MetadataMediatorTest.cpp
- src/tests/PhysicsTest.cpp
- src/tests/SimTest.cpp
This PR replaces [the old version found here](https://github.com/facebookresearch/habitat-sim/pull/954) since much of the old PR was split out into individual PRs that have been merged already.
This PR adds the support for importing scene instances.  A scene instance describes a scene layout, using handles to attributes for the various assets used that are specified/defined in a scene dataset configuration file.  The scene instance can describe the assets and transformations needed to build instances of a stage, 1 or more objects, a lighting configuration, navmesh and semantic scene descriptor files. 
The stage and object instances described in a scene instance include their necessary transformations to align them properly in the scene.  For objects, it also includes the motion type the …
> Scene Import 1.0

- src/esp/core/esp.h
Our current smart pointer macro breaks if a class template with more than one type parameter is passed to it.  This is because the C Preprocessor sees the type definition, including the list of params, and breaks it into multiple types.
(so `MyType<T,U>` is seen as `MyType<T` and `U>`)
The changes introduced in this small PR fix this issue.  Thanks @mosra!
> [BUGFIX] : Handle class template with multiple params in Smart Ptr Macro

- src/esp/bindings/AttributesManagersBindings.cpp
- src/esp/core/ManagedContainer.h
- src/esp/metadata/MetadataMediator.h
- src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
- src/esp/metadata/managers/AssetAttributesManager.h
- src/esp/metadata/managers/AttributesManagerBase.h
- src/esp/metadata/managers/LightLayoutAttributesManager.h
- src/esp/metadata/managers/ObjectAttributesManager.h
- src/esp/metadata/managers/PhysicsAttributesManager.h
- src/esp/metadata/managers/SceneAttributesManager.h
- src/esp/metadata/managers/SceneDatasetAttributesManager.h
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.h
This slight refactor adds a nontype template parameter to govern whether the ManagedContainers will provide copies of managed objects upon get, or the object itself.  Certain potential managed objects do not lend themselves to the current process where a copy is provided, and this change enables the actual object that is tracked to be provided to the user.
> --Add managed container template argument to govern object access.

- src/esp/metadata/attributes/LightLayoutAttributes.h
- src/esp/metadata/attributes/SceneAttributes.h
Minor Bugfix - These two methods should be returning const refs to the desired containers, not copies.
C++ and python
> --[Bugfix] Should be returning a ref, not a copy.

- src/esp/bindings/AttributesManagersBindings.cpp
- src/esp/core/ManagedContainer.h
- src/esp/metadata/MetadataMediator.h
- src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
- src/esp/metadata/managers/AssetAttributesManager.h
- src/esp/metadata/managers/AttributesManagerBase.h
- src/esp/metadata/managers/LightLayoutAttributesManager.h
- src/esp/metadata/managers/ObjectAttributesManager.h
- src/esp/metadata/managers/PhysicsAttributesManager.h
- src/esp/metadata/managers/SceneAttributesManager.h
- src/esp/metadata/managers/SceneDatasetAttributesManager.h
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.h
- src/tests/AttributesManagersTest.cpp
Minor refactor for Managed Containers of some things that bothered me (all are internal to c++ sim code) : 
1. Change name of Type Param to ManagedObjectAccess, since it governs how the managed objects are accessed, not how the managed container is accessed.
2. Made getObjectOrCopyByXXX methods that are intended to be used by the python bindings and any other access that might be expected to be MC-type-agnostic (such as testing).  This is intended to provide either a ptr to a copy of the managed object or a ptr to the object itself, a decision that is governed by the type of the ManagedContainer (specifically the Type Param ManagedObjectAccess).  Internally/programmatically, access will still be direct, either retrieving a copy or the object itself depending on the requirements of the …
> [Refactor] Managed Container access refactor

- examples/tutorials/physics_benchmarking.py
Fixed a bug where a quaternion was initialized to a non-normalized value.
> Normalized quaternion value. Is this value precise enough?

- .clang-tidy
- src/esp/io/json.h
- src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
- src/esp/metadata/managers/LightLayoutAttributesManager.cpp
- src/esp/metadata/managers/ObjectAttributesManager.cpp
- src/esp/metadata/managers/PhysicsAttributesManager.cpp
- src/esp/metadata/managers/SceneAttributesManager.cpp
- src/tests/IOTest.cpp
[A recent PR](https://github.com/facebookresearch/habitat-sim/pull/1094) updated clang-tidy to flag std::bind when used to pass a function as an argument and replace it with a more efficient lambda, but, being autogenerated, the synthesized lambdas tend to be contextually arcane.
This PR refactors these lambdas to be more readable.
> --Replace auto-gen lambda args with accurate arguments

- src/esp/sensor/CameraSensor.cpp
- src/esp/sensor/CameraSensor.h
- src/esp/sensor/SensorFactory.cpp
- src/esp/sensor/SensorFactory.h
- src/esp/sensor/VisualSensor.cpp
- src/esp/sensor/VisualSensor.h
Quick PR from discussion with @bigbike. displayObservation will be called by all VisualSensors, so this PR lifts it from derived class CameraSensor to VisualSensor. 
This PR also removes unused import statements in SensorFactory as noted here: https://github.com/facebookresearch/habitat-sim/pull/1064/files
Build and run tests
> [sensor] Lift displayObservation from CameraSensor to VisualSensor

- habitat_sim/simulator.py
- src/esp/bindings/MetadataMediatorBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/metadata/MetadataMediator.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/tests/SimTest.cpp
- tests/test_simulator.py
This PR adds the ability to construct a Metadata Mediator in python, either from an existing Simulator Configuration or using a default, without requiring a Simulator to exist.  It also adds the ability to pass an existing Metadata Mediator into Simulator as a constructor default, as well as to retrieve a reference to the Metadata Mediator currently in use from Simulator.
The purpose of this is that Metadata Mediator maintains all the configuration files that have been loaded into the system, which can be expensive for large datasets.  By enabling the MM to be created and accessed independent of a Simulator instance, this loading process can be performed once, and then maintained through multiple simulator lifetimes.  
Existing C++ and python tests.  Simtest.cpp has been modified to test …
> --Support stand alone Metadata Mediator, and building Simulator from MM

- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
This PR changes BulletRigidObject::activateCollisionIsland() to use a Magnum::BoolVector instead of a std::set.  The std::set.insert function can throw an exception due to allocation, but BulletRigidObject::activateCollisionIsland is called from the BulletRigidObject destructor, which cannot allow exceptions.  Instead of bypassing a useful clang-tidy check, this uses a Magnum::BoolVector that does not throw exceptions.
Magnum::BoolVector also has a smaller memory footprint per element ([an integer set requires approximately 32 bytes per 32 bit element](https://lemire.me/blog/2016/09/15/the-memory-usage-of-stl-containers-can-be-surprising/)); the BoolVector<65536> requires 8kb storage space, which is equivalent to a std::set<int> containing approx 200 elements.
A potential issue is if we …
> --[Bug Fix]Remake activateCollisionIsland with bitset

- .circleci/config.yml
- src/esp/core/ManagedContainerBase.h
* There have been several PRs recently to get our headers compliant with clang-tidy. This change allows clang-tidy to enforce style on all our headers.
* Locally and in CircleCI
> [CIRCLECI] Enforce Clang-Tidy on headers

- src/esp/bindings/SceneBindings.cpp
- src/esp/gfx/RenderCamera.cpp
- src/esp/scene/SceneNode.cpp
- src/esp/scene/SceneNode.h
Culling for dynamic objects.  This updates the local AABB to be in world coordinates if a scene node doesn't have a precomputed AABB.  Uses caching and lazy computation to be efficient (@mosra I think I have done this correctly, but I would appreciate a double check).
Tests pass, in the viewer now you can see the number of culled objects increase as you add objects.
New feature (non-breaking change which adds functionality)
> Dynamic culling

- src/esp/gfx/RenderTarget.cpp
- src/esp/gfx/RenderTarget.h
- src/esp/gfx/Renderer.cpp
- src/esp/gfx/Renderer.h
Potential rendering speedup.
**Before:**
The renderTarget will contain 1 rgb buffer, 1 depth texture, 1 objectId Buffer (color attachment) no matter what the sensor type is.
**After:**
The renderTarget will have different combination based on sensor type.
**For rgb sensor**: 1 rgb buffer + 1 depth buffer (no objectId buffer, and No depth texture). 
This is based on the fact that usually depth buffer is faster than the depth texture.
**For depth sensor**: 1 depth texture (No rgb buffer, no objectId buffer).
This will speed up the rendering based on the observation [here](https://github.com/facebookresearch/habitat-sim/pull/1011#discussion_r577347437).
**For ObjectId sensor** 1 objectId buffer + 1 depth buffer (No rgb buffer, and no depth texture).
Reason is the same as above.
More test …
> [Potential Speedup] Set render buffer properly based on sensor type

- examples/colab_utils/colab_install.sh
Colab recently updated the default install to Python 3.7 which broke everything. This should mostly future proof it so that it will always install the dependencies with the right version of Python.
#1109 documents this
With a Colab
> Dynamically update PythonVersion for Colab Install

- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/tests/CMakeLists.txt
- src/tests/GfxReplayTest.cpp
This is a fix for a bug that caused replay recording to not get enabled. I also added a test for simulator replay integration which will catch this kind of bug in the future.
See new unit test.
> fix for Simulator::reconfigureReplayManager; added a replay unit test

- src/esp/bindings/bindings.cpp
- src/esp/core/CMakeLists.txt
- src/esp/core/Check.cpp
- src/esp/core/Check.h
- src/esp/gfx/LightSetup.cpp
Add ESP_CHECK macro, for use with fatal runtime errors. The Check.h header also gives guidelines on error-handling in Habitat-sim.
Thanks @mosra for providing most of the implementation here.
See [this internal doc](https://docs.google.com/document/d/1v99XKd5EljCGYytdmjZrV20WsyhrcpbLxGSgy4UHlx0/edit?usp=sharing) for more discussion.
I added one example usage of ESP_CHECK in LightSetup.cpp.
Ad hoc testing from a Python unit test (causing an AssertionError exception) and a C++ unit test (causing an abort).
> add ESP_CHECK and one example usage

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
These two functions in ResourceManager do not change any internal RM variables' states, so this small PR specifies them as const.  This will open them up 
All c++ and python tests.
> --[Bugfix]Const specifier added to functions that do not change internal state.

- habitat_sim/simulator.py
- src/esp/bindings/SimBindings.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
Something somewhere is leaking GPU memory because we create and destroy the background render thread all the time.  Ideally we'd fix that, but we currently have no idea how.  This is a workaround to not destroy the context or renderer on a close call.
Just putting this here for visibility and to note the caveats: If you change flags related to the renderer, those won't be propagated.  This is fine ATM and fixable in the long run, but not needed currently.
Ran the training script for a long time with lots of scene swaps and no leaks!
Planning to land if the CI is happy
> [AO Prototype] Fix leak in BG renderer

- src/esp/gfx/replay/Player.cpp
- src/esp/gfx/replay/Player.h
- src/tests/GfxReplayTest.cpp
Bugfix. Player manipulates the scene graph, adding render asset instances as necessary. It should remove everything on destruction.
I modified a GfxReplayTest unit test.
> bugfix for replay::Player not cleaning up on destruction

- src/utils/viewer/viewer.cpp
@bigbike kindly mentioned that https://github.com/facebookresearch/habitat-sim/pull/1090 forgot to set the sensor's subtype based on whether or not "orthographic" was in agent args. This PR is a quick fix for that. It also renames pinholeCameraSpec to cameraSensorSpec. 
Build and run
> [Sensor] Quick Fix for agent sensorSubType, rename pinholeCameraSpec to cameraSensorSpec

- src/esp/bindings/OpaqueTypes.h
- src/esp/core/configure.h.cmake
- src/esp/geo/CoordinateFrame.h
- src/esp/gfx/MaterialUtil.h
- src/esp/gfx/cuda_helpers/helper_cuda.h
- src/esp/gfx/cuda_helpers/helper_string.h
We decided with [PR 806 to make Habitat-Sim c++ headers use #defines, as per google c++ code guidelines](https://github.com/facebookresearch/habitat-sim/pull/806).  This PR refactors a few pragmas that got missed, or introduced, since then.
all c++ and python tests pass
> --Refactor : Change pragma once to full header guard

- examples/tutorials/colabs/replay_tutorial.ipynb
- examples/tutorials/nb_python/replay_tutorial.py
- src/esp/bindings/GfxReplayBindings.cpp
- src/esp/gfx/replay/Player.cpp
- src/esp/gfx/replay/Player.h
- tests/test_examples.py
A recent change to replay::Player cleanup logic broke the visual output of this replay (replay video #4).
I've also added this tutorial to test_examples.py to catch regressions.
On doing this, I encountered a crash during shutdown which I avoid here by explicitly closing Players before closing the sim. I also added a TODO for a better long-term fix.
I added replay tutorial to test_examples.py. I ran this test locally.
> fix for replay tutorial; add replay tutorial to test_examples.py

- src/esp/sensor/Sensor.cpp
- src/esp/sensor/Sensor.h
SensorSpec can't have a print in its destructor since they are created/destroyed on episode swap in habitat-lab.  Having one makes logging really noisy and, as a byproduct, kill perf -- while most of the time training is done with logging off, leaving it on can be useful for debugging, so we should not overly spam INFO.
In prod.
> [Sensor] Remove logging on SensorSpec destructor

- src/esp/bindings/SensorBindings.cpp
- src/esp/bindings_js/bindings_js.cpp
- src/esp/sensor/CameraSensor.cpp
- src/esp/sensor/CameraSensor.h
- src/esp/sensor/VisualSensor.cpp
- src/esp/sensor/VisualSensor.h
This PR introduces changes to VisualSensor, CameraSensor, VisualSensorSpec, and CameraSensorSpec in order for 
the hierarchical SensorSpec to be correct when new Sensors are introduced.
In this PR: 
- Lift getObservation, getObservationSpace, and readObservation from CameraSensor to Visual Sensor
- Deprecate observationSpace and encoding in SensorSpec
- Move channels, near, and far to VisualSensorSpec, move ortho_scale to CameraSensorSpec
See https://github.com/facebookresearch/habitat-sim/pull/1090/files#r588849042 for context
Build and run tests
> [Sensor] VisualSensor and CameraSensor updates for Hierarchical SensorSpec

- src/esp/bindings/SimBindings.cpp
- src/esp/physics/ArticulatedObject.h
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/physics/bullet/BulletArticulatedObject.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
Joint limit constraints in Bullet do not rectify error occurring from DoF setters or infeasible constraint solves. Pose clamping appears to be a practical solution to this issues for some objects (such as fixed base articulated furniture). This PR implements automated joint limit clamping for cases such as theses.
Note: clamping pose for fully dynamic articulated objects (e.g. robots) may result in artifacts due to the nature of warring constraints and discrete collision detection/response.
Added Simulator API to:
- query joint limits: `get_articulated_object_position_limits`
- get/set automated joint limit clamping for each articulated object: `set_auto_clamp_joint_limits` and `get_auto_clamp_joint_limits`
Notes:
- Automated clamping occurs before every call to physics simulation step …
> [AO] joint limit query and clamping

- src/esp/bindings/GfxBindings.cpp
- src/esp/bindings/SensorBindings.cpp
- tests/test_sensors.py
Magnum bindings define a single Deg type, Degd(64-bit), for rotation. Some Habitat functions return/expect the 32-bit variant (Deg) which fail to convert to/from python. This PR casts the type for known bindings with this issue.
Local testing in python:
e.g.
- `render_camera.set_projection_matrix(100,100,-1.0,1.0,mn.Deg(80.0))`
- `sim._sensors[sensor_name]._sensor_object.fov = mn.Deg(80.0)`
- `print(sim._sensors[sensor_name]._sensor_object.fov)`
- `print(sim._sensors[sensor_name]._sensor_object.hfov)`
> [bugfix] Modify python bindings to cast mn.Degd

- src/esp/physics/ArticulatedObject.h
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/RigidObject.h
- src/esp/physics/bullet/BulletArticulatedObject.cpp
Joint clamping occurs during the simulation step phase and calls `setPositions()` which in turn updates the visual nodes on the SceneGraph. This breaks the assumptions of the async renderer that physics step will not touch the SceneGraph. This PR solves the problem by extending the deferred update functionality to include articulated objects.
Includes unrelated minor clang-tidy fix.
Local testing.
> [AO][bugfix] - defer node update for ArticulatedObjects (joint clamping)

- src/esp/core/Check.cpp
- src/esp/core/Check.h
- src/esp/gfx/CubeMap.cpp
This brings:
- Support for 2D EXR [import](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1OpenExrImporter.html)/[export](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1OpenExrImageConverter.html) (the code is there, but the plugins are not enabled in any way yet)
- A [reworked `ImageConverter` plugin interface](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1AbstractImageConverter.html) that adds 3D image support and clears up strange API naming inconsistencies (but no 3D/cubemap/deep EXR support yet, sorry, that needs a bit more work)
- A few macros that existed only for compatibility with GCC 4.7 and other ancient nightmares got obsoleted, so I updated the code to not emit deprecation warnings.
- The `TestSuite` got new …
> Upgrade Magnum & co to latest

- src/esp/assets/ResourceManager.cpp
- src/tests/SimTest.cpp
- src/utils/viewer/viewer.cpp
- avoid crash in addObjectByHandle for invalid object handle
- Change C++ viewer default object-dir to be relative path. This will make it easier to directly load objects, e.g. you can write `simulator_->addObjectByHandle("data/objects/my_object.object_config.json");`
- add unit test for addObjectByHandle
I added a unit test.
> addObjectByHandle polish

- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/utils/viewer/viewer.cpp
Object deactivation (sleeping) is disabled when a dynamic constraint is created referencing the object. Since constraints can reference multiple objects and objects can be referenced by multiple constraints, re-enabling object deactivation should wait until all referencing constraints are removed. This PR adds (P2P and fixed) constraint tracking and deactivation state logic.
Locally in viewer
> [AO] constraint management and object deactivation state

- src/tests/CMakeLists.txt
- src/tests/VoxelGridTest.cpp
VoxelGridTest was failing if --vhacd was not enabled (with no actual tests to run, the test suite considers this a failure), so this PR does not compile the test unless it has --vhacd is enabled.  All compiler directives in the test file were removed as well, since they were not necessary.
C++ and python tests with and without flag passed.
> [BUGFIX] Fix Voxel grid test failing when --vhacd not enabled.

- src/esp/assets/MeshMetaData.h
- src/esp/assets/ResourceManager.cpp
`ResourceManager::shaderManager_` holds materials keyed by `Magnum::ResourceKey`. The current data import pipeline assumes these materials are keyed by int and that all materials for an asset are keyed contiguously. This is a limiting paradigm as it does not allow us to use arbitrary string keying for programmatic or user-defined materials.
Concretely an example of this case is material overriding in URDF requiring on-the-fly material registration and editing existing MeshMetaData.
This change refactors away from int ids for material keys and the notion of local material ids in `MeshMetaData` to instead directly store global string keys. The previous method of creating new unique ids during import by incrementing a counter remains.
All current tests pass after the refactor.
> Material ID refactor

- examples/settings.py
- src/esp/bindings/SensorBindings.cpp
- src/esp/sensor/CameraSensor.cpp
- src/esp/sensor/CameraSensor.h
- tests/test_sensors.py
During a refactor, we lost the ability to set the initial hfov via a sensor config. This restores the ability to do that via the CameraSensorSpec. See the corresponding Habitat-Lab bug: https://github.com/facebookresearch/habitat-lab/issues/627. This should add the necessary bindings to set the initial hfov of a CameraSensorSpec.
> [BUGFIX] Add hfov to CameraSensor config settings

- src/utils/viewer/viewer.cpp
When the viewer works with a new stage, the view usually starts from a random position and orientation. We need a functionality to quickly set the agent and its sensors to some desired (previously saved) transformations. This diff is to address this problem.
(NOTE: it assumes all the sensors are at the same position on the agent, which is the current setting.)
This diff includes:
- Fix: Previously, the camera save/load functions are outdated (as we deprecated the "default" renderCamera in the scene graph). It is fixed in this diff.
- It saves 2 relative transformations -- one is the default agent's and the other one is the rgb camera sensor's.
- It loads and sets the agent's transformation, and load the sensor's transformation and sets it to **all the sensors.** 
- It deprecates the …
> [Sensor][viewer] Save/load agent and sensors' transformations to/from disk

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/bindings/AttributesBindings.cpp
- src/esp/metadata/CMakeLists.txt
- src/esp/metadata/MetadataUtils.cpp
- src/esp/metadata/MetadataUtils.h
- src/esp/metadata/attributes/ObjectAttributes.cpp
- src/esp/metadata/attributes/ObjectAttributes.h
- src/esp/metadata/attributes/SceneAttributes.cpp
- src/esp/metadata/attributes/SceneAttributes.h
- src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
- src/esp/metadata/managers/SceneAttributesManager.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/RigidBase.h
- src/esp/physics/RigidObject.cpp
- src/esp/physics/RigidObject.h
- src/esp/physics/RigidStage.cpp
- src/esp/physics/RigidStage.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/sim/Simulator.cpp
[(Replaces this PR which included wrong commit)](https://github.com/facebookresearch/habitat-sim/pull/1134)
This PR is the first of 2 PRs intended to introduce configuration-file level support for independent shader types being specified for the stage and objects in a scene. Supported shader types that the user can specify are Flat, Phong and PBR (case insensitive), and these values can be specified in either stage and object configurations (to specify a default value for a particular stage or object TYPE), or in the scene instance configurations (which, if specified, will override the default values given in stage or object configs for a single instance only).
To support this functionality, stage and object creation had to be slightly modified in order to accept a copy of the appropriate …
> Support for shader_type specification in stage and object configurations - Part 1 of 2

- src/esp/sim/Simulator.cpp
This PR will allow disabling agent sliding when executing actions in C++ and JS viewer. 
Locally using C++ and JS viewers
> [BUGFIX]Add check to use allowSliding flag for agent move filter function

- examples/tutorials/URDF_robotics_tutorial.py
- src/esp/physics/ArticulatedObject.h
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/physics/bullet/BulletArticulatedObject.h
- src/esp/sim/Simulator.cpp
Many common navigation obstacles can be represented as `ArticulatedObjects` (e.g. doors, drawers, etc...). Instead of computing 3D collisions with these objects, it can be more efficient to use the NavMesh to constraint agent motion. This PR extends NavMesh re-computation to include `ArticulatedObject`s with `MotionType::STATIC` to enable these use cases.
Supporting changes:
- `ArticulatedObjects` can have `MotionType::STATIC` with equivalent treatment in the simulator to `MotionType::KINEMATIC` except that they are considered in NavMesh re-computation.
- Each 'ArticulatedLink' now caches its visual components for later query during mesh merge process.
- The base for an `ArticulatedObject` is now a stored as an `ArticulatedLink` in `baseLink_` and can be queried with `getLink(-1)` for …
> [AO] - recompute_navmesh with STATIC ArticulatedObjects

- src/esp/bindings/CMakeLists.txt
- src/esp/bindings/CoreBindings.cpp
- src/esp/bindings/bindings.cpp
- src/esp/bindings/bindings.h
This PR has a minor refactor to move the core namespace bindings to their own file from "bindings.cpp".  New bindings of core namespace classes are pending as part of the ongoing work making physics constructs managed objects, which will be placed in these files.
> Refactor core bindings to their own file.

- src/esp/nav/PathFinder.cpp
`bounds_ ` was not being set for PathFinder during NavMesh recomputation. If a previous NavMesh was loaded with bounds, querying would produce the old bounds instead of updating.
local testing
> [bugfix] - set bounds_ for recomputed NavMesh

- src/esp/physics/bullet/BulletRigidObject.cpp
- tests/test_physics.py
Setting world transform of an object in Bullet does not update the broadphase AABB automatically. This results in a bug where collision queries which do not perform a full discrete collision check (most prominently ray casting) can miss objects with manual kinematic updates since the last simulation or collision check. 
`test_raycast` was missing this bug because the test ray originated at the world origin where objects are spawned, so the broad-phase was triggered for moved objects anyway. This has been addressed and golden numbers updated.
> [bugfix] - Update the broad-phase aabb of an object when manually setting state

- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/physics/bullet/BulletArticulatedObject.h
- src/esp/physics/bullet/BulletRigidObject.cpp
AO analog of PR #1190. AABBs should be updated for all `btCollisionObjects` when kinematic states are manually set.
Locally for AOs.
> [AO][bugfix] - Update AABB after setting kinematic state

- habitat_sim/utils/validators.py
Magnum requires normalized quaternions, but I've found that a tol of 1e-5 is too tight. The quaternion returned by agent_state.rotation has a norm that is off by at most 1e-4. In some cases, I get errors from this function because the norm is really something like 0.9995
> tol 1e-5 too tight for checking normalized quaternions

- src/esp/bindings/AttributesBindings.cpp
- src/esp/bindings/AttributesManagersBindings.cpp
- src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
This PR modifies the help text for the attributes managers' various python bindings to include the type of the object template being managed, instead of just referencing an ambiguous "template".
> Attributes Managers python bindings more descriptive help text.

- src/esp/gfx/RenderTarget.cpp
- src/esp/gfx/RenderTarget.h
- src/esp/gfx/Renderer.cpp
As titled.
The benefit:
The texture is much easier to be visualized.
Should have no performance lose.
> [Sensor] Use texture instead of render buffer for semantic info rendering

- docs/pages/attributesJSON.rst
- examples/tutorials/lighting_tutorial.py
- src/esp/bindings/GfxBindings.cpp
- src/esp/gfx/LightSetup.cpp
- src/esp/gfx/LightSetup.h
- src/esp/metadata/attributes/LightLayoutAttributes.cpp
- src/esp/metadata/attributes/LightLayoutAttributes.h
- src/esp/metadata/managers/LightLayoutAttributesManager.cpp
- src/tests/AttributesManagersTest.cpp
- src/tests/SimTest.cpp
- tests/test_light_setup.py
This PR introduces JSON support, and appropriate testing and documentation, for setting the desired position model/frame of reference for a lighting instance.  With this setting, the user can specify whether they wish for a particular light info/instance to be placed in the scene relative to the global origin or the camera.  Object-relative positioning is also fully supported in the configuration, but only as a stub currently in the underlying lighting code.
The enum describing the position model value has also been refactored to follow our naming conventions, from  ALL_CAPS to pascal case, in the c++ and python code.
All existing and added c++ and python test cases pass
> Support specifying position model/frame of reference for lighting instances

- src/esp/core/managedContainers/ManagedContainerBase.cpp
- src/esp/core/managedContainers/ManagedContainerBase.h
- src/esp/core/managedContainers/ManagedFileBasedContainer.h
This PR moves a few file-based managed object functions to the appropriate Class template from the Managed Container base that were missed in [this PR](https://github.com/facebookresearch/habitat-sim/pull/1195).
Existing c++ and python tests pass
> Move file based functions to ManagedFileBasedContainer

- .circleci/config.yml
- build_js.sh
- src/cmake/dependencies.cmake
* Habitat-Sim could not be built without Bullet if Bullet wasn't installed due to a CMake issue.
Without having Bullet installed on your system, if you tried to build Habitat-Sim without Bullet, you would get this error:
```
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
Could NOT find Bullet (missing: Bullet_Dynamics_LIBRARY
Bullet_Collision_LIBRARY Bullet_LinearMath_LIBRARY Bullet_SoftBody_LIBRARY
Bullet_INCLUDE_DIR)
Call Stack (most recent call first):
/usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
deps/magnum-integration/modules/FindBullet.cmake:193 (find_package_handle_standard_args)
deps/magnum-integration/src/Magnum/BulletIntegration/CMakeLists.txt:31 (find_packag
```
This solves that …
> [CMake][Bullet] Let Sim be built without Bullet

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/bindings/SceneBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/physics/ArticulatedObject.h
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
Add query API for ArticulatedObject and ArticulatedLink SceneNode and visual SceneNodes (created to hold render asset Drawables).
New functions:
- `get_articulated_link_scene_node` and `get_articulated_link_visual_scene_nodes` which take a link id (or -1 for base link) and return a node or vector of nodes.
Modified functions:
- `get_object_scene_node` and `get_object_visual_scene_nodes` which now accept ArticulatedObject id and return root AO SceneNode and all AO visual SceneNodes respectively.
Local testing. 
**Example: query visual nodes and set semantic_id for semantic mask render:**
https://user-images.githubusercontent.com/1445143/116758981-196b1900-a9c6-11eb-92f9-4cf30891f1a7.mov
> [AO] ArticulatedLink|Object SceneNode query

- data/test_assets/URDF/fridge/fridge.urdf
- examples/tutorials/URDF_robotics_tutorial.py
- examples/tutorials/physics_benchmarking.py
- src/esp/bindings/SimBindings.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/physics/bullet/BulletArticulatedObject.h
- src/esp/physics/bullet/BulletBase.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/tests/PhysicsTest.cpp
Extends `contactTest` function to support `ArticulatedObjects` by id. Individually checks each link and base collision shape against the world and screens self collisions if necessary returning a boolean indicator of whether or not any multibody collision shape is in contact with any other collision object in the scene.
Also modified the `contactTest` setup to use configured collision group and mask filters by default. A side-effect of this change is that `STATIC` objects (including articulated fixed base) will not report contact with other `STATICs` (such as the stage). An option override is provided by setting `static_as_stage` to false which then treats the queried `STATIC` as a dynamic object.
Local testing of AO. Modified some tests for rigids.
> [AO] - ContactTest for ArticulatedObject

- src/esp/gfx/RenderTarget.cpp
- src/esp/gfx/RenderTarget.h
- src/esp/gfx/Renderer.cpp
- src/esp/gfx/TextureVisualizerShader.cpp
- src/esp/gfx/TextureVisualizerShader.h
- src/shaders/textureVisualizer.frag
- src/utils/viewer/viewer.cpp
As titled.
This PR adds a brand new functionality to visualize the observations from the semantic sensor.
The results are as follows:
> [Sensor] Visualize the semantic observations

- src/esp/physics/URDFImporter.cpp
- src/utils/viewer/viewer.cpp
Force reload URDF was not clearing old cached entry before attempting to cache the newly parsed model.
Viewer now always forces reload for convenience when iterating on URDF files.
Local
> [AO][bugfix] - URDF force reload

- src/esp/core/managedContainers/ManagedContainerBase.h
- src/esp/metadata/managers/AssetAttributesManager.h
- src/esp/metadata/managers/LightLayoutAttributesManager.h
- src/esp/metadata/managers/ObjectAttributesManager.h
- src/esp/metadata/managers/PhysicsAttributesManager.h
- src/esp/metadata/managers/SceneAttributesManager.h
- src/esp/metadata/managers/SceneDatasetAttributesManager.h
- src/esp/metadata/managers/StageAttributesManager.h
This PR renames an internal function that is called upon deleting an object in the Managed Containers to something more appropriate.  This function is only accessed internally to the Managed Containers, and performs MC Specialization-specific functionality.
All c++ and python tests pass.
> Managed Containers : Rename delete finalization function

- data/test_assets/urdf/fridge/fridge_static.urdf
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/physics/bullet/BulletArticulatedObject.h
- src/esp/physics/bullet/BulletBase.cpp
- src/esp/physics/bullet/BulletBase.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletURDFImporter.cpp
- src/esp/physics/bullet/BulletURDFImporter.h
- src/tests/PhysicsTest.cpp
- src/utils/viewer/viewer.cpp
Primary changes refactors the convex collision shape generation pipeline to separate joined and compound variants and support compounds for ArticulatedObjects. 
Secondary is a change to default behavior for fixed base ArticulatedObjects. We now only create proxy rigid objects for static links when the URDF explicitly overrides the collision shape filter group with `NonCollidable (256)`. This change prioritizes stability since neighboring links in the kinematic chain often have overlapping collision shapes (see the fridge.urdf asset). Using the rigid object proxy in these cases requires the dynamic links to mask contacts with STATIC objects such as the stage with a manual group override in URDF or they will become unstable in simulation with fixed base. As such, fixed base rigid proxy …
> [AO] - convex compound collision shapes

- src/esp/bindings/PhysicsObjectBindings.cpp
- src/esp/physics/PhysicsObjectBase.h
- src/esp/physics/RigidBase.h
- src/esp/physics/objectWrappers/ManagedPhysicsObjectBase.h
- src/esp/physics/objectWrappers/ManagedRigidBase.h
This PR makes kinematic node-based transformations available to all PhysicsBaseObjects, promoting the functionality from RigidBase.  This is in preparation for the coming Articulated Object merger, where it was decided that kinematic transformation-based functions should be made available to AO's, operating on their root node.  For standard rigid objects, this change should be transparent.
Existing c++ and python tests pass
> Promote kinematic properties to PhysicsBaseObject

- src/esp/assets/GenericInstanceMeshData.cpp
- src/esp/assets/ResourceManager.cpp
- src/esp/geo/VoxelGrid.cpp
- src/esp/geo/VoxelGrid.h
- src/esp/geo/VoxelUtils.cpp
- src/esp/geo/geo.cpp
- src/esp/gfx/CubeMap.cpp
- src/esp/gfx/CubeMap.h
- src/esp/gfx/CubeMapShaderBase.h
- src/esp/gfx/DoubleSphereCameraShader.h
- src/esp/gfx/EquirectangularShader.h
- src/esp/gfx/GenericDrawable.cpp
- src/esp/gfx/GenericDrawable.h
- src/esp/gfx/MeshVisualizerDrawable.cpp
- src/esp/gfx/MeshVisualizerDrawable.h
- src/esp/gfx/PbrShader.cpp
- src/esp/gfx/PbrShader.h
- src/esp/gfx/RenderTarget.cpp
- src/esp/gfx/TextureVisualizerShader.h
- src/esp/gfx/test/DepthUnprojectionTest.cpp
- src/tests/DrawableTest.cpp
- src/utils/viewer/ObjectPickingHelper.cpp
- src/utils/viewer/ObjectPickingHelper.h
- src/utils/viewer/viewer.cpp
This is mostly just a bunch of boring renames. As usual, backward-compat headers and aliases are in place so don't worry about other "in-flight" PRs and work-in-progress branches -- those will still compile and only give you a bunch of deprecation warnings that you can fix whenever you feel like doing that.
- Initialization tags like `NoInit` or `DefaultInit` were moved from the `Containers` namespace to the root `Corrade` namespace. Magnum does the same for `NoCreate` and this makes it consistent, it's also much less typing
- All shaders are now suffixed with `GL`, to make room for `Vk`-suffixed Vulkan shaders (actually, this took me 3 years to make, I was desperately looking for other options like separate libraries with GL and Vulkan shaders or having a subnamespace or having a single …
> Update to latest Magnum with various APIs renamed

- src/deps/tinyxml2/CMakeLists.txt
Removes a line added in #1137. This one in particular causes many `-Wzero-as-null-pointer-constant`
warnings and as we can't really have control over what's in 3rd party code, we shouldn't be forcing our own warning flags on it. The build was pretty much warning-clear before, which is a good thing, so let's try to keep it that way.
The build has less spammy output now.
> Don't enable pedantic warnings for 3rd party dependencies

- src/esp/bindings/PhysicsObjectBindings.cpp
- src/esp/bindings/bindings.cpp
- src/esp/core/managedContainers/AbstractManagedObject.h
- src/esp/core/managedContainers/ManagedContainer.h
- src/esp/gfx/RenderCamera.h
- src/esp/physics/PhysicsManager.h
- src/esp/physics/PhysicsObjectBase.h
- src/esp/physics/RigidBase.h
- src/esp/physics/RigidObject.h
- src/esp/physics/RigidStage.h
The new documentation for the object wrappers was incorrectly marking certain functions as static.  This PR addresses this.
Also, there are nearly 4 thousand warnings indicative of missing docstrings, improper references, or other issues with the documentation when the docs are built.  This PR attempts to address some of these, although many thousand issues still remain.
C++ and python tests pass local. Docs build locally (with thousands of warnings).
> Fix some documentation warnings and issues

- src/cmake/dependencies.cmake
While looking through the build log for #1233, I found some other things that don't have to be there.
- Don't enable any export code in Assimp. Magnum doesn't have an Assimp-based exporter (yet) and no mesh export functionality is used in Habitat either, so this is not needed.
- Don't enable tests, docs and examples for GLFW. We don't need any of that.
This removes about 120 targets from my local Ninja build (1228 before, 1105 after). Not sure about impact on compile times, since a majority of that is C code and Assimp isn't *that* crazy C++ either, but it could remove a few seconds I think.
I'm not expecting the CI to fail.
> Disable some useless 3rd party code

- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/PhysicsObjectBase.h
- src/esp/physics/RigidBase.h
- src/esp/physics/RigidObject.cpp
- src/esp/physics/RigidObject.h
- src/esp/physics/RigidStage.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
This PR moves the code to instantiate an object from a [scene object instance attributes](https://aihabitat.org/docs/habitat-sim/classesp_1_1metadata_1_1attributes_1_1SceneObjectInstanceAttributes.html) (which describes the initial state an object should be in) to PhysicsManager from Simulator.  It also moves the object instancing functionality from Simulator::createSceneInstance to a separate function that can be called at any time to create the objects at their initial locations.
> Scene Instance : Improve Object instancing process

- .circleci/config.yml
- .pre-commit-config.yaml
- examples/tutorials/nb_python/ECCV_2020_Advanced_Features.py
- examples/tutorials/nb_python/ECCV_2020_Interactivity.py
- examples/tutorials/nb_python/ECCV_2020_Navigation.py
- examples/tutorials/nb_python/managed_rigid_object_tutorial.py
- examples/tutorials/nb_python/replay_tutorial.py
- examples/tutorials/nb_python/rigid_object_tutorial.py
* This speed up the CI by: Making it More Parallel
* Removing typeguard which gives a 50X speedup on some tests.
* Fix a bug the CircleCI cache loading (will now build a lot faster for subsequent builds on PR branches).
Total testing cut by more than half! Build times from 4 minutes -> 2 minutes on CI Cache. PyTest suite speed up from 30 minutes to just 5 minutes!
* CI Tests were very slow (taking 30 minutes to run the whole suite)
CI
> [CircleCI] Optimize CI Tests (6X speed up on test suite)

- src/esp/io/URDFParser.h
- src/esp/physics/ArticulatedObject.h
- src/esp/physics/CollisionGroupHelper.h
- src/esp/physics/URDFImporter.h
- src/esp/physics/bullet/BulletArticulatedObject.h
- src/esp/physics/bullet/BulletDebugManager.h
- src/esp/physics/bullet/BulletURDFImporter.h
This PR changes "pragma once" declarations to file-based header guards, which is the standard we use across habitat-sim.
Local tests c++ and python.
> [AO] Minor bugfixes/refactors

- examples/tutorials/physics_benchmarking.py
- src/esp/bindings/PhysicsBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/PhysicsObjectBase.h
- src/esp/physics/bullet/BulletBase.cpp
- src/esp/physics/bullet/BulletBase.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidObject.h
- src/esp/physics/bullet/CMakeLists.txt
- src/esp/physics/objectWrappers/ManagedPhysicsObjectBase.h
- src/esp/sim/Simulator.h
- src/tests/PhysicsTest.cpp
- src/utils/viewer/viewer.cpp
- tests/test_physics.py
ArticulatedObject migration PR split from #1226.
Contains all minor, straightforward changes from #1247:
- refactoring object activation API
- refactoring collision compound construction from mesh hierarchy
- doc changes
Current tests should cover most of this.
> [AO migration] minor physics changes

- conda-build/common/delete_old_night_packages.py
Given our average binary size of ~150 MB and building 12 different binaries on the CI, we can't retain any and stay under the 3 GB limit.
Just changing a number
> 1 version of retention for nightly packages

- src/esp/metadata/MetadataMediator.cpp
This addresses a bug in MetadataMediator::removeDataset where string comparisons had inverted behavior.[ This bug existed before this PR](https://github.com/facebookresearch/habitat-sim/pull/1250), but became more obvious because of it. So horray expanded clang-tidy checks!
Existing c++ and python tests pass
> [BUGFIX] fix bug in string compares in MetadataMediator

- src/esp/bindings/MetadataMediatorBindings.cpp
- src/esp/metadata/MetadataMediator.cpp
- src/esp/metadata/MetadataMediator.h
- src/tests/MetadataMediatorTest.cpp
This PR adds a python binding to the existing remove dataset functionality, as well as a c++ test to verify functionality.
Existing c++ and python tests pass. C++ test added to verify functionality.
> MetadataManager: Add binding to remove dataset functionality.

- src/esp/metadata/managers/LightLayoutAttributesManager.cpp
If the user specifies a type of light explicitly in their lighting attributes, that lighting type overrides any type inferred by whether the vector value provided is "position" or "direction".   However, if an inappropriate vector value is provided (position for explicitly specified directional lights, or direction for explicitly specified point lights) there will be a disconnect and the light will be given a default value for its vector.
This PR copies the value given for position (if given) into direction (if not given) for directional lights, and copies the value given for direction (if given) into position (if not given) for positional lights.  
This may not be a bugfix per se (specifying the wrong vector for a given type is really user error), but since we are trumping inferred type …
> [BUGFIX/Improvement] Make sure appropriate light vec is set based on specified light type

- src/esp/metadata/MetadataMediator.h
- src/esp/metadata/attributes/AttributesBase.h
- src/esp/metadata/attributes/SceneDatasetAttributes.h
- src/esp/sim/Simulator.h
- src/tests/MetadataMediatorTest.cpp
This PR makes all scene dataset attributes managers accessed by const refs.  This required a slight change to how the current active dataset is queried - now there will never be an occasion for a null ptr return for any of the managers - if somehow a non-existent dataset has become active (which is not currently possible) then the default dataset will be called upon to provide the managers.  
The scene dataset attributes also has been changed so that its destructor will kill its various managers.  This is so that any persistent external references to the managers will give an error, and not leak, if the dataset they reference has been removed, addressing an extant possible bug in the scene dataset removal process.
Ideally these managers would be accessed by weak pointers, which would …
> [Bugfix] Scene Dataset Attributes Managers access enforcement

- src/esp/core/managedContainers/ManagedContainer.h
- src/esp/metadata/managers/AssetAttributesManager.cpp
- src/esp/metadata/managers/AssetAttributesManager.h
- src/esp/metadata/managers/LightLayoutAttributesManager.h
- src/esp/metadata/managers/ObjectAttributesManager.h
- src/esp/metadata/managers/PhysicsAttributesManager.h
- src/esp/metadata/managers/SceneAttributesManager.h
- src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
- src/esp/metadata/managers/SceneDatasetAttributesManager.h
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.h
- src/esp/physics/objectManagers/RigidObjectManager.h
The Managed Containers have a virtual function which instances a map of copy constructors for the objects being managed (this is so we can have one manager manage all the different types of attributes for related types, such as primitives). Unfortunately, this function was being called from the specialization class's constructor (Which is very bad - function does not act virtual if called from ctor, so if any class ever inherits from these existing managers, they would experience difficult to diagnose bugs).  This PR removes this function and moves the functionality from it to the various constructors.
> [Bugfix]Remove virtual function call from manager specialization ctors

- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsObjectBase.h
- src/esp/physics/RigidBase.h
- src/esp/physics/RigidObject.cpp
- src/esp/physics/RigidObject.h
- src/esp/physics/RigidStage.h
This PR improves how objects are instanced.  It also introduces the ability to save the scene object instance attributes used to place an object to the object itself.  This will make it easier in the future to return an object to its initial position.
> --Save Physics Objects' Scene Instancing attributes on placement

- src/esp/core/esp.h
- src/esp/physics/bullet/BulletPhysicsManager.h
Small PR that adds functionality so that a derived class's shared_from_this is appropriately downcast when the parent class inherits from std::enable_shared_from_this<parent>.
All c++ and python tests pass locally
> Derived class able to use base class's shared_from_this properly

- src/esp/assets/MeshMetaData.h
* Tidying up some code to use default member inits. This should clean up the constructor and make it more readable and may allow the compiler to do some further optimization by marking the constructor as trivial.
> Tidy mesh transform node

- .clang-tidy
- src/esp/physics/bullet/BulletBase.h
- src/esp/sensor/CameraSensor.cpp
- src/esp/sensor/CubeMapSensorBase.cpp
* Tweaks the clang-tidy config slightly  .
* Cleans up the BulletBase to use a default member initializer. This will help the ctor get optimized away and make it more readable.
* Most notable, moves the initializer of the RenderCamera into a member initializer list. This prevents a move and temporary variable from being created in the constructor and should yield performance gains as well as make the code more readable. It also remove the clang-tidy false positive that existed there before.
* CI Tests
> [clang-tidy]Tweak clang-tidy config and optimize RenderCamera

- src/esp/bindings/PhysicsObjectBindings.cpp
- src/esp/bindings/PhysicsWrapperManagerBindings.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/physics/bullet/CMakeLists.txt
- src/esp/physics/bullet/objectWrappers/ManagedBulletRigidObject.h
- src/esp/physics/objectManagers/PhysicsObjectBaseManager.h
- src/esp/physics/objectManagers/RigidObjectManager.cpp
- src/esp/physics/objectManagers/RigidObjectManager.h
- src/esp/physics/objectWrappers/ManagedPhysicsObjectBase.h
- src/esp/physics/objectWrappers/ManagedRigidBase.h
- src/esp/physics/objectWrappers/ManagedRigidObject.h
- src/tests/PhysicsTest.cpp
- tests/test_physics.py
This PR adds the ability for the rigidObjectManager to manage either ManagedRigidObjects or ManagedBulletRigidObjects, depending on whether bullet is available or not.  Without this, Bullet-specific object functionality would not be accessible through the wrappers.
PhysicsTest was also modified to conduct many of the tests through the wrappers instead of by accessing individual objects through PhysicsManager.   test_physics.py's dynamics test also has a small check that verifies that the proper wrapper is being served.
C++ and python tests passed.
> [BugFix] Add wrapper for bullet rigid objects

- src/esp/metadata/attributes/AttributesBase.h
- src/esp/metadata/managers/AssetAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/objectWrappers/ManagedPhysicsObjectBase.h
- src/esp/sim/Simulator.h
Numerous virtual function calls were being called from constructors or destructors.  This is bad in that it bypasses virtual dispatch (i.e. the functions do not behave as virtual anymore).  This PR addresses these situations by either specifying the owning class in the call (in effect manually bypassing virtual dispatch) or changing function to no longer be virtual (Note : close() in Simulator was marked as virtual, but is no longer).
> [Bugfix] Refactor virtual function calls in ctors and dtors.

- docs/docs.rst
- habitat_sim/simulator.py
- src/esp/assets/ResourceManager.h
- src/esp/core/managedContainers/ManagedFileBasedContainer.h
- src/esp/geo/VoxelGrid.cpp
- src/esp/geo/VoxelGrid.h
- src/esp/geo/VoxelWrapper.h
- src/esp/gfx/CubeMap.h
- src/esp/gfx/CubeMapCamera.h
- src/esp/gfx/DoubleSphereCameraShader.h
- src/esp/gfx/DrawableGroup.h
- src/esp/gfx/EquirectangularShader.h
- src/esp/gfx/PbrDrawable.h
- src/esp/gfx/PbrShader.h
- src/esp/gfx/RenderCamera.h
- src/esp/gfx/Renderer.h
- src/esp/metadata/managers/AttributesManagerBase.h
- src/esp/nav/PathFinder.h
- src/esp/physics/PhysicsManager.h
- src/esp/physics/RigidBase.h
- src/esp/physics/RigidObject.h
- src/esp/physics/RigidStage.h
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/physics/bullet/BulletRigidStage.h
- src/esp/physics/objectManagers/RigidObjectManager.h
- src/esp/scene/SemanticScene.h
- src/esp/sensor/CameraSensor.h
- src/esp/sensor/Sensor.h
- src/esp/sim/Simulator.h
Address some doc build warnings, mostly related to `@param` use in function doc-strings.
Existing tests, no functionality changed.
> address some doc warnings

- README.md
- build_js.sh
- src/CMakeLists.txt
- src/esp/bindings_js/CMakeLists.txt
This flag helps define the division between the Emscripten-built `hsim_bindings.wasm` binary and the demo web apps that showcase it. I also updated documentation to convey this.
The flag simplifies and speeds up the build if you're just building the binary and not using the demo web apps.
This is a small change but there's a lot of diff spam due to indenting changes.
I built locally with `--no-web-apps`. (Is a new CI step warranted? To build with this flag?)
> add --no-web-apps for JS build; update JS build documentation

- examples/settings.py
- src/esp/bindings/SensorBindings.cpp
- src/esp/sensor/FisheyeSensor.cpp
- src/esp/sensor/FisheyeSensor.h
* We currently have to specify the Principal Point which is a big annoyance on the Habitat-Lab side. Most of the time, the principal point should lie in the center of the image. If not, the user can still specify it. Using the new fixed Corrade::Optional bindings to make this a sensible and easy to compute default.
* PyTest and locally
> [GFX][FisheyeBindings] Allow principal point to default to center of sensor

- src/esp/io/URDFParser.cpp
- src/esp/io/URDFParser.h
- src/esp/physics/URDFImporter.cpp
- src/tests/IOTest.cpp
`URDF::Model` is no longer owned by `URDF:Parser` and is instead created externally and passed in to be filled. All parser internal model scaling is removed in favor of a model post-process. 
Added tests for model scaling and parser overwriting an existing model variable.
> [AO] Decouple URDF::Model and URDF::Parser + tests

- src/esp/bindings/PhysicsObjectBindings.cpp
- src/esp/bindings/PhysicsWrapperManagerBindings.cpp
- src/esp/physics/bullet/objectWrappers/ManagedBulletArticulatedObject.h
- src/esp/physics/bullet/objectWrappers/ManagedBulletRigidObject.h
- src/esp/physics/objectManagers/ArticulatedObjectManager.cpp
- src/esp/physics/objectManagers/ArticulatedObjectManager.h
- src/esp/physics/objectManagers/RigidObjectManager.cpp
- src/esp/physics/objectManagers/RigidObjectManager.h
This adds dummy python bindings for the BulletRigidObject and BulletArticulatedObject constructs when bullet is not included in compilation, so that the python derivations can be included regardless of bullet state.  The bindings provide default values but otherwise act as no ops, similar to how such methods in physicsManager used to work.
> [BUGFIX] - add dummy function mappings for no-bullet compilation

- src/esp/agent/Agent.h
- src/esp/core/random.h
- src/esp/gfx/CubeMapCamera.cpp
- src/esp/gfx/CubeMapCamera.h
- src/shaders/doubleSphereCamera.frag
- src/shaders/equirectangular.frag
This diff is to:
- reset the orientation of a cubemap so it aligns to the official definition found here:
https://www.khronos.org/opengl/wiki/Cubemap_Texture
(It is a must-have change as I will use the cubemap heavily in the PBR IBL)
- make changes in the fisheye shader and equirectangular shader accordingly;
- fix 2 places that caused the compiler warnings;
Cubemap before and after:
They are the same if the orientation is ignored.
But when you do consider the orientation, one is just transformed by rotating the other cube 180 degrees around the Y-axis.
The one after this fix is the "standard, correct" cubemap that we should use in the system.
> [Sensor] reset the orientation of a cubemap

- src/esp/metadata/attributes/ObjectAttributes.cpp
- src/esp/metadata/attributes/ObjectAttributes.h
Small bugfix that specifies a stage's default shader type to be flat instead of unknown.  Since stages often come with lighting baked into the textures, we do not want to apply phong or pbr shading on top of this.   This, of course, can be easily overridden, either at the stage config level, or for individual instancing scenes.
All c++ and python tests pass locally
> [Bugfix] Specify default stage shader type as flat;

- src/esp/metadata/MetadataUtils.cpp
- src/esp/metadata/attributes/ObjectAttributes.cpp
- src/esp/metadata/attributes/ObjectAttributes.h
- src/esp/metadata/attributes/SceneAttributes.cpp
- src/esp/sim/Simulator.cpp
- src/tests/AttributesManagersTest.cpp
This small PR introduces an accepted value of "material" for the "shader_type" field within the various configuration files describing objects and stages.  This value will override any previously set shader_type values for the particular asset to instead use whatever shader_type is specified by the materials within in asset's file.  This is necessary because there is a hierarchy of configuration specification in place, and without this option, the user would be unable to override any shader type specification set at a lower level configuration.  
For instance, a user may specify that the desired shader_type for all bananas (in their copy of banana.object_config.json) should be Flat.  However, within a certain scene, they may wish for a particular instance of banana to be rendered using …
> [Bugfix]Shader type config value "material" option

- src/esp/assets/ResourceManager.cpp
- src/esp/metadata/attributes/PrimitiveAssetAttributes.cpp
- src/esp/metadata/attributes/PrimitiveAssetAttributes.h
- src/esp/metadata/managers/AssetAttributesManager.cpp
- src/esp/metadata/managers/AssetAttributesManager.h
- src/tests/AttributesManagersTest.cpp
This small PR will take a valid PrimitiveAssetAttributes handle and use it to create and configure an appropriate PrimitiveAssetAttributes template.  The handles of these templates encode all the relevant information required to properly instantiate a Magnum Primitive, and the handles cannot be changed by the user, so these handles can be expected to be valid descriptions/encodings of the described primitive template.
All c++ and python tests pass.  C++ tests have been added to verify that template handles can be parsed into templates with appropriate field values.
> Create Appropriate PrimitiveAssetAttributes from valid handle

- src/esp/sim/Simulator.cpp
This little PR removes duplicate sequential points from a point trajectory before building the trajectory visualization. Centripetal CR spline doesn't behave well with duplicate points in a sequence.
C++ and python tests pass locally.
> Dedupe sequential points in trajectory for visualization.

- src/esp/gfx/Drawable.cpp
- src/esp/gfx/Drawable.h
- src/esp/gfx/GenericDrawable.cpp
- src/esp/gfx/MeshVisualizerDrawable.cpp
- src/esp/gfx/PTexMeshDrawable.cpp
- src/esp/gfx/PbrDrawable.cpp
As titled.
So the actual drawable type (pbr, generic, ptex etc.) can be identified even from the base class "Drawable" during the fly.
It will be useful later when creating new drawables only used in the shadow map pre-computation.
> [PBR][IBL] Add a drawable type for runtime identification

- src/esp/assets/ResourceManager.cpp
This small PR adds support for orientation frame changes for objects.  This primarily came to light when attempting to load glb stages as objects in [this PR](https://github.com/facebookresearch/habitat-sim/pull/1318).
All local c++ and python tests pass
> [BUGFIX] add missing orientation support for objects.

- .circleci/config.yml
- setup.py
- tests/test_physics_benchmarking.py
Note: migrated from #1304 
Adds `pytest-benchmark` integration for benchmarking simulator functionality locally and automatically on CI.
Initial PoC function benchmarks URDF parse->instance->remove loop with and without force_reload caching option.
Note: requires local installation with pip install pytest-benchmark.
Local testing and CI integration. Example output of pytest tests/benchmark_physics.py:
> pytest-benchmark integration

- src/esp/physics/ArticulatedObject.h
* Performance Optimization. Unordered maps are often faster than std::map with one notable exception, when they have to be resized. Unlike std::maps though, the size can be reserved ahead of time. We should do that whenever possible prevent the O(n(log(n))). Even if we aren't sure of the exact size, we often have an upperbound.
* CI
> [Perf] Use reserve() on unordered_map calls

- src/esp/physics/bullet/BulletRigidObject.h
The bug I observed with the old code was: already-asleep bodies got stuck in the WANTS_DEACTIVATION state.
Ad hoc testing in [arrange recorder](https://github.com/eundersander/habitat-sim/tree/eundersander/arrange_recorder2)
> fix for rigid body setActive(false)

- src/esp/physics/bullet/BulletRigidObject.cpp
- src/tests/PhysicsTest.cpp
Alex and I have both seen behavior where a Bullet body with kinematic motion will get moved by Bullet stepWorld. This is avoided by setting zero mass. Alex speculated that collision-resolution code isn't checking the kinematic flag and is thus moving the kinematic body when the mass is non-zero.
I tested locally in a scene with kinematic and dynamic objects. This change fixed the behavior bug for me.
> fix for KINEMATIC objects being moved by Bullet unexpectedly

- src/esp/core/managedContainers/ManagedContainerBase.cpp
- src/esp/core/managedContainers/ManagedContainerBase.h
This small PR removes the platform-dependent pivot character used to partition the count component of the object instance name, so that users can write platform-independent code referencing object instances by name.  Checks were also added to verify that candidate names were formatted appropriately.
All c++ and python tests pass locally.
> [ObjectInstances] Remove platform dependence on pivot char; add checks for validity

- src/esp/metadata/attributes/LightLayoutAttributes.cpp
- src/esp/metadata/attributes/LightLayoutAttributes.h
- src/esp/metadata/managers/LightLayoutAttributesManager.cpp
- src/tests/AttributesManagersTest.cpp
This PR adds to values to the lighting config jsons - "positive_intensity_scale" and "negative_intensity_scale".  These multiplicative values are used to scale the intensities of all light configs in a single command, to easily tweak existing lighting configs for habitat sim engine, at least in a broad stroke.  This is intended to provide a simple config-based mechanism for (somewhat heavy-handed) lighting adjustments, instead of necessitating hand tweaking of config values, if, for example, scenes are too dark.  
All c++ and python tests pass locally.  Added test cases to verify being properly configured in AttributesManagersTest.cpp
> Lighting Attributes : Add intensity scaling vals

- src/esp/bindings/SimBindings.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
This small PR adds a convenience method to acquire the light setup used to instantiate the current stage/scene (after reconfigure).  Note : individual objects'/articulatedObjects' light setups can be changed by the user, and this accessor will not reflect that change. 
> --Add helper and binding to get LightSetup used to create current scene.

- src/esp/scene/ReplicaSemanticScene.cpp
- src/esp/scene/SemanticScene.cpp
- src/esp/scene/SemanticScene.h
- src/esp/scene/test/ReplicaSceneTest.cpp
This small PR modifies Replica support to also support the ReplicaCAD semantic lexicon.  The ReplicaCAD semantic lexicon just contains semantic category id's and names for all the mappings across the dataset, and does not have per-scene object mappings.  This is because every object config has the semantic_id specified for that object, which are used to provide the semantic mapping.
ReplicaSceneTest has been modified to make sure this behaves properly.  
C++ and python tests pass locally.  ReplicaSceneTest modified to cover this functionality.
> [ReplicaCAD] Support ReplicaCAD semantic lexicon json format.

- src/esp/gfx/replay/Player.h
- src/esp/gfx/replay/Recorder.cpp
- src/esp/gfx/replay/Recorder.h
- src/esp/io/CMakeLists.txt
- src/esp/io/JsonMagnumTypes.cpp
- src/esp/io/JsonMagnumTypes.h
- src/esp/io/JsonUtils.h
- src/esp/io/json.cpp
- src/esp/io/json.h
- src/tests/GfxReplayTest.cpp
Turning off the PrettyWriter and reducing precision helps reduce filesize for gfx-replay and `arrange_recorder`.
I also made a small change to how Quaternions are serialized, again to reduce filesize.
GfxReplayTest was modified to ensure we test precision of serialized/deserialized Quaternions.
> usePrettyWriter and precision options for JSON writing

- src/esp/bindings/MetadataMediatorBindings.cpp
- src/esp/metadata/MetadataMediator.h
This small PR adds a function that will retrieve a list of all the scene instance handles in the currently active scene dataset.
All c++ and python tests pass locally
> Retrieve list of scene instance handles of current dataset

- src/esp/bindings/AttributesManagersBindings.cpp
- src/esp/bindings/PhysicsWrapperManagerBindings.cpp
- src/esp/core/managedContainers/ManagedContainer.h
- src/esp/core/managedContainers/ManagedContainerBase.cpp
- src/esp/core/managedContainers/ManagedContainerBase.h
- src/esp/metadata/attributes/AttributesBase.h
- src/esp/metadata/attributes/LightLayoutAttributes.h
- src/esp/metadata/attributes/ObjectAttributes.h
- src/esp/metadata/attributes/PhysicsManagerAttributes.h
- src/esp/metadata/attributes/PrimitiveAssetAttributes.h
- src/esp/metadata/attributes/SceneAttributes.cpp
- src/esp/metadata/attributes/SceneAttributes.h
- src/esp/metadata/attributes/SceneDatasetAttributes.h
- src/esp/metadata/managers/SceneAttributesManager.cpp
- src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/tests/AttributesManagersTest.cpp
- src/tests/MetadataMediatorTest.cpp
- tests/test_attributes_managers.py
This PR contains bugfixes and cleanup for the following issues : 
- Remove out-of-date attributes todo messages
- Fix bug where Articulated Object model filename was getting erroneously parsed before saving upon load of SceneDataset, causing file to be unloadable.
- Add SceneInstance-level Articulated Object instance support for initial "autoClampJointLimits_" boolean setting, which controls whether or not dof limits should be enforced automatically before physics step is taken.
- Add mechanism to query whether ManagedContainer has an entry with a passed integer ID value.
All c++ and python tests pass.  
Tests added to 
- Verify autoClampJointLimits is read properly from SceneInstance
- AO model filename actually exists as specified in SceneDataset config.
- Test to verify that query for …
> [Bugfix] Various fixes for articulated object loading and instancing

- habitat_sim/utils/datasets_download.py
Add [YCB objects](https://www.ycbbenchmarks.com/object-models/) to `datasets_download.py` with habitat compatible configs.
NOTE: objects are a bit dark in-engine currently.
Local testing with script and viewer.
> Add YCB objects to download script

- habitat_sim/utils/datasets_download.py
A subset of assets is necessary to run the Habitat-lab rearrange pick task. Adding a data_group makes download/setup a 1 line call.
Local testing.
> Add rearrange task data_group to datasets_download.py

- src/esp/assets/ResourceManager.cpp
- src/esp/gfx/MaterialData.h
- src/esp/gfx/MaterialUtil.cpp
Phong and PBR materials respond very differently to that same lighting. We recently updated the light setups to support our transition to PBR primary materials which caused Phong materials (primarily primitives and URDF with color overrides) to be very bright. This PR adds a multiplier hack to balance the color intensities of Phong and PBR.
Used Viewer to balance w/ default lights:
Before: 
After:
> Scale Phong materials to better match PBR intensities

- conda-build/linux_matrix_builder.py
* Now that we build bullet from source, this should solve the issues were having with building both withbullet and non-headless. This disables the filter that prevents it.
CI
> Allow non-headless bullet conda-builds

- habitat_sim/utils/datasets_download.py
Add `--no-replace` to datasets_download.py to skip existing data automatically. Should fix use-cases with automated download that are run multiple times, currently requiring re-download with `--replace` or crashing due to user prompt.
Locally.
> Add --no-replace to datasets_download.py 

- habitat_sim/utils/datasets_download.py
Change default data_path from git to ./data/ so the script has a reasonable default outside of git repo but is also compatible with previous default behavior in habitat-sim directory and doesn't flood an existing user directory. 
Locally
> datasets_download.py - change default data_path 

- habitat_sim/physics.py
- src/esp/bindings/PhysicsBindings.cpp
Added some missing docstrings and added ContatPointData to the `habitat_sim.physics` module.
Local doc build.
> [docs] ContactPointData 

- src/utils/viewer/viewer.cpp
Minor bug fix to make sure we accurately find starting scene in list of scenes in viewer, and tab/shift tab appropriately cycles through other scenes.
Locally  c++.
> --[Bugfix] Scene Instance Viewer list start.

- src/esp/physics/objectWrappers/ManagedArticulatedObject.h
Fixes #1405 where getLinkNumDoFs returned the wrong value in the ArticulatedObjectWrapper.
* Fixes a typo in the ArticulatedObjectWrapper that returned the wrong value.
> [BugFix] Fix Typo in Articulated Object Manager

- src/esp/gfx/CMakeLists.txt
- src/esp/gfx/PbrPrecomputedMapShader.cpp
- src/esp/gfx/PbrPrecomputedMapShader.h
- src/esp/physics/URDFImporter.cpp
- src/shaders/Shaders.conf
- src/shaders/pbrCommon.glsl
- src/shaders/pbrIrradianceMap.frag
- src/shaders/pbrPrecomputedMap.vert
- src/shaders/pbrPrefilteredMap.frag
This shader can render 2 cubemap textures that are must-have ones form IBL.
These 2 textures are:
Irradiance map, used in IBL diffuse part;
prefiltered map, used in IBL specular part;
Shader are tested in #1389.
> [PBR][IBL] Shaders to pre-compute prefiltered environment map and irradiance map

- src/esp/physics/bullet/BulletPhysicsManager.cpp
The loading of assets for articulated objects did not support unlit/flat-shaded assets, even if "no_lights" was specified.  This PR addresses this by only setting "requiresLighting" for the assetInfo used to instantiate the asset if the lighting specification is not no_lights. 
C++ and Python tests, locally
> [BugFix] Enable URDF AO Loader to support unlit / baked lighting assets.

- tools/create_basis_compressed_glbs.py
This PR fixes the modification code for setting the materials in a glb to be unlit using the Khronos extension "KHR_materials_unlit" by adding a top-level entry for this extension in the "extensionsUsed" key. Without this setting, the created .gltf/.glb files will fail Khronos validation.
Locally
> [BugFix] gltf/glb "extensionsUsed" not being set

- src/esp/physics/bullet/BulletPhysicsManager.cpp
I'd like us to avoid using asserts in this way. In principle, asserts are a debugging tool and we should be able to disable them in a release build. Here, the (essential) loading is happening inside the assert.
Tested locally in viewer.
> change URDF assert to ESP_CHECK

- docs/conf.py
- docs/namespaces.dox
- docs/pages/index.rst
- docs/pages/logging.rst
- src/esp/core/CMakeLists.txt
- src/esp/core/logging.cpp
- src/esp/core/logging.h
- src/esp/core/test/CMakeLists.txt
- src/esp/core/test/LoggingTest.cpp
In #1184 we discussed having different logging subsystems for habitat-sim so that we can filter logs based on different subsystems.  This PR takes an attempt at implementing this.  The most important user facing part of this is how different logging filters are constructed with the environment variable (named `HABITAT_SIM_LOG`).  This simply applies a series of changes to the logging level for each system or a subset of systems, letting you construct an arbitrary filter.
The filter has a simple grammar
```
Filter: SetLevelCommand (COLON SetLevelCommand)*
SetLevelCommand: (SUBSYSTEM (COMMA SUBSYSTEM)* EQUALS)? LOGGING_LEVEL
```
So to have verbose logging on just the physics subset, you can do
```
quiet:physics=verbose
```
The "quiet" sets all subsets to subsystem and "physics=verbose" sets …
> Subsystem Logging

- src/esp/core/Configuration.h
- src/esp/io/json.cpp
- src/esp/io/json.h
- src/esp/metadata/managers/AttributesManagerBase.h
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsObjectBase.h
- src/tests/AttributesManagersTest.cpp
Presently, the user-defined attributes fields within the various configuration files only support a single layer of data values of various types, but this PR adds support for nested json objects within user-defined attributes values, enabling a user to be able to specify sub-groupings within these fields.  
This functionality is required for ReplicaCAD to be properly used in Habitat 2.0 (to provide support for per-object placement box configurations)
Tests added in c++ to verify functionality.  Tested locally c++ and python
> --Add support for nested User-defined attributes

- src/esp/metadata/attributes/PhysicsManagerAttributes.cpp
We have a bug where someone installing Hab 2.0 from conda (and downloading our datasets) will generally find physics to be nonfunctional/disabled. The default attribs updated by this PR are used when `default.physics_config.json` is not found. Conda hab-sim users generally don't have this file (it isn't included in our current datasets). 
The source of confusion here was that we (Hab Sim Infra engineers) usually test with our data at `habitat-sim/data`, and our source tree includes `habitat-sim/data/default.physics_config.json`. Conda users don't have this because they don't get our source tree as part of a conda install.
Local testing with the C++ viewer
> Better default physics attribs (fix for disabled physics)

- src/esp/physics/objectWrappers/ManagedArticulatedObject.h
* Static analysis suggested we were passing this by value when there was no reason to do so add the object was 80 bytes large. This should remove a copy of those 80 bytes with no bad effects. Surprised clang-tidy didn't pick up on this. Found by checking the lgtm.com static analysis.
* Locally
> [Perf] AOWrapper pass settings by const ref instead of by value

- src/utils/viewer/viewer.cpp
On HiDPI displays like Macbook retina displays, the frame buffer dimensions can be 2x the window size.  This will result in a mouse event position (i.e. click) appearing to have occurred halfway toward the screen-space origin from where the user intended, unless corrected.  
This PR fixes this issue, by scaling the mouse event position by the ratio of frameBuffer to Window size, multiplied by dpiScaling.
It's viewer! It always works! (Tested locally, including on macbook retina display)
> [Bugfix] Scale mouse event locs by ratio of dpiScale * framebuffer/windowSize

- examples/tutorials/colabs/ECCV_2020_Advanced_Features.ipynb
- examples/tutorials/colabs/ECCV_2020_Interactivity.ipynb
- examples/tutorials/nb_python/ECCV_2020_Advanced_Features.py
- examples/tutorials/nb_python/ECCV_2020_Interactivity.py
- src/esp/bindings/AttributesManagersBindings.cpp
- src/esp/bindings/PhysicsWrapperManagerBindings.cpp
- src/esp/core/managedContainers/ManagedContainer.h
- src/esp/core/managedContainers/ManagedContainerBase.cpp
- src/esp/core/managedContainers/ManagedContainerBase.h
- src/esp/metadata/attributes/PrimitiveAssetAttributes.h
- src/esp/metadata/managers/AssetAttributesManager.h
- src/esp/metadata/managers/ObjectAttributesManager.cpp
- src/esp/metadata/managers/ObjectAttributesManager.h
- src/tests/SimTest.cpp
This PR changes the underlying data structure for the Managed Containers from std::map to std::unordered_map, for better performance with containers holding many elements.  
The only downside to this process is that formerly, any string-based query of the managed container would return results in sorted order. This PR will sort the results from such a query as default behavior, which can also be overridden on demand if sorting is not required. Since generally the results set is small (where the query is matching a substring of the handles of objects held in the map), the overhead for this sort will also generally be small.  
C++ and python tests
> ManagedContainers - Change underlying data structure to unordered map

- habitat_sim/utils/viz_utils.py
As identified by #1421, overlay_settings was not being forwarded during video creation.
Locally with ECCV_2020_Interactivity.py
> [bugfix] fix overlay_settings not being forwarded

- src/esp/gfx/DebugLineRender.cpp
This early-outs DebugLineRender::flushLines when there are no lines to be flushed. It significantly improves performance on frames where there are no debug lines to render.
I tested this optimization on my WebXR mobile demo webapp.
> Don't run flushLines code when there are no lines

- examples/benchmark.py
- examples/tutorials/physics_benchmarking.py
- src/esp/core/managedContainers/ManagedContainerBase.cpp
* The lack of a __main__  prevents the multiprocessing in examples/benchmark.py from running on certain versions of OSX and the physics benchmarking example uses the BaseException which is incorrect as it can mask other exceptions (like SyntaxErrors).
* Locally
> [Bugfix] Fix bugs in examples benchmarking

- src/esp/assets/ResourceManager.cpp
- src/esp/gfx/BackgroundRenderer.cpp
- src/esp/gfx/DebugLineRender.cpp
- src/esp/gfx/replay/Player.cpp
- src/esp/gfx/replay/Recorder.cpp
- src/esp/gfx/replay/ReplayManager.cpp
- src/esp/metadata/MetadataMediator.cpp
- src/esp/metadata/MetadataMediator.h
- src/esp/sim/Simulator.cpp
- src/tests/GfxReplayTest.cpp
- src/utils/viewer/viewer.cpp
With the most recent logging functionality, filename, source function, and line number for logging message is provided automatically.  This PR removes some remaining log messages that were also including this information, which is now redundant.
Locally, c++ and python tests pass
> [BUGFIX]Remove redundant method refs in log messages

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/metadata/MetadataMediator.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/tests/CullingTest.cpp
- src/tests/DrawableTest.cpp
- src/tests/PhysicsTest.cpp
- src/tests/ResourceManagerTest.cpp
This small PR changes the argument list for loadStage to remove createSemanticMesh and forceSeparateSemanticSceneGraph, and instead query the MetadataMediator's copy of simConfig for these values, which is always synced with Simulator and always the most relevant/pertinent simConfig whenever a scene's assets are loaded. 
This PR also passes the SceneObjectInstance attributes to loadStage so that (in a future PR) the stage can have transformations performed during creation (if required) and per-instance user defined attributes metadata merged with existing user attributes data.
Local C++ and python tests.
> Modify ResourceManager::loadStage to receive SceneObjectInstance for stage, and consume MM instead of arguments.

- src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.cpp
This PR fixes an issue when someone loads an asset with a particular extension that we have hardcoded internally to have a certain orientation (for backwards compatibility).  If the desired asset does not have that orientation, it is impossible to set the orientation via default attributes settings in scene dataset configuration file.  
This fix is a stopgap measure for now, and should work mostly, but the only foolproof solution to this is going to be getting rid of the hardcoded asset setting based on extension.  As we get more dataset assets, we cannot assume anything orientation-wise about assets solely on their extension.  To do this, we need to rework the tests to use config-backed assets.
Locally c++ and python.
> [BUGFIX] Do not set orientation based on file ext if default attributes provided, overrides default config for orientation.

- src/esp/core/managedContainers/ManagedFileBasedContainer.h
- src/esp/io/JsonBuiltinTypes.h
This small pr gets rid of 2 **Wzero-as-null-pointer-constant** warnings our rapidjson-consuming code was generating.  
Locally all c++ and python tests pass
> [Bugfix]Clean up '0-as-null pointer' warnings

- src/esp/bindings/AttributesManagersBindings.cpp
- src/esp/bindings/PhysicsWrapperManagerBindings.cpp
- src/esp/core/managedContainers/ManagedContainer.h
- src/esp/core/managedContainers/ManagedContainerBase.h
- tests/test_attributes_managers.py
- tests/test_physics.py
In the existing system, you can search an attributes/object manager for a list of handles by providing a substring, and then retrieve the managed objects each handle references.  
This PR cuts a step from this, and adds the ability to retrieve a dictionary of managed objects (templates or object wrappers) via a substring search, where each entry is keyed by the handle and value is the managed object corresponding to that handle. 
Locally c++ and python tests.  test_attributes_managers.py and test_physics.py have been modified to test this functionality directly.
> --Add ability to retrieve a dictionary of handle-keyed templates/wrapped objects via substring query

- src/utils/viewer/viewer.cpp
* Before this, the user could not hide the mouseInteraction text which made taking screnshots without the overlay impossible.
* Locally
> [bugfix][viewer] Allow user to hide mouseinteraction text

- src/esp/physics/CollisionGroupHelper.cpp
- tests/test_physics.py
Fix to ensure CollisionGroup::Noncollidable has a mask of 0 and thus collides with nothing.
The previous code used a mask of -1, with the result that a Noncollidable would collide with another Noncollidable.
Ad hoc local testing
> CollisionGroup::Noncollidable fix

- src/esp/core/Configuration.cpp
This small PR addresses a logic error in a check attempting to verify that all possible values of an enum are properly supported in switch statements of two functions. 
Locally tested c++ and python
> --[BugFix]Fix erroneous ConfigStoredType checks

- setup.py
* This fixes a bug where setup.py would not detect if it was running in pip when run with `python -m pip ...` . This uses a more robust ENV variable to see if it is being called from setup.py or not.
* Locally and on CLI
* Also removes deprecated setup_requires which was only used as hack anyhow to install pytest automatically when `python setup.py test` . This argument is deprecated anyway so best to remove and further simplify the script.
> [bugfix] Fix bug in detecting if is_pip()

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/core/managedContainers/ManagedContainerBase.cpp
- src/esp/metadata/MetadataMediator.cpp
- src/esp/metadata/attributes/AttributesBase.h
- src/esp/metadata/attributes/LightLayoutAttributes.cpp
- src/esp/metadata/attributes/LightLayoutAttributes.h
- src/esp/metadata/attributes/ObjectAttributes.cpp
- src/esp/metadata/attributes/ObjectAttributes.h
- src/esp/metadata/attributes/PhysicsManagerAttributes.h
- src/esp/metadata/attributes/SceneAttributes.cpp
- src/esp/metadata/attributes/SceneAttributes.h
- src/esp/metadata/attributes/SceneDatasetAttributes.cpp
- src/esp/metadata/managers/SceneAttributesManager.cpp
- src/esp/physics/ArticulatedObject.h
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/PhysicsObjectBase.h
- src/esp/physics/RigidBase.h
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/physics/objectWrappers/ManagedArticulatedObject.h
- src/esp/physics/objectWrappers/ManagedPhysicsObjectBase.h
- src/esp/physics/objectWrappers/ManagedRigidBase.h
- src/esp/physics/objectWrappers/ManagedRigidObject.h
- src/esp/sim/Simulator.cpp
- src/tests/MetadataMediatorTest.cpp
This PR provides some improvements in AbstractManagedObject-inheriting classes.
- Use Corrade::utility::formatString for all toString functionality, instead of chains of appends.
- Make SceneObjectInstanceAttributes shared_ptrs to const for when scenes are instanced.
Locally c++ and python
> --Attributes improvements and refactor.

- examples/colab_utils/colab_install.sh
* This pin's numba to the appropriate colab version.
* It also allows more flexible matching of colab requirements (minor version can differ).
* Colab
> [bugfix][colab] Dynamically pin numba to appropiate colab version

- src/esp/io/URDFParser.cpp
- src/esp/io/URDFParser.h
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsObjectBase.h
- src/esp/physics/URDFImporter.cpp
- src/esp/physics/bullet/BulletArticulatedObject.cpp
This PR introduces support of Json config files for URDF-based ArticulatedObject models in the URDFParser, which will hold default user-defined attributes (Such as bounding boxes for placements) that apply to all instances of articulated objects built from these models.   This PR also removed extraneous markers from error messages that did not match the format of our current message logging in the URDFParser.
To be compatible with this functionality, the json config file holding the user_defined attributes must meet these criteria : 
- Must be in the same directory as the AO's .urdf file
- Must have the same core filename (minus extensions) as the AO's .urdf file
- Must have the following extension :  <filename>**.ao_config.json**
- Internally, the file must have a root Json object, and …
> ArticulatedObjects: Enable support for secondary json config files.

- src/esp/bindings/MetadataMediatorBindings.cpp
Provide read-only bindings to dictionary of urdf paths in current scene dataset.  Keyed by simplified name, value is fully qualified filepath.
Locally c++ and python tests
> --add binding to access read-only dictionary of URDF paths

- .circleci/config.yml
- setup.py
- src/CMakeLists.txt
* I just tested the latest LLVM (13.0) and it fixes the segfault that prevented us from using using ThinLTO compilation. 
* Also tries to fix a flaky portion of the CI
* I can remove the cludge for EMSCRIPTEM (which is already at a supported LLVM version number), once my toolchains PR is merged in (https://github.com/mosra/toolchains/pull/14) Ping @mosra
* Tested with LLVM Clang 13.0
> [Compilation] Allow ThinLTO and Fix CI flakiness

- .circleci/config.yml
- requirements.txt
- src/esp/bindings/PhysicsObjectBindings.cpp
- src/esp/physics/ArticulatedObject.h
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/physics/objectWrappers/ManagedArticulatedObject.h
- tests/test_physics.py
Articulated objects can be programmatically scaled upon instantiation in the scene. Any geometric metadata defined in the original frame should be scaled also, requiring that this global scale is cached when the object is created and queryable later.
Added a simple test in python.
> Add cache and query for ArticulatedObject global scaling.

- src/esp/bindings/ConfigBindings.cpp
- src/esp/core/Configuration.cpp
- src/esp/core/Configuration.h
- src/esp/io/URDFParser.cpp
- src/esp/io/URDFParser.h
- src/esp/io/json.cpp
- src/esp/metadata/MetadataMediator.cpp
- src/esp/metadata/attributes/AttributesBase.cpp
- src/esp/metadata/attributes/AttributesBase.h
- src/esp/metadata/attributes/LightLayoutAttributes.cpp
- src/esp/metadata/attributes/LightLayoutAttributes.h
- src/esp/metadata/attributes/SceneAttributes.cpp
- src/esp/metadata/attributes/SceneAttributes.h
- src/esp/metadata/managers/LightLayoutAttributesManager.cpp
- src/esp/metadata/managers/SceneAttributesManager.cpp
- src/tests/AttributesManagersTest.cpp
Use subconfig system instead of redundant member variable vectors to store stage, object and articulated object scene instances, and lighting configs.  Lights and scene instances are now supported.
Locally c++ and python tests pass.
> --Use subconfigs instead of local vectors for scene instance and light attributes

- src/esp/metadata/attributes/AttributesBase.h
- src/tests/AttributesManagersTest.cpp
- src/tests/SimTest.cpp
- tests/test_configs.py
The Configuration class is a robust and flexible mechanism for storing and accessing hierarchical aggregations of data, providing templated setters and getters that will save and retrieve data of various types.  
The AbstractAttributes class, which inherits from the Configuration class, provides the base for the Attributes classes that define various components of the Habitat-sim simulation and dataset ecosystem.  The purpose of these various Attributes is to provide full and safe access to all the data fields pertinent to the constructs they define.
This PR makes the Configuration base class's templated setter in AbstractAttributes protected so that it can only be accessed from the derived implementations, removing external access from any AbstractAttributes-derived class object.  This …
> --Hide Configuration Setters in Attributes for safety

- src/esp/geo/CMakeLists.txt
- src/esp/geo/CoordinateFrame.cpp
- src/esp/geo/CoordinateFrame.h
- src/tests/GeoTest.cpp
This small PR removes the JSON functionality from the CoordinateFrame class, to more closely match the current paradigm for building objects from JSON, and also enabling the removal of io as dependency in geo, in an effort to address some of our circular dependency woes.
> --Remove redundant JSON functionality, and geo's dep on io.

- src/tests/AttributesManagersTest.cpp
- src/tests/CMakeLists.txt
- src/tests/CoreTest.cpp
- src/tests/CullingTest.cpp
- src/tests/DrawableTest.cpp
- src/tests/GeoTest.cpp
- src/tests/GfxReplayTest.cpp
- src/tests/IOTest.cpp
- src/tests/MetadataMediatorTest.cpp
- src/tests/Mp3dTest.cpp
- src/tests/NavTest.cpp
- src/tests/PhysicsTest.cpp
- src/tests/ResourceManagerTest.cpp
- src/tests/SceneGraphTest.cpp
- src/tests/SensorTest.cpp
- src/tests/SimTest.cpp
- src/tests/SuncgTest.cpp
- src/tests/VoxelGridTest.cpp
This PR refactors all the existing c++ tests in esp/tests/ to use the Corrade test suite instead of google test.  The eventual goal is to remove the gtest suite entirely.  
This is the first of 2 PRs to address this and only addresses the tests in the esp/tests/ directory.  Part 2 of this series of PRs will move all tests that reside elsewhere to be in esp/tests/ directory, and will also refactor any other remaining c++ tests to use the Corrade test suite.
C++ tests locally
> [TechDebt]--Refactor tests to use Corrade test suite (Part 1 of 2)

- habitat_sim/simulator.py
- src/esp/sim/Simulator.cpp
Due to legacy reasons, we create a pathfinder object in the python sim _after_ the cpp sim has been initialized. This means that the navmesh loaded via the scene dataset get's unloaded!
Via tests. We have a lot of tests that require the navmesh to be loaded correctly and I do not see python saying it loaded the navmesh, so cpp must be doing it correctly!
> Fix Double PathFinder

- src/cmake/dependencies.cmake
* Previously our corrade plugins were not statically linked which complicated the rpath resolution. Apparently, this was a bug and can be fixed with a simple cmake change which ensure that corrade is built statically as well.
* Now that this change is made, it vastly simplifies the rpath issues we were having before since Magnum and Habitat-Sim are both separately and statically linked.
* Fixes a bug where importing magnum would fail if habitat_sim was not imported first (due to shared lib dependencies installed in the habitat_sim folder.
* Locally on OSX and on CI.
> [Bugfix]: make corrade plugins static

- .circleci/config.yml
* Miniconda is installed, unnecessary dependencies are installed and Anaconda are installed through the installer script all corrupting each other.
* Should just work.
> [CI] Stops nightly-condabuild from corrupting itself.

- src/esp/assets/ResourceManager.cpp
- src/esp/bindings/AttributesBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/core/Configuration.h
- src/esp/core/managedContainers/ManagedContainerBase.cpp
- src/esp/core/managedContainers/ManagedFileBasedContainer.h
- src/esp/gfx/LightSetup.cpp
- src/esp/metadata/MetadataMediator.cpp
- src/esp/metadata/attributes/LightLayoutAttributes.h
- src/esp/metadata/attributes/ObjectAttributes.cpp
- src/esp/metadata/attributes/ObjectAttributes.h
- src/esp/metadata/attributes/PhysicsManagerAttributes.h
- src/esp/metadata/attributes/SceneAttributes.cpp
- src/esp/metadata/attributes/SceneAttributes.h
- src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
- src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/nav/GreedyFollower.cpp
- src/esp/nav/PathFinder.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletRigidStage.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/esp/sim/SimulatorConfiguration.cpp
- src/esp/sim/SimulatorConfiguration.h
- src/tests/SimTest.cpp
- src/utils/viewer/viewer.cpp
- tests/test_attributes_managers.py
This PR refactors a few things system-wide, and also adds some optimizations and small features to the Metadata/Attributes pipeline. 
- Improved stl checking/building in various locations in ManagedContainers, AbstractAttributes, and elsewhere.
- Renamed SimulatorConfiguration.sceneLightSetup ->SimulatorConfiguration.sceneLightSetupKey
- Cleaned up string search functionality used by ManagedContainers
- Add Scene Instance support for visibility flag (Note : ArticulatedObjects will require further coding to support config-based visibility setting, to be provided by a future PR.
- Hide Configuration setter access in AbstractAttributes bindings to prevent accidental type errors for essential fields.  Attributes' fields should always be accessed via specified property bindings
- Various …
> [TechDebt]--Minor Refactors; Attributes/ManagedContainer optimizations and documentation updates.

- .circleci/config.yml
* There was an issue where the miniconda package is still cached preventing the conda install from functioning properly.
> [CI] Fix conda nightly package cache

- src/esp/physics/objectManagers/ArticulatedObjectManager.h
- src/esp/physics/objectManagers/RigidObjectManager.h
- tests/test_physics.py
When bullet is available at compilation time, but the user has disabled physics via  a runtime configuration setting (causing a base PhysicsManager to be created, instead of a BulletPhysicsManager), object wrappers were statically cast to ManagedBulletRigidObject / ManagedBulletArticulatedObject when accessed from python, causing them to be None (since BulletPhysicsManager is required to create Bullet-based objects, and this does not exist when physics is disabled).  This PR addresses this by attempting to dynamically cast the wrapper objects, and if this fails, returning instead the uncast wrapper.
Locally C++ and python.  Python test_physics.py test suite expanded to include kinematics test with physics disabled in configuration.
> [BugFix]--Address when Bullet is available but physics is not enabled.

- data/test_assets/testing.physics_config.json
- docs/pages/attributesJSON.rst
- docs/pages/managed-rigid-object-tutorial.rst
- src/esp/bindings/ConfigBindings.cpp
- src/esp/metadata/attributes/PhysicsManagerAttributes.h
This PR is updating the attributesJSON, which is currently out of date, to match the currently supported fields for the various configuration types.  Still a work in progress.  This is the first of many documentation PRs to cover the MetadataMediator/SceneDataset/SceneInstance system.
Docs build
> [TechDebt]--JsonAttributes Docs update

- src/esp/metadata/managers/LightLayoutAttributesManager.cpp
This fixes an improper access to a JSON object - Objects do not have Size function.  Just removed query.
Locally c++ build (using debug flag that exposed issue originally)
> [BugFix]--Fix improper JSON object access.

- src/tests/DrawableTest.cpp
- src/tests/SimTest.cpp
This small PR cleans up 2 tests : 
- Removes the superfluous ResourceManager child class def from DrawableTest
- Refactors 3 tests in SimTest to always use the test instancing functionality that is used in all the other SimTest tests.
Locally all c++ tests pass
> [Cleanup]--Clean up tests.

- src/esp/bindings/ShortestPathBindings.cpp
> added path arg to load_nav_mesh

- .circleci/config.yml
- src/esp/bindings/PhysicsWrapperManagerBindings.cpp
- src/esp/io/URDFParser.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/physics/bullet/BulletURDFImporter.cpp
- src/esp/physics/bullet/BulletURDFImporter.h
- src/esp/physics/objectManagers/ArticulatedObjectManager.cpp
- src/esp/physics/objectManagers/ArticulatedObjectManager.h
- tests/test_physics.py
For consistency with other simulators (e.g. pybullet), this PR adds an option to preserve the order of links parsed from URDF files as link indices.
To use this option:
`add_articulated_object_from_urdf(urdf_filename, maintain_link_order=true)`
Added a pytest.
> Add option to preserve URDF link ordering

- src/esp/sim/Simulator.cpp
This PR addresses segfaults that would happen if, due to misspelling or other errors, a required or expected attributes necessary for scene building is not found (i.e. queries to MetadataMediator returned nullptr).  Now, should these queries fail, a salient message is displayed and the program ends via std::abort.
C++ and python tests pass locally
> [Bugfix]--address segfaults by catching nullptr attribs and exiting gracefully

- .circleci/config.yml
- .pre-commit-config.yaml
- examples/tutorials/nb_python/ECCV_2020_Advanced_Features.py
- examples/tutorials/nb_python/ECCV_2020_Interactivity.py
- examples/tutorials/nb_python/ECCV_2020_Navigation.py
- examples/tutorials/nb_python/ReplicaCAD_quickstart.py
- examples/tutorials/nb_python/asset_viewer.py
- examples/tutorials/nb_python/managed_rigid_object_tutorial.py
- examples/tutorials/nb_python/replay_tutorial.py
- examples/tutorials/nb_python/rigid_object_tutorial.py
* Makes clang-format a proper pre-commit hook using a new pip package we created for PyBind11
* Automatically handles clang-format versioning and dependencies with the new hook
> Add proper clang-format to pre-commit

- habitat_sim/agent/agent.py
- src/esp/gfx/Renderer.cpp
- src/esp/sim/Simulator.h
- tests/test_gfx.py
Semantic rendering requires an activeSemenaticSceneGraph, not a semenaticScene. The former is the Magnum SceneGraph used for rendering while the latter contains information about semantic annotations. We are currently checking for the latter while needing the former.
Via the new test.
> Fix semantic rendering

- examples/viewer.py
Quick fix to Python-Viewer which is currently not running because of an arguments error.
> Fixing bug in python-viewer with draw event callable argument

- tests/test_sensors.py
Small PR to bypass sensor tests if gpu2gpu is specified and torch is not found.
Locally
> [BugFix]--bypass test_sensor tests if no torch is found.

- examples/fairmotion_interface.py
- examples/motion_viewer.py
- examples/viewer.py
- src/esp/assets/ResourceManager.cpp
With this PR merged, the Fairmotion viewer will have an additional mouse interaction mode called "MOTION".
This mode allows users to select a loaded Fairmotion character and click to a desired location for the character and its motion. It also allows users to set rotation around the floor-normal axis by scrolling the mouse wheel with fine-grain rotating using the Shift key. These are useful features for positioning the character in the scene. 
It is works in parallel with the Key Frame and Trajectory Object Previews, which gives the user the ability to foresee scene collision throughout the timeline of the motion for improved character placement choice.
Currently the Fairmotion viewer supports one character at a time and this PR feature is lightly coupled to that fact. In a future PR …
> Fairmotion Character Positioning via MOTION MouseMode

- examples/fairmotion_interface.py
- examples/motion_viewer.py
- examples/viewer.py
This PR give FairmotionInterface users the ability to save and load their MoCap Character data to and from JSON metadata files. It also allows for rapid testing by simplifying data setting.
* A default file and metadata directory will always be created if missing on init().
* Metadata includes, model build data, motion data, and character rotation and translation offsets.
* Use command-line arguments to **Load** whole metadata files or individual attributes completed with default data into the character on init().
* **Save** and **Load** metadata files with `P` and `L`, respectively.
* Quickly **Save** to generated timestamped file for easy metadata capturing and avoiding user input prompts ("*user_YY-MM-DD_hh-mm-ss*").
* Quickly **Save** to last file fetched for easy file editing with …
> Fairmotion Save/Load Metadata via JSON

- src/esp/assets/ResourceManager.cpp
- src/esp/bindings/AttributesBindings.cpp
- src/esp/core/Configuration.h
- src/esp/metadata/CMakeLists.txt
- src/esp/metadata/MetadataMediator.cpp
- src/esp/metadata/MetadataMediator.h
- src/esp/metadata/attributes/ObjectAttributes.cpp
- src/esp/metadata/attributes/ObjectAttributes.h
- src/esp/metadata/attributes/SceneDatasetAttributes.cpp
- src/esp/metadata/attributes/SceneDatasetAttributes.h
- src/esp/metadata/attributes/SceneInstanceAttributes.cpp
- src/esp/metadata/attributes/SceneInstanceAttributes.h
- src/esp/metadata/managers/ObjectAttributesManager.cpp
- src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
- src/esp/metadata/managers/SceneInstanceAttributesManager.cpp
- src/esp/metadata/managers/SceneInstanceAttributesManager.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/tests/AttributesConfigsTest.cpp
- src/tests/AttributesManagersTest.cpp
- src/tests/CMakeLists.txt
- src/tests/MetadataMediatorTest.cpp
This PR is the first of 2 PRs intended to expand Attributes support, specifically to enable saving SceneInstanceAttributes to JSON correctly.  This PR focuses on some necessary refactoring and cleanup to facilitate the new functionality.
Details of PR functionality : 
- Rename SceneAttributes -> SceneInstanceAttributes
- Split existing AttributesManagersTests  (which was growing very large and unruly) into two test files, AttributesConfigsTests (which is focused on accurately setting Attributes values from a given JSON string, saving to JSON files, and validating reload of saved JSON) and AttributesManagersTests (which is focused on creating, copying, modifying and deleting configs via AttributesManagers functionality).
The work in this PR forms the basis for the 2nd part, which will …
> [Part 1 of 2]--SceneInstanceAttributes rename; Attributes testing improvements

- src/esp/geo/Geo.cpp
- src/esp/geo/Geo.h
This PR fixes a couple bugs with the CR spline trajectory tube calc.  The precalculated distances to be used as knot values were being accessed off-by-one, and the time interpolant itself was never reaching t2.
This PR also introduces support for other color spaces to traverse for the trajectory gradient.
> [Bugfix]--Fix CatmullRom Traj off-by-ones; add multiple colorspaces gradient support

- src/esp/assets/ResourceManager.cpp
- src/esp/core/Logging.cpp
- src/esp/core/managedContainers/ManagedContainer.h
- src/esp/core/managedContainers/ManagedContainerBase.cpp
- src/esp/core/managedContainers/ManagedFileBasedContainer.h
- src/esp/gfx/replay/Player.cpp
- src/esp/gfx/replay/ReplayManager.cpp
- src/esp/metadata/attributes/SceneDatasetAttributes.cpp
- src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
- src/esp/metadata/managers/AssetAttributesManager.cpp
- src/esp/metadata/managers/AttributesManagerBase.h
- src/esp/metadata/managers/ObjectAttributesManager.cpp
- src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
- src/esp/metadata/managers/SceneInstanceAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/physics/objectManagers/PhysicsObjectBaseManager.h
- src/esp/scene/SemanticScene.h
- src/esp/sim/Simulator.cpp
- src/tests/LoggingTest.cpp
This PR cleans up a lot of the "::nospace" directives in the various log messages - if any message has more than 2 of these, the log macro itself is directed to use the nospace flag instead.
This PR also introduces a timestamp to the log messages, with resolution to microsecond (using std::chrono::high_resolution_clock).
C++ and python tests pass locally. Logging c++ test modified to validate output properly while ignoring timestamp.
> [Logging]--Minimize "nospace" directives; add timestamp to log messages

- src/esp/metadata/attributes/AttributesBase.h
- src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
- src/esp/metadata/managers/AssetAttributesManager.cpp
- src/esp/metadata/managers/LightLayoutAttributesManager.cpp
- src/esp/metadata/managers/ObjectAttributesManager.cpp
- src/esp/metadata/managers/ObjectAttributesManager.h
- src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
- src/esp/metadata/managers/SceneInstanceAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.h
This PR adds support for a wildcard/sentinel value in the name of the render or collision asset for object attributes or stage attributes (or the navmesh, Semantic Scene asset or Semantic Scene Descriptor text file for stages) in the "default_attributes" tag of the Scene Dataset configuration file.  This value, "%%CONFIG_NAME_AS_ASSET_FILENAME%%" will be replaced by the name used to synthesize the attributes upon instantiation, so a stage- or object-specific value can be requested at the Scene Dataset level, in one spot.  Any value synthesized using this tag will be verified to actually exist before it is written (otherwise the field is cleared).   
With datasets like HM3D, where the data is organized such that a scene's assets and other pertinent information is stored in a single …
> --Scene Dataset default attributes filename wildcard handling.

- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/tests/PhysicsTest.cpp
This small PR adds the acquisition of the render context when objects are deleted in PhysicsManager, as well as when Articulated Objects are created (necessary now since we no longer pass through Simulator to instantiate these objects).  A few redundant "PhysicsManager::addObject" overloads were also removed.
C++ and python tests locally pass.
> [Bugfix/Refactor]--Acquire render context on object removal; Cleanup superfluous add objects

- src/esp/metadata/attributes/AttributesBase.h
- src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
- src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
This small PR addresses a few minor issues with configuration attributes : 
- [Bugfix] Clears out wildcard string in asset filename if no assets found to match wildcard (otherwise asset loading attempts will be made on wildcard string).
- [Bugfix] Provides missing declaration for AssetType description function.
- [Refactor] Generalizes handling of paths in SceneDataset Configuration "paths" lists - now any file extension can be specified as a key, and an attempt to load assets with the given extension will be made in the provided path given as the value.
All c++ and python tests pass locally.
> [Bugfix/Refactor]--Some attributes fixes and improvements

- docs/pages/attributesJSON.rst
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/bindings/AttributesBindings.cpp
- src/esp/metadata/attributes/ObjectAttributes.cpp
- src/esp/metadata/attributes/ObjectAttributes.h
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/tests/AttributesConfigsTest.cpp
This PR introduces the ability to specify a frame to use for a semantic stage asset independent of the frame specified for the stage's render asset.  This is specifically needed for MP3D support, which has semantic plys that are orthogonal to the render glbs they correspond to.  Formerly, this was handled via hardcoded transforms, but these are incompatible with HM3D and other datasets with semantic meshes.
Locally c++ and python tests pass.  C++ attributes tests have been expanded to explicitly test this functionality.
> [Attributes]--Add semantic mesh orientation support

- src/utils/viewer/viewer.cpp
Modification to viewer.cpp to prevent it from saving useless ini file generated by imgui.ini related to 2d HUD text overlay.
> --Prevent viewer.cpp from saving uselss imgui.ini file

- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/physics/bullet/BulletArticulatedObject.h
- tests/test_physics.py
This function was previously only implemented for RigidObjects. Without this, it is not possible to turn off collisions for ArticulatedObjects programmatically (i.e., without modifying the URDF). 
The implementation in this PR only covers uniform override of all links. Individual link overrides should be added in a later PR.
Added a python test verifying group override.
> OverrideCollisionGroup for BulletArticulatedObject

- DATASETS.md
- src/esp/assets/GenericSemanticMeshData.cpp
- src/esp/assets/GenericSemanticMeshData.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/scene/SemanticScene.cpp
- src/tests/ReplicaSceneTest.cpp
- src/utils/datatool/SceneLoader.cpp
- src_python/habitat_sim/utils/datasets_download.py
- tests/test_sensors.py
This PR adds various functions and refactors required to implement support for HM3D semantic scenes in the correct format.  Included are : 
- Better vertex color handling in semantic mesh load
- More rigorous string verification for sentinel string denoting Semantic Scene Descriptor file type
- Proper application of frame re-orientation to Semantic Mesh data.  This is required to enable any semantic meshes to be re-oriented in engine.
- Force all semantic meshes to be treated as Instance Meshes (temporary so that vertex colors and vertex ids are supported).
Also, some refactors to improve efficiency and debug message content in Resource Manager are included.
Locally c++ and python tests
> [HM3D]--Semantic scene support/bugfixes.

- src_python/habitat_sim/robots/mobile_manipulator.py
- src_python/habitat_sim/utils/datasets_download.py
- Add hab2 benchmarking assets to downloader
- Use automatic joint limit clamping instead of manual for mobile_manipulators 
NA
> Minor updates to support hab2 benchmarking

- .circleci/config.yml
This PR restricts CI to use expected versions of mypy and hypothesis, since both have recently had changes which either [have bugs](https://github.com/python/mypy/issues/11853) or [dropped support for python 3.6](https://hypothesis.readthedocs.io/en/latest/changes.html#v6-32-0).  This PR restricts mypy to v0.910 and hypothesis to 6.29.3 (conda-available version that supports python 3.6).  
Locally all tests pass, and versions are available.
> [CI/Bugfix]--fix ci to use non-buggy mypy vers, hypothesis vers compat w/python 3.6

- src/esp/assets/ResourceManager.cpp
This PR fixes an issue with attempting to load an asset with multiple meshes assigned to the same MeshTransformNode.  A recent change to the loading mechanism ignored all subsequent meshes that were assigned to the same transform; this PR fixes this by assigning these subsequent meshes as children in the MeshTransformNode.  This is what was done originally in the Magnum Importer.
Locally; All c++ and python tests pass
> [Bugfix]--Appropriately handle multiple meshes being assigned to the same transform node.

- src/esp/metadata/MetadataMediator.h
- src/esp/sim/Simulator.h
- src/utils/viewer/viewer.cpp
This PR adds the following functionality to viewer to facilitate paging through scene datasets : 
- If only 1 scene instance exists, will page through existing stage-based scenes instead.  This is useful for datasets such as HM3D that do not have explicit scene instance json configurations but rather build them on the fly.
- Preserve render target binding through reconfigure.  This is useful when viewing depth or semantic scene views that the viewer might wish to continue viewing on subsequent scenes.
- Display the name of the currently displayed scene instance to the viewer's title bar
It's viewer! It Just Works (tested locally)
> --Expand Viewer scene paging functionality

- src/esp/assets/GenericSemanticMeshData.cpp
- src/esp/bindings/SceneBindings.cpp
- src/esp/scene/HM3DSemanticScene.cpp
- src/esp/scene/HM3DSemanticScene.h
- src/esp/scene/SemanticScene.h
This PR fixes how the Semantic Object ID is constructed for the HM3D dataset.  Previously, it was constructing the Semantic Object ID to be "<category>_<int idx within category>" (i.e. "wall_1") but this was incorrect - the current standard in engine is to have the final value of the Semantic Object ID be a unique int across all categories, corresponding to the Semantic ID in the Scene Node.  This PR fixes this.  
Locally c++ and python tests pass.
> [Bugfix]--Fix HM3D Semantic Object ID construction

- build.sh
- data/default.physics_config.json
- src/esp/assets/BaseMesh.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/sim/Simulator.h
In preparation for rewriting the asset load pipeline, I'm coming across some unused code in ResourceManager and the various mesh constructs, among other places.  This PR is for removing these methods, so that the pending asset load functionality PRs will retain their focus :) .  This PR also has a few minor refactors/cleanups that I've come across :
- Remove unused/unimplemented voxel function declaration from Simulator.h
- Make build script 'src_python' message a bit more relevant to the user
- Remove deprecated config field from default physics config
All local c++ and python tests pass
> [Refactor]--Cleaup;Remove unused field/methods.

- examples/viewer.py
- src/utils/viewer/viewer.cpp
This PR addresses a few minor bugs in viewer, where values that should have been mapped from constants were being mapped via magic numbers, or else not being mapped at all (such as the agent's dims if navmesh recalc is requested).
drawEvent functionality was also refactored to not recreate the Sensor Key string every frame when it only changed if sensorMode_ or visualizeMode_ changed.
It's Viewer! It Always Works!
> --Viewer : minor bugs; refactor drawEvent

- src/esp/assets/CMakeLists.txt
- src/esp/assets/ResourceManager.cpp
This PR adds new functionality where individual submesh transforms can be queried and applied on semantic mesh load before a compound mesh is flattened into a single mesh.  Previously, compound semantic meshes were aggregated without preserving their transformations.  This is particularly relevant with HM3D dataset semantic meshes that were annotated using mtl+obj source and have embedded transforms.
Locally c++ and python tests pass.
> --Flatten compound semantic scenes whilst preserving submesh transforms.

- examples/viewer.py
- src/esp/bindings/SimBindings.cpp
- src/esp/sim/Simulator.cpp
This small PR fixes 2 bugs : 
- Viewer.py : Update the locally maintained scene name to be the unique, minimal, name of the currently loaded scene. This is necessary if the user requested a scene by some non-unique substring of a scene name (in which case the first match would be the scene rendered)
- Do not build a navmesh on a joined collision mesh devoid of vertices.  **If this is attempted, the process will assert.** Reviewers, please share if you feel this is the appropriate response.
Locally all python and c++ tests pass
> --Bug fixes: Navmesh building and reconfigure in viewer.py

- .circleci/config.yml
- examples/settings.py
This PR fixes some CI issues:
- OSX conda build times out occasionally, failing CI. Increase the timeout duration to reduce incidence of this problem.
- Fix the pytest-cov version (3.0) to prevent issues caused by automatic fetch of an older version (2.5)
- Fix a python style nit from flake failing the python-lint test
CI
> Increase timeout for osx conda build 

- src/esp/assets/GenericSemanticMeshData.cpp
Minor bugfix to move .ply-file-based transformation of semantic mesh vertices to be before any vert-based calcs might occur so that transform is reflected in calculations.
Locally c++ and python tests
> [Bugfix]--Move .ply transform to before all potential vert-based calcs

- src/esp/physics/bullet/BulletArticulatedObject.cpp
Should be indexing positions by link index and torques/velocities by link DoF index as these vectors can have different sizes.
Tests pass CI, but should add another URDF to test this kind of mismatch in the future.
> [bugfix] - index torques by link DoF

- .gitmodules
- src/cmake/dependencies.cmake
- src/esp/assets/Mp3dInstanceMeshData.cpp
- src/esp/scene/ReplicaSemanticScene.cpp
- src/esp/scene/SemanticScene.cpp
- src/tests/ReplicaSceneTest.cpp
- src/utils/datatool/SceneLoader.cpp
- src/utils/viewer/viewer.cpp
This PR gets rid of a superfluous dependency, Sophus, which was accessed only in 1 place, building a Special Euclidean group transform (translate and rotate but no reflection) for Replica semantic object bounding boxes. The calc was easily replaced using Eigen Isometry transforms.  A test was added to ReplicaSceneTest to verify that the results using Isometries are approximately the same result as what Sophus was giving us.
> --Remove unused/superfluous dependency, Sophus

- src/esp/assets/GenericMeshData.cpp
- src/esp/geo/VoxelGrid.cpp
Updates Magnum deps to include shader-based semantic texture id processing.  Pending on final update :) 
locally c++ and python tests
> --update magnum deps for texture semantic shader support

- .circleci/config.yml
- .pre-commit-config.yaml
- BUILD_FROM_SOURCE.md
- README.md
- conda-build/Dockerfile
- conda-build/README.md
- conda-build/matrix_builder.py
- examples/tutorials/nb_python/ECCV_2020_Advanced_Features.py
- examples/tutorials/nb_python/ECCV_2020_Interactivity.py
- examples/tutorials/nb_python/ECCV_2020_Navigation.py
- examples/tutorials/nb_python/ReplicaCAD_quickstart.py
- examples/tutorials/nb_python/asset_viewer.py
- examples/tutorials/nb_python/managed_rigid_object_tutorial.py
- examples/tutorials/nb_python/replay_tutorial.py
- mypy.ini
- requirements.txt
- setup.py
- src/cmake/dependencies.cmake
- src_python/habitat_sim/robots/fetch_robot.py
- src_python/habitat_sim/robots/mobile_manipulator.py
- src_python/habitat_sim/simulator.py
- tests/test_physics.py
Python 3.6 is past end of life, time to upgrade.
CI
> Python 3.7 upgrade

- src/esp/assets/CMakeLists.txt
- src/utils/datatool/CMakeLists.txt
- src/utils/datatool/Datatool.cpp
- src/utils/datatool/Mp3dInstanceMeshData.cpp
- src/utils/datatool/Mp3dInstanceMeshData.h
This PR moves the Mp3dInstanceMeshData .h/.cpp files to the datatool directory, since Datatool is the only consumer of this class.  This was also done in preparation for the upcoming migration to Magnum Meshdata as part of the planned unification of the asset loading pathways for instance and general meshes.
> --Remove Mp3dInstanceMeshData from habitat-sim source

- src/esp/geo/OBB.cpp
This fixes 2 minor performance issues. 
1.  is that all std::vectors in this algorithm are of known sizes at runtime and should reserve the appropiate amount of heap space for their calculation
1. There is an std::vector that was being treated more as a tuple. I replaced it with an std::array since the size is known at compile time.
* PyTest and CI
> Fix performance issues with calc MOBB

- src/esp/assets/BaseMesh.cpp
- src/esp/assets/BaseMesh.h
- src/esp/assets/GenericSemanticMeshData.cpp
- src/esp/assets/GenericSemanticMeshData.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/bindings/SimBindings.cpp
- src/esp/scene/GibsonSemanticScene.cpp
- src/esp/scene/HM3DSemanticScene.cpp
- src/esp/scene/HM3DSemanticScene.h
- src/esp/scene/Mp3dSemanticScene.cpp
- src/esp/scene/SemanticScene.cpp
- src/esp/scene/SemanticScene.h
- src/esp/sim/Simulator.h
- src/tests/CMakeLists.txt
- src/tests/HM3DSceneTest.cpp
- src/utils/viewer/viewer.cpp
This PR is to provide semantic object OBBs for semantic scenes that have per-vertex annotations of either semantic ID or semantic Color. 
This PR also adds functionality to c++ viewer to visualize these bbs when semantic regions are clicked.
> --Vertex-based semantic annotation : Semantic object OBB gen

- requirements.txt
- src_python/habitat_sim/robots/mobile_manipulator.py
Reverts numpy version bump as this can cause some issues with Google Colab. Typing isn't worth hurting compatibility like that.
* Locally
> Revert numpy version bump

- src_python/habitat_sim/agent/controls/default_controls.py
Fixes bug that only allow constraints to be set in one direction of a singular axis
https://github.com/facebookresearch/habitat-sim/issues/1641
It is a bug fix, discussed in the issue linked above. We have applied it already to our local implementation of habitat_sim. 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.
- [ x ] I have completed my CLA (see **CONTRIBUTING**)
- [ x ] All new and existing tests passed.
> Fixes bug that only allow constraints to be set in one direction of a singular axis

- src/esp/physics/PhysicsManager.h
- src/esp/physics/RigidBase.h
- src/esp/physics/RigidObject.h
- src/esp/scene/HM3DSemanticScene.cpp
This bugfix addresses the rare case where HM3D annotation labels has commas embedded, so that they are loaded properly.
EDIT : unused includes were also removed.
> [Bugfix]--Support HM3D categories having commas between quotes

- src/esp/assets/GenericSemanticMeshData.h
- src/esp/assets/ResourceManager.h
- src/esp/scene/HM3DSemanticScene.cpp
- src/esp/sim/Simulator.h
- tests/test_semantic_scene.py
Minor bugfix to address bindings to colormap query not working properly.  Added python test to verify colormap is accessible through bindings.
> [Bugfix]-- Fix semantic color map binds (arrayView -> const ref)

- src/esp/assets/BaseMesh.cpp
- src/esp/assets/BaseMesh.h
- src/esp/assets/CMakeLists.txt
- src/esp/assets/GenericSemanticMeshData.cpp
- src/esp/assets/GenericSemanticMeshData.h
- src/esp/assets/ResourceManager.cpp
- src/esp/metadata/attributes/ObjectAttributes.cpp
- src/esp/metadata/attributes/ObjectAttributes.h
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/scene/HM3DSemanticScene.cpp
- src/esp/scene/ReplicaSemanticScene.cpp
- src/tests/AttributesConfigsTest.cpp
- src/tests/HM3DSceneTest.cpp
- src/tests/ReplicaSceneTest.cpp
- src/utils/datatool/SceneLoader.cpp
- src/utils/viewer/viewer.cpp
This PR fixes a bug/oversight in the creation of the Semantic Scene for HM3D dataset, where semantic ID 0 should have corresponded to an "Unknown" Object with black color.
This PR also lays some essential groundwork for the ongoing texture-based semantics effort by making GenericSemanticMeshData use Magnum vectors instead of Eigen and moving some essential color and id-based functionality to BaseMesh that might be shared amongst Semantic and Render mesh loading.  Also adds a stage attributes field denoting the semantic asset has annotated textures.
> [Bugfix]--Add "unknown" object corresponding to semantic ID 0 for HM3D; Refactors for Texture Semantics

- .circleci/config.yml
This should make it work with latest docutils, Pelican, Doxygen etc., not being so painful to install and use anymore; plus also various fixes to adapt to new pybind11 changes. A corresponding PR is being opened on the website repo as well: https://github.com/facebookmicrosites/habitat-website/pull/114
With two weeks of labour-intensive work, getting all dependencies to work again like they used to. Yay.
> Update m.css to latest

- src/esp/assets/Asset.cpp
- src/esp/assets/Asset.h
- src/esp/assets/BaseMesh.cpp
- src/esp/assets/GenericSemanticMeshData.cpp
- src/esp/assets/GenericSemanticMeshData.h
- src/esp/assets/RenderAssetInstanceCreationInfo.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/bindings/SimBindings.cpp
- src/esp/core/Esp.h
- src/esp/gfx/GenericDrawable.cpp
- src/esp/gfx/MaterialData.h
- src/esp/io/JsonEspTypes.h
- src/esp/metadata/attributes/ObjectAttributes.h
- src/esp/scene/HM3DSemanticScene.cpp
- src/esp/scene/HM3DSemanticScene.h
- src/esp/scene/SemanticScene.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/SimulatorConfiguration.cpp
- src/esp/sim/SimulatorConfiguration.h
- src/tests/ReplicaSceneTest.cpp
- src/utils/datatool/SceneLoader.cpp
- src/utils/viewer/viewer.cpp
This PR provides support for semantically annotated textures on meshes. Bounding boxes are still calculated using vertex annotations, but the actual semantic annotations are derived from textures.
To enable texture-based semantics both of the following settings must be set to true
- The dataset used must support texture semantic annotations (currently only HM3D) - the scene dataset config or stage config must have the field ` "has_semantic_textures": true`
- SimulatorConfiguration /sim_config has a field "use_semantic_textures" (in python) that needs to be set to true.
Loading of texture-based semantics is currently approx. 15-20% slower than loading the same scene for vertex annotation.  This primarily caused by the online conversion from semantic color textures to integer semantic id …
> --Semantic texture support

- src/esp/core/managedContainers/ManagedFileBasedContainer.h
A minor bugfix for when the scene directory is empty, should not consider the file name found.
All local c++ and python tests pass
> [Bugfix]--verify directory is not empty before using it to save attributes

- src_python/habitat_sim/utils/datasets_download.py
Adding a v1 of the data set for the pick task using the new data generator schema.
> Adding rearrange_pick_dataset_v1

- src/esp/assets/BaseMesh.cpp
- src/esp/assets/BaseMesh.h
- src/esp/assets/GenericSemanticMeshData.cpp
- src/esp/assets/GenericSemanticMeshData.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/bindings/GeoBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/core/Esp.h
- src/esp/geo/Geo.cpp
- src/esp/geo/Geo.h
- src/esp/geo/OBB.cpp
- src/esp/geo/OBB.h
- src/esp/scene/HM3DSemanticScene.cpp
- src/esp/scene/HM3DSemanticScene.h
- src/esp/scene/SemanticScene.cpp
- src/esp/scene/SemanticScene.h
- src/esp/sim/Simulator.h
- src/utils/viewer/viewer.cpp
This PR adds the following functionality : 
- Derive connected components on a set of vertices conditioned on some vertex attribute, such as color.  It finds all cc's that share the same vertex attribute value, finds the AABB of the resultant vertex cloud, and aggregates the results into a map keyed by semantic object IDX.
- Semantic BBoxes are being generated when needed (currently only in HM3D dataset) using CC with largest BBox (by volume) for a particular semantic annotation.
- Reporting tools are provided through viewer, including the ability to go through all the scenes in a dataset to derive and save the report to csv file.  A python binding is also provided to give access to this data.
All existing local c++ and python tests pass.
> [HM3D]--Connected Components Utility; CC-based Semantic BBox generation; Mesh connectivity reporting

- src/esp/assets/GenericSemanticMeshData.cpp
- src/esp/assets/GenericSemanticMeshData.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/bindings/SimBindings.cpp
- src/esp/geo/OBB.cpp
- src/esp/scene/HM3DSemanticScene.cpp
- src/esp/scene/SemanticScene.cpp
- src/esp/scene/SemanticScene.h
- src/esp/sim/Simulator.h
- src/utils/viewer/viewer.cpp
This PR will provide a reporting tool usable on semantic scenes (currently only HM3D) that have vertex-annotated colors and semantic scene descriptor file color-to-id mappings.  This report will list all the verts that have colors assigned in the mesh that are not present in the semantic scene descriptor, and all the semantic objects that have colors that are not found on the mesh.
This report can be synthesized via a viewer key bind and also using the python binding `sim.build_vertex_color_map_report()` after the scene is loaded.  This returns a list of strings containing the pertinent report data.
Locally via c++ and python tests
> --Semantic Vertex-Color-Semantic object mapping report capabilities.

- src/esp/assets/ResourceManager.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/utils/viewer/viewer.cpp
This will prevent viewer or bindings from calling the reporting and semantic CC calculation functionality if no semantic scene mesh exists.
> [Bugfix]--Verify that semantic scenes exist before reporting

- src/esp/assets/ResourceManager.cpp
Fixes texture transformation with flat materials. Was done for Phong but not for flat.
Once we port away from these custom structures and use Magnum's `MaterialData` everywhere, this kind of bugs will become *much* less likely.
Trust Me :tm:
> Properly use texture transformation matrix for flat materials as well.

- src/esp/sensor/RedwoodNoiseModel.cpp
- src/esp/sensor/RedwoodNoiseModel.cu
- src/esp/sensor/RedwoodNoiseModel.cuh
- src/esp/sensor/RedwoodNoiseModel.h
- src_python/habitat_sim/sensors/noise_models/redwood_depth_noise_model.py
- tests/test_noise_models.py
When matching the GPU to CPU implementation of the noise model, I copied over a bug from the CPU side.
This PR also fixes some other issues in the GPU implementation, like not writing the curand states back to global memory and gives each thread it's own state (that should have been done earlier, the CUDA docs are confusing on if they a thread safe or not but they aren't).
Closes #1455 
Via the test.
> Fix noise model

- DATASETS.md
- src_python/habitat_sim/utils/datasets_download.py
This PR updates the dataset download script to use HM3D semantics files with corrected directory structure. It also ensures that the HM3D semantics files are smoothly merged with the original HM3D files for ease of use. 
Note: The tests will not pass until the Matterport repo PR containing the new example files is merged into main. 
Tested locally
> HM3D Semantics v0.1 fixes

- examples/viewer.py
Needed a way to escape NavMesh islands in disconnected scenes.
Added a keypress `ALT`+`'n'` to resample position from the NavMesh and randomize orientation.
Locally
> viewer.py - agent state re-sampling with ALT+'n'

- src_python/habitat_sim/utils/datasets_download.py
Updates the default downloader version for ReplicaCAD to v1.4.
Changes with v1.4:
- NavMeshes recomputed for agent radius 0.3m (from default 0.1m) corresponding to Fetch robot base as used in Habitat 2.0 (default navmeshes also included in a separate folder for optional use)
- Minor furniture layout modifications to the following scenes in order to better accommodate robot access to the full set of receptacles for rearrange tasks:
- sc1_staging_02
- sc1_staging_05
- sc1_staging_12
- sc1_staging_03
- sc1_staging_06
- sc1_staging_09
- sc1_staging_10
- sc1_staging_13
- sc1_staging_16
- sc2_staging_00
- sc2_staging_07
- sc2_staging_09
- sc3_staging_03
- sc3_staging_05
- sc3_staging_11
- sc4_staging_08
- Fixed layout error with Fridge intersecting tv_stand in sc2_staging_20
- Minor furniture …
> ReplicaCAD v1.4

- .circleci/config.yml
Sometimes during conda builds (always recently), login will issue prior-login warning and wait for input stalling the build. We'll pass yes to automate this. 
Manually tested this solution for linux CI conda build blocking nightly via SSH.
I haven't tested for macos and don't know if this is necessary since that CI job has been blocked by linux. 
If it doesn't work for next nightly we can roll it back or address in CI SSH.
> Conda build pass yes

- .circleci/config.yml
The yes pipe working for linux is not working for osx as ci interprets the pipe return to terminate the job though it works in SSH.
Tested and working in CI on another branch.
> fix osx conda nightly

- src/esp/batched_sim/BatchedSimulator.cpp
Right now the actions are not normalized. This can cause issues: for example, the rotate action value needs to be between                -0.0873 and 0.0873 because of clamping. It is easier for the network to output values in the range [-1,1] and makes entropy easier to tune.
> normalizing the actions so that -1 and 1 become the limits

- src/esp/bindings/CoreBindings.cpp
- src/esp/core/Utility.h
- src/esp/sensor/VisualSensor.cpp
- src_python/habitat_sim/robots/mobile_manipulator.py
- src_python/habitat_sim/utils/common.py
When setting scene graph transformations, we need to explicitly normalize the rotation component to be orthonormal as sometimes floating point errors accumulate.
I also preemptively added an orthornomalize call when updating the camera positions for a robot as that seems like it'll be prone to this issue.
This was discovered in https://github.com/facebookresearch/habitat-lab/issues/697, so I used the repro script there.
> orthonormalize the rotationShear() part of transforms

- src/esp/core/Configuration.cpp
This addresses a memory leak in the ConfigValues where non-trivially constructible objects (like strings) were never getting properly disposed of.
Valgrind output before fix : 
`==22314== LEAK SUMMARY:
==22314==    definitely lost: 418,522 bytes in 4,963 blocks`
after fix : 
`==28380== LEAK SUMMARY:
==28380==    definitely lost: 13,544 bytes in 42 blocks`
Locally c++ and python tests pass, valgrind's mood definitely improved.
> [BUGFIX]--Address mem leak in ConfigValue destructor for strings.

- src/esp/bindings/ShortestPathBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/bindings_js/bindings_js.cpp
- src/esp/nav/PathFinder.cpp
- src/esp/nav/PathFinder.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/SimulatorConfiguration.cpp
- src/esp/sim/SimulatorConfiguration.h
- src/tests/PathFinderTest.cpp
- src_python/habitat_sim/simulator.py
- tests/test_navmesh.py
`simulator.py` `reconfigure()` automatically recomputes the NavMesh if `default_agent` has non-default parameters. Generally this makes sense because most of our saved NavMeshes are generated for the default agent. However, users may want to skip this if they've generated their own custom NavMeshes as in ReplicaCAD dataset for Hab2.0 rearrangement tasks.
~This PR primarily adds a new config option `recompute_navmesh_on_agent_params` which defaults to previous behavior, but if toggled off allows skipping automatic recomputation.~
Edit: This PR adds cache, query, and serialization of navmesh settings accompanying any programmatically computed or loaded NavMesh. Existing NavMeshes computed before this PR are assumed to use default settings. If agent params are different from cached settings …
> Make NavMesh recomputation for non-default agent params optional

- src/esp/assets/ResourceManager.cpp
Set the SceneNode bounding box for navmesh visualization nodes upon creation. Fixes incorrect culling on navmesh visualization causing navmesh wireframes to disappear for some camera positions.
locally in viewer
> [bugfix] - compute navmesh visualization node AABB

- tools/create_basis_compressed_glbs.py
Updates the create_basis_compressed_glbs tool from TinyglTF to CgltfImporter
Also screens some false positives in `finalize` function where files in the working directory were getting picked up for rename and may not actually exist.
locally used the tool
> Update create_basis_compressed_glbs tool to use CgltfImporter

- src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
- src/esp/metadata/managers/AttributesManagerBase.h
This PR promotes functionality for filename and wildcard handling to AttributesManagerBase from AbstractObjectAttributesManagerBase to open it up to non-object-related managers and the configs they manage.
All C++ and python tests pass locally
> --Move wildcard filename handling to AttributesManagerBase

- src/esp/metadata/attributes/SceneInstanceAttributes.cpp
- src/esp/metadata/attributes/SceneInstanceAttributes.h
- src/esp/metadata/managers/SceneInstanceAttributesManager.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/sim/Simulator.cpp
- src/tests/AttributesConfigsTest.cpp
This PR adds SceneObjectInstance support of non-uniform scaling.  Coupled with the existing online support of modifying scale via setting stage or object config attributes, non-uniform scaling capabilities can be provided to the user.  Note : this scaling is only available before instantiation - once an object is instantiated, the scale is set and unmodifiable (as is the existing paradigm for scale).
Please also see [this PR for an alternative, online approach to nonuniform scaling.](https://github.com/facebookresearch/habitat-sim/pull/1740)
Existing c++ and python tests pass.  C++ tests added to verify appropriate load from json and save to json file for new fields.
> --Rigid Object Instance Non-uniform scaling

- src/utils/viewer/viewer.cpp
Override light setups with `SimulatorConfiguration` requires `overrideSceneLightDefaults==true`. Viewer `--stage-requires-lighting` argument should therefore set both `overrideSceneLightDefaults` and `sceneLightSetupKey` to function.
locally w/ viewer and test assets.
`./build/viewer --recompute-navmesh --stage-requires-lighting -- data/test_assets/scenes/simple_room.glb`
> [bugfix] - viewer toggle lighting override with --stage-requires-lighting

- src/esp/bindings/ConfigBindings.cpp
- src/esp/core/Configuration.cpp
- src/esp/core/Configuration.h
- src/esp/io/JsonMagnumTypes.cpp
- src/esp/io/JsonMagnumTypes.h
- src/tests/CoreTest.cpp
- src/tests/IOTest.cpp
- tests/test_configs.py
This PR adds support for 3x3 float Magnum Matrices to the ConfigValue/Configuration subsystem.  This includes writing/reading json values, as well internally storing the data within a ConfigValue structure.
IOTest has also been streamlined somewhat, to make adding tests to validate json read/write for new types easier.
Locally c++ and python tests pass.  CoreTest and IOTest have been modified to test appropriate functionality.
> --Add ConfigValue support for Mn::Matrix3 (3x3 matrices of floats)

- src/esp/assets/Asset.cpp
- src/esp/assets/Asset.h
This PR adds missing fields in operator==() for AssetInfo.  Also added is a comparison operator for the esp::assets::PhongMaterialColor struct.
> [Bugfix]--add missing fields to AssetInfo comparator;

- src/esp/scene/ObjectControls.cpp
`moveUp` and `moveDown` actions (in C++) are used exclusively in the viewer application to raise and lower the agent camera. Current implementation uses camera local "up" translation. When the camera is pitched this results in moving the camera node off-axis, changing the axis of rotation. 
This PR changes moveUp and moveDown action to apply parent coordinate system +Y translation instead of local "up" so the camera always stays constrained to the agent's "up" axis.
If moving the camera off-axis is desirable it should be implemented as a separate action.
Local in viewer.
> [bugfix] - moveUp moveDown

- examples/tutorials/audio_agent.py
- src/esp/bindings/SensorBindings.cpp
- src_python/habitat_sim/__init__.py
- src_python/habitat_sim/bindings/__init__.py
- src_python/habitat_sim/sensor.py
* hsim_bindings is supposed to be a private API as indicated by the underscore. I guess it was used since one of the bindings wasn't properly exported under habitat_sim.sensor. I went ahead and added the missing exports and changed the tutorial accordingly.
> (bugfix): remove direct usage of hsim_bindings for audio and fix missing reexports

- .circleci/config.yml
- examples/viewer.py
This argument allows terminal override of stage lighting defaults to enable synthetic lighting for scenes which require it but may not be configured to use it automatically.
Locally with stage assets which crash when rendered with flat shader.
> Port stage_requires_lighting arg to python viewer

- examples/viewer.py
When choosing to skip navmesh recompute for none scene, need to handle cases where the "NONE" scene is not all upper case.
locally
> [bugfix] - viewer.py navmesh recompute skip for "none" scene

- src_python/habitat_sim/utils/viz_utils.py
New imageio version may have conflicting API. mypy asserts that `format` should be `Format` type, but should actually be string as written.
CI SSH and local
> [mypy] - ignore erroneous type warning in new imageio version.

- src/esp/bindings/EnumOperators.h
- src/esp/bindings/GfxBindings.cpp
- src/esp/bindings/PhysicsBindings.cpp
- src/esp/geo/VoxelUtils.cpp
- src/esp/gfx_batch/CMakeLists.txt
- src/esp/gfx_batch/Renderer.cpp
- src/tests/CMakeLists.txt
- src/tests/PhysicsTest.cpp
- src/utils/datatool/SceneLoader.cpp
Changes that aren't really related to the upcoming second batch renderer PR, thus submitting them separately.
Regular update of Magnum submodules:
- Adapting to a minor API deprecation (`BoolVector` -> `BitVector`, for consistency with new `BitArray` containers and because it's one character less to type)
- Using now-builtin `std::hash` specialization for `Containers::String`
- No other changes worth mentioning, the major piece of work done lately isn't published yet
And some minor fixes. For faster iterations I'm having a second build directory that uses a system-installed Magnum and has various features disabled, and various code rot prevented that from working:
- Various CMake updates that are needed if Magnum is external (and are no-op if it's a subproject)
- Making a build without …
> Update Magnum to latest & fix various minor buildsystem issues

- .circleci/config.yml
Public sim docs are built during the lab-build job, so updating the docs should wait until this phase is complete. This is already the case for version builds.
Re-running the failed update-doc job after everything else completed works. Failure was inability to find and copy the built doc directory.
> [CI] - Updating docs should wait until lab-build is complete

- src/cmake/dependencies.cmake
- src/tests/CMakeLists.txt
Just a regular boring dependency update ... with 20k+ lines of changes.
- [Interfaces for generic scene export](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1AbstractSceneConverter.html), including meshes, images, scene hierarchy, materials, lights etc. Not hooked up into the command-line tools *yet* so things like `magnum-sceneconverter gripper_link.dae gripper_link.gltf` aren't possible at the moment. But it's getting closer!
- Initial implementation of a [glTF export plugin](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1GltfSceneConverter.html), which is a prerequisite for the whole preprocessing pipeline in the batch renderer. Currently just (multi-)mesh export. Material, image and scene hierarchy export is in a branch and undergoing a final cleanup.
- …
> Update to Magnum with initial support for glTF export and CPU feature dispatch

- src/esp/gfx/GenericDrawable.cpp
- src/esp/gfx/replay/Recorder.cpp
- src/utils/viewer/viewer.cpp
* This is a minor optimization PR that removes some useless temporaries found through static analysis. 
* Locally and through CI
> chore: optimize src/esp by removing temporaries

- .circleci/config.yml
- conda-build/habitat-sim/meta.yaml
Nightly conda failing due to conflicting files during merge. Implement suggested change setting `preserve_egg_dir = True` seems to fix it.
Built and uploaded nightly CI from this PR branch.
> [CI] - fix nightly conda preserve_egg_dir

- examples/tutorials/colabs/ECCV_2020_Navigation.ipynb
- examples/tutorials/nb_python/ECCV_2020_Navigation.py
- src/esp/bindings/ShortestPathBindings.cpp
- src/esp/nav/PathFinder.h
Added more descriptive API docs for C++ and copied into python bindings for users wishing to customize NavMesh construction.
NA
> [docs] - better API documentation for NavMeshSettings

- src/esp/bindings/SensorBindings.cpp
While reviewing #1849 I noticed that we are doing some very inefficent things for modifying the attributes on the Python object. Mainly we are casting to a C++ object and then back again. Since we know the first argument will be an injected "self" argument, that it will be non-null, and it will manage it's own ownership we can just use a lightweight handle pointing to the underlying py::object. This means we don't have to do any casting and can just call the relevant C++ python API directly. 
Locally by running the test_sensors tests.
> Chore: Remove unnecessary casts from SensorSpec bindings

- src/utils/viewer/viewer.cpp
#1853 converted viewer.cpp to use Magnum text instead of imgui. Syntax for referencing variables in strings changed and one refactor was missed.
locally with viewer.cpp
> [bugfix] minor fix to viewer text string creation for semantic labels

- src/tests/GfxReplayTest.cpp
The `GfxReplayTest::testSimulatorIntegration` test is currently using the same simulator instance to record and play a playback file. This doesn't model real use cases and may hide issues.
This changeset refactors the test so that separate simulator instances record and play.
Tests are successful locally.
> Refactor GfxReplayTest::testSimulatorIntegration

- src/esp/sim/Simulator.cpp
Tiny performance bug in simulator.cpp relating to lighting setup. This removes an unnecessary extra copy.
* Locally
> (bugfix): Remove an extra tmp copy of lightsetup in Simulator.cpp

- docs/docs.rst
- examples/tutorials/colabs/ECCV_2020_Navigation.ipynb
- examples/tutorials/nb_python/ECCV_2020_Navigation.py
- src/esp/bindings/ShortestPathBindings.cpp
- src/esp/nav/PathFinder.cpp
- src/esp/nav/PathFinder.h
- tests/test_navmesh.py
Though the underlying C++ nav module has been computing islands on the back-end, we hadn't yet exposed island filtered queries for NavMesh operations.
This PR introduces new island operations:
- `get_island(point)` - get the island index closest to a point
- `island_area(index)` - get the area of a specific island by index
- `island_radius(point)` and `island_radius(index)` - get the radius heuristic for island size
- `num_islands` - property for number of islands on a NavMesh
and adds optional island specification to other operations:
- `get_random_navigable_point()` and `get_random_navigable_point_near()` - now can query a specific island by index
- `snap_point()` - now can snap to a specified island
- `build_navmesh_vertices()` - can get vertex buffer for a specific island
- …
> Add islands to NavMesh API

- src/esp/core/Configuration.h
- src/esp/geo/VoxelGrid.cpp
- src/esp/geo/VoxelGrid.h
- src/esp/metadata/managers/AssetAttributesManager.cpp
- src/esp/metadata/managers/AttributesManagerBase.h
- src/esp/metadata/managers/ObjectAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/scene/HM3DSemanticScene.cpp
- src/esp/scene/SemanticScene.cpp
* When I was reviewing @jturner65's PR, I noticed a series of strings that were being copied into their std::set. This explicitly moves them when inserting them into the set instead which should prevent an unnecessary copy.
Locally
> (bugfix): Prevent unnecessary copies with more std::move and emplace

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/gfx/replay/Keyframe.h
- src/esp/gfx/replay/Player.cpp
- src/esp/gfx/replay/Player.h
- src/esp/gfx/replay/Recorder.cpp
- src/esp/gfx/replay/Recorder.h
- src/esp/gfx/replay/ReplayManager.cpp
- src/esp/gfx/replay/ReplayManager.h
- src/esp/io/JsonEspTypes.cpp
- src/esp/io/JsonEspTypes.h
- src/esp/io/JsonMagnumTypes.h
- src/esp/io/JsonStlTypes.h
- src/esp/metadata/attributes/AttributesEnumMaps.cpp
- src/esp/sim/Simulator.cpp
- src/tests/GfxReplayTest.cpp
This changeset adds light serialization to the gfx-replay format.
Lights are serialized incrementally - they are only written to the json file when lighting changes occur. We assume that the keyframes are always read sequentially.
<details><summary>`GfxReplayTest::testLightIntegration` Replay File</summary>
```json
{
"keyframes": [
{
"lightsChanged": true,
"lights": [
{
"vector": [
1.5,
2.0,
2.5,
1.0
],
"color": [
1.5,
2.0,
5.0
],
"model": "global"
},
{
"vector": [
-10.0,
4.25,
10.0,
1.0
],
"color": [
5.0,
5.0,
0.0
],
"model": "camera"
}
]
},
{
"lightsChanged": true,
"lights": [
{
"vector": [
0.0,
1.2,
-4.0,
1.0
],
"color": [
4.0,
4.0,
4.0
],
"model": "object"
}
]
},
{},
{
"lightsChanged": true,
"lights": [
{
"vector": [
0.1,
0.2,
-0.3,
0.0
],
"color": [
0.0,
0.0,
1.0
],
"model": "global" …
```
> Serialize lights into gfx-replay json format.

- .gitignore
- src/cmake/dependencies.cmake
PR #1861 switched from GLX/EGL to unconditionally using EGL on Linux-y platforms. Which is a good thing to have in general, but there might still be cases where EGL might be broken, and for these it should be possible to switch back to something that works.
That has to be done manually by turning `MAGNUM_TARGET_EGL` to `OFF` in `dependencies.cmake`, and this PR makes necessary buildsystem fixes to make the code compile again. The default EGL workflow is not affected by these changes in any way.
Also contains a vaguely-related update for `.gitignore`.
Locally by setting the CMake option, running `ninja` and executing a few tests.
> Allow GLX to still be used if EGL doesn't work for whatever reason

- src_python/habitat_sim/utils/__init__.py
When importing from outside of habitat-sim, settings module was not available from utils.
> python - Add settings module to utils init

- .circleci/config.yml
- examples/colab_utils/colab_install.sh
With the baselines/lab split from [PR 922](https://github.com/facebookresearch/habitat-lab/pull/922), requirements.txt was moved. This PR updates install paths for sim testing and colab install pipelines.
Addresses #1884 and should fix broken lab test.
Here
> [bugfix] Support habitat-lab requirements.txt after split

- docs/Doxyfile
- docs/Doxyfile-mcss
- docs/README.md
- docs/theme.css
Sorry for opening too many PRs lately :D I was in the process of writing high-level docs for the batch renderer in #1874, submitted #1889 for doc updates already, but then wanted to put some note blocks into the doc copy, realized they look kinda awful, and had to fix those too. Before:
After:
The "warning" note was good enough already, but apparently those two were never used so far so they still had the dark theme colors. I didn't spend time updating the remaining color styles for "primary" and "danger" as I don't need them at the moment, and this was enough of a detour already :sweat_smile: Same for #1812, originally I wanted to merge those changes with mine, but the font and spacing changes felt like a lot more time investment would be needed to get things look consistent again, so I …
> Better colors for "info" and "success" notes in the documentation and website

- .circleci/config.yml
Builds on `main` are getting a lot of these errors due to the coverage being collected after the Audio build (originating from https://github.com/facebookresearch/habitat-sim/pull/1646), losing the coverage collected earlier:
> libgcov profiling error:/home/circleci/project/habitat-sim/build/esp/bindings/CMakeFiles/habitat_sim_bindings.dir/Bindings.cpp.gcda:overwriting an existing profile data with a different timestamp
With this change the coverage is back at 60% (from 40%), and still includes also everything from the Audio build.
The better long-term solution, however, would be like something in https://github.com/facebookresearch/habitat-sim/pull/1860 -- this unnecessarily duplicates a lot of the CI setup code. (@Skylion007 or anybody else who knows YAML or CircleCI, do you know if …
> Temporarily work around lost code coverage reports

- src_python/habitat_sim/agent/agent.py
> Better check of type before converting vector to quaternion

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/gfx/GenericDrawable.cpp
- Enables shader texture transform only if it's actually textured. If it's not (for example if a texture failed to load or if the material data are strange in some way), then the shader construction would assert with
Shaders::PhongGL: texture transformation enabled but the shader is not textured
This change *doesn't* fix any root causes of a texture missing or failing to load, it only makes it not abort anymore. ~~Also removed a now-irrelevant TODO and a branch in flat material data setup -- that check should have been done in the shader setup code in the first place anyway, which is how it's done now.~~ The TODO was about a different thing, reverted that back.
- Fixed a crash if the `BasisImporter` plugin wouldn't be present for whatever reason. (I disabled it in order to be able to test …
> Assorted fixes for more robust handling of asset corner cases

- src_python/habitat_sim/utils/datasets_download.py
Follow-up to #1910 which updated paths for HM3D Semantics v0.2.
As pointed out by @srama2512, some download paths were changed for HM3D's annotated v0.2 scenes which were not correctly updated in the previous PR.
Primary changes:
- correctly reference v0.2 of non-semantic HM3D. 
- remove obj+mtl from habitat downloader (these were not updated with v0.2 and have no reason to be connected to Habitat).
- clean up uid tags to no longer reference version (like all other data-sources)
Local testing in progress.
> Cleanup dataset_downloader for HM3D v0.2 

- src/esp/assets/ResourceManager.cpp
- src/esp/core/managedContainers/ManagedContainer.h
- src/esp/core/managedContainers/ManagedFileBasedContainer.h
- src/esp/io/Json.h
- src/esp/metadata/attributes/LightLayoutAttributes.cpp
- src/esp/metadata/attributes/SceneInstanceAttributes.cpp
- src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
- src/esp/metadata/managers/AssetAttributesManager.cpp
- src/esp/metadata/managers/LightLayoutAttributesManager.cpp
- src/esp/metadata/managers/ObjectAttributesManager.cpp
- src/esp/metadata/managers/PhysicsAttributesManager.h
- src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
- src/esp/metadata/managers/SceneInstanceAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/nav/PathFinder.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/bullet/BulletCollisionHelper.cpp
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/objectManagers/PhysicsObjectBaseManager.h
- src/esp/sim/Simulator.cpp
* I found a new clang-tidy check in that is being proposed and decided to give it an early try. I went through all the fixes manually and removed any false positives. This should get rid of of most of the unnecessary copies left in the codebase.
* Locally and with Clang-Tidy
> (perf): Improve codebase by adding std::move on last use of object

- src/esp/assets/ResourceManager.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidStage.cpp
- src/utils/viewer/viewer.cpp
Instead just skipping them. See [this Slack thread](https://cvmlp.slack.com/archives/CFN5TAUSD/p1663176292006099) for background info.
As this makes the `isMeshPrimitiveValid()` check obsolete, I removed the whole implementation of it (which, after all, was just a very verbose way to print the mesh primitive name originating back in the days when Habitat used glog and thus couldn't just call [Magnum's builtin output operator for MeshPrimitive](https://doc.magnum.graphics/magnum/namespaceMagnum_1_1Vk.html#a7a3593c8ac0af192feba9eae70e2d62d)). Furthermore, a call to this function was also the only reason why `addStage()` too the collision mesh group parameter, so I removed it from there as well. Which is a documentation TODO: 
The check is now moved to inside …
> Don't give up when encountering lines/points/... in collision mesh data

- docs/docs.rst
- src_python/habitat_sim/utils/settings.py
Added some documentation for settings utility module.
Local rendering:
> [docs] - utils.settings.py

- src/esp/assets/ResourceManager.cpp
@mosra fixed a bug with non-triangle primitive support in #1888. This worked for physics, but was not being applied to navmesh recomputation resulting in artifacts for affected scenes. See [comments ](https://github.com/facebookresearch/habitat-sim/pull/1888#issuecomment-1312803701)for details. 
Locally with FP scene 102816627.
> [bugfix] - skip non-triangle mesh primitives in mesh join for navmesh recomputation

- .circleci/config.yml
- src_python/habitat_sim/utils/datasets_download.py
For some reason habitat-lab caching was broken resulting in a stale commit failing tests. For now we'll not cache while we figure out the issue.
Note: also adds hab_stretch to ci_test_assets as required by new lab tests.
CI is passing again.
> [ci] - Don't cache habitat-lab

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/gfx/replay/ReplayManager.h
- src/esp/physics/objectWrappers/ManagedPhysicsObjectBase.h
* This prevents some unnecessary atomic increments and decrements of a shared pointer. We only ever appear to pass the shared pointer by value anyway so this should be more efficient. The previous version of the code always performed a copy.
> chore: Add a few missing std::move to shared_ptr. 

- src/esp/gfx/RenderTarget.cpp
- src/esp/gfx/RenderTarget.h
- src/esp/gfx_batch/Renderer.cpp
- src/esp/gfx_batch/Renderer.h
- src/esp/gfx_batch/RendererStandalone.cpp
- src/esp/gfx_batch/RendererStandalone.h
- src/esp/sensor/CameraSensor.cpp
- src/esp/sensor/CameraSensor.h
- src/tests/GfxBatchRendererTest.cpp
Contains various minor updates and fixes that *don't* depend on changes from #1947, thus hopefully possible to be reviewed & merged in isolation:
- Ability to bake-in an initial transformation for added hierarchy (i.e., without it being overwritten next time the hierarchy transform is updated). Will be used for specifying initial scale and coordinate frame correction and should fix 99.7% of nasty transformation bugs I had in the initial gfx-replay demo screenshots in September.
- Opt-in flag to generate texture mipmaps. This is something that Vulkan will not give us for free in the driver (and so the assets will need to contain full mip pyramids themselves), so it's not enabled by default, but it's currently used to have a pixel-perfect match with the classic renderer.
- Adds a more …
> Assorted updates to the batch renderer

- src/cmake/FindCorrade.cmake
- src/cmake/FindMagnum.cmake
- src/cmake/FindMagnumPlugins.cmake
- src/cmake/dependencies.cmake
- src/esp/gfx/DebugLineRender.h
- src/esp/gfx/GenericDrawable.cpp
- src/esp/gfx_batch/Renderer.cpp
- src/utils/viewer/ObjectPickingHelper.h
Upgrades Magnum to latest, containing the following:
- builtin [joint ID and weight mesh attributes](https://doc.magnum.graphics/magnum/namespaceMagnum_1_1Trade.html#a8a0ec4599a941c8f155bd76efc765808adcce9dc2baf9b04769cf83ecac3fd081), including support in [MeshTools::compile()](https://doc.magnum.graphics/magnum/namespaceMagnum_1_1MeshTools.html#ad49a02705028736a719136dbcfe5697c)
- skinning support in the [PhongGL](https://doc.magnum.graphics/magnum/classMagnum_1_1Shaders_1_1PhongGL.html#Shaders-PhongGL-skinning), [FlatGL](https://doc.magnum.graphics/magnum/classMagnum_1_1Shaders_1_1FlatGL.html#Shaders-FlatGL-skinning) and [MeshVisualizerGL](https://doc.magnum.graphics/magnum/classMagnum_1_1Shaders_1_1MeshVisualizerGL3D.html#Shaders-MeshVisualizerGL3D-skinning) shaders, including …
> Update to latest Magnum with full skinning support and much more

- src/esp/assets/ResourceManager.cpp
- src/esp/gfx/replay/Player.cpp
- src/esp/gfx/replay/Recorder.cpp
- src/esp/gfx/replay/Recorder.h
- src/esp/scene/SceneManager.h
- src/esp/sim/Simulator.cpp
When the simulator changes scene, the previous scene graph is not deleted. Because `Recorder` relies on scene node deletion to issue deletion entries to gfx-replay, the previous scene is not cleared from the replay renderer.
This changeset adds a method to delete all gfx-replay nodes within a scene graph so that the replay renderer can correctly render process scene changes.
Tested through Python viewer.
> gfx-replay: Record scene graph deletions.

- .circleci/config.yml
The latest Miniconda installer (22.11.1) fails to work with sh.
This changes the invocation of `miniconda.sh` to bash.
Tested through CI.
> Fix Miniconda installation on CI.

- src/esp/gfx/replay/Player.cpp
The batch renderer currently cannot delete individual instances. Because of this, it quickly reaches internal limits when repeatedly changing scenes. The batch renderer can however delete all instances at once.
This changeset clears the frame when the player detects that the applied keyframe is deleting all instances.
This implementation is preferred to an explicit `clearFrame` keyframe flag as it doesn't force the implementer (blender script, etc) to delete its instances in a specific way. However, it cannot detect leaking instances from a misused recorder.
Tested in python viewer by repeatedly changing scenes.
> Clear replay renderer when all instances are deleted.

- .pre-commit-config.yaml
This pins `toml-sort` to a specific version to fix a pre-commit CI issue.
The same fix was applied to lab here: https://github.com/facebookresearch/habitat-lab/pull/1063
Tested on CI.
> Pin toml-sort version to fix pre-commit issue on CI.

- src/tests/PathFinderTest.cpp
The current PathfinderTest.cpp is writing a test file to disk to validate file read ability. This PR removes that file after the test is complete.
> --Minor fix to remove file being written by test

- src/esp/bindings/SimBindings.cpp
- src/esp/sim/AbstractReplayRenderer.cpp
- src/esp/sim/AbstractReplayRenderer.h
- src/esp/sim/BatchReplayRenderer.cpp
- src/esp/sim/BatchReplayRenderer.h
- src/esp/sim/ClassicReplayRenderer.cpp
- src/esp/sim/ClassicReplayRenderer.h
- src/tests/BatchReplayRendererTest.cpp
This adds replay renderer bindings to get CUDA device pointers from Python.
Device pointers are tested in `BatchReplayRendererTest`.
> Add replay renderer bindings to get CUDA device pointers.

- src/esp/bindings/ShortestPathBindings.cpp
- src/esp/nav/PathFinder.cpp
- src/esp/nav/PathFinder.h
Currently, if any of the requested_end points don't snap to the navmesh, `MultiGoalShortestPath` will early abort and return `inf` distance.
Expected behavior: if *any* of the points in `requested_ends` are valid, the shortest path should be computed accurately.
Additional feature: adds `closest_end_point_index` to `MultiGoalShortestPath` struct API. Makes it easier to know which point form the input set was actually selected as closets. Corresponds to the end of the `path`.
TODO:
May need to update tests to check these edge cases:
- all points off navmesh
- some points off navmesh
- all points on other island
- all point son other island or off navmesh
- [x ] I have read the **CONTRIBUTING** document.
> MultiGoalShortestPath improvements

- src/esp/metadata/attributes/ObjectAttributes.cpp
Current default is to join all collision shapes into a single convex unless explicitly configured otherwise. This is an outdated stability consideration from a buggier time and should no longer be the default.
locally
> don't default to joined collision objects

- src_python/habitat_sim/utils/datasets_download.py
The PR updates Spot mesh appearance. The previous PR uses the factory default color: https://github.com/facebookresearch/habitat-sim/commit/58921deb970177aa312beda4518a137473202ace
interactive_play.py can load Spot robot correctly.
> update Spot mesh

- src/esp/physics/bullet/BulletPhysicsManager.cpp
- tests/test_physics.py
`RayHitInfo.rayDistance` should be in units of ray length. In other words, `rayDistance==1` indicates a world distance of `length(ray.direction)`. The hit fraction from Bullet is already scaled this way, so additional scaling is not necessary, but was being done erroneously.
Because no tests or downstream code had the audacity to use non-unit ray directions, this bug was not caught until now.
Added a test.
> [bugfix] - ray distance scaling

- src_python/habitat_sim/utils/viz_utils.py
If there are more islands than pre-set colors we should invent some new ones to avoid overflow.
Also fixes a bug with the images being reflected because PIL corrdinate system is +Y downwards with origin in the top left.
Locally with large disjoint navmeshes.
> [bugfix] - color overflow in get_island_colored_map

- src/esp/gfx_batch/Renderer.cpp
- src/tests/GfxBatchRendererTest.cpp
This replaces an assertion that prevents drawing empty scenes by an early-out.
Tested locally and via unit test.
> Allow the batch renderer to draw empty scenes.

- src/esp/bindings/SimBindings.cpp
This adds a missing replay renderer python binding to transfer sensor output into CPU images.
Note that this function only works for _one color sensor_. This will be revisited as we integrate multiple sensors into the batch renderer.
Tested manually in Python from Habitat-Lab.
> Add python binding to render color sensors into CPU images.

- tests/test_semantic_scene.py
- tests/test_sensors.py
This fixes two flake8 errors that surfaced after a dependency upgrade.
Tested on CI.
> [CI Fix] Fix flake8 errors.

- src/esp/gfx_batch/Renderer.h
- src/esp/gfx_batch/RendererStandalone.cpp
- src/esp/gfx_batch/RendererStandalone.h
- src/tests/BatchReplayRendererTest.cpp
This fixes `RendererStandalone` leaking its context.
Tested on Habitat-Lab and updated replay batch renderer test.
> Fix standalone batch renderer context deletion.

- .gitignore
- docs/pages/attributesJSON.rst
- src/esp/bindings/ConfigBindings.cpp
- src/esp/core/Configuration.cpp
- src/esp/core/Configuration.h
- src/esp/io/JsonMagnumTypes.cpp
- src/esp/io/JsonMagnumTypes.h
- src/esp/metadata/attributes/ObjectAttributes.cpp
- src/esp/metadata/attributes/PhysicsManagerAttributes.h
- src/esp/metadata/attributes/SceneInstanceAttributes.cpp
- src/esp/metadata/attributes/SceneInstanceAttributes.h
- src/esp/metadata/managers/AttributesManagerBase.h
- src/esp/metadata/managers/SceneInstanceAttributesManager.cpp
- src/esp/physics/PhysicsManager.cpp
- src/tests/AttributesConfigsTest.cpp
- src/tests/IOTest.cpp
- tests/test_configs.py
This PR adds Configuration support for Magnum Vector4.  With regard to the user_defined attributes, the type for equivalently sized fields in JSON is determined by substring tags found in the numeric fields' labels -  'orient', 'quat', or 'rotat' will denote a quaternion for a size 4 numeric field, and otherwise the size 4 fields will be Magnum vector4 's.
These are some features that I worked on some before my last contract ended and felt would be useful to add now.
NOTE : I removed Explicit Color3 and Color4 since these were superfluous, but I retrained accessors that would treat Color3 and Color4 getter requests the same as Vector3 and Vector4 respectively.
NOTE : I also added support of user-defined attributes containing a list of variable length of strings, which was already …
> --Configuration support for Magnum Vector2, Vector4, Color3 and Color4, UserDefinedAttr support of str Lists

- src/esp/metadata/attributes/SceneDatasetAttributes.h
A logic bug here was causing dereference of a past-the-end iterator (`artObjPathIter->second`), causing this log statement to print garbage text.
Local testing.
> bugfix for setArticulatedObjectModelFilename causing garbage log output

- src/esp/bindings/GfxReplayBindings.cpp
- src/esp/gfx/replay/Player.cpp
- src/esp/gfx/replay/Recorder.cpp
- src/esp/gfx/replay/Recorder.h
- src/esp/sim/BatchReplayRenderer.cpp
Some polish needed to get the batch renderer working in a new Python application.
Ran it locally.
> Gfx-replay polish: workaround for material-overrides; new keyframe getter

- .pre-commit-config.yaml
Apparently pre-commit 's default behavior is to install node as part of the prep process.  This PR tells pre-commit to use the system version of node if it exists.  (This was causing a problem on Ubuntu 18.04 since the installed version of node was requiring glibc 2.28 and 18.04 uses 2.27.)
Pre-commit now works properly on 18.04
> --Have pre-commit use node version compatible with Ubuntu 18.04

- examples/viewer.py
Upon initializing the python viewer, the framebuffer size may differ from the application config size due to environment factors.
This change ensures that the appropriate size is used for rendering.
Fixes: #2049
> Fix viewer.py framebuffer size mismatch.

- src/esp/bindings/SimBindings.cpp
- src/esp/gfx/DebugLineRender.cpp
- src/esp/gfx/DebugLineRender.h
- src/esp/sim/AbstractReplayRenderer.cpp
- src/esp/sim/AbstractReplayRenderer.h
- src/esp/sim/BatchReplayRenderer.cpp
- src/esp/sim/BatchReplayRenderer.h
- src/esp/sim/ClassicReplayRenderer.cpp
- src/esp/sim/ClassicReplayRenderer.h
- src/tests/BatchReplayRendererTest.cpp
Adding some features (and hacks) to our experimental replay renderers, needed for a Python application for SIRo.
* integrate DebugLineRender into replay renderers
* add ClassicReplayRenderer.unproject
* stub implementation for BatchReplayRenderer.unproject
* lighting hack in ClassicReplayRenderer to get ReplicaCAD stages to render correctly
Local testing.
> Replay renderer: add line-rendering and unproject()

- src/esp/physics/bullet/BulletRigidObject.cpp
Using a modified primitive cylinder shape as a collision asset resulted in erroneous collision shape because constructor ignored configured half-length.
Locally. Isn't CI tested. :thinking: 
TODO: Could be tested by comparing render and collision bounding boxes for these edge cases.
Example:
```
def construct_cylinder_object(
sim: Simulator,
cyl_radius: float = 0.04,
cyl_height: float = 0.15,
):
constructed_cyl_obj_handle = f"cylinder_test_obj_r{cyl_radius}_h{cyl_height}"
otm = sim.metadata_mediator.object_template_manager
if not otm.get_library_has_handle(constructed_cyl_obj_handle):
atm = sim.metadata_mediator.asset_template_manager
half_length = (cyl_height / 2.0) / cyl_radius
custom_prim_name = f"cylinderSolid_rings_1_segments_12_halfLen_{half_length}_useTexCoords_false_useTangents_fal …
```
> [bugfix]: cylinder primitive collision shape did not use halflength

- src/tests/SimTest.cpp
Currently the tests in simtest are instanced in such a way that they are each executed 2 times, once with a direct simulator creation, and once with a simulator created with a pre-existing metadata mediator, using Magnum's instanced testing protocols.  [This PR (#1308)](https://github.com/facebookresearch/habitat-sim/pull/1308) added support and testing for creating simulator without a renderer. 
The test that was added (createMagnumRenderingOff) did not follow the existing protocol for creating sims (calling the appropriate array of function pointers), but instead directly built it within the test's body. Due to this, the same test of the same functionality is being executed twice.
This PR makes the createMagnumRenderingOff test a regular test, and not an instanced one, so that it is …
> --[BugFix]Testing disabled renderer in simtest should only happen 1 time

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/bindings/SimBindings.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/tests/SimTest.cpp
`Simulator.get_runtime_perf_stat_names` and `get_runtime_perf_stat_values` together are a flexible way to report a large number of arbitrary named scalars to Python. For now, I focus on some physics counts and Drawable counts.
I opted for separate `get...names` and `get...values` so that we can just call `get...values` on every env step and avoid the cost of creating/passing strings every step.
Unit test added to SimTest.cpp
> Add runtime perf stats for troubleshooting perf problems

- src/esp/assets/ResourceManager.cpp
A Magnum function that we were using to flatten transformations in semantic meshes was deprecated and replaced with one with a slightly different API.  This PR addresses this, replacing the deprecated function and updating the code appropriately; also, a global transformation is now being applied more efficiently, as the flatten transformations are being built.
All existing tests pass.
> --Refactor Semantic Mesh loading/flattening to remove deprecated functionality and improve efficiency 

- src/esp/bindings/MetadataMediatorBindings.cpp
- src/esp/metadata/MetadataMediator.cpp
- src/esp/metadata/MetadataMediator.h
This PR adds access to the user-defined attributes for the scene instance corresponding to the passed name.  If one does not exist, it returns nullptr.
Current Tests pass.  Additional tests would probably be helpful.
> --Add access to Scene Instance-level user defined attributes.

- src/esp/metadata/MetadataMediator.cpp
- src/tests/AttributesConfigsTest.cpp
[This PR](https://github.com/facebookresearch/habitat-sim/pull/2081) added user defined attributes retrieval for scene instance attributes. Unfortunately, in the process it made an unnecessary copy of the existing scene instance attributes.  This PR accesses the existing scene instance without making the copy.  A test was also added to verify that the user attributes retrieved are as expected.
Locally existing and added C++ and existing python tests.
> --Don't make needless copy of scene instance attributes when retrieving user defined values

- src/esp/gfx/replay/Recorder.cpp
This avoids a fatal error where `fromMatrix` fails because the input matrix includes a reflection (negative scaling), which a quaternion rotation can't represent.
Notice the todo in the code. I'm still investigating and I may update this PR before merging.
Local testing with Floorplanner assets, some of which (apparently) have this reflection built-in.
- [ x I have completed my CLA (see **CONTRIBUTING**)
> Fix to remove reflection for gfx-replay recording

- data/test_assets/urdf/skinned_prism.ao_config.json
- src/esp/io/URDFParser.cpp
- src/esp/io/URDFParser.h
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/physics/bullet/BulletArticulatedObject.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/tests/SimTest.cpp
This changeset adds support for semantic rendering of skinned articulated objects.
The semantic ID of an articulated object can be defined in the corresponding `ao_config.json` file as such:
```
{
"render_asset": "human.glb",
"semantic_id": 100
}
```
The identifiers can be specified in a semantic map, e.g. `object_semantic_id_mapping.json` as such:
```
{
<...>
"table": 98,
"plant": 99,
"human": 100,
<...>
}
```
Tested locally and in `SimTest::testArticulatedObjectSkinned`.
> Articulated object semantics

- src/esp/gfx/GenericDrawable.cpp
- src/esp/gfx/PbrDrawable.cpp
- src/esp/gfx/PbrShader.h
[This PR introduced](https://github.com/facebookresearch/habitat-sim/pull/2083) syntactically incorrect bitflag checks to the drawables to determine how to handle vertex-level and texture level semantic ids; furthermore, an important check was being performed incorrectly for the PBR shader to support vertex-based Object IDs or not.  This PR fixes #2087 
Locally tests pass.
> --Address inappropriate bitflag check; add vertexID flag to PBR shader

- src/esp/sim/ClassicReplayRenderer.cpp
Bugfix (no good reason to ever disable frustum culling)
Local testing on 2019 Macbook Pro
> enable frustum-culling for classic replay renderer

- src_python/habitat_sim/simulator.py
The navmesh is needed for blind agents, batch rendering, and other use cases where the sim is created with `create_renderer==false`.
Note a potential source of confusion: when `create_renderer==false`, we don't load textures, upload mesh vertices to the GPU, or create "GL meshes". However, we still load mesh data from disk, so we can still generate a navmesh on the CPU.
Local testing on 2019 Macbook Pro
> enable recompute_navmesh when creating sim with create_renderer==false

- examples/tutorials/lighting_tutorial.py
- src/esp/gfx/GenericDrawable.cpp
- src/esp/gfx/LightSetup.cpp
- src/esp/gfx/PbrDrawable.cpp
- src/esp/gfx/PbrShader.cpp
- src/esp/metadata/managers/LightLayoutAttributesManager.cpp
- src/tests/GfxReplayTest.cpp
- src/tests/SimTest.cpp
- src/utils/viewer/default_light_override.lighting_config.json
A long standing issue/bug with Habitat is that our directional lights have always been backwards - pointing away from the direction they are intended to be pointing toward.  This PR fixes this issue, without removing the performance benefit the backwards direction gave (in the phong and pbr shaders).  
The existing light setups using directional lights have been corrected in this PR, but any datasets that provide directional lighting will need to have those lights reversed, so this should probably be considered a breaking change.
> --[BUGFIX] Reverse directional lights before sending to uniform;

- src/esp/assets/ResourceManager.cpp
We were not handling single channel textures, causing them to display red.  This PR addresses this - any single channel textures get their swizzle modified to pull RGB from the R channel.  This currently is not supported in magnum for WebGL builds, so a warning is displayed instead.
C++ and python Tests pass locally
> --[BUGFIX] Single channel texture support

- examples/viewer.py
- src/esp/bindings/PhysicsWrapperManagerBindings.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/physics/objectManagers/ArticulatedObjectManager.cpp
- src/esp/physics/objectManagers/ArticulatedObjectManager.h
As discussed in issue #2095 some URDF files behave poorly when inertia is computed automatically from collision shapes. This PR adds the API option to parse inertia matrices directly from the URDF file instead.
Also the viewer URDF loader now creates JointMotors by default.
In the viewer app (as shown in the linked issue)
> Add intertiaFromURDF option to URDF loading API

- .circleci/config.yml
- requirements.txt
Following the example of Habitat-lab [1319](https://github.com/facebookresearch/habitat-lab/pull/1319). Should make it easier to find and debug dependency related CI issues without impacting development turn-around. Nightly or the first CI job each day will re-cache.
Also specifies numpy version to avoid new CI bug that has emerged with new version.
Here
> [CI] - Add daily re-caching and log dependency state for pip and conda

- src/cmake/dependencies.cmake
Python importer used in Habitat-lab requires linked Magnum plugins from Habitat=sim.
NA
> additional magnum importer plugins in python build dependencies

- src/esp/bindings/SimBindings.cpp
This PR adds a python binding to the simulatorConfig field that enables/disables image based lighting in the PBR shader.
C++ and python tests pass locally
> --[PBR Update 0 of 3] Add python binding to enable IBL.

- src/esp/gfx/GenericDrawable.cpp
- src/esp/gfx/PbrDrawable.cpp
- src/esp/gfx/PbrDrawable.h
- src/esp/gfx/PbrShader.cpp
- src/esp/gfx/PbrShader.h
- src/shaders/pbr.frag
This PR is the first of 3 (or possibly 4) PRs to implement Habitat's new PBR materials extension support, [drawn from the original WIP found here](https://github.com/facebookresearch/habitat-sim/pull/2091).
In this PR the gltf extension data present in the Magnum material are loaded into each drawable's existing cache structure, to be more easily accessed each draw.  No changes to the shader are present in this PR.
Existing C++ and python tests pass locally.
> --[PBR Update 1 of 3] Map materials' extension/layer data to Drawables cache

- mypy.ini
- src_python/habitat_sim/simulator.py
- src_python/habitat_sim/utils/data/data_extractor.py
* This makes all our optionals explicit with improve the documentation. I also turned on the feature in mypy. This produces better documentation and is less likely to hide issues with mypy. It also is the default in newer mypy versions.
> chore: typing - make optionals explicit

- src/cmake/FindMagnumPlugins.cmake
- src/esp/assets/ResourceManager.cpp
Another ~two weeks and ~15k lines of changes in Magnum :sweat_smile: This PR mainly brings initial support for loading glTFs with Basis-compressed files that aren't pre-Y-flipped, as -- due to unfortunate featurebugs in Basis itself -- that makes them problematic to load in all other software. 
This is implemented by [Y-flipping the block-compressed data on import](https://doc.magnum.graphics/magnum/ColorBatch_8h.html). So far this is implemented only for a few formats, more will be gradually added [once I figure them out](https://learn.microsoft.com/en-us/windows/win32/direct3d11/bc7-format-mode-reference). GPUs that don't support any formats I have Y-flip implemented will fall back to RGBA8.
Compared to other libraries, this means that Magnum is now capable of loading both Y-up and …
> Update to latest Magnum with glTF additions and block Y-flip APIs

- src/esp/gfx/BackgroundRenderer.cpp
- src/esp/gfx/BackgroundRenderer.h
- src/esp/gfx/DebugLineRender.cpp
- src/esp/gfx/Drawable.cpp
- src/esp/gfx/PbrDrawable.cpp
- src/esp/gfx/PbrShader.cpp
- src/esp/gfx/PbrShader.h
- src/esp/gfx/RenderCamera.cpp
- src/esp/gfx/TextureVisualizerShader.cpp
- src/esp/gfx/replay/Recorder.cpp
This changeset fixes some `clang_tidy` warnings needed for #2129.
Local build,  CI
> Fix clang tidy warning and typos.

- src/esp/gfx/PbrDrawable.cpp
- src/esp/gfx/PbrDrawable.h
This fixes the following clang-tidy error:
```
/home/circleci/project/habitat-sim/src/esp/gfx/PbrDrawable.cpp:57:44: error: missing field 'clearCoat' initializer [clang-diagnostic-missing-field-initializers,-warnings-as-errors]
matCache = {tmpMaterialData.baseColor()};  // baseColor;
```
Tested on CI.
> Fix clang-tidy issue with PbrDrawable + typo fixes.

- src/esp/gfx/replay/Player.cpp
- src/esp/gfx/replay/Player.h
- src/esp/sim/AbstractReplayRenderer.cpp
- src/esp/sim/AbstractReplayRenderer.h
- src/esp/sim/BatchPlayerImplementation.cpp
- src/esp/sim/BatchPlayerImplementation.h
- src/esp/sim/BatchReplayRenderer.cpp
- src/esp/sim/CMakeLists.txt
- src/esp/sim/ClassicReplayRenderer.cpp
- src/tests/BatchReplayRendererTest.cpp
The batch renderer can only delete full scenes - it cannot delete single objects.
To circumvent this, deletions are processed as such:
1. Latest transforms are cached.
2. All instances are deleted.
3. Remaining instances are re-created.
4. Latest transforms are re-applied.
> Replay renderer partial deletion

- src/esp/core/Logging.cpp
- src/esp/core/Logging.h
- src/esp/metadata/MetadataMediator.cpp
- src/esp/metadata/attributes/SceneDatasetAttributes.cpp
- src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
- src/esp/metadata/managers/AssetAttributesManager.cpp
- src/esp/metadata/managers/AttributesManagerBase.h
- src/esp/metadata/managers/LightLayoutAttributesManager.cpp
- src/esp/metadata/managers/ObjectAttributesManager.cpp
- src/esp/metadata/managers/PhysicsAttributesManager.cpp
- src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
- src/esp/metadata/managers/SceneInstanceAttributesManager.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/sim/Simulator.cpp
- src/tests/LoggingTest.cpp
The default logging behavior in habitat-sim has been overwhelming for some time now.  So much debug information is displayed to the console that any important warnings or errors get lost in the noise.  This PR is intended to address this issue.
Habitat-sim supports 4 logging levels : **VERY_VERBOSE**,  **DEBUG**, **WARNING** and **ERROR**. The intended purpose of these logging level messages is as follows :
- **ERROR** means some action or process has failed that the user needs to be aware of.
- **WARNING** means that although a process didn't outright fail, it may be yielding an unexpected/inappropriate result that the user should take note of.
- **DEBUG** means "here's the result of a process"
- **VERY_VERBOSE** means "here's the result of a process with in-depth explanation".
This PR …
> --[BE Week] Minimize logging spam

- src/esp/bindings/SimBindings.cpp
- src/esp/sim/AbstractReplayRenderer.cpp
- src/esp/sim/AbstractReplayRenderer.h
- src/esp/sim/BatchReplayRenderer.cpp
- src/esp/sim/BatchReplayRenderer.h
- src/esp/sim/ClassicReplayRenderer.cpp
- src/esp/sim/ClassicReplayRenderer.h
- src/tests/BatchReplayRendererTest.cpp
This adds an explicit `close()` method to replay renderer to ensure that resources aren't leaked when being used in Python.
See https://github.com/facebookresearch/habitat-lab/pull/1436.
Tested locally and on https://github.com/facebookresearch/habitat-lab/pull/1436.
> Add close() to replay renderer to allow for explicit resource release.

- .circleci/config.yml
This fixes an ongoing CI issue with Linux `conda_build_binaries` that was probably caused by an automated update of a git dependency.
Error:
```
Traceback (most recent call last):
File "/remote/habitat-sim/conda-build/matrix_builder.py", line 160, in <module>
main()
File "/remote/habitat-sim/conda-build/matrix_builder.py", line 142, in main
sha = repo.head.object.hexsha
File "/opt/conda/envs/py39/lib/python3.9/site-packages/git/refs/symbolic.py", line 219, in _get_object
return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
File "/opt/conda/envs/py39/lib/python3.9/site-packages/git/objects/base.py", line 94, in new_from_sha
oinfo = repo.odb.info(sha1)
File "/opt/conda/envs/py39/lib/python3.9/site-packages/git/db.py", line 40, in info
hexsha, …
```
> Fix conda build CI issue with git commands.

- DATASETS.md
- examples/viewer.py
- src/esp/bindings/SimBindings.cpp
- src/esp/metadata/attributes/SceneDatasetAttributes.cpp
- src/esp/metadata/attributes/SceneDatasetAttributes.h
- src/esp/metadata/managers/LightLayoutAttributesManager.cpp
- src/esp/sim/Simulator.cpp
- src/utils/viewer/viewer.cpp
This PR addresses a few minor issues.
- The viewer.py/viewer.cpp tag "--stage-requires-lighting" is renamed to the more accurate "--use-default-lighting"
- Our internally-specified lighting keys "NO_LIGHT_KEY" and "DEFAULT_LIGHTING_KEY" are handled more appropriately when a light setup is requested by name from the LightLayoutAttributesManager.
C++ and Python tests pass.
> --[BE Week]Minor Lighting-related refactoring

- src/esp/assets/ResourceManager.cpp
- src/esp/core/managedContainers/ManagedContainer.h
- src/esp/core/managedContainers/ManagedContainerBase.cpp
- src/esp/core/managedContainers/ManagedContainerBase.h
- src/esp/core/managedContainers/ManagedFileBasedContainer.h
- src/esp/metadata/MetadataMediator.cpp
- src/esp/metadata/MetadataMediator.h
- src/esp/metadata/attributes/PrimitiveAssetAttributes.h
- src/esp/metadata/attributes/SceneDatasetAttributes.h
- src/esp/metadata/managers/AbstractObjectAttributesManagerBase.h
- src/esp/metadata/managers/AssetAttributesManager.cpp
- src/esp/metadata/managers/AssetAttributesManager.h
- src/esp/metadata/managers/AttributesManagerBase.h
- src/esp/metadata/managers/ObjectAttributesManager.cpp
- src/esp/metadata/managers/SceneInstanceAttributesManager.cpp
- src/esp/metadata/managers/SceneInstanceAttributesManager.h
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/RigidStage.h
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/objectManagers/PhysicsObjectBaseManager.h
This PR addresses a few key issues with regard to the data load process and providing the user meaningful feedback on progress and issues that may arise.  Along with clarifying many messages, the following changes were made :
**MetadataMediator** 
- Some errors were updated to ESP_CHECK so that they would end the load process immediately if issues were present in the dataset load.
- A compound ESP_CHECK pertaining to the initial loading of the scene dataset was broken up into 3 individual checks, so that specific errors could be clearly communicated to the user.
**ResourceManager/AttributesManagers**
- Some Debug messages were demoted to Very Verbose
- Conditionally build a compound debug message string only if Debug-level messages are enabled.
**SceneInstanceAttributes**
The default …
> --[BE Week]More informative and appropriate data/metadata load and processing messages

- .circleci/config.yml
- .pre-commit-config.yaml
Bump `isort` to `5.12.0`.
The dependency was previously pinned at `5.11.5` due to dropped support of Python 3.7. We have since upgraded Habitat's python version. See https://github.com/facebookresearch/habitat-lab/pull/1107.
Tested on CI.
> Bump isort to 5.12.0.

- .circleci/config.yml
New Doxygen version 1.9.7 breaks on our doc build system, so fix the version at 1.9.5 for now.
CI
> [CI] - fix doxygen version at 1.9.5

- src_python/habitat_sim/utils/settings.py
Expand quick start settings util to support rgb clear color.
CI examples and tests instantiate these sensors with settings.
> add clear_color to settings for rgb sensor initialization

- src_python/habitat_sim/utils/datasets_download.py
Adds HSSD and AI2THOR-hab scenes and episode datasets to the dataset downloader. 
Locally by running the downloader for each of the added entries.
> Adds HSSD to dataset downloader

- src/esp/gfx/BackgroundRenderer.cpp
- src/esp/gfx/BackgroundRenderer.h
This PR fixes an issue where an additional GL context was being created in the Background Renderer, which was causing problems, including seg faults with [examples/tutorials/async_rendering.py
](https://github.com/facebookresearch/habitat-sim/blob/main/examples/tutorials/async_rendering.py)
Existing C++ and python tests pass
> --[BUGFIX] Background renderer should not create extra contexts

- .circleci/config.yml
This javascript test is broken, probably just due to timing out. Habitat JS support is still experimental so it's not vital to have this JS tested for now. We'll revisit CI for the JS build in the future.
I'm also making `--no-web-apps` the default for the JS build. This is a simpler build that doesn't rely on npm or webpack and should make the Habitat JS build more accessible and easy to understand for new folks looking to experiment here.
More background and specifics: the Habitat JS build is a version of our C++ library that is emscripten-compiled into a WebAssembly module (a `.wasm` file). This can be imported into a webpage and used by Javascript. Our legacy web apps (bindings.html, viewer.html) are examples of using the Habitat JS build, but they're not a required part of the JS …
> Disable broken JS test and make --no-web-apps the default

- src/esp/scene/GibsonSemanticScene.cpp
Reading a JSON element should be check exists then read, not attempt to read then check if null, which is what the GibsonSemanticScene attempts to do.  This was failing an assertion in RapidJSON that was only visible if compiled in Debug mode; in Release RapidJSON silenced the assertion and attempted to work around the problem.
All C++ and python tests (in both release and debug)
> --[BugFix] GibsonSemanticScene JSON access.

- src/esp/io/JsonAllTypes.h
- src/esp/io/JsonMagnumTypes.h
- src/esp/io/JsonStlTypes.h
- src/esp/metadata/managers/AttributesManagerBase.h
- src/esp/metadata/managers/LightLayoutAttributesManager.cpp
- src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
- src/esp/metadata/managers/SceneInstanceAttributesManager.cpp
- src/esp/scene/ReplicaSemanticScene.cpp
- src/esp/scene/SemanticScene.cpp
Using HasMember and then subsequently accessing a JSON value does a double lookup in the JSON document string. Using FindMember will provide an iterator pointing to the desired value or the end of the document if not found.  
This PR replaces HasMember lookups with iterator-based FindMember ones.  Note : those that remain in URDFParser and SceneDatasetAttributesManager will be removed in the [Articulated Object Attributes/Manager PR](https://github.com/facebookresearch/habitat-sim/pull/2178). 
All Tests in c++ and python pass locally
> --[BugFix] Get rid of double JSON lookups using HasMember

- src/esp/bindings/SimBindings.cpp
- src/esp/bindings_js/bindings_js.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/tests/SimTest.cpp
- src_python/habitat_sim/simulator.py
Multi-scene dummy API has been around for awhile. Cleaning it up.
CI
> [BE] - remove dummy sceneId from the API

- data/test_assets/urdf/skinned_prism.ao_config.json
This PR removes a deprecated field and adds the new fields introduced in [the "ArticulatedObject attributes and managers" PR](https://github.com/facebookresearch/habitat-sim/pull/2178) to the test asset "data/test_assets/urdf/skinned_prism.ao_config.json", except for "urdf_filepath" which is purposely left blank to test that the config load process will successfully find the pertinent urdf, which must reside in the same directory as the json config if it is not specified explicitly in the json.
Locally c++ and python tests.
> --[Bugfix] Add new fields to test asset `skinned_prism.ao_config.json`.

- src_python/habitat_sim/utils/datasets_download.py
Previously the code would not work for directories containing spaces (due to a split function being called). This has now been fixed.
For example, if you try to run the command:
`python -m habitat_sim.utils.datasets_download --uids habitat_test_scenes --data-path ./Data"` from the directory: `"/Users/vishnesh/Master/Sample Folder With Spaces"`, you get the following [error.](https://drive.google.com/file/d/1w8-jsi95AV8hJ2O60t0sUWSfw1l45KAg/view?usp=sharing)
This has been tested by reviewing how the path is split and by running the same command `python -m habitat_sim.utils.datasets_download --uids habitat_test_scenes --data-path ./Data"` without any errors.
- Would like some confirmation on whether the bug fix follows the code style or if something needs to be changed.
- (Not sure where to …
> Fixed bug for directories containing spaces

- src/esp/physics/PhysicsManager.cpp
All AO creation is driven by ArticulatedObjectAttributes now, with the caveat that to be used, any ArticulatedObjectAttributes must reference an existing and legitimate URDF file by relative path name from which to actually build the AO. ArticulatedObjectAttributes can be created using the name of their corresponding URDF file, in which case they will reference -that- URDF, and there is no need to complain if there is no existing ArticulatedObjectAttributes matching that name, since a legal one will be created .  This PR removes the erroneous and potentially misleading complaint, and proceeds silently to make a new ArticulatedObjectAttributes referencing the passed URDF file if one does not already exist.
This was peeled off [this PR, to minimize topical …
> --[BE/Bugfix]Modify creation of Articulated Object from URDF file name.

- src/esp/bindings/SimBindings.cpp
- src/esp/sim/AbstractReplayRenderer.h
- src/esp/sim/ClassicReplayRenderer.cpp
This changeset adds a config option to disable culling for replay renderers.
The classic replay renderer currently has an issue related to frustum culling. This allows to work-around the issue for immediate needs.
Tested locally in Python viewer.
> Add option to toggle frustum culling in replay renderer.

- src_python/habitat_sim/utils/datasets_download.py
CI lab test is failing due to missing test asset required by changes in https://github.com/facebookresearch/habitat-lab/pull/1543. Adding that asset appears to resolve the issue.
Thanks @ASzot for the suggested fix.
CI
> [CI] - add spot robot assets to CI test set

- examples/viewer.py
- src/esp/bindings/SimBindings.cpp
- src/esp/sim/SimulatorConfiguration.h
- src/utils/viewer/viewer.cpp
- src_python/habitat_sim/utils/settings.py
IBL is now enabled and balanced against direct lighting in the PBR shader by settings in xxx.pbr_config.json files and programmatically via PbrShaderAttributes configurations. 
These flags have been ignored since the [IBL rework was merged here](https://github.com/facebookresearch/habitat-sim/pull/2155) but this PR removes them.
NOTE : This is a breaking change, in that any code that is setting the flag will now break. Any code doing this can be removed without issue, since whatever the flag is set to has been ignored since the PBR/IBL rework.
> --[Habitat3.0] Removal of out-of-date/deprecated flags for IBL

- src/esp/io/Io.cpp
- src/esp/io/Io.h
- src/esp/metadata/managers/AttributesManagerBase.h
- src/tests/IOTest.cpp
If an ellipsis is specified in a path and this ellipsis attempts to back-step across an OS link, functions that attempt to read this path will get lost. On such function we use is **glob()**.  Such path configurations may be present in our scene dataset configurations, where the user might wish to access assets from another installed dataset that requires navigating to their directory outside the current dataset directory.
This PR adds a function that recursively removes ellipses if it can remove their parent directory (so a path with leading ellipses would be ignored). Tests are also added to verify functionality, and the path data being used for glob calls is now being appropriately filtered, albeit only in the case where the path within the scene dataset config path list starts with …
> --[BUGFIX] -Ellipses in paths

- src/tests/BatchReplayRendererTest.cpp
This changes test instance data structures that were incorrect, but still worked due to luck.
Tests pass.
> Fix wrong instance structures in replay renderer test.

- src/esp/bindings/SimBindings.cpp
- src/esp/sim/AbstractReplayRenderer.h
- src/esp/sim/ClassicReplayRenderer.cpp
This adds a flag to `ReplayRendererConfiguration` to enable HBAO.
Tested in `viewer.py` and HITL tool.
> Add replay renderer flag to enable HBAO.

- src/esp/nav/PathFinder.cpp
**TL;DR:** This PR adds a new implementation for sampling random points within a circle.
Currently, we use a Detour function `findRandomPointAroundCircle` for these queries. This function is implemented with a breadth-first search over navmesh polygons, excluding polygons outside the circle, starting from the closest snap point. 
**The problem with this function is that it excludes regions of the navmesh which are inside the circle, but separated from the region containing the start point.**
For example, this image shows points resulting from the query within the circle centered on the red object. Note that only bed points are considered because the "ramp" off the bed is outside the circle, cutting it off from the rest of that room and the other rooms.
To fix this behavior and accurately …
> More accurate get_random_navigable_point_near

- src/esp/core/managedContainers/ManagedFileBasedContainer.h
- src/esp/metadata/attributes/SceneDatasetAttributes.h
- src/esp/metadata/managers/AssetAttributesManager.h
- src/esp/metadata/managers/LightLayoutAttributesManager.h
- src/esp/metadata/managers/ObjectAttributesManager.h
- src/esp/metadata/managers/PhysicsAttributesManager.cpp
- src/esp/metadata/managers/PhysicsAttributesManager.h
- src/esp/metadata/managers/SceneDatasetAttributesManager.h
- src/esp/metadata/managers/SceneInstanceAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.h
- src/esp/physics/ArticulatedObject.h
- src/esp/physics/RigidBase.h
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/sim/Simulator.cpp
- src/tests/AttributesConfigsTest.cpp
- src/tests/AttributesManagersTest.cpp
- src/tests/MetadataMediatorTest.cpp
- src/tests/PhysicsTest.cpp
This PR fixes a few minor bugs and updates various comments.
Bugfixes : 
- When saving a Managed File-based Object (such as a SceneInstanceAttributes JSON file) and not wishing to overwrite an existing copy, Habitat sim generates a numbered suffix (copy xxxx) where xxxx will be an integer sequence starting at 0000 and incrementing for each copy saved. Currently on main branch, if such a copy is then loaded in a subsequent execution and then another copy is saved, and 2nd 'copy 0000' string is appended to the name. This PR fixes this, and instead properly increments the existing copy count in the name.
- AttributesConfigsTest and AttributesManagersTest are modified to use the correct TEST_ASSETS test directory macro for file IO.
- Unnecessary 'using' statements are also removed from …
> --[BUGFIX] Minor bugfixes

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/core/Esp.h
- src/esp/gfx/PbrDrawable.cpp
- src/esp/gfx/PbrShader.cpp
- src/esp/gfx/PbrShader.h
- src/esp/metadata/MetadataMediator.h
- src/esp/metadata/attributes/SceneDatasetAttributes.cpp
- src/esp/metadata/attributes/SceneDatasetAttributes.h
- src/esp/metadata/managers/AssetAttributesManager.cpp
- src/esp/metadata/managers/AssetAttributesManager.h
- src/shaders/gfx/pbr.vert
- src/shaders/gfx/pbrMaterials.glsl
- src/shaders/gfx/pbrUniforms.glsl
This PR introduces PBR material support and generation for primitives and generated meshes such as trajectories, which were formerly restricted to just phong materials, which looked out of place in scenes that were predominantly rendered using PBR with image-based lighting.  This also adds vertex color support for PBR materials.  Lastly, this also fixes a bug that was present if trying to build a PBR containing scene without a context (which was being done in a few of the tests).
This functionality was originally going to be part of the PBRTesting PR but I chose to go a different direction with that test due to the difficulty in assigning custom materials to primitive assets on creation.
C++ and python tests pass locally.
> --PBR Primitive support and gl context bugfix

- src/esp/gfx/replay/Recorder.cpp
A sneaky reference was causing the `rigId` to reset to the default value (`-1`) after the instance record was cleared, causing the removal from internal maps to fail.
Tested locally with the sandbox tool humanoid switching.
> Fix rigs not being deleted from the recorder.

- src/esp/bindings/PhysicsObjectBindings.cpp
- src/esp/metadata/URDFParser.h
- src/esp/physics/ArticulatedObject.h
- src/esp/physics/PhysicsObjectBase.h
- src/esp/physics/RigidBase.h
- src/esp/physics/RigidObject.h
- src/esp/physics/RigidStage.h
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/physics/bullet/BulletRigidStage.cpp
- src/esp/physics/objectWrappers/ManagedArticulatedObject.h
Follow-up refactor after adding support for ArticulatedObjectAttributes to expose creation attributes for AOs.
TODO
> Expose ArticulatedObject creation_attributes

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
The default materials were changed to PBR [here](https://github.com/facebookresearch/habitat-sim/pull/2235), including the default fallback material. When rendering with depth cameras, no texture is loaded from materials. The fallback material is instead applied to objects.
Because skinning only works with Phong, it breaks when the only sensors present in the simulation are depth.
This changes the default fallback material to Phong. We can revert this change when skinning support is added to PBR.
Tested locally on the SIRo HITL tool.
> Set the default fallback material as Phong.

- src/tests/PhysicsTest.cpp
The Magnum::Math::angle() function has been[ renamed/deprecated in this PR](https://github.com/facebookresearch/habitat-sim/pull/2243). This PR addresses a leftover reference to the deprecated function call.
Locally all C++ and python tests pass
> --Update reference to deprecated Magnum 'angle' function

- examples/tutorials/colabs/ECCV_2020_Navigation.ipynb
- examples/tutorials/nb_python/ECCV_2020_Navigation.py
Recast|Detour links were outdated 404 in ECCV_Navigation tutorial. Changed to github.
local
> [BE][doc] - update links to recast|detour page and image in ECCV tutorial

- src/esp/gfx/RenderCamera.cpp
- src/esp/gfx_batch/Hbao.cpp
- src/esp/sensor/CameraSensor.h
- src/utils/viewer/viewer.cpp
This PR fixes or updates a few things related to the near/far plane calculation for projection matrices : 
- The manual calculations in sim have been replaced with recently implemented Magnum calls
- The projection matrix far plane calculation for the `RenderCamera::unproject` function now not only calls the Magnum function, but also picks the correct calculation based on the nature of the Projection matrix, using the element at mat[3][3] to determine whether the matrix is perspective or orthographic.
- Some minor cleanup in Viewer.cpp
> --[BE Week] Update projection matrix near/far plane calcs

- examples/viewer.py
- src/esp/core/managedContainers/ManagedContainerBase.cpp
- src/esp/core/managedContainers/ManagedContainerBase.h
- src/esp/metadata/MetadataMediator.h
- src/esp/metadata/attributes/SceneDatasetAttributes.cpp
- src/esp/metadata/attributes/SceneDatasetAttributes.h
- src/esp/metadata/managers/AttributesManagerBase.h
- src/esp/metadata/managers/ObjectAttributesManager.cpp
- src/utils/viewer/viewer.cpp
This PR leverages the recent [updates to our Magnum libs](https://github.com/facebookresearch/habitat-sim/pull/2278) to address some inefficiencies and bugs, and fixes a minor bug with how scene instances were being loaded.
**Viewer.cpp/Viewer.py :** 
1. Improve text rendering in the viewers by using the magnum's new glyph handling.
2. Fix the black-box background around text in viewer.py by enabling, defining and subsequently disabling the appropriate blend state when text is being drawn.
**Attributes** 
1. Speed up string handle match search by checking size of target string before forcing it to lowercase
2. Add missing Articulated Object Attributes verification on Scene Instance load to be consistent with Stage, Object and Lighting Attributes handling.
Locally all tests pass
> --[BE Week] Better Attributes Handle search efficiency; Viewer.cpp/Viewer.py text render fixes

- examples/viewer.py
This fixes an indentation errors in the python viewer that causes the batch renderer to execute multiple times. This is not an issue under normal usage.
> Minor fix in python viewer.

- docs/AUDIO.md
- docs/docs.rst
- docs/noise_models.rst
- docs/pages/image-extractor.rst
- docs/pages/managed-rigid-object-tutorial.rst
This fixes various typos in the documentation pages.
N/A
> Fix typos in documentation.

- examples/viewer.py
This changes the default dataset to "default", removing a dependency to `ycb` and matching the behavior of `viewer.cpp`.
> Change default python viewer dataset to 'default'.

- setup.py
This PR just updates the link to the source attribution/explanation behind our setup.py file, ( [Building and testing a hybrid Python/C++ package](www.benjack.io/building-and-testing-a-hybrid-python/c-package/) ) which had broken some time ago.
No tests - just a comment link.
> --Update setup.py attribution link

- docs/pages/attributesJSON.rst
- src/esp/metadata/attributes/SceneInstanceAttributes.cpp
- src/esp/metadata/attributes/SceneInstanceAttributes.h
- src/esp/metadata/managers/SceneInstanceAttributesManager.cpp
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/URDFImporter.cpp
- src/esp/physics/URDFImporter.h
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletURDFImporter.cpp
- src/esp/physics/bullet/BulletURDFImporter.h
- src/esp/physics/objectManagers/ArticulatedObjectManager.cpp
- src/esp/physics/objectManagers/ArticulatedObjectManager.h
- src/tests/AttributesConfigsTest.cpp
This PR introduces some cleanup and essential prerequisite work for the upcoming support for Non-uniform scaling for Articulated Objects.
- A scene instance boolean is introduced to specify whether or not to apply the product of the geometric scale vector to the mass for objects and articulated objects.
- A few functions were refactored to get rid of unconventional or non-descriptive function prototypes
- A few unused functions were removed.
All c++ and python tests passed locally
> --[BE Week] Articulated Object Loading refactors and cleanup

- src/esp/bindings_js/bindings_js.cpp
**Note:** Requires https://github.com/facebookresearch/habitat-lab/pull/1776 in order to pass the CI. The lab PR can be merged independently, as the syntax should work even with the original code.
Another ~2 months worth of Magnum features, fixes and improvements. What's new since #2278:
- Fixed compatibility with Emscripten 3.1.49+
- Fixed [Matrix::isOrthogonal()](https://doc.magnum.graphics/magnum/classMagnum_1_1Math_1_1Matrix.html#a5a5ba4486a72512a19f73e9b591725e9) to catch negative dot product values. Note that this effectively tightens up certain assertions and could cause previously-incorrect but seemingly working code to assert (or raise an exception in Python). Thanks to @jturner65 for the discovery.
- New [Math::join()](https://doc.magnum.graphics/magnum/namespaceMagnum_1_1Math.ht …
> Update Magnum and m.css to latest

- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/physics/objectManagers/ArticulatedObjectManager.cpp
- src/esp/physics/objectManagers/RigidObjectManager.cpp
- src/esp/sim/Simulator.cpp
- src/tests/PhysicsTest.cpp
This PR is intended to address an issue when saving a scene instance, where an AO 's current configuration is not being saved as a SceneAOInstance.  In the process this PR also simplifies object/AO creation and makes sure some important processes always take place (which was not formerly the case) such as saving an instance creation attributes upon object/ao creation (and creating a default one if none exists)
> --[WIP]Object/AO creation refactor and Object/AO Instance save/creation

- examples/viewer.py
- src/esp/bindings/SceneBindings.cpp
- src/esp/scene/SemanticScene.cpp
- src/esp/scene/SemanticScene.h
- tests/test_semantic_scene.py
Add functions to query region containment for one point and a set of points.
Added pytests and a demo in viewer.py.
In the below video when the crib object is selected, containing regions are displayed colored by containment percentage. Red is full containment fading to green with less containment. Notice the hues shift as the object is moved between regions.
https://github.com/facebookresearch/habitat-sim/assets/1445143/695d1aa6-5eb3-4948-914f-ee6d34e98f82
Note: this demo will be reverted before merge.
> Region Query API

- src/esp/bindings/GfxReplayBindings.cpp
- src/esp/gfx/replay/Recorder.cpp
- src/esp/gfx/replay/Recorder.h
- src/esp/io/Json.cpp
- src/esp/io/Json.h
- src/tests/BatchReplayRendererTest.cpp
- src/tests/GfxReplayTest.cpp
This changes the gfx-replay `Recorder` to make the maximum float decimal places configurable.
This is an easy way to increase performance of JSON-based systems, as well as making the output text more compact.
**Example usage:**
```
sim.gfx_replay_manager.set_max_decimal_places(3)
[...]
sim.gfx_replay_manager.save_keyframe()
keyframe = sim.gfx_replay_manager.write_saved_keyframes_to_string()
```
**Example data (update frames):**
| Default | 3 Decimal Places |
|---|---|
| 4223 bytes| 3656 bytes |
| ![jsonbefore](https://github.com/facebookresearch/habitat-sim/assets/110583667/52f5be08-cec2-424a-8cd1-963a085a7379) | ![jsonafter](https://github.com/facebookresearch/habitat-sim/assets/110583667/66f46adf-80a5-4cbf-9fa7-cce50ea50d87) |
Added a unit test, and tested locally on the HITL tool.
> Add max decimal place option to recorder.

- examples/viewer.py
- src/esp/bindings/Bindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/core/Esp.h
- src/esp/physics/RigidStage.cpp
- src/tests/PhysicsTest.cpp
- src_python/habitat_sim/__init__.py
- src_python/habitat_sim/bindings/__init__.py
- tests/test_physics.py
- tests/test_simulator.py
The stage ID is referenced in python and from lab in numerous places, usually as a mark of where added objects' ids begin, or else as a final target for collision detection. Unfortunately, this is often referenced or checked by using magic number references to the stage (i.e. -1).
This PR introduces a global constant to denote the stage ID (`esp::RIGID_STAGE_ID`), and bindings to that constant to expose it to python (`habitat_sim.stage_id`), which should be used to refer to the stage ID.  A matching Habitat-Lab PR is pending for this support as well, once this PR is merged.  Ultimately this is to facilitate t[he instanced -based semantic sensor support PR here 
](https://github.com/facebookresearch/habitat-sim/pull/2316)
All c++ and python tests pass locally
> --Define constant and bindings for stage ID

- src/esp/gfx/RenderTarget.cpp
- src/utils/viewer/viewer.cpp
Changes needed in the native viewer application and the RenderTarget to allow for rendering at a resolution that's smaller than the actual framebuffer. For simplicity halving the framebuffer width and height, thus quarter of the size, however the limit at which this switch is done is configurable, so it's also achievable on non-HiDPI displays if you pass `--quarter-resolution-scaling-limit 1` to the app.
It also:
- Removes use of 4x MSAA which achieved nothing as the content was rendered to a non-multisampled framebuffer in the first place.
- Cleans up various interesting ways of doing vector math.
- Removes an assertion in the RenderTarget that required the source and destination size to match, and switches the filter to linear to not look *that* blocky.
- Removes an errorneous …
> Ability to render the viewer content at quarter resolution on very-high-DPI screens

- .circleci/config.yml
Using the latest miniconda versions is referencing python 3.12 which is undesirable, and causes osx builds to break (pkgutil.ImpImporter class was deprecated in python 3.3 and removed in 3.12.)
This PR will freeze our miniconda version to most recent python 3.10 version for both linux and mac.
> --[CI Fix] Fix miniconda versions

- src/esp/bindings/PhysicsObjectBindings.cpp
- src/esp/physics/PhysicsObjectBase.h
- src/esp/physics/RigidObject.h
- src/esp/physics/bullet/BulletRigidObject.h
- src/esp/physics/objectWrappers/ManagedRigidBase.h
This PR adds a few minor fixes and code improvements.
- Adds bound access to rigid object com correction vector (translation of underlying visual node).
- Cleans up some existing RigidObject comments referencing outdated constructs
All existing c++ and python tests pass
> --Minor fixes and improvements

- src/esp/bindings/SceneBindings.cpp
- src/esp/scene/SemanticScene.cpp
- src/esp/scene/SemanticScene.h
- src/esp/sim/Simulator.h
- tests/test_semantic_scene.py
This PR adds functions to test for point-region membership and point collection-region membership with a weighting factor, to account for possibly nested regions. If a point is only found in a single region, its weighting in that region is 1. 
Otherwise, each region is assigned a weighting that is inversely proportional to the area of a particular region containing the point.  The weighting is calculated like so : 
` 
1 - (region_area/total_region_area)
`
where `region_area` is the area of a specific region the point is found in and total_region_area is the total area of all regions that point is found in. 
For collections of points that are assumed to belong to the same construct, the region membership check has been modified to give ~~a weighting value only to the innermost (i.e. …
> --Region query tools

- examples/motion_viewer.py
- examples/viewer.py
- src_python/habitat_sim/__init__.py
This removes the `RTLD_GLOBAL` flag from python apps, which is no longer required since [this magnum update](https://github.com/facebookresearch/habitat-sim/pull/2309).
The flag is also set in `habitat-sim`'s `__init__.py` to handle cases where `habitat-sim` bindings are used before `magnum`/`corrade` is imported.
This flag was required before loading native magnum/habitat modules to de-duplicate globals across shared modules. [This is now done automatically when importing corrade.](https://github.com/mosra/magnum-bindings/commit/b4d437bb3ff7bf925064532a39b02c7e6ee1356f#diff-e6d652e2d587ecbff4369a8f11be89982863d5f613feb96777d9aa95136d1675).
[This PR](https://github.com/facebookresearch/habitat-lab/pull/1783) does the same changes in `habitat-lab`.
Tested the viewers locally on Linux.
> Remove RTLD_GLOBAL flag from apps.

- examples/motion_viewer.py
- examples/viewer.py
- src_python/habitat_sim/__init__.py
This reverts commit d890c644a35cefdde1d0962b3e16ecc4f1dd326d (#2312), which is causing downstream issues (for instance, in `habitat-llm`).
The downstream issues will be stabilized prior to re-introducing this change.
N/A
> Revert "Remove RTLD_GLOBAL flag from apps. (#2312)

- src/cmake/FindAssimp.cmake
- src/cmake/FindBullet.cmake
- src/cmake/FindCorrade.cmake
- src/cmake/FindEGL.cmake
- src/cmake/FindGLFW.cmake
- src/cmake/FindMagnum.cmake
- src/cmake/FindMagnumBindings.cmake
- src/cmake/FindMagnumIntegration.cmake
- src/cmake/FindMagnumPlugins.cmake
Another month+ worth of Magnum updates, this time containing two important usability features:
- The [StanfordImporter](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1StanfordImporter.html) and [StlImporter](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1StlImporter.html) plugins now delegate to Assimp for ASCII files instead of failing the import. Which brings the best of the two worlds -- I don't need to suffer through implementing an ASCII PLY or STL parser myself, and you don't need to suffer with slow import of binary PLY and STL files by defaulting to Assimp instead. In particular, https://github.com/facebookresearch/habitat-lab/pull/1869 can be reverted after this PR is merged, and everything should continue to work.
- Text rendering artifacts that started …
> Update Magnum for ASCII PLY import and artifact-free text rendering

- src/esp/bindings/AttributesBindings.cpp
- src/esp/bindings/ConfigBindings.cpp
- src/esp/core/Configuration.cpp
- src/esp/core/Configuration.h
- src/esp/metadata/attributes/AbstractObjectAttributes.h
- src/esp/metadata/attributes/ArticulatedObjectAttributes.h
- src/esp/metadata/attributes/AttributesBase.h
- src/esp/metadata/managers/AOAttributesManager.cpp
- src/esp/metadata/managers/AttributesManagerBase.h
- src/esp/metadata/managers/ObjectAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/tests/AttributesConfigsTest.cpp
- src/tests/CoreTest.cpp
This PR supports the loading, modification, and saving of nested marker sets in the configs for AO, objects and stages. 
Local C++ and python tests pass
> --Support marker set specifications in Object, Stage and AO config jsons

- src/esp/bindings/AttributesManagersBindings.cpp
- src/esp/core/managedContainers/AbstractFileBasedManagedObject.h
- src/esp/core/managedContainers/ManagedContainer.h
- src/esp/core/managedContainers/ManagedFileBasedContainer.h
- src/esp/metadata/attributes/AttributesBase.cpp
- src/esp/metadata/attributes/AttributesBase.h
- src/esp/metadata/managers/AOAttributesManager.cpp
- src/esp/metadata/managers/AOAttributesManager.h
- src/esp/metadata/managers/AssetAttributesManager.cpp
- src/esp/metadata/managers/AssetAttributesManager.h
- src/esp/metadata/managers/LightLayoutAttributesManager.cpp
- src/esp/metadata/managers/LightLayoutAttributesManager.h
- src/esp/metadata/managers/ObjectAttributesManager.cpp
- src/esp/metadata/managers/ObjectAttributesManager.h
- src/esp/metadata/managers/PbrShaderAttributesManager.h
- src/esp/metadata/managers/PhysicsAttributesManager.h
- src/esp/metadata/managers/SceneDatasetAttributesManager.cpp
- src/esp/metadata/managers/SceneDatasetAttributesManager.h
- src/esp/metadata/managers/SceneInstanceAttributesManager.cpp
- src/esp/metadata/managers/SceneInstanceAttributesManager.h
- src/esp/metadata/managers/SemanticAttributesManager.h
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.h
- src/esp/physics/objectManagers/PhysicsObjectBaseManager.h
- src/esp/sim/Simulator.cpp
This PR exposes the attributes save-to-disk functionality via python; 
It expands the possible saving capabilities so that both directories and filenames can be independently specified.
It also addresses some longstanding inefficiencies and potential issues with attribute registration
All C++ and python tests pass locally
> --Expose Attributes save functionality to python; cleanup/improve attribute registration.

- src/esp/physics/bullet/BulletPhysicsManager.cpp
This change sets the `OBJECT_ID` fields for articulated object nodes.
Notes:
* For gfx-replay use cases, the articulated object link IDs are important. They are used to match gfx-replay instances with real objects.
* For semantic rendering cases, we might want to have a separate field for the root object ID.
* Tests are missing.
Tested using gfx-replay (`habitat-sim -> habitat-lab -> Unity`).
> Set node object IDs for articulated object links.

- src/esp/gfx/WindowlessContext.cpp
- tests/test_gfx.py
This change omits `setCudaDevice` when `gpu_device_id == -1`.
Hydra override:
```
habitat.simulator.habitat_sim_v0.gpu_device_id=-1
```
Source: https://github.com/facebookresearch/habitat-sim/commit/a26f3accbce93caa0cecf9841b3f2217b96c002d
Tested on cpu-only AWS servers.
> Avoid setting CUDA device when there is no GPU.

- src/esp/gfx/replay/Keyframe.h
- src/esp/gfx/replay/Player.cpp
- src/esp/gfx/replay/Player.h
- src/esp/gfx/replay/Recorder.cpp
- src/esp/gfx/replay/Recorder.h
- src/esp/io/JsonEspTypes.cpp
- src/esp/io/JsonEspTypes.h
- src/tests/GfxReplayTest.cpp
- src/tests/IOTest.cpp
This changeset adds an `InstanceMetadata` entry to `gfx-replay` keyframes so that this information can be made available to external players.
This information can be used to do commands on `gfx-replay` instances based on real simulation IDs, for example:
* Hiding an agent.
* Highlighting an object's mesh.
* Tooling.
* ...
* Added test.
* Tested in Unity gfx-replay client.
> Add instance metadata to gfx-replay.

- src_python/habitat_sim/utils/datasets_download.py
Updates the replica_cad rearrange dataset links for v2.
V2 remaps all entries in `RearrangeEpisode.name_to_receptacle` dict to correctly reference the `Receptacle.unique_name` instead of `Receptacle.name`.
Also removes all v0 pickle files from the dataset.
CI?
> [data] update dataset_downloader.py with replica_cad rearrange dataset v2

- src/esp/scene/SceneNode.cpp
- src/esp/scene/SceneNode.h
This bugfix fixes the incorrect initialization of the SceneNode semanticIDs_ vector which was causing a heap corruption.
Local c++ and python tests pass
> --Properly initialize std::vector member variable to be correct size

- src/esp/assets/Asset.cpp
- src/esp/assets/Asset.h
- src/esp/assets/ResourceManager.cpp
- src/esp/assets/ResourceManager.h
- src/esp/core/Esp.h
- src/esp/metadata/attributes/AttributesBase.cpp
- src/esp/metadata/attributes/AttributesBase.h
- src/esp/metadata/attributes/AttributesEnumMaps.cpp
- src/esp/metadata/attributes/AttributesEnumMaps.h
- src/esp/metadata/attributes/SemanticAttributes.cpp
- src/esp/metadata/attributes/StageAttributes.cpp
- src/esp/metadata/managers/AbstractObjectAttributesManager.h
- src/esp/metadata/managers/ObjectAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.cpp
- src/esp/metadata/managers/StageAttributesManager.h
- src/esp/physics/URDFImporter.cpp
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/sim/Simulator.cpp
- src/tests/IOTest.cpp
- src/tests/SimTest.cpp
- src/utils/datatool/SceneLoader.cpp
This PR moves the AssetType enum from the asset namespace to the metadata::attributes namespace where it can reside with the other metadata-related enum classes in AttributesEnumMaps.  This is primarily for consistency but also to facilitate interactions with the enum-backed data in the Attributes that consume it.
The PR also moves the EMPTY_SCENE definition to Esp.h from Asset.h, in an effort to also maintain consistency in where our system-wide consts are stored.
> --Move AssetType enum class attributes namespace

- src/esp/bindings/PhysicsObjectBindings.cpp
- src/esp/physics/ArticulatedObject.h
- src/esp/physics/PhysicsObjectBase.h
- src/esp/physics/objectWrappers/ManagedPhysicsObjectBase.h
This PR adds a few convenience functions and bindings to provide quick access to the nested dictionary structure of marker points in both object local and world space.
> --Convenience functions for accessing markers in local and world space

- .circleci/config.yml
Fixes the current emergent CI issue with pip install.
Not sure of exact details, but it appears the behavior or routing of `cd -` resulted in pip installation targeting the root directory '/home/circleci` instead of the expected `/home/circleci/project` directory containing the cloned repo.
Emergent permission issues in  `/opt/circleci/.pyenv/` suspected of being part of the problem.
Empirical solution was to skip the initial setup and route directly to project/ directory for pip installation.
CI
> [CI] fix pip install

- src/esp/core/Configuration.h
- src/esp/metadata/attributes/AttributesBase.h
- src/esp/metadata/attributes/MarkerSets.h
- src/esp/metadata/attributes/SemanticAttributes.cpp
- src/esp/metadata/attributes/SemanticAttributes.h
- src/esp/metadata/managers/AttributesManagerBase.h
- src/esp/metadata/managers/SemanticAttributesManager.cpp
- src/esp/scene/SemanticScene.cpp
This PR takes the support for vectors of points introduced with MarkerSets, promotes it to the underlying Configuration and expands it to be vectors of any type.  In a nutshell a vector of data can be stored in a subconfig by having the key be a string rep of the index in the vector referencing the value.  
This obviates the need for local vectors to implementers of the Configuration class, such as SemanticAttributes, which stored the polyloop of points in a vector member varaiable. 
Locally c++ and python tests pass.
> --Configuration : Add ability to handle vectors of fields within subconfigs

- src/esp/core/Configuration.cpp
- src/esp/core/Configuration.h
- src/esp/metadata/attributes/SceneInstanceAttributes.cpp
- src/esp/metadata/attributes/SceneInstanceAttributes.h
- src/esp/metadata/attributes/SemanticAttributes.h
- src/esp/metadata/managers/AttributesManagerBase.h
- src/esp/metadata/managers/SceneInstanceAttributesManager.cpp
- src/esp/metadata/managers/SemanticAttributesManager.cpp
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/tests/AttributesConfigsTest.cpp
As an extension of [this PR, which](https://github.com/facebookresearch/habitat-sim/pull/2394) provided vector/array-backed support to subconfigurations, and in [preparation for #2382](https://github.com/facebookresearch/habitat-sim/pull/2382) , which brings substantial expansion to the Configuration subsystem capabilities, this PR expands and unifies the handling of vector/array-based configuration fields.  
Now, a json construct that is expected to be either an array or an array-like key-value store (where the keys are string representations of the indices of the subsquent array) will be handled by the same code, and a paradigm of consistency is introduced to provide vector set/get access to configuration-based vector-like constructs. A float specialization is also added for the …
> --Configurations : Expand and unify vector/array-backed value handling

- .circleci/config.yml
Git LFS was broken on CI by new security measures https://github.com/git-lfs/git-lfs/issues/5749
This PR disables the clone protections for pulling data from our HF repos.
CI
> [CI] - Disable new clone protection for git lfs

- .circleci/config.yml
This PR adds ycb and rearrange_v2 data downloads to support removal of auto-downloader from lab tests in https://github.com/facebookresearch/habitat-lab/pull/1962
CI
> [CI] - add lab ci asset downloads

- src/esp/bindings/ConfigBindings.cpp
- tests/test_configs.py
Python seems to treat bindings as a dict or list and searches for the first matching override for a bound function. Python treats Bool as a subclass of Integer, so set(key, Bool) in Configuration was writing integers. Re-ordering the bindings fixes this.
Local testing and new python test case
> [bugfix] - reorder Configuration setter bindings 

- src/esp/io/Io.cpp
- src/tests/IOTest.cpp
This PR addresses some edge case situations that might arise when absolute filepaths are made relative to other paths.
It also substantially expands the tests of this functionality.
> --Bugfix : Expand absolute-to-relative filepath mapping rigor

- src/esp/metadata/attributes/SceneInstanceAttributes.cpp
- src/esp/metadata/attributes/SceneInstanceAttributes.h
- src/esp/physics/PhysicsManager.cpp
This PR properly copies the user defined attributes from a base config to an instance config's user-defined subconfig, instead of in the subconfig's base level.
Local c++ and python tests
> --[BUGFIX] - Properly set instance user config from base passed base config.

- src/esp/bindings/PhysicsObjectBindings.cpp
- src/esp/physics/ArticulatedObject.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/objectWrappers/ManagedArticulatedObject.h
- tests/test_physics.py
This PR adds `link_ids_to_object_ids` python property and `getLinkIdsToObjectIds` function to python and C++ ManagedArticulatedObject APIs respectfully.
We have had `link_object_ids` for while providing the opposite mapping. However, collision detection, raycasting, etc... opertate primarily on object_ids. If we want to know the object_id for a link in order to check it, we had to create an inverted map like:
```
links_to_obj_ids = {v: k for k, v in ao.link_object_ids.items()}
```
which is a pain.
Added a unit test for the maps in both directions.
> add ManagedArticulatedObject attribute for link_id to object_id map

- src/esp/bindings/PhysicsObjectBindings.cpp
- src/esp/metadata/attributes/SceneInstanceAttributes.h
- src/esp/physics/ArticulatedObject.h
- src/esp/physics/PhysicsObjectBase.h
- src/esp/physics/RigidBase.h
- src/esp/physics/bullet/objectWrappers/ManagedBulletRigidObject.h
- src/esp/physics/objectWrappers/ManagedPhysicsObjectBase.h
- src/tests/PhysicsTest.cpp
- src/tests/SimTest.cpp
- tests/test_physics.py
This small PR exposes a read-only property ("is_articulated") in the python bindings that says whether an object is articulated or not, as an alternative to checking for the object type before attempting to access type-specific functions.
c++ PhysicsTest.cpp and SimTest.cpp and python test_physics.py have been expanded to test this field, and all tests pass locally.
> --[BE] - Add utility function to specify whether object is ao or not

- examples/tutorials/nb_python/ECCV_2020_Interactivity.py
- examples/tutorials/notebooks/ECCV_2020_Interactivity.ipynb
- src/esp/bindings/SimBindings.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/sim/Simulator.h
The sim/physics manager version of contact test has been deprecated since before Habitat 2.0 was released, and should have been removed then. This PR removes it.
> --[BE] - Remove deprecated Sim-level contact test

- src/esp/bindings/PhysicsWrapperManagerBindings.cpp
- src/esp/physics/ArticulatedObject.h
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/PhysicsObjectBase.h
- src/esp/physics/RigidObject.h
- src/esp/physics/objectManagers/ArticulatedObjectManager.cpp
- src/esp/physics/objectManagers/ArticulatedObjectManager.h
- src/esp/physics/objectManagers/RigidObjectManager.cpp
- src/esp/physics/objectManagers/RigidObjectManager.h
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
This function enables the easy and accurate duplication of existing rigid and articulated objects. If an object has been instantiated by an scene object/ao instance attributes, that object's state will be impacted by both its creation template and the instance attributes, which can be arcane. Instead of attempting to duplicate this process externally, the instance attributes and config template are accessed internally for the existing object and used to recreate another just like it.
Locally existing c++ and python tests pass. Tests to be added to verify duplication process.
> --[BE] - Duplicate existing rigid or articulated object

- src/esp/physics/ArticulatedObject.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
We've been computing AO bboxes during creation only if they were specified to use visuals based on link shapes.  This PR changes this to always compute cumulative bboxes for loaded AOs.  This was not a problem before due to simulator::reconfigure calling reset() which would recompute the cumulative bbox on the scene root node, which would hit the AOs as well, but any AOs that were loaded after reconfigure would be missed.
Local C++ and Python tests pass.
> --[Bugfix] - Compute AO cumulative bbox on creation unconditionally.

- .circleci/config.yml
- conda-build/Dockerfile
Our current conda build docker for linux is based on a centos 7 image.
centos7 reached end of life (EoL) in June 2024. 
The mirror repos were moved to centos vault causing our current build to fail.
This PR updates the docker to centos 8.
CI conda build test passed.
On branch https://github.com/facebookresearch/habitat-sim/tree/alex-07_11-conda_deploy_test_rhel8 I deployed a test linux package which is currently available [here](https://anaconda.org/aihabitat/habitat-sim-test-rhel8/files). I was able to successfully install this package and run tests locally on Fedora 39.
> [CI][conda] - Update conda build docker to centos8

- src/esp/bindings/AttributesBindings.cpp
- src/esp/bindings/AttributesManagersBindings.cpp
- src/esp/bindings/Bindings.cpp
- src/esp/bindings/Bindings.h
- src/esp/bindings/ConfigBindings.cpp
- src/esp/bindings/GfxBindings.cpp
- src/esp/bindings/MetadataMediatorBindings.cpp
- src/esp/bindings/PhysicsObjectBindings.cpp
- src/esp/bindings/SceneBindings.cpp
- src/esp/bindings/SensorBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/metadata/attributes/LightLayoutAttributes.h
- src/esp/metadata/attributes/SemanticAttributes.h
- src/esp/metadata/managers/SemanticAttributesManager.cpp
This PR adds missing bindings and fixes broken ones as exposed by pybind11-stubgen which is being [introduced in this PR](https://github.com/facebookresearch/habitat-sim/pull/2415)
All local c++ and python tests pass
> --[BE] Fix issues with bindings exposed by pybind11-stubgen

- src/esp/core/Configuration.h
- src/esp/metadata/attributes/MarkerSets.h
If all the markers in a markerset are removed, the markerset should also be removed. This should apply to all levels of the hierarchy, so that empty (sub)objects are not written to JSON on save.
> --[BUGFIX] Make sure empty Markerset subconfigs are removed when appropriate

- src/esp/core/Configuration.cpp
- src/esp/metadata/attributes/MarkerSets.h
Removing the markerset subconfigs when they were empty caused memory corruption in certain rare cases (python variables retaining possession of a removed variable), so [the change introduced in this PR](https://github.com/facebookresearch/habitat-sim/pull/2434) is being reverted; 
Instead, a subconfig with no values in its entire subconfig hierarchy (all of its own subconfigs and so on, instead of just in its own primary map) will not be written to JSON.
Locally c++ and python tests. Also verified with python app that fix works.
> --[BUGFIX] - Revert markerset subconfig removals; Don't write empty configs to file

- src/esp/physics/ArticulatedObject.h
- src/esp/physics/PhysicsObjectBase.h
This PR will properly handle transformations of points assigned to the baseLink of an ArticulatedObject between local and world space. It will also accommodate transforming baseLink-assigned marker points to world space if any should exist.
Locally C++ and python tests.
> --[BugFix] - Handle transformations of points assigned to an AO's baselink

- src/esp/bindings/AttributesBindings.cpp
- src/esp/bindings/AttributesManagersBindings.cpp
- src/esp/bindings/GfxBindings.cpp
- src/esp/bindings/PhysicsBindings.cpp
- src/esp/bindings/SceneBindings.cpp
- src/esp/metadata/attributes/AttributesEnumMaps.h
- src/esp/metadata/attributes/LightLayoutAttributes.h
- src/esp/metadata/managers/AbstractObjectAttributesManager.h
This PR fixes some issues that were [missed in the previous PR](https://github.com/facebookresearch/habitat-sim/pull/2430), which manifest when pybind11 stubs are being generated (see [here](https://github.com/facebookresearch/habitat-sim/pull/2415) ). 
Until all such issues are fixed, adding pybind11-stubgen to the build process will generate a stub file that will fail mypy precommit. In other words, no python source code changes or additions will be able to be committed to the repo with the erroneous stub file.
- Cannot have argument names in a method that are python reserved words.
- Same applies for enums.  All enums should be all caps in python, so that's an essential refactor that needs to happen which would obviate this issue.
- All types accessed by the bindings, either as args or …
> --[WIP][Bugfix]- Address remaining issues with bindings stubgen

- src/esp/physics/PhysicsManager.h
- src/esp/physics/RigidObject.h
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/tests/PhysicsTest.cpp
- src_python/habitat_sim/simulator.py
- tests/test_physics.py
- tests/test_simulator.py
This PR add expanded reset logic to base Simulator:
- object states are reset to initial conditions
- ~default light setup key points to scene's light setup key~ (moved to https://github.com/facebookresearch/habitat-sim/pull/2453)
**This is a breaking change, previously reset only set world time to 0.**
CI should still pass.
Added new unit test to validate the rest logic
> Expanded reset logic for Simulator 

- src/esp/bindings/SceneBindings.cpp
docstring wasn't rendering with the newlines
tested with local doc build
> [doc] - fixes docstring format for get_weighted_regions_for_point 

- src/esp/bindings/SimBindings.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletPhysicsManager.h
- src/esp/sim/Simulator.h
- tests/test_physics.py
This PR fixes a long-standing raycasting bug related to the behavior of Bullet physics raycasting within the collision margin of a convex shape.
**TL;DR: we add a hidden "buffer distance" to the raycast to avoid missing an object from within its margin.**
**Context:** 
- Bullet physics raycasts do not register hits from within convex shapes, neither entering, nor exiting.
- Each collision shape has a configurable margin distance which is used to pad the collision detection algorithm to better catch upcoming impacts between dynamic shapes and avoid discrete collision issues near boundaries.
- (a) Raycasts against convex shapes hit the shape, not the margin.
- (b) Raycast origins within the margin are not considered.
- Taken together, (a) and (b) result in a narrow region of space near the …
> [bugfix] - raycast buffer distance

- src/esp/core/Configuration.h
- src/esp/metadata/attributes/AbstractAttributes.h
- src/esp/metadata/attributes/AbstractObjectAttributes.h
- src/esp/metadata/attributes/ArticulatedObjectAttributes.cpp
- src/esp/metadata/attributes/ArticulatedObjectAttributes.h
- src/esp/metadata/attributes/AttributesEnumMaps.cpp
- src/esp/metadata/attributes/SceneInstanceAttributes.cpp
- src/esp/metadata/attributes/SceneInstanceAttributes.h
- src/esp/metadata/managers/SceneInstanceAttributesManager.cpp
- src/esp/physics/ArticulatedObject.h
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsManager.h
- src/esp/physics/PhysicsObjectBase.h
- src/esp/physics/RigidBase.h
- src/esp/physics/RigidObject.cpp
- src/esp/physics/RigidStage.cpp
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/physics/bullet/BulletRigidObject.cpp
- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
This PR addresses the SceneInstance-specified DefaultCOMCorrection specification not being properly represented when an object is created in an existing, running scene. This causes these added objects to not be saved at the appropriate location should the modified scene be saved to JSON.
Locally c++ and python
> --[Bugfix] - Address ObjectInstanceAttributes save issues

- src/esp/core/Esp.h
- src/esp/physics/ArticulatedObject.h
- src/esp/physics/PhysicsManager.h
- src/esp/physics/PhysicsObjectBase.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/BulletURDFImporter.cpp
- src/esp/physics/bullet/BulletURDFImporter.h
- src/esp/physics/objectWrappers/ManagedArticulatedObject.h
This small PR adds a constant to replace the magic number '-1' used to reference the baselink ID for articulated objects.  A few other magic numbers were replaced with more semantically meaningful constants, based on context.
> --[BE] - Baselink ID init via constant

- src/esp/core/Configuration.cpp
- src/esp/core/Configuration.h
- src/tests/ConfigurationTest.cpp
This PR adds, and tests, proper fuzzy comparison between scalar ConfigValues that require it (i.e. doubles) using the same Magnum mechanism that supported Magnum floating point vector-based types use.  This comparison uses a scaled epsilon value that acts as a threshold between two values being equal or not.  See [here for comparison details](https://github.com/mosra/magnum/blob/ccb96f73c7154326589594e6c4260be9e796ecfb/src/Magnum/Math/TypeTraits.h#L485).
Support for fuzzy comparison must be implemented (following the pattern here for doubles) for any numeric types added to the ConfigValue supported list only if they do not use a similar comparison mechanism already (i.e. this does not need to be included for any magnum floating-point types)
Locally c++ and python. Tests have been added to …
> --[Bugfix] - Compare Configuration scalar doubles properly

- .circleci/config.yml
- requirements.txt
Force every numpy version for CI to be the version we need to use due to Quaternion library (1.26.4). Also, restrict Pillow to 10.4.0, since the unrestricted version (11.0) introduced typing that conflicts with our current consumption of the library.
CI is testing it.
> --Restrict CI Numpy version.

- src/esp/sim/Simulator.cpp
- src/esp/sim/Simulator.h
- src/tests/SimTest.cpp
This PR expands the `addSensorToObject` function to cover all possible valid values for `objectId` and to throw an exception for invalid values.
- adds attachment to an ArticulatedObject's root or to any link
- adds attachment to the root SceneNode (global space) when `objectId == esp::RIGID_STAGE_ID`
Added a C++ test.
> addSensorToObject() expanded

- src/esp/physics/ArticulatedLink.h
- src/esp/physics/ArticulatedObject.h
- src/esp/physics/CMakeLists.txt
- src/esp/physics/PhysicsManager.cpp
- src/esp/physics/PhysicsObjectBase.h
- src/esp/physics/RigidObject.h
- src/esp/physics/bullet/BulletArticulatedLink.h
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/physics/bullet/BulletArticulatedObject.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/bullet/CMakeLists.txt
This PR adds a pointer to each Rigid and Articulated Object to the Managed Object containing it. This is for python-driven internal access, so that, for instance, an articulated link can return a ManagedArticulatedObject reference to the AO it is a part of.
TODO : add tests for functionality
> --[BE] - Save ref to object's ManagedObject wrapper for internal access.

- src/tests/CMakeLists.txt
This PR will link to the 'assets' library for HM3DSceneTest, which otherwise has recently started failing due to required Importers not being found.  Not sure of the cause, or why this is only happening locally on my machine (currently) but this addresses the issue.
Locally C++ tests pass
> --[BUGFIX] - Link missing 'assets' library to HM3DSceneTest

- src/esp/bindings/ConfigBindings.cpp
- src/esp/core/Configuration.cpp
- src/esp/core/Configuration.h
- src/esp/io/JsonMagnumTypes.cpp
- src/esp/io/JsonMagnumTypes.h
- src/esp/metadata/attributes/AttributesEnumMaps.cpp
- src/esp/metadata/attributes/AttributesEnumMaps.h
- src/esp/sensor/CubeMapSensorBase.h
- src/esp/sensor/EquirectangularSensor.h
- src/esp/sensor/FisheyeSensor.cpp
- src/esp/sensor/FisheyeSensor.h
- src/esp/sensor/Sensor.cpp
- src/esp/sensor/Sensor.h
- src/tests/ConfigurationTest.cpp
This PR has performs some prerequisite work needed for the ongoing Sensor system refactor.  Specifically, this PR  :  
- Introduces Configuration support for Magnum types needed for Sensor specification : Vector2i, Degrees (including testing)
- Expands Sensor enums with string-to-enum mappings used by configurations.
- Removes unsupported SensorType enumerations
Locally (expanded) c++ and python tests pass
> --[BE] - Config and Sensor system cleanup/expanded support, pre-Sensor refactor

- src/esp/bindings/GfxBindings.cpp
- src/esp/gfx/DebugLineRender.cpp
- src/esp/gfx/DebugLineRender.h
This PR adds some utility functions and python bindings to the DebugLineRenderer that will draw coordinate axes and draw a cone at a specific location.
draw_axes : 
Inserting the following python line in a draw statement  :
`debug_line_render.draw_axes(obj.translation)`
will yield the following axes centered at obj.translation (note the cones at the end of each axis indicated direction of increasing value):
Locally with python utilities
> --[BE] - add drawCoordinateAxes and drawCone to debug line renderer

- .github/actions/download_test_data/action.yml
- .github/actions/install_ubuntu_deps/action.yml
- .github/actions/install_ubuntu_gpu_deps/action.yml
- .github/workflows/install_and_test.yml
- tests/test_configs.py
Working branch to test migration to github actions. Do not merge.
CI
> [BE] github actions migration

- .github/workflows/install_and_test.yml
PR to test a fix of the doc build deployment. 
github Workflow CI demonstrated successful doc push as noted in comments below.
> [CI] - fix doc deployment with SSH

- .github/workflows/install_and_test.yml
- conda-build/habitat-sim/meta.yaml
- src_python/habitat_sim/utils/viz_utils.py
The `imageio-ffmpeg` dependency is not strictly required to run `habitat-sim`.
This package depends on `libva`, which depends on `libgl`, `libglx`, `libegl` and `libglvnd`.
Those 4 last packages may conflict with Linux packages, causing the OpenGL front-end libraries to fail to communicate to the OpenGL backend.
This error may occur:
```
GL::Context: cannot retrieve OpenGL version: GL::Renderer::Error::InvalidValue
```
Tested locally on a new conda environment.
> [CI] Remove `imageio-ffmpeg` from dependencies.

- .github/actions/install_ubuntu_deps/action.yml
- examples/tutorials/async_rendering.py
- examples/tutorials/stereo_agent.py
- src/esp/core/managedContainers/ManagedFileBasedContainer.h
- src/esp/physics/objectWrappers/ManagedArticulatedObject.h
- src/esp/physics/objectWrappers/ManagedPhysicsObjectBase.h
- src/esp/physics/objectWrappers/ManagedRigidBase.h
- src/esp/physics/objectWrappers/ManagedRigidObject.h
- src/tests/AttributesManagersTest.cpp
- tests/conftest.py
- tests/test_compare_profiles.py
- tests/test_examples.py
- tests/test_greedy_follower.py
- tests/test_light_setup.py
- tests/test_navmesh.py
- tests/test_noise_models.py
- tests/test_physics_benchmarking.py
- tests/test_profiling_utils.py
- tests/test_random_seed.py
- tests/test_snap_point.py
- tests/test_utils.py
This PR will contain various minor refactors and cleanup that I find as I complete other BE work that may be thematically orthogonal to the purpose of that work.
An important issue this PR addresses is that the python tests will currently abort if Habitat-sim is compiled with audio support. This is due to the import of habitat_sim in conftest.py causing an invalid free() unless the python quaternion library is imported first. This is discussed [in this issue](https://github.com/facebookresearch/habitat-sim/issues/1747).  Until a reason for this aberrant behavior can be determined, quaternion will be imported here so tests and examples don't fail.
NOTE : There is still an ongoing issue with running python tests with the audio subsystem enabled during compilation, where a greedy path …
> --[BE] - Miscellaneous minor refactors and cleanup

- src/esp/bindings/AttributesBindings.cpp
- src/esp/bindings/AttributesManagersBindings.cpp
- src/esp/bindings/GeoBindings.cpp
- src/esp/bindings/GfxBindings.cpp
- src/esp/bindings/MetadataMediatorBindings.cpp
- src/esp/bindings/SensorBindings.cpp
- src/esp/bindings/ShortestPathBindings.cpp
- src/esp/bindings/SimBindings.cpp
- src/esp/sim/SimulatorConfiguration.h
This changeset fixes asorted typos in bindings and stubs.
N/A
> [BE] - Fix typos in bindings and stubs.

- src/esp/gfx/replay/Player.cpp
This fixes a segfault that can occur in gfx-replay when an asset has an invalid path.
Tested locally on HITL.
> Fix segfault in gfx-replay when there's an invalid path.

- src/esp/core/managedContainers/ManagedFileBasedContainer.h
- src/esp/metadata/managers/AbstractAttributesManager.h
This PR changes how attributes' directory paths are stored so that they end in an os separator ('/'). This corrects an issue where path merging was sometimes giving erroneous results in certain conditions, and also simplifies and unifies path building code called from the scene dastaset load.
Locally c++ and python tests.
> --[Bugfix] - Storage of attribute source directory paths

- src/esp/core/managedContainers/ManagedFileBasedContainer.h
- src/esp/metadata/attributes/AbstractObjectAttributes.cpp
This PR addresses when an attributes filename has to be constructed from its handle. One of the paths to do this looked for the attributes' original file directory in its handle, and then removed that directory +1 from the handle to account for the once-missing trailing slash.  
However,  PR  #2541 modified the fileDirectory that is stored in the attributes to include the trailing slash, which required the modifications in this PR.
This also fixes a minor attributes issue where a boolean default value is not set as an init value (i.e. so it won't be written out to json if it is not changed).
Locally c++ and python
> --[Bugfix] - Fix attributes save

- docs/conf.py
- examples/marker_viewer.py
- examples/mod_viewer.py
- examples/spot_viewer.py
- examples/viewer.py
- src_python/habitat_sim/utils/__init__.py
- src_python/habitat_sim/utils/classes/__init__.py
- src_python/habitat_sim/utils/classes/markersets_editor.py
- src_python/habitat_sim/utils/classes/object_editor.py
- src_python/habitat_sim/utils/classes/semantic_display.py
- src_python/habitat_sim/utils/common/__init__.py
- src_python/habitat_sim/utils/common/common.py
- src_python/habitat_sim/utils/common/quaternion_utils.py
- src_python/habitat_sim/utils/namespace/__init__.py
- src_python/habitat_sim/utils/namespace/hsim_physics.py
- src_python/habitat_sim/utils/sim_utils.py
This PR introduces python utilities and a directory hierarchy structure for including those utilities.
This also introduces python utility class objects that can be inserted into a viewer file to facilitate editing and analysis of scenes.
Locally; the included example viewers act as tests for the functionality.
> --[BE] - Python-based utilities

- src/esp/assets/ResourceManager.cpp
This PR changes an assertion that no scale is provided to the vertex-semantics mesh instantiation method to instead be a user error message, and removes an assertion that no lighting key be provided, but rather hardcodes the actual creation to be NO_LIGHT_KEY.  Recent changes to allow for support of stage scaling have caused datasets that instantiate vertex-semantics meshes (like Replica) to unnecessarily fire this assertion.  Besides, seems a bit extreme to assert on data being provided that is not even used. 
Locally C++ and Python tests pass
> --[Bugfix] - Change assertion to just provide a user error if unused scale provided

- examples/mod_viewer.py
- src/esp/core/managedContainers/ManagedFileBasedContainer.h
- src/esp/metadata/managers/AbstractAttributesManager.h
- src/esp/metadata/managers/SensorAttributesManager.cpp
A few minor bugfixes
1. render_camera references in mod_viewer needed to be fixed, and an extraneous print statement commented out.
2. Attributes' source file directories needed a bit more consistent setting.
> --[Bugfix] - Miscellaneous minor bugfixes

- src/esp/bindings/PhysicsObjectBindings.cpp
- src/esp/physics/ArticulatedObject.h
- src/esp/physics/bullet/BulletArticulatedObject.cpp
- src/esp/physics/bullet/BulletArticulatedObject.h
- src/esp/physics/bullet/BulletPhysicsManager.cpp
- src/esp/physics/objectWrappers/ManagedArticulatedObject.h
This changeset exposes new Bullet variables and introduces a few bugfixes to allow for multiple render assets per link nodes.
Credits to @aclegg3 
Tested locally / CI.
> New Bullet bindings for teleoperation.

- src/esp/bindings/SimBindings.cpp
- src/esp/sim/RenderInstanceHelper.cpp
- src/esp/sim/RenderInstanceHelper.h
Adds a 3D scale vector to the add_instance python binding. Allows setting the render asset scale without instantiating a ManagedObject in Habitat (e.g. from the isaac integration).
Tested in a local app.
> add scale variable to the add_instance binding. 
